export const ERRORS = {
  NO_WEB3: "NO_WEB3",
  WALLET_INITIALISATION_FAILED: "WALLET_INITIALISATION_FAILED",
  NO_WEB3_PHANTOM: "NO_WEB3_PHANTOM",
  NO_WEB3_CRYPTO_COM: "NO_WEB3_CRYPTO_COM",
  NO_WEB3_BITGET: "NO_WEB3_BITGET",
  WEB3_REJECTED: "WEB3_REJECTED",
  NO_FARM: "NO_FARM",
  FAILED_REQUEST: "FAILED_REQUEST",
  REJECTED_TRANSACTION: "REJECTED_TRANSACTION",
  BLOCKED: "BLOCKED",
  NETWORK_CONGESTED: "NETWORK_CONGESTED",
  WITHDRAW_DUPLICATE: "WITHDRAW_DUPLICATE",
  RAFFLE_RESULTS_SERVER_ERROR: "RAFFLE_RESULTS_SERVER_ERROR",

  // Blockchain session has changed - they are doing something sneaky refreshing the browser
  SESSION_EXPIRED: "SESSION_EXPIRED",

  // Server errors
  DISCORD_USER_EXISTS: "DISCORD_USER_EXISTS",
  DISCORD_NOT_ON_SERVER: "DISCORD_NOT_ON_SERVER",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  MAINTENANCE: "MAINTENANCE",
  MULTIPLE_DEVICES_OPEN: "MULTIPLE_DEVICES_OPEN",
  UNAUTHORIZED: "UNAUTHORIZED",

  // Trade errors
  TRADE_NOT_FOUND: "TRADE_NOT_FOUND",

  // Server Errors (Named after API endpoint)
  AUTOSAVE_SERVER_ERROR: "AS-001",
  AUTOSAVE_CLOCK_ERROR: "AS-002",
  AUTOSAVE_CLIENT_ERROR: "AS-003",
  SYNC_SERVER_ERROR: "SY-001",
  SYNC_DAILY_SFL_MINT_EXCEEDED: "SY-002",
  SESSION_SERVER_ERROR: "SE-001",
  SESSION_CLIENT_ERROR: "SE-003",
  SIGN_UP_SERVER_ERROR: "SU-001",
  SIGN_UP_FARM_EXISTS_ERROR: "SU-002",
  SIGN_UP_TOO_MANY_FARMS: "SU-003",
  LOGIN_SERVER_ERROR: "LO-001",
  RESET_SERVER_ERROR: "RE-001",
  RESET_MARKETPLACE_TRANSFER_IN_PROGRESS: "RE-002",
  RESET_MARKETPLACE_UNCLAIMED_LISTINGS: "RE-003",
  AUCTIONEER_SERVER_ERROR: "AU-001",
  AUCTIONEER_UPCOMING_AUCTION_NOT_FOUND: "AU-002",
  AUCTION_RESULTS_SERVER_ERROR: "AR-001",
  DISCORD_ROLE_SERVER_ERROR: "DI-001",
  BUMPKINS_METADATA_ERROR: "BM-001",
  MARKET_PRICE_SERVER_ERROR: "MP-001",
  SELL_MARKET_RESOURCE_SERVER_ERROR: "SM-001",
  PORTAL_LOGIN_ERROR: "PL-001",
  PORTAL_LOAD_ERROR: "PL-002",
  CLAIM_FARM_SERVER_ERROR: "CF-001",
  CLAIM_FARM_TOO_MANY_FARMS: "CF-002",
  EFFECT_SERVER_ERROR: "EF-001",
  EFFECT_BAD_REQUEST: "EF-002",
  EFFECT_TOO_MANY_REQUESTS: "EF-003",
  EFFECT_NOT_FOUND: "EF-004",
  WITHDRAW_FLOWER_VALIDATION_ERROR: "WF-001",
  BUY_GEMS_SERVER_ERROR: "BG-001",
  BUY_GEMS_MARKETPLACE_TRANSFER_IN_PROGRESS: "BG-002",
  BUY_GEMS_MARKETPLACE_UNCLAIMED_LISTINGS: "BG-003",
  // Wishing well errors
  NO_TOKENS: "NO_TOKENS",

  // Sequence
  SEQUENCE_NOT_CONNECTED: "SEQUENCE_NOT_CONNECTED",

  WALLET_ALREADY_LINKED: "WALLET_ALREADY_LINKED",

  MISSING_PROVIDER: "MISSING_PROVIDER",
};

export type ErrorCode = keyof typeof ERRORS;
