import { SUNNYSIDE } from "assets/sunnyside";
import art0 from "assets/fish/battle_fish_trophy.webp";
import art1 from "assets/fish/crimson_carp_trophy.png";
import art2 from "assets/fish/crystal_shrimp_trophy.webp";
import art3 from "assets/fish/deep_sea_pig_trophy.webp";
import art4 from "assets/fish/deep_sea_slug_trophy.webp";
import art5 from "assets/sfts/dinosaur_bone_case.webp";
import art6 from "assets/fish/dollocaris_trophy.webp";
import art7 from "assets/sfts/easter/easter_bunny_eggs.webp";
import art8 from "assets/sfts/foliant_case.webp";
import art9 from "assets/sfts/galleon_case.webp";
import art10 from "assets/fish/isopod_trophy.webp";
import art11 from "assets/fish/gilded_swordfish_trophy.png";
import art12 from "assets/sfts/golden_bear_head_case.webp";
import art13 from "assets/sfts/iron_idol_case.webp";
import art14 from "assets/fish/jellyfish_trophy.webp";
import art15 from "assets/fish/lemon_shark_trophy.webp";
import art16 from "assets/fish/cow_fish_trophy.webp";
import art17 from "assets/fish/nautilus_trophy.webp";
import art18 from "assets/sfts/obie.gif";
import art19 from "assets/sfts/parasaur_skull_case.webp";
import art20 from "assets/fish/phantom_barracuda_trophy.png";
import art21 from "assets/fish/pink_dolphin_trophy.webp";
import art22 from "assets/sfts/poseidon_fish_aquarium.webp";
import art23 from "assets/fish/radiant_ray_trophy.png";
import art24 from "assets/sfts/aoe/sir_goldensnout.png";
import art25 from "assets/sfts/skeleton_key_staff_case.webp";
import art26 from "assets/fish/starlight_tuna_trophy.png";
import art27 from "assets/sfts/sunflower_coin_case.webp";
import art28 from "assets/sfts/starfish_marvel_tank.webp";
import art29 from "assets/sfts/t_rex_skull_case.webp";
import art30 from "assets/fish/twilight_anglerfish_trophy.png";
import type { CollectibleName } from "features/game/types/craftables";

/**
 * GENERATED layout table for the ~300 static collectible components
 * (scripted extraction from features/island/collectibles/components/*.tsx —
 * see docs/phaser-farm-migration/CHECKLIST.md Phase 6). Offsets are source px
 * relative to the placement box, bottom-left anchored like the DOM's
 * `absolute bottom-0` images. `art` omitted = ITEM_DETAILS[name].image
 * (verified identical import path); `centeredIn` = the DOM centres the image
 * horizontally inside a wrapper of that width.
 */
export type StaticCollectibleSpec = {
  art?: string;
  width: number;
  bottom?: number;
  left?: number;
  right?: number;
  top?: number;
  centeredIn?: number;
  /** npcs/shadow.png underlay (the DOM's two-img beaver template). */
  shadow?: {
    width: number;
    bottom?: number;
    left?: number;
    right?: number;
    top?: number;
  };
};

export const STATIC_COLLECTIBLES: Partial<
  Record<CollectibleName, StaticCollectibleSpec>
> = {
  "Abandoned Bear": { width: 16 },
  "Acorn House": { width: 33, bottom: -2, left: -1 },
  "Adrift Ark": { width: 29, left: 2 },
  Alba: { width: 13 },
  "Alien Chicken": { width: 16, left: -1 },
  "Amethyst Nightshade Goblet": { width: 16 },
  Anchor: { width: 27, bottom: 3, left: 3 },
  "Anemone Flower": { width: 20, left: -1.75 },
  "Angel Bear": { width: 25, left: 4 },
  "Ant Queen": { width: 20 },
  "Anubis Jackal": { width: 28, left: 2.25 },
  "Apprentice Beaver": {
    width: 15,
    bottom: 2,
    shadow: { width: 15, bottom: 0 },
  },
  "Ascended Chicken": { width: 24, left: -4 },
  "Ascended Cow": { width: 29, left: 1.5 },
  "Ascended Sheep": { width: 33, left: -0.5 },
  "Ascension Age Banner": { width: 20, bottom: 2, left: -2 },
  "Astronaut Cow": { width: 25, bottom: -2, left: -4.5 },
  "Astronaut Sheep": { width: 25, bottom: -2, left: -4.5 },
  "Aurora Lantern": { width: 11 },
  "Autumn Duckling": { width: 8, bottom: 4, left: 4 },
  "Autumn Guardian": { width: 35, left: -2 },
  "Ayam Cemani": { width: 15 },
  "Baby Cow": { width: 16 },
  "Baby Panda": { width: 16, bottom: 2 },
  "Baby Sheep": { width: 16 },
  "Badass Bear": { width: 18 },
  Bale: { width: 28, bottom: 1 },
  "Balloon Rug": { width: 23, bottom: 2, left: 5 },
  "Banana Chicken": { width: 15, left: 0.5 },
  "Baobab Tree": { width: 51, left: -1.5 },
  Baozi: { width: 16, bottom: 2 },
  "Barn Blueprint": { width: 32 },
  "Basic Bear": { width: 16 },
  "Basic Scarecrow": { width: 22, left: -3 },
  "Battle Fish": { art: art0, width: 32 },
  "Battlecry Drum": { width: 21, bottom: 2 },
  "Beach Ball": { width: 15 },
  "Beach Umbrella": { width: 24, left: 5 },
  "Bear Trap": { width: 16 },
  "Beetroot Rug": { width: 64 },
  "Benevolence Flag": { width: 16, bottom: 2 },
  "Beta Bear": { width: 16 },
  "Better Together Banner": { width: 18, bottom: 2, left: -0.5 },
  "Betty Lantern": { width: 11 },
  "Big Table": { width: 45, left: 1.5 },
  "Black Bearry": {
    width: 16,
    bottom: 2,
    shadow: { width: 16, bottom: 0, left: 0 },
  },
  "Black Hole Flower": { width: 28, bottom: -2, left: -6 },
  "Black Sheep": { width: 25 },
  "Blossom Royale": { width: 28 },
  "Blossom Tree": { width: 32 },
  Blossombeard: { width: 13, bottom: 3, left: 1.5 },
  "Blue Paint Bucket": { width: 16 },
  "Blue Slime Balloon": { width: 16 },
  "Bonnie's Tombstone": {
    art: SUNNYSIDE.decorations.bonniesTombstone,
    width: 14,
    bottom: 2,
    left: 1,
  },
  "Brilliant Bear": { width: 16 },
  "Bronze Slime Trophy": { width: 16 },
  "Bull Run Banner": { width: 20, left: -1.5, top: -5 },
  "Bullseye Board": { width: 24, bottom: 2 },
  "Bumpkin Bunting": { width: 32 },
  "Bumpkin Candles": { width: 9 },
  "Bumpkin Faction Banner": { width: 16 },
  "Bumpkin Faction Rug": { width: 48 },
  "Bumpkin Lantern": { width: 11 },
  "Bumpkin Left Wall Sconce": { width: 7 },
  "Bumpkin Nutcracker": { width: 14, bottom: 2, left: 1 },
  "Bumpkin Right Wall Sconce": { width: 7 },
  "Bumpkin Rug": { width: 32 },
  "Bumpkin Throne": { width: 17 },
  "Cabbage Boy": { width: 16, bottom: 2, shadow: { width: 15 } },
  "Cabbage Girl": { width: 16, bottom: 2, shadow: { width: 15 } },
  Cactus: { art: SUNNYSIDE.decorations.cactus, width: 10, bottom: 1, left: 3 },
  "Cactus King": { width: 19, left: -1.5 },
  Capybara: { width: 29 },
  "Carrot House": { width: 32 },
  "Carrot Rug": { width: 64 },
  "Carrot Sword": { width: 20, left: -2 },
  "Catch the Kraken Banner": { width: 16, bottom: 2 },
  "Celestial Frostbloom": { width: 12 },
  Chamomile: { width: 14 },
  "Chef Bear": { width: 16 },
  "Chess Rug": { width: 64 },
  "Chestnut Fungi Stool": { width: 12, bottom: 2, left: 2 },
  "Chicken Coop": { width: 33, left: -1 },
  Chicory: { width: 19 },
  "Christmas Bear": { width: 20 },
  "Christmas Candle": { width: 13, left: 2 },
  "Christmas Rug": { width: 48 },
  "Christmas Snow Globe": { width: 20, bottom: 4, left: 6 },
  "Christmas Stocking": { width: 10, bottom: 1, left: 3 },
  "Christmas Tree": { width: 23, left: 4 },
  "Clash of Factions Banner": { width: 18, left: -1, top: -3 },
  "Classy Bear": { width: 16 },
  "Clay Tablet": { width: 32 },
  Clementine: { width: 9, bottom: 3, left: 3.5 },
  Clock: { width: 11 },
  Cluckapult: { width: 31, bottom: 2 },
  Cobalt: { width: 9, bottom: 3, left: 3.5 },
  "Collectible Bear": { width: 22, bottom: 6, left: 6 },
  "Color Wheel": { width: 32 },
  "Community Egg": { width: 16, bottom: 2 },
  "Construction Bear": { width: 16 },
  "Cow Scratcher": { width: 17 },
  "Cozy Fireplace": { width: 32, bottom: -2 },
  "Crab House": { width: 54, left: -3 },
  "Crabs and Traps Banner": { width: 18, bottom: 2, left: -1 },
  "Creator Banner": { width: 16, top: -3 },
  "Crim Peckster": { width: 22, left: -2, shadow: { width: 15, bottom: 2 } },
  "Crimson Cap": { width: 24, bottom: 2, left: 4 },
  "Crimson Carp": { art: art1, width: 32 },
  "Crop Circle": { width: 39, left: -3 },
  "Crow Rock": { art: SUNNYSIDE.decorations.crowRock, width: 29 },
  "Crystal Shrimp": { art: art2, width: 35, top: -1 },
  "Cup of Chocolate": { width: 32 },
  "Cyborg Bear": { width: 16 },
  "Dawn Breaker Banner": { width: 16, bottom: 2 },
  "Dawn Flower": { width: 13, bottom: 2, left: 1.5 },
  "Dawn Umbrella Seat": { width: 12, bottom: 2, left: 2 },
  "Deep Sea Pig": { art: art3, width: 32 },
  "Deep Sea Slug": { art: art4, width: 32 },
  "Definitely not a Flower": { width: 16 },
  "Desert Gnome": { width: 9, bottom: 3, left: 3.5 },
  "Desert Rose": { width: 18 },
  "Devil Bear": { width: 21, left: -2 },
  "Devotion Flag": { width: 16, bottom: 2 },
  "Dhol Drum": { width: 32 },
  "Dinosaur Bone": { art: art5, width: 22 },
  "Diving Helmet": { width: 18 },
  Dollocaris: { art: art6, width: 32 },
  "Dr Cow": { width: 25, left: 3.5 },
  "Duamutef Jar": { width: 14, left: 1 },
  "Dumbo Octopus": { width: 32 },
  "Earn Alliance Banner": { width: 18, left: -1, top: -3 },
  "Easter Basket": { width: 32 },
  "Easter Bear": { width: 16 },
  "Easter Bunny": { art: art7, width: 32 },
  "Eggplant Bear": { width: 16 },
  "Eggplant Grill": { width: 16 },
  "El Pollo Veloz": { width: 16, shadow: { width: 15 } },
  "Emerald Goblin Goblet": { width: 16 },
  "Emerald Turtle": { width: 22, bottom: -3, left: -3 },
  "Empty Pot": { width: 28, left: 2 },
  "Enchanted Rose": { width: 14 },
  "Fairy Circle": { width: 35, bottom: 3, left: -1.5 },
  "Fake Mouse": { width: 16 },
  "Fake Treasure": { width: 32 },
  "Fancy Rug": { width: 48 },
  "Farm Cat": { width: 20, left: -2 },
  "Farm Dog": { width: 16 },
  "Farmer Bath": { width: 32, bottom: 1 },
  "Farmer Bear": { width: 16 },
  "Fat Chicken": { width: 17, left: -1 },
  "Fat Crab": { width: 23, left: -2 },
  "Festive Toy Train": { width: 32 },
  "Field Maple": { width: 28, bottom: 1.5 },
  "Fish Bowl": { width: 28, left: 2 },
  "Fish Kite": { width: 24, left: 4 },
  Flamingo: { width: 25, bottom: 8, left: 3.5 },
  "Flamingo Chicken": { width: 16, left: 0.5 },
  "Floating Toy": { width: 16 },
  "Floor Mirror": { width: 16, bottom: 2 },
  "Floral Arch": { width: 44, bottom: -4, left: 2 },
  "Flower Cart": { width: 29 },
  "Flower Coin": { width: 34, bottom: 3, left: -1 },
  "Flower Fox": { width: 21 },
  "Flower Rug": { width: 48 },
  "Flower Statue": { width: 32, bottom: 2 },
  "Flower-Scribed Statue": { width: 39, left: -3 },
  Foliant: { art: art8, width: 32 },
  "Fool's Gold": { width: 32 },
  "Foreman Beaver": { width: 15, bottom: 2, shadow: { width: 15, bottom: 0 } },
  "Freya Fox": { width: 21, left: -3 },
  "Frozen Cow": { width: 27 },
  "Frozen Meat": { width: 16 },
  "Frozen Sheep": { width: 27 },
  "Fruit Tune Box": { width: 20 },
  Galleon: { art: art9, width: 32 },
  "Garbage Bin": { width: 18, left: -1 },
  "Gaucho Rug": { width: 37, left: 5.5 },
  "Generosity Flag": { width: 16, bottom: 2 },
  "Genie Bear": { width: 16 },
  "Genie Lamp": { width: 22, left: 4 },
  "Giant Acorn": { width: 32 },
  "Giant Apple": { width: 26, left: 3 },
  "Giant Artichoke": { width: 27, bottom: 3, left: 1 },
  "Giant Banana": { width: 32 },
  "Giant Cabbage": { width: 27, left: 3 },
  "Giant Carrot": { width: 26, left: 3 },
  "Giant Dawn Mushroom": { width: 28, bottom: 2, left: 2 },
  "Giant Donut": { width: 32 },
  "Giant Gold Bone": { width: 28, left: 2 },
  "Giant Isopod": { art: art10, width: 32 },
  "Giant Kale": { width: 32, bottom: 3 },
  "Giant Onion": { width: 20, bottom: 3, left: -2 },
  "Giant Orange": { width: 28, left: 2 },
  "Giant Potato": { width: 17 },
  "Giant Pumpkin": { width: 26, left: 3 },
  "Giant Turnip": { width: 31, bottom: 5, left: 3 },
  "Giant Yam": { width: 22, bottom: 3, left: -3 },
  "Giant Zucchini": { width: 23, bottom: 3, left: -3 },
  "Gift Turtle": { width: 28, left: 2 },
  "Gilded Swordfish": { art: art11, width: 32 },
  Gnome: { width: 9, bottom: 3, left: 3.5 },
  Goblet: { width: 16 },
  "Goblin Bear": { width: 16 },
  "Goblin Bunting": { width: 32 },
  "Goblin Candles": { width: 9 },
  "Goblin Crown": { width: 9, bottom: 5, left: 3 },
  "Goblin Faction Banner": { width: 20 },
  "Goblin Faction Rug": { width: 48 },
  "Goblin Lantern": { width: 17 },
  "Goblin Left Wall Sconce": { width: 7 },
  "Goblin Right Wall Sconce": { width: 7 },
  "Goblin Rug": { width: 32 },
  "Goblin Throne": { width: 21 },
  "Goblin War Banner": { width: 16, bottom: 2 },
  "Gold Beetle": { width: 15, left: 0.5 },
  "Goldcrest Mosaic Rug": { width: 64 },
  "Golden Bear Head": { art: art12, width: 32 },
  "Golden Bonsai": { width: 18 },
  "Golden Bush": { width: 24, left: 4 },
  "Golden Cauliflower": { width: 32 },
  "Golden Christmas Stocking": { width: 10, bottom: 1, left: 3 },
  "Golden Cow": { width: 32 },
  "Golden Faction Goblet": { width: 16 },
  "Golden Gallant": { width: 11, bottom: 2, left: 3 },
  "Golden Garrison": { width: 10, bottom: 2, left: 3 },
  "Golden Guardian": { width: 9, bottom: 2 },
  "Golden Maple": { width: 28, bottom: 1.5 },
  "Golden Pine Tree": { width: 18, bottom: 3, left: -1 },
  "Golden Sheep": { width: 32, left: 0.5 },
  "Golden Slime Trophy": { width: 16 },
  "Golden Sunflorian Egg": { width: 22 },
  "Golden Tree": { width: 26, bottom: 2, left: 3 },
  "Grain Grinder": { width: 26 },
  "Grape Granny": { width: 15, bottom: 1 },
  "Great Bloom Banner": { width: 16, top: -4 },
  "Green Field Rug": { width: 48 },
  "Green Holiday Ornament": { width: 30, left: 1 },
  "Green Paint Bucket": { width: 16 },
  "Grinx's Hammer": { width: 13, bottom: 2 },
  "Groovy Gramophone": { width: 25, left: -3 },
  "Grubnash's Tombstone": {
    art: SUNNYSIDE.decorations.grubnashTombstone,
    width: 9,
    bottom: 2,
    left: 3.5,
  },
  "Halloween Scarecrow": { width: 22, left: -3 },
  "Hapy Jar": { width: 15, left: 0.5 },
  "Harlequin Rug": { width: 64 },
  "Haunted House": { width: 93, left: 2 },
  "Haunted Stump": { width: 18 },
  "Haunted Tomb": { width: 14, left: 1 },
  "Heart Air Balloon": { width: 64, left: -8 },
  "Heart Balloons": { width: 18 },
  "Heart of Davy Jones": {
    width: 23,
    bottom: 6,
    left: 4,
    shadow: { width: 21, bottom: 3, left: 5 },
  },
  "Heartstruck Tree": { width: 31, left: 2 },
  "Hideaway Herman": { width: 17 },
  "High Table": { width: 12, left: 2 },
  "Ho Ho oh oh…": { width: 32 },
  "Holiday Decorative Totem": { width: 18, left: -1 },
  "Homeless Tent": { width: 28 },
  Hoot: { width: 16, bottom: 1 },
  "Human Bear": { width: 16 },
  "Human War Banner": { width: 16, bottom: 2 },
  "Humming Bird": { width: 18 },
  "Hungry Caterpillar": { width: 15 },
  "Hungry Hare": { width: 22, bottom: 2, left: 5 },
  "Immortal Pear": { width: 22 },
  "Imsety Jar": { width: 15, left: 0.5 },
  "Iron Beetle": { width: 15, left: 0.5 },
  "Iron Idol": { art: art13, width: 32 },
  "Janitor Chicken": { width: 26, left: -1.75 },
  "Jelly Lamp": { width: 32, bottom: 2 },
  Jellyfish: { art: art14, width: 32 },
  "Jester in a box": { width: 32 },
  "Jurassic Droplet": { width: 32 },
  Karkinos: { width: 27, bottom: 4, left: 2 },
  Kernaldo: { width: 16 },
  "Knight Chicken": { width: 23, left: -5 },
  "Knowledge Crab": { width: 19, left: -2 },
  "Kraken Head": { width: 11 },
  "Kraken Tentacle": { width: 8 },
  Kuebiko: { width: 30, bottom: 1, left: 1 },
  "Lab Grown Carrot": { width: 12, shadow: { width: 14, bottom: 0, left: 1 } },
  "Lab Grown Pumpkin": { width: 12, shadow: { width: 14, bottom: 0, left: 1 } },
  "Lab Grown Radish": { width: 14, shadow: { width: 14, bottom: 0, left: 1 } },
  "Lady Bug": { width: 16, bottom: 2, shadow: { width: 15 } },
  "Lake Rug": { width: 48 },
  "Large Podium": { width: 40, left: 4 },
  "Large Rug": { width: 64 },
  "Laurie the Chuckle Crow": { width: 25, left: -4 },
  "Lemon Frog": { width: 19, left: -1.5 },
  "Lemon Shark": { art: art15, width: 32 },
  "Lemon Tea Bath": { width: 38, left: 5 },
  "Lifeguard Bear": { width: 17 },
  "Lifeguard Ring": { width: 17 },
  "Lifetime Farmer Banner": { width: 16, top: -3 },
  "Lily Egg": { width: 16 },
  "Long Rug": { width: 64 },
  "Long Table": { width: 24, left: 4 },
  "Longhorn Cowfish": { art: art16, width: 32 },
  "Love Chicken": { width: 21, left: -1.75 },
  "Luminous Lantern": { width: 11 },
  Lunalist: { width: 18, bottom: 1.5 },
  "Lunar Calendar": { width: 15 },
  "Lunar Temple": { width: 46, left: 1.5 },
  "Magma Stone": { width: 22, left: -3 },
  "Mahogany Cap": { width: 24, bottom: 2, left: 4 },
  "Mama Duck": { width: 16, bottom: 2 },
  "Maneki Neko": { width: 16 },
  Maximus: { width: 21, bottom: 1, left: 5 },
  "Mechanical Bull": { width: 32, bottom: 3 },
  "Mermaid Cow": { width: 25, bottom: -2 },
  "Mermaid Fountain": { width: 36, bottom: -2, left: -2 },
  "Mermaid Sheep": { width: 25, left: -4.5 },
  "Mimic Egg": { width: 19, left: -2 },
  "Mimic Slime Ball": { width: 16 },
  "Mimic Winged Slime Ball": { width: 16 },
  "Mini Corn Maze": { width: 16 },
  "Mini Floating Island": { width: 26, bottom: 3, left: 3 },
  "Moo-ver": { width: 36, bottom: 2, left: -1 },
  "Moon Fox Statue": { width: 31, bottom: -2 },
  Mootant: { width: 25 },
  "Mushroom House": { width: 37, left: -3 },
  "Mysterious Entrance": { width: 54, bottom: -2, left: -3 },
  "Mysterious Head": { width: 25, bottom: 3, left: 3 },
  "Mysterious Parsnip": { width: 16 },
  Nana: { width: 17 },
  Nancy: { width: 20, bottom: 1, left: -2 },
  Nautilus: { art: art17, width: 32 },
  "Navigation Table": { width: 32, left: -1.5 },
  "Nightshade Bunting": { width: 32 },
  "Nightshade Candles": { width: 9 },
  "Nightshade Faction Banner": { width: 20 },
  "Nightshade Faction Rug": { width: 48 },
  "Nightshade Left Wall Sconce": { width: 7 },
  "Nightshade Right Wall Sconce": { width: 7 },
  "Nightshade Throne": { width: 18 },
  "Novice Knight": { width: 11, bottom: 2, left: 3 },
  Nugget: { width: 21, right: -3 },
  "Nurse Sheep": { width: 25, left: 3.5 },
  "Nyon Statue": { width: 32 },
  Obie: {
    art: art18,
    width: 15,
    bottom: 2,
    shadow: { width: 15, bottom: 0, left: 0 },
  },
  Observer: { width: 17 },
  "Obsidian Turtle": { width: 22, bottom: -3, left: -3 },
  "Ocean Lantern": { width: 11 },
  "Orange Bunny Lantern": { width: 16 },
  "Orange Tunnel Bunny": { width: 18 },
  "Orchard Rug": { width: 64 },
  "Pablo The Bunny": { width: 14, shadow: { width: 15 } },
  "Paint Buckets": { width: 16 },
  "Paint Can": { width: 21, bottom: 2, left: 5.5 },
  "Palm Tree": { width: 29 },
  "Paper Reed": { width: 22, left: -3 },
  "Parasaur Skull": { art: art19, width: 32 },
  "Paw Prints Banner": { width: 16, bottom: 2 },
  "Paw Prints Rug": { width: 64 },
  "Peeled Potato": {
    width: 15,
    bottom: 2,
    shadow: { width: 15, bottom: 0, left: 0 },
  },
  "Penguin Pool": { width: 32 },
  "Penguin Surprise": { width: 51, left: -2 },
  "Pet Bed": { width: 32 },
  "Pet Bowls": { width: 32 },
  "Pet Kennel": { width: 26, left: 3 },
  "Pet Playground": { width: 34, left: -1 },
  "Pet Rug": { width: 32 },
  "Pet Toys": { width: 25, left: -5 },
  "Pet Tree": { width: 16 },
  "Petnip Plant": { width: 26, left: 3 },
  "Phantom Barracuda": { art: art20, width: 32 },
  "Pharaoh Chicken": { width: 17 },
  "Pharaoh Gnome": { width: 11, bottom: 3, left: 2.5 },
  "Pharaoh's Treasure Banner": { width: 16, top: -3 },
  "Pine Tree": { art: SUNNYSIDE.decorations.pineTree, width: 18, bottom: 4 },
  "Pink Dolphin": { art: art21, width: 32 },
  "Pirate Bear": { width: 19 },
  "Pony Toy": { width: 18 },
  Poppy: { width: 11 },
  "Pork Jelly": { width: 16 },
  Poseidon: { art: art22, width: 32 },
  "Potato Statue": { width: 24 },
  "Potent Potato": { width: 22, bottom: -2, right: -3 },
  "Potted Potato": {
    art: SUNNYSIDE.decorations.pottedPotato,
    width: 14,
    bottom: 1,
    left: 1,
  },
  "Potted Pumpkin": {
    art: SUNNYSIDE.decorations.pottedPumpkin,
    width: 13,
    bottom: 1,
    left: 1,
  },
  "Potted Sunflower": {
    art: SUNNYSIDE.decorations.pottedSunflower,
    width: 12,
    bottom: 1,
    left: 2,
  },
  "Primula Enigma": { width: 15 },
  "Prism Petal": { width: 15 },
  "Purple Paint Bucket": { width: 16 },
  "Purple Trail": { width: 15, bottom: 2 },
  "Qebehsenuef Jar": { width: 15, left: 0.5 },
  "Queen Bee": { width: 15 },
  "Queen Cornelia": { width: 16 },
  "Radiance Lantern": { width: 11 },
  "Radiant Ray": { art: art23, width: 32 },
  "Radical Radish": { width: 22, bottom: -2, right: -3 },
  Rainbow: { width: 36 },
  "Rainbow Artist Bear": { width: 16 },
  "Rainbow Flower": { width: 32, left: 4 },
  "Rainbow Pork Jelly": { width: 16 },
  "Rainbow Well": { width: 32, left: 4 },
  "Rat King": { width: 21, left: -3 },
  "Red Holiday Ornament": { width: 31 },
  "Red Maple": { width: 28, bottom: 1.5 },
  "Red Nose Reindeer": { width: 29, left: 2 },
  "Red Slime Balloon": { width: 16 },
  "Reelmaster's Chair": { width: 17, bottom: 2, left: -1 },
  "Regular Pawn": { width: 9, bottom: 2 },
  "Reveling Lemon": { width: 23, left: 4 },
  "Rice Panda": { width: 15, bottom: 2 },
  "Rich Bear": { width: 24, right: -4 },
  "Rich Chicken": { width: 22, right: -3 },
  "Rock Golem": { width: 34, left: -2 },
  "Rocket Statue": { width: 22, left: -3 },
  "Rocky the Mole": { width: 21, right: -3 },
  "Rookie Rook": { width: 10, bottom: 2, left: 3 },
  Rooster: { width: 15 },
  "Royal Crab Pot": { width: 35, left: -1.5 },
  "Royal Podium": { width: 22, left: 5 },
  "Royal Throne": { width: 19 },
  "Rubber Ducky": { width: 13, left: 2 },
  "Ruby Faction Goblet": { width: 16 },
  Rug: { art: SUNNYSIDE.decorations.rug, width: 38, bottom: 3, left: 5 },
  "Ruins Flower": { width: 16 },
  "Salt Awakening Banner": { width: 16, bottom: 2 },
  "Salt Crystal Flower": { width: 21, left: -2.5 },
  "Sand Golem": { width: 28, left: 2 },
  "Sandy Mosaic Rug": { width: 64 },
  "Santa Penguin": { width: 18, bottom: 2, left: -1 },
  "Sapo Docuras": { width: 16 },
  "Sapo Travessuras": { width: 16 },
  "Scarab Beetle": { width: 26, left: 3 },
  Scarecrow: { width: 26, bottom: 1, left: 3 },
  "Scary Mike": { width: 22, left: -3 },
  "Seahorse Dad": { width: 32 },
  "Sheaf of Plenty": { width: 22, bottom: 2, left: -3 },
  "Shifty Sheldon": { width: 17 },
  "Shroom Glow": {
    art: SUNNYSIDE.decorations.shroomGlow,
    width: 32,
    bottom: 2,
  },
  Shrub: { width: 16 },
  "Silver Sentinel": { width: 10, bottom: 2, left: 3 },
  "Silver Slime Trophy": { width: 16 },
  "Silver Squire": { width: 9, bottom: 2 },
  "Silver Stallion": { width: 11, bottom: 2, left: 3 },
  "Sir Goldensnout": { art: art24, width: 24, bottom: 2, left: 4 },
  "Skeleton King Staff": { art: art25, width: 22 },
  "Skill Shrimpy": { width: 14, left: 1 },
  "Sky Pillar": { width: 23, bottom: 3, left: 4 },
  "Sleepy Chicken": { width: 26, left: -5 },
  "Sleepy Rug": { width: 48 },
  "Slime Totem": { width: 32 },
  "Snail King": { width: 19, left: -1 },
  "Snake in Jar": { width: 18, left: -1 },
  "Snorkel Bear": { width: 16 },
  "Soil Krabby": { width: 19, left: -2 },
  "Solar Flare Banner": { width: 16, bottom: 2 },
  "Solar Lantern": { width: 11 },
  Soybliss: { width: 16 },
  "Spa Cow": { width: 25, left: 3.5 },
  "Spa Sheep": { width: 25, left: 3.5 },
  "Speed Chicken": { width: 15 },
  "Speed Trap": { width: 19, left: -1.5 },
  "Spinning Wheel": { width: 30, bottom: 4, left: 1 },
  "Splendor Flag": { width: 16, bottom: 2 },
  "Spooky Tree": { art: SUNNYSIDE.decorations.spookyTree, width: 26 },
  "Spring Duckling": { width: 8, bottom: 4, left: 4 },
  "Spring Guardian": { width: 35, left: -2 },
  "Square Table": { width: 22, left: 5 },
  "Squeaky Chicken": { width: 23, left: -3 },
  "Squid Chicken": { width: 19, left: -1.75 },
  "Starlight Tuna": { art: art26, width: 32 },
  "Stellar Sunflower": { width: 22, bottom: -2, right: -3 },
  "Stone Beetle": { width: 15, left: 0.5 },
  "Streamer's Statue": { width: 19, left: -1.5 },
  "Summer Chicken": { width: 21 },
  "Summer Duckling": { width: 8, bottom: 4, left: 4 },
  "Summer Guardian": { width: 35, left: -2 },
  "Sunflorian Bunting": { width: 32 },
  "Sunflorian Candles": { width: 9 },
  "Sunflorian Faction Banner": { width: 16 },
  "Sunflorian Faction Rug": { width: 48 },
  "Sunflorian Left Wall Sconce": { width: 7 },
  "Sunflorian Right Wall Sconce": { width: 7 },
  "Sunflorian Throne": { width: 21 },
  "Sunflower Bear": { width: 16 },
  "Sunflower Coin": { art: art27, width: 32 },
  "Sunflower Rock": { width: 76, left: 2 },
  "Sunflower Statue": { width: 48 },
  "Sunflower Tombstone": { width: 26, bottom: 2, right: 3 },
  "Sunlit Citadel": { width: 28, left: 2 },
  "Sunrise Bloom Rug": { width: 48 },
  "Super Star": { art: art28, width: 32 },
  Surfboard: { width: 13, bottom: 2, left: 2 },
  "Swiss Whiskers": { width: 21, left: -4 },
  "T-Rex Skull": { art: art29, width: 32 },
  "Tea Rug": { width: 48 },
  "Teeth Toy": { width: 32 },
  "The Sunflower Man Statue": { width: 32 },
  "Tiki Torch": { width: 9, left: 4 },
  "Tiki Totem": { width: 13, left: 1 },
  "Tin Turtle": { width: 22, bottom: -3, left: -3 },
  "Toadstool Seat": { width: 12, bottom: 2, left: 2 },
  "Tomato Clown": { width: 19 },
  "Toxic Tuft": { width: 25 },
  "Trainee Target": { width: 16 },
  "Treasure Map": { width: 34 },
  "Tunnel Mole": { width: 20, right: -2 },
  "Turbo Sprout": { width: 29 },
  "Turtle Bear": { width: 17 },
  "Tuxedo Claus": { width: 37, left: -3 },
  "Twilight Anglerfish": { art: art30, width: 32 },
  "Twilight Rug": { width: 64 },
  "Twister Rug": { width: 48 },
  "Ugly Duckling": { width: 16, bottom: 2 },
  "Undead Rooster": { width: 15 },
  "Valentine Bear": { width: 16 },
  "Vampire Bear": { width: 18 },
  "Vampire Coffin": { width: 24, left: 4 },
  "Venus Bumpkin Trap": { width: 20, left: -1.75 },
  "Victoria Sisters": { width: 32 },
  Vinny: { width: 19 },
  "Volcano Gnome": { width: 9, bottom: 3, left: 3.5 },
  Wagon: { width: 28 },
  Walrus: { width: 25, bottom: 4 },
  "War Skull": { art: SUNNYSIDE.decorations.warSkull, width: 16 },
  "War Tombstone": {
    art: SUNNYSIDE.decorations.warTombstone,
    width: 14,
    left: 1,
  },
  "Whale Bear": { width: 16 },
  "Wheat Whiskers": { width: 17, left: -1 },
  "White Bunny Lantern": { width: 16 },
  "White Crow": { width: 20 },
  "White Festive Fox": { width: 33, bottom: 2 },
  "White Tulips": {
    art: SUNNYSIDE.decorations.whiteTulips,
    width: 8,
    bottom: 1,
    left: 4,
  },
  "White Tunnel Bunny": { width: 18 },
  "Wicker Man": { width: 19 },
  "Winter Alpaca": { width: 32, bottom: -2 },
  "Winter Duckling": { width: 8, bottom: 4, left: 4 },
  "Winter Guardian": { width: 35, left: -2 },
  "Witch's Cauldron": { width: 38, left: -3 },
  "Witches' Eve Banner": { width: 16, bottom: 2 },
  "Wood Nymph Wendy": { width: 15, bottom: 1 },
  "Woody the Beaver": {
    width: 15,
    bottom: 2,
    shadow: { width: 15, bottom: 0 },
  },
  "Yellow Paint Bucket": { width: 16 },
};

/**
 * Collectibles the DOM renders via TemplateCollectible: ITEM_DETAILS art at
 * its natural width, horizontally centred, flush with the box bottom
 * (TemplateCollectible.tsx). DECORATION_TEMPLATES names get the same
 * treatment at runtime.
 */
export const TEMPLATE_COLLECTIBLES: CollectibleName[] = [
  "Speckled Kissing Fish",
  "Dark Eyed Kissing Fish",
  "Yellow Submarine Trophy",
  "Fisherman's Boat",
  "Sea Arch",
  "Crabs and Fish Rug",
  "Fish Flags",
  "Fish Drying Rack",
  "Crimstone Clam",
  "Dino Egg Trophy",
  "Salt Lamp",
  "World Map Rug",
  "Ripped Salt Bag",
  "Salt Rug",
  "Ascended Idol",
  "Ascended Wheel",
  "Coat Rack",
  "Marble Head",
  "Otty the Otter",
  "Salt Worker Gnome",
  "Shards Turtle",
  "Winged Vase",
];
