import { KNOWN_ITEMS } from "features/game/types";
import { BumpkinItem, ITEM_NAMES } from "features/game/types/bumpkin";
import { InventoryItemName } from "features/game/types/game";
import { CollectionName } from "features/game/types/marketplace";

export type TradeType = "instant" | "onchain";

export const ITEM_TRADE_TYPES: {
  collectibles: Record<InventoryItemName, TradeType>;
  wearables: Record<BumpkinItem, TradeType>;
} = {
  collectibles: {
    "Tornado Pinwheel": "instant",
    Mangrove: "instant",
    "Sunflower Seed": "instant",
    "Potato Seed": "instant",
    "Pumpkin Seed": "instant",
    "Carrot Seed": "instant",
    "Cabbage Seed": "instant",
    "Beetroot Seed": "instant",
    "Cauliflower Seed": "instant",
    "Parsnip Seed": "instant",
    "Radish Seed": "instant",
    "Wheat Seed": "instant",
    "Kale Seed": "instant",
    "Apple Seed": "instant",
    "Blueberry Seed": "instant",
    "Orange Seed": "instant",
    "Magic Bean": "instant",
    "Eggplant Seed": "instant",
    "Corn Seed": "instant",
    "Banana Plant": "instant",
    "Sunpetal Seed": "instant",
    "Bloom Seed": "instant",
    "Lily Seed": "instant",
    "Soybean Seed": "instant",
    "Grape Seed": "instant",
    "Rice Seed": "instant",
    "Olive Seed": "instant",
    "Tomato Seed": "instant",
    "Lemon Seed": "instant",
    "Barley Seed": "instant",
    Sunflower: "instant",
    Potato: "instant",
    Pumpkin: "instant",
    Carrot: "instant",
    Cabbage: "instant",
    Beetroot: "instant",
    Cauliflower: "instant",
    Parsnip: "instant",
    Radish: "instant",
    Wheat: "instant",
    Kale: "instant",
    Apple: "instant",
    Blueberry: "instant",
    Orange: "instant",
    Eggplant: "instant",
    Corn: "instant",
    Banana: "instant",
    "Red Pansy": "instant",
    "Yellow Pansy": "instant",
    "Purple Pansy": "instant",
    "White Pansy": "instant",
    "Blue Pansy": "instant",
    "Red Cosmos": "instant",
    "Yellow Cosmos": "instant",
    "Purple Cosmos": "instant",
    "White Cosmos": "instant",
    "Blue Cosmos": "instant",
    "Red Balloon Flower": "instant",
    "Yellow Balloon Flower": "instant",
    "Purple Balloon Flower": "instant",
    "White Balloon Flower": "instant",
    "Blue Balloon Flower": "instant",
    "Red Carnation": "instant",
    "Yellow Carnation": "instant",
    "Purple Carnation": "instant",
    "White Carnation": "instant",
    "Blue Carnation": "instant",
    "Prism Petal": "instant",
    "Celestial Frostbloom": "instant",
    "Primula Enigma": "instant",
    "Red Daffodil": "instant",
    "Yellow Daffodil": "instant",
    "Purple Daffodil": "instant",
    "White Daffodil": "instant",
    "Blue Daffodil": "instant",
    "Red Lotus": "instant",
    "Yellow Lotus": "instant",
    "Purple Lotus": "instant",
    "White Lotus": "instant",
    "Blue Lotus": "instant",
    Soybean: "instant",
    Grape: "instant",
    Rice: "instant",
    Olive: "instant",
    Tomato: "instant",
    Lemon: "instant",
    Barley: "instant",
    Axe: "instant",
    Pickaxe: "instant",
    "Stone Pickaxe": "instant",
    "Iron Pickaxe": "instant",
    Hammer: "onchain",
    Rod: "instant",
    "Rusty Shovel": "instant",
    Shovel: "instant",
    "Sand Shovel": "instant",
    "Sand Drill": "instant",
    "Gold Pickaxe": "instant",
    "Oil Drill": "instant",
    "Petting Hand": "instant",
    Brush: "instant",
    "Music Box": "instant",
    "Sunflower Statue": "onchain",
    "Potato Statue": "onchain",
    "Christmas Tree": "onchain",
    Scarecrow: "onchain",
    "Farm Cat": "onchain",
    "Farm Dog": "onchain",
    Gnome: "onchain",
    "Chicken Coop": "onchain",
    "Gold Egg": "onchain",
    "Golden Cauliflower": "onchain",
    "Sunflower Tombstone": "onchain",
    "Sunflower Rock": "onchain",
    "Goblin Crown": "onchain",
    Fountain: "onchain",
    "Woody the Beaver": "onchain",
    "Apprentice Beaver": "onchain",
    "Foreman Beaver": "onchain",
    "Mysterious Parsnip": "onchain",
    "Carrot Sword": "onchain",
    Nancy: "onchain",
    Kuebiko: "onchain",
    "Nyon Statue": "onchain",
    "Farmer Bath": "onchain",
    "Homeless Tent": "onchain",
    "Mysterious Head": "onchain",
    "Golden Bonsai": "instant",
    "Rock Golem": "onchain",
    "Tunnel Mole": "onchain",
    "Rocky the Mole": "onchain",
    Nugget: "onchain",
    "Wicker Man": "instant",
    "Victoria Sisters": "instant",
    "Peeled Potato": "onchain",
    "Cabbage Boy": "onchain",
    "Cabbage Girl": "onchain",
    "Wood Nymph Wendy": "onchain",
    "Stellar Sunflower": "instant",
    "Potent Potato": "instant",
    "Radical Radish": "instant",
    "Immortal Pear": "instant",
    "Lady Bug": "onchain",
    "Squirrel Monkey": "onchain",
    "Black Bearry": "onchain",
    "Ayam Cemani": "instant",
    "Maneki Neko": "onchain",
    "Tiki Totem": "instant",
    "Lunar Calendar": "instant",
    "Treasure Map": "instant",
    "Heart of Davy Jones": "onchain",
    "Heart Balloons": "onchain",
    Flamingo: "onchain",
    "Blossom Tree": "onchain",
    "Iron Idol": "onchain",
    Karkinos: "onchain",
    "Mushroom House": "onchain",
    "Purple Trail": "onchain",
    Obie: "onchain",
    Maximus: "onchain",
    "Genie Lamp": "instant",
    Hoot: "onchain",
    "Basic Scarecrow": "instant",
    "Emerald Turtle": "onchain",
    "Tin Turtle": "onchain",
    Bale: "instant",
    "Sir Goldensnout": "onchain",
    "Scary Mike": "instant",
    "Laurie the Chuckle Crow": "instant",
    "Freya Fox": "onchain",
    "El Pollo Veloz": "instant",
    Poppy: "instant",
    "Grain Grinder": "instant",
    Kernaldo: "instant",
    "Queen Cornelia": "onchain",
    "Lab Grown Carrot": "instant",
    "Lab Grown Pumpkin": "instant",
    "Lab Grown Radish": "instant",
    Walrus: "onchain",
    Alba: "onchain",
    "Knowledge Crab": "onchain",
    Anchor: "onchain",
    Goblet: "onchain",
    "Rubber Ducky": "onchain",
    "Kraken Head": "onchain",
    "Skill Shrimpy": "instant",
    "Soil Krabby": "instant",
    Nana: "instant",
    "Banana Chicken": "instant",
    "Grinx's Hammer": "onchain",
    "Humming Bird": "onchain",
    "Queen Bee": "onchain",
    "Flower Fox": "instant",
    "Hungry Caterpillar": "onchain",
    "Crim Peckster": "instant",
    "Turbo Sprout": "onchain",
    Soybliss: "onchain",
    "Grape Granny": "onchain",
    "Royal Throne": "onchain",
    "Lily Egg": "onchain",
    "Knight Chicken": "instant",
    "Pumpkin Soup": "instant",
    "Roasted Cauliflower": "instant",
    Sauerkraut: "instant",
    "Radish Pie": "instant",
    "Sunflower Cake": "instant",
    "Potato Cake": "instant",
    "Pumpkin Cake": "instant",
    "Carrot Cake": "instant",
    "Cabbage Cake": "instant",
    "Beetroot Cake": "instant",
    "Cauliflower Cake": "instant",
    "Parsnip Cake": "instant",
    "Radish Cake": "instant",
    "Wheat Cake": "instant",
    "Boiled Eggs": "instant",
    "Bumpkin Broth": "instant",
    "Bumpkin Salad": "instant",
    "Goblin's Treat": "instant",
    "Mashed Potato": "instant",
    "Cauliflower Burger": "instant",
    "Club Sandwich": "instant",
    "Roast Veggies": "instant",
    Pancakes: "instant",
    "Apple Pie": "instant",
    "Blueberry Jam": "instant",
    "Fermented Carrots": "instant",
    "Honey Cake": "instant",
    "Kale & Mushroom Pie": "instant",
    "Kale Stew": "instant",
    "Mushroom Jacket Potatoes": "instant",
    "Mushroom Soup": "instant",
    "Orange Cake": "instant",
    "Sunflower Crunch": "instant",
    "Reindeer Carrot": "instant",
    "Apple Juice": "instant",
    "Orange Juice": "instant",
    "Purple Smoothie": "instant",
    "Power Smoothie": "instant",
    "Bumpkin Detox": "instant",
    "Pirate Cake": "instant",
    "Bumpkin Roast": "instant",
    "Goblin Brunch": "instant",
    "Fruit Salad": "instant",
    "Kale Omelette": "instant",
    "Cabbers n Mash": "instant",
    "Fancy Fries": "instant",
    "Bumpkin ganoush": "instant",
    Cornbread: "instant",
    "Eggplant Cake": "instant",
    Popcorn: "instant",
    Chowder: "instant",
    Gumbo: "instant",
    "Fermented Fish": "instant",
    "Banana Blast": "instant",
    "Beetroot Blaze": "instant",
    "Rapid Roast": "instant",
    "Shroom Syrup": "instant",
    "Carrot Juice": "instant",
    "Seafood Basket": "instant",
    "Fish Burger": "instant",
    "Fish n Chips": "instant",
    "Fish Omelette": "instant",
    "Fried Calamari": "instant",
    "Fried Tofu": "instant",
    "Grape Juice": "instant",
    "Ocean's Olive": "instant",
    "Quick Juice": "instant",
    "Rice Bun": "instant",
    "Slow Juice": "instant",
    "Steamed Red Rice": "instant",
    "Sushi Roll": "instant",
    "The Lot": "instant",
    "Tofu Scramble": "instant",
    Antipasto: "instant",
    Caponata: "instant",
    "Glazed Carrots": "instant",
    Paella: "instant",
    Cheese: "instant",
    "Pizza Margherita": "instant",
    "Blue Cheese": "instant",
    "Honey Cheddar": "instant",
    "Caprese Salad": "instant",
    "Sour Shake": "instant",
    "Spaghetti al Limone": "instant",
    "Lemon Cheesecake": "instant",
    Wood: "instant",
    Stone: "instant",
    Iron: "instant",
    Gold: "instant",
    Egg: "instant",
    Chicken: "instant",
    Cow: "onchain",
    Pig: "onchain",
    Sheep: "onchain",
    "Speed Chicken": "instant",
    "Fat Chicken": "instant",
    "Rich Chicken": "instant",
    Rooster: "onchain",
    Honey: "instant",
    "Wild Mushroom": "instant",
    "Magic Mushroom": "instant",
    Diamond: "onchain",
    Tree: "instant",
    "Stone Rock": "instant",
    "Iron Rock": "instant",
    "Gold Rock": "instant",
    "Crop Plot": "instant",
    "Fruit Patch": "instant",
    Boulder: "onchain",
    "Basic Land": "instant",
    Earthworm: "instant",
    Grub: "instant",
    "Red Wiggler": "instant",
    "Sprout Mix": "instant",
    "Fruitful Blend": "instant",
    "Rapid Root": "instant",
    "Fishing Lure": "instant",
    Beehive: "instant",
    "Flower Bed": "instant",
    "Crimstone Rock": "instant",
    Crimstone: "instant",
    "Sunstone Rock": "instant",
    Sunstone: "instant",
    Oil: "instant",
    "Oil Reserve": "instant",
    Leather: "instant",
    Wool: "instant",
    "Merino Wool": "instant",
    Feather: "instant",
    Milk: "instant",
    Hay: "instant",
    "Kernel Blend": "instant",
    NutriBarley: "instant",
    "Mixed Grain": "instant",
    "Barn Delight": "instant",
    Cushion: "instant",
    Timber: "instant",
    "Bee Box": "instant",
    Crimsteel: "instant",
    "Merino Cushion": "instant",
    "Kelp Fibre": "instant",
    "Hardened Leather": "instant",
    "Synthetic Fabric": "instant",
    "Ocean's Treasure": "instant",
    "Royal Bedding": "instant",
    "Royal Ornament": "instant",
    Omnifeed: "instant",
    "Green Thumb": "instant",
    "Barn Manager": "instant",
    "Seed Specialist": "instant",
    Wrangler: "instant",
    Lumberjack: "instant",
    Prospector: "instant",
    Logger: "instant",
    "Gold Rush": "instant",
    Artist: "instant",
    Coder: "instant",
    "Liquidity Provider": "instant",
    "Discord Mod": "instant",
    "Trading Ticket": "instant",
    Warrior: "instant",
    "Beta Pass": "instant",
    "Red Envelope": "instant",
    "Love Letter": "instant",
    "Block Buck": "instant",
    "Solar Flare Ticket": "instant",
    "Dawn Breaker Ticket": "instant",
    "Sunflower Supporter": "instant",
    "Solar Flare Banner": "instant",
    "Dawn Breaker Banner": "instant",
    "Witches' Eve Banner": "instant",
    "Crow Feather": "instant",
    "Gold Pass": "instant",
    "Potion Ticket": "instant",
    "Bud Ticket": "instant",
    "Bud Seedling": "onchain",
    "Catch the Kraken Banner": "instant",
    "Mermaid Scale": "instant",
    "Community Coin": "instant",
    "Arcade Token": "instant",
    "Farmhand Coupon": "instant",
    Farmhand: "instant",
    "Spring Blossom Banner": "instant",
    "Tulip Bulb": "instant",
    "Clash of Factions Banner": "instant",
    Scroll: "instant",
    "Lifetime Farmer Banner": "instant",
    "Goblin Emblem": "instant",
    "Bumpkin Emblem": "instant",
    "Sunflorian Emblem": "instant",
    "Nightshade Emblem": "instant",
    Mark: "onchain",
    "Pharaoh's Treasure Banner": "instant",
    "Amber Fossil": "instant",
    Gem: "instant",
    "Bull Run Banner": "instant",
    "Cow Skull": "instant",
    Horseshoe: "instant",
    "Trade Point": "onchain",
    "Australian Flag": "onchain",
    "Belgian Flag": "onchain",
    "Brazilian Flag": "onchain",
    "Chinese Flag": "onchain",
    "Finnish Flag": "onchain",
    "French Flag": "onchain",
    "German Flag": "onchain",
    "Indonesian Flag": "onchain",
    "Indian Flag": "onchain",
    "Iranian Flag": "onchain",
    "Italian Flag": "onchain",
    "Japanese Flag": "onchain",
    "Moroccan Flag": "onchain",
    "Dutch Flag": "onchain",
    "Philippine Flag": "onchain",
    "Polish Flag": "onchain",
    "Portuguese Flag": "onchain",
    "Russian Flag": "onchain",
    "Saudi Arabian Flag": "onchain",
    "South Korean Flag": "onchain",
    "Spanish Flag": "onchain",
    "Sunflower Flag": "onchain",
    "Thai Flag": "onchain",
    "Turkish Flag": "onchain",
    "Ukrainian Flag": "onchain",
    "American Flag": "onchain",
    "Vietnamese Flag": "onchain",
    "Canadian Flag": "onchain",
    "Singaporean Flag": "onchain",
    "British Flag": "onchain",
    "Sierra Leone Flag": "onchain",
    "Romanian Flag": "onchain",
    "Rainbow Flag": "onchain",
    "Goblin Flag": "onchain",
    "Pirate Flag": "onchain",
    "Algerian Flag": "onchain",
    "Mexican Flag": "onchain",
    "Dominican Republic Flag": "onchain",
    "Argentinian Flag": "onchain",
    "Lithuanian Flag": "onchain",
    "Malaysian Flag": "onchain",
    "Colombian Flag": "onchain",
    "Red Egg": "instant",
    "Blue Egg": "instant",
    "Yellow Egg": "instant",
    "Pink Egg": "instant",
    "Purple Egg": "instant",
    "Orange Egg": "instant",
    "Green Egg": "instant",
    "Easter Bunny": "onchain",
    "Engine Core": "onchain",
    Observatory: "onchain",
    "Goblin Key": "onchain",
    "Sunflower Key": "onchain",
    "Ancient Goblin Sword": "onchain",
    "Ancient Human Warhammer": "onchain",
    "Rapid Growth": "instant",
    "War Bond": "instant",
    "Goblin War Point": "instant",
    "Human War Point": "instant",
    "Human War Banner": "instant",
    "Goblin War Banner": "instant",
    "Jack-o-lantern": "instant",
    "Golden Crop": "instant",
    "Wooden Compass": "instant",
    "Pablo The Bunny": "onchain",
    "Iron Compass": "instant",
    "Old Bottle": "instant",
    "Emerald Compass": "instant",
    "Earn Alliance Banner": "onchain",
    "Treasure Key": "instant",
    "Luxury Key": "instant",
    "Rare Key": "instant",
    "Prize Ticket": "instant",
    "Baby Panda": "instant",
    Baozi: "instant",
    "Community Egg": "instant",
    "Hungry Hare": "instant",
    "Bumpkin Faction Banner": "instant",
    "Nightshade Faction Banner": "instant",
    "Sunflorian Faction Banner": "instant",
    "Goblin Faction Banner": "instant",
    Market: "instant",
    "Fire Pit": "instant",
    Workbench: "instant",
    Tent: "instant",
    "Water Well": "instant",
    "Hen House": "instant",
    Bakery: "instant",
    Kitchen: "instant",
    Deli: "instant",
    "Smoothie Shack": "instant",
    Toolshed: "instant",
    Warehouse: "instant",
    "Town Center": "instant",
    "Compost Bin": "instant",
    "Turbo Composter": "instant",
    "Premium Composter": "instant",
    House: "instant",
    Manor: "instant",
    Greenhouse: "instant",
    "Crop Machine": "instant",
    Barn: "instant",
    "Crafting Box": "instant",
    "Chef Apron": "onchain",
    "Chef Hat": "instant",
    "Sunflower Amulet": "onchain",
    "Carrot Amulet": "onchain",
    "Beetroot Amulet": "onchain",
    "Green Amulet": "onchain",
    "Warrior Shirt": "onchain",
    "Warrior Helmet": "onchain",
    "Warrior Pants": "onchain",
    "Sunflower Shield": "onchain",
    "Skull Hat": "onchain",
    "War Skull": "onchain",
    "War Tombstone": "onchain",
    "Undead Rooster": "onchain",
    "White Tulips": "instant",
    "Potted Sunflower": "instant",
    Cactus: "instant",
    "Basic Bear": "instant",
    "Chef Bear": "instant",
    "Construction Bear": "instant",
    "Angel Bear": "instant",
    "Badass Bear": "instant",
    "Bear Trap": "instant",
    "Brilliant Bear": "instant",
    "Classy Bear": "instant",
    "Farmer Bear": "instant",
    "Sunflower Bear": "instant",
    "Rich Bear": "instant",
    "Potted Potato": "instant",
    "Potted Pumpkin": "instant",
    "Christmas Bear": "instant",
    "Rainbow Artist Bear": "instant",
    "Christmas Snow Globe": "onchain",
    "Devil Bear": "instant",
    "Collectible Bear": "onchain",
    "Cyborg Bear": "onchain",
    "Abandoned Bear": "instant",
    "Turtle Bear": "instant",
    "T-Rex Skull": "instant",
    "Sunflower Coin": "instant",
    Foliant: "instant",
    "Skeleton King Staff": "instant",
    "Lifeguard Bear": "instant",
    "Snorkel Bear": "instant",
    "Parasaur Skull": "onchain",
    "Golden Bear Head": "onchain",
    "Pirate Bear": "instant",
    "Goblin Bear": "instant",
    Galleon: "instant",
    "Easter Bear": "instant",
    "Dinosaur Bone": "instant",
    "Human Bear": "instant",
    "Whale Bear": "instant",
    "Valentine Bear": "instant",
    "Palm Tree": "onchain",
    "Beach Ball": "onchain",
    "Easter Bush": "onchain",
    "Giant Carrot": "onchain",
    "Dirt Path": "instant",
    Bush: "instant",
    Fence: "instant",
    Shrub: "instant",
    "Luminous Lantern": "instant",
    "Radiance Lantern": "instant",
    "Aurora Lantern": "instant",
    "Bonnie's Tombstone": "instant",
    "Chestnut Fungi Stool": "instant",
    "Crimson Cap": "instant",
    "Dawn Umbrella Seat": "instant",
    "Eggplant Grill": "instant",
    "Giant Dawn Mushroom": "instant",
    "Grubnash's Tombstone": "instant",
    "Mahogany Cap": "instant",
    "Toadstool Seat": "instant",
    Clementine: "instant",
    Cobalt: "instant",
    "Shroom Glow": "instant",
    "Genie Bear": "instant",
    "Ocean Lantern": "instant",
    "Beta Bear": "onchain",
    "Field Maple": "instant",
    "Red Maple": "instant",
    "Golden Maple": "instant",
    "Pine Tree": "instant",
    "Stone Fence": "instant",
    "Solar Lantern": "instant",
    "Betty Lantern": "instant",
    "Bumpkin Lantern": "instant",
    "Eggplant Bear": "instant",
    "Goblin Lantern": "instant",
    "Dawn Flower": "instant",
    Candles: "instant",
    "Haunted Stump": "instant",
    "Spooky Tree": "instant",
    "Giant Cabbage": "instant",
    "Giant Potato": "instant",
    "Giant Pumpkin": "instant",
    "Town Sign": "instant",
    Observer: "instant",
    "Crow Rock": "instant",
    "Mini Corn Maze": "instant",
    "White Crow": "instant",
    "Lifeguard Ring": "instant",
    Surfboard: "instant",
    "Hideaway Herman": "instant",
    "Shifty Sheldon": "instant",
    "Tiki Torch": "instant",
    "Beach Umbrella": "instant",
    "Sapo Docuras": "instant",
    "Sapo Travessuras": "instant",
    "Time Warp Totem": "instant",
    "Bumpkin Nutcracker": "instant",
    "Festive Tree": "instant",
    "Pirate Bounty": "instant",
    Pearl: "instant",
    Coral: "instant",
    "Clam Shell": "instant",
    Pipi: "instant",
    Starfish: "instant",
    Seaweed: "instant",
    "Sea Cucumber": "instant",
    Crab: "instant",
    "Black Magic": "instant",
    "Golden Helios": "instant",
    Chiogga: "instant",
    "Purple Cauliflower": "instant",
    "Adirondack Potato": "instant",
    "Warty Goblin Pumpkin": "instant",
    "White Carrot": "instant",
    "Camel Bone": "instant",
    "Cockle Shell": "instant",
    Hieroglyph: "instant",
    Sand: "instant",
    Scarab: "instant",
    Vase: "instant",
    Anchovy: "instant",
    Butterflyfish: "instant",
    Blowfish: "instant",
    Clownfish: "instant",
    "Sea Bass": "instant",
    "Sea Horse": "instant",
    "Horse Mackerel": "instant",
    Squid: "instant",
    "Red Snapper": "instant",
    "Moray Eel": "instant",
    "Olive Flounder": "instant",
    Napoleanfish: "instant",
    Surgeonfish: "instant",
    "Zebra Turkeyfish": "instant",
    Ray: "instant",
    "Hammerhead shark": "instant",
    Tuna: "instant",
    "Mahi Mahi": "instant",
    "Blue Marlin": "instant",
    Oarfish: "instant",
    "Football fish": "instant",
    Sunfish: "instant",
    Coelacanth: "instant",
    "Whale Shark": "instant",
    "Barred Knifejaw": "instant",
    "Saw Shark": "instant",
    "White Shark": "instant",
    "Twilight Anglerfish": "instant",
    "Starlight Tuna": "instant",
    "Radiant Ray": "instant",
    "Phantom Barracuda": "instant",
    "Gilded Swordfish": "instant",
    "Kraken Tentacle": "instant",
    Angelfish: "instant",
    Halibut: "instant",
    Parrotfish: "instant",
    "Crimson Carp": "instant",
    "Battle Fish": "instant",
    "Lemon Shark": "instant",
    "Longhorn Cowfish": "instant",
    "White Festive Fox": "instant",
    Rug: "instant",
    Wardrobe: "instant",
    "Sunrise Bloom Rug": "instant",
    "Blossom Royale": "onchain",
    Rainbow: "instant",
    "Enchanted Rose": "instant",
    "Flower Cart": "instant",
    Capybara: "instant",
    Blossombeard: "instant",
    "Flower Rug": "instant",
    "Tea Rug": "instant",
    "Green Field Rug": "instant",
    "Fancy Rug": "instant",
    Clock: "instant",
    Vinny: "instant",
    "Desert Gnome": "instant",
    "Gaucho Rug": "instant",
    "Bullseye Board": "instant",
    "Chess Rug": "instant",
    Cluckapult: "instant",
    "Golden Gallant": "instant",
    "Golden Garrison": "instant",
    "Golden Guardian": "instant",
    "Novice Knight": "instant",
    "Regular Pawn": "instant",
    "Rookie Rook": "instant",
    "Silver Sentinel": "instant",
    "Silver Squire": "instant",
    "Silver Stallion": "instant",
    "Trainee Target": "instant",
    "Twister Rug": "instant",
    "Battlecry Drum": "instant",
    "Rice Panda": "instant",
    "Benevolence Flag": "instant",
    "Devotion Flag": "instant",
    "Generosity Flag": "instant",
    "Splendor Flag": "instant",
    "Jelly Lamp": "instant",
    "Paint Can": "instant",
    "Sunflorian Throne": "instant",
    "Nightshade Throne": "instant",
    "Goblin Throne": "instant",
    "Bumpkin Throne": "instant",
    "Golden Sunflorian Egg": "instant",
    "Goblin Mischief Egg": "instant",
    "Bumpkin Charm Egg": "instant",
    "Nightshade Veil Egg": "instant",
    "Emerald Goblin Goblet": "instant",
    "Opal Sunflorian Goblet": "instant",
    "Sapphire Bumpkin Goblet": "instant",
    "Amethyst Nightshade Goblet": "instant",
    "Golden Faction Goblet": "instant",
    "Ruby Faction Goblet": "instant",
    "Sunflorian Bunting": "instant",
    "Nightshade Bunting": "instant",
    "Goblin Bunting": "instant",
    "Bumpkin Bunting": "instant",
    "Sunflorian Candles": "instant",
    "Nightshade Candles": "instant",
    "Goblin Candles": "instant",
    "Bumpkin Candles": "instant",
    "Sunflorian Left Wall Sconce": "instant",
    "Nightshade Left Wall Sconce": "instant",
    "Goblin Left Wall Sconce": "instant",
    "Bumpkin Left Wall Sconce": "instant",
    "Sunflorian Right Wall Sconce": "instant",
    "Nightshade Right Wall Sconce": "instant",
    "Goblin Right Wall Sconce": "instant",
    "Bumpkin Right Wall Sconce": "instant",
    "Gourmet Hourglass": "instant",
    "Harvest Hourglass": "instant",
    "Timber Hourglass": "instant",
    "Ore Hourglass": "instant",
    "Orchard Hourglass": "instant",
    "Blossom Hourglass": "instant",
    "Fisher's Hourglass": "instant",
    "Sunflorian Faction Rug": "instant",
    "Nightshade Faction Rug": "instant",
    "Goblin Faction Rug": "instant",
    "Bumpkin Faction Rug": "instant",
    "Goblin Gold Champion": "instant",
    "Goblin Silver Champion": "instant",
    "Goblin Bronze Champion": "instant",
    "Bumpkin Bronze Champion": "instant",
    "Bumpkin Gold Champion": "instant",
    "Bumpkin Silver Champion": "instant",
    "Nightshade Bronze Champion": "instant",
    "Nightshade Gold Champion": "instant",
    "Nightshade Silver Champion": "instant",
    "Sunflorian Bronze Champion": "instant",
    "Sunflorian Gold Champion": "instant",
    "Sunflorian Silver Champion": "instant",
    "Desert Rose": "instant",
    "Hapy Jar": "instant",
    "Duamutef Jar": "instant",
    "Qebehsenuef Jar": "instant",
    "Imsety Jar": "instant",
    Cannonball: "instant",
    Sarcophagus: "instant",
    "Clay Tablet": "instant",
    "Snake in Jar": "instant",
    "Reveling Lemon": "instant",
    "Anubis Jackal": "instant",
    Sundial: "instant",
    "Sand Golem": "instant",
    "Cactus King": "instant",
    "Lemon Frog": "instant",
    "Scarab Beetle": "instant",
    "Pharaoh Chicken": "instant",
    "Adrift Ark": "instant",
    Castellan: "instant",
    "Sunlit Citadel": "instant",
    "Pharaoh Gnome": "onchain",
    "Lemon Tea Bath": "onchain",
    "Tomato Clown": "onchain",
    Pyramid: "onchain",
    Oasis: "onchain",
    "Paper Reed": "instant",
    "Baobab Tree": "instant",
    Camel: "instant",
    "Tomato Bombard": "instant",
    "Stone Beetle": "instant",
    "Iron Beetle": "instant",
    "Gold Beetle": "instant",
    "Fairy Circle": "instant",
    Squirrel: "instant",
    Macaw: "instant",
    Butterfly: "instant",
    Marty: "instant",
    Miffy: "instant",
    Mog: "instant",
    Morty: "instant",
    "Basic Bed": "instant",
    "Sturdy Bed": "instant",
    "Floral Bed": "instant",
    "Fisher Bed": "instant",
    "Pirate Bed": "instant",
    "Cow Bed": "instant",
    "Desert Bed": "instant",
    "Royal Bed": "instant",
    "Cow Scratcher": "instant",
    "Spinning Wheel": "instant",
    "Sleepy Rug": "instant",
    Meteorite: "instant",
    "Sheaf of Plenty": "instant",
    "Mechanical Bull": "instant",
    "King of Bears": "instant",
    "Moo-ver": "onchain",
    "Swiss Whiskers": "onchain",
    Cluckulator: "onchain",
    UFO: "onchain",
    Chicory: "instant",
    Wagon: "instant",
    "Black Sheep": "onchain",
    "Alien Chicken": "instant",
    Mootant: "instant",
    "Toxic Tuft": "instant",
    "Crop Circle": "instant",
    "Halloween Scarecrow": "instant",
    "Vampire Bear": "instant",
    "Super Totem": "instant",
    "Egg Basket": "instant",
    "Trade Cake": "instant",
    "Christmas Stocking": "instant",
    "Golden Christmas Stocking": "instant",
    "Cozy Fireplace": "instant",
    "Christmas Rug": "instant",
    "Christmas Candle": "instant",
    "Santa Penguin": "instant",
    "Penguin Pool": "instant",
    Snowman: "instant",
    "Festive Toy Train": "instant",
    "Golden Cow": "onchain",
  },
  wearables: {
    "New Years Crown": "instant",
    "Beige Farmer Potion": "instant",
    "Dark Brown Farmer Potion": "instant",
    "Light Brown Farmer Potion": "instant",
    "Goblin Potion": "instant",
    "Basic Hair": "instant",
    "Rancher Hair": "instant",
    "Explorer Hair": "instant",
    "Red Farmer Shirt": "instant",
    "Yellow Farmer Shirt": "instant",
    "Blue Farmer Shirt": "instant",
    "Chef Apron": "onchain",
    "Warrior Shirt": "onchain",
    "Farmer Overalls": "instant",
    "Lumberjack Overalls": "instant",
    "Farmer Pants": "instant",
    "Warrior Pants": "onchain",
    "Black Farmer Boots": "instant",
    "Farmer Pitchfork": "instant",
    "Farmer Hat": "onchain",
    "Chef Hat": "onchain",
    "Warrior Helmet": "onchain",
    "Sunflower Amulet": "onchain",
    "Carrot Amulet": "onchain",
    "Beetroot Amulet": "onchain",
    "Green Amulet": "onchain",
    "Sunflower Shield": "onchain",
    "Farm Background": "instant",
    "Fancy Top": "onchain",
    "Brown Boots": "instant",
    "Brown Suspenders": "instant",
    "Fancy Pants": "onchain",
    "Maiden Skirt": "onchain",
    "Maiden Top": "onchain",
    "Peasant Skirt": "onchain",
    "SFL T-Shirt": "instant",
    "Yellow Boots": "instant",
    "Buzz Cut": "instant",
    "Parlour Hair": "instant",
    Axe: "instant",
    Sword: "instant",
    "Blue Suspenders": "instant",
    "Forest Background": "instant",
    "Seashore Background": "instant",
    Blondie: "instant",
    "Brown Long Hair": "instant",
    "Sun Spots": "instant",
    "White Long Hair": "instant",
    "Cemetery Background": "onchain",
    "Teal Mohawk": "onchain",
    "Space Background": "onchain",
    Parsnip: "onchain",
    "Jail Background": "onchain",
    "Golden Spatula": "onchain",
    "Artist Scarf": "onchain",
    "Bumpkin Art Competition Merch": "onchain",
    "Project Dignity Hoodie": "instant",
    "Developer Hoodie": "onchain",
    "Blacksmith Hair": "onchain",
    Hammer: "onchain",
    "Bumpkin Boots": "onchain",
    "Fire Shirt": "onchain",
    "Red Long Hair": "onchain",
    "Snowman Onesie": "onchain",
    "Reindeer Suit": "onchain",
    "Shark Onesie": "onchain",
    "Christmas Background": "onchain",
    "Devil Wings": "onchain",
    "Angel Wings": "onchain",
    "Fire Hair": "onchain",
    "Luscious Hair": "onchain",
    "Ancient War Hammer": "onchain",
    "Ancient Goblin Sword": "onchain",
    "Mountain View Background": "onchain",
    "Skull Hat": "onchain",
    "Reindeer Antlers": "onchain",
    "Santa Hat": "onchain",
    "Pineapple Shirt": "onchain",
    "China Town Background": "onchain",
    "Lion Dance Mask": "onchain",
    "Fruit Picker Shirt": "instant",
    "Fruit Picker Apron": "instant",
    "Fruit Bowl": "instant",
    "Striped Blue Shirt": "instant",
    "Peg Leg": "instant",
    "Pirate Potion": "instant",
    "Pirate Hat": "instant",
    "Pirate General Coat": "onchain",
    "Pirate Pants": "onchain",
    "Pirate Leather Polo": "onchain",
    "Crab Claw": "onchain",
    "Pirate Scimitar": "onchain",
    "Cupid Hair": "onchain",
    "Cupid Dress": "onchain",
    "Cupid Sandals": "onchain",
    "Love Quiver": "onchain",
    "SFL Office Background": "onchain",
    "Bumpkin Puppet": "onchain",
    "Goblin Puppet": "onchain",
    "Hawaiian Shirt": "onchain",
    "Bear Onesie": "onchain",
    "Frog Onesie": "onchain",
    "Tiger Onesie": "onchain",
    "Beach Sarong": "onchain",
    "Lifeguard Hat": "onchain",
    "Lifeguard Pants": "onchain",
    "Lifeguard Shirt": "onchain",
    "Sleeping Otter": "onchain",
    "Tropical Sarong": "onchain",
    "Sequence Hat": "onchain",
    "Sequence Shirt": "onchain",
    "St Patricks Hat": "onchain",
    "Bunny Onesie": "onchain",
    "Light Brown Worried Farmer Potion": "onchain",
    "Polkastarter Shirt": "onchain",
    "Beach Trunks": "onchain",
    "Club Polo": "onchain",
    "Dawn Breaker Background": "onchain",
    "Dawn Lamp": "onchain",
    "Eggplant Onesie": "onchain",
    "Fox Hat": "instant",
    "Grave Diggers Shovel": "onchain",
    "Infected Potion": "onchain",
    "Mushroom Hat": "onchain",
    "Mushroom Lamp": "onchain",
    "Mushroom Lights Background": "onchain",
    "Mushroom Pants": "onchain",
    "Mushroom Shield": "instant",
    "Mushroom Shoes": "instant",
    "Mushroom Sweater": "instant",
    "Rash Vest": "onchain",
    "Squid Hat": "onchain",
    "Striped Red Shirt": "instant",
    "Striped Yellow Shirt": "instant",
    "Summer Top": "onchain",
    "Sunburst Potion": "onchain",
    "Water Gun": "onchain",
    "Wavy Pants": "onchain",
    "White Turtle Neck": "onchain",
    "Trial Tee": "onchain",
    "Auction Megaphone": "onchain",
    "Auctioneer Slacks": "onchain",
    "Bidder's Brocade": "onchain",
    "Harry's Hat": "onchain",
    "Leather Shoes": "onchain",
    "Tangerine Hair": "onchain",
    "Straw Hat": "instant",
    "Traveller's Backpack": "onchain",
    "Traveller's Pants": "onchain",
    "Traveller's Shirt": "onchain",
    "Witching Wardrobe": "instant",
    "Witch's Broom": "instant",
    "Infernal Bumpkin Potion": "instant",
    "Infernal Goblin Potion": "instant",
    "Imp Costume": "instant",
    "Ox Costume": "instant",
    "Luna's Hat": "onchain",
    "Infernal Pitchfork": "onchain",
    "Infernal Horns": "onchain",
    Cattlegrim: "onchain",
    "Crumple Crown": "onchain",
    "Merch Bucket Hat": "instant",
    "Merch Coffee Mug": "instant",
    "Dawn Breaker Tee": "instant",
    "Merch Tee": "instant",
    "Merch Hoodie": "instant",
    "Birthday Hat": "instant",
    "Double Harvest Cap": "instant",
    "Streamer Helmet": "instant",
    "Corn Onesie": "instant",
    "Crow Wings": "instant",
    "Witches' Eve Tee": "instant",
    "Wise Beard": "instant",
    "Pumpkin Hat": "instant",
    "Wise Book": "onchain",
    "Wise Hair": "onchain",
    "Wise Robes": "instant",
    "Wise Slacks": "onchain",
    "Wise Staff": "onchain",
    "Greyed Glory": "instant",
    "Tattered Jacket": "instant",
    "Hoary Chin": "onchain",
    "Tattered Slacks": "onchain",
    "Old Shoes": "onchain",
    "Bat Wings": "instant",
    "Gothic Twilight": "onchain",
    "Dark Enchantment Gown": "onchain",
    "Goth Hair": "onchain",
    "Pale Potion": "instant",
    "Stretched Jeans": "onchain",
    "Skull Shirt": "instant",
    "Victorian Hat": "instant",
    "Boater Hat": "onchain",
    "Antique Dress": "onchain",
    "Crimson Skirt": "onchain",
    "Chic Gala Blouse": "onchain",
    "Ash Ponytail": "onchain",
    "Pink Ponytail": "instant",
    "Silver Streaks": "onchain",
    "Brown Rancher Hair": "instant",
    "Parsnip Horns": "instant",
    "Potato Suit": "instant",
    "Whale Hat": "onchain",
    "Pumpkin Shirt": "instant",
    Halo: "instant",
    Kama: "instant",
    "Grey Merch Hoodie": "instant",
    "Unicorn Horn": "instant",
    "Unicorn Hat": "instant",
    "Feather Hat": "onchain",
    "Valoria Wreath": "instant",
    "Earn Alliance Sombrero": "instant",
    "Fresh Catch Vest": "instant",
    "Fish Pro Vest": "instant",
    "Reel Fishing Vest": "instant",
    "Clown Shirt": "instant",
    "Luminous Anglerfish Topper": "instant",
    "Abyssal Angler Hat": "onchain",
    Harpoon: "onchain",
    "Ancient Rod": "onchain",
    "Fishing Hat": "instant",
    Trident: "instant",
    "Infernal Rod": "onchain",
    "Bucket O' Worms": "instant",
    "Coconut Mask": "onchain",
    "Crab Trap": "instant",
    "Seaside Tank Top": "instant",
    "Fish Trap": "onchain",
    "Fishing Pants": "instant",
    "Angler Waders": "instant",
    "Fishing Spear": "instant",
    "Flip Flops": "onchain",
    Wellies: "instant",
    "Saw Fish": "onchain",
    "Skinning Knife": "instant",
    "Sunflower Rod": "instant",
    "Tackle Box": "onchain",
    "Mermaid Potion": "onchain",
    "Squirrel Monkey Potion": "onchain",
    "Koi Fish Hat": "instant",
    "Normal Fish Hat": "instant",
    "Stockeye Salmon Onesie": "instant",
    "Tiki Armor": "instant",
    "Tiki Mask": "instant",
    "Tiki Pants": "instant",
    "Banana Amulet": "onchain",
    "Banana Onesie": "instant",
    "Basic Dumbo": "onchain",
    "Companion Cap": "instant",
    "Dazzling Dumbo": "onchain",
    "Deep Sea Helm": "instant",
    "Gloomy Dumbo": "onchain",
    "Pickaxe Shark": "onchain",
    "Seedling Hat": "instant",
    "Stormy Dumbo": "onchain",
    "Ugly Christmas Sweater": "instant",
    "Candy Cane": "onchain",
    "Elf Hat": "instant",
    "Elf Potion": "instant",
    "Elf Shoes": "onchain",
    "Elf Suit": "instant",
    "Santa Beard": "instant",
    "Santa Suit": "instant",
    "Butterfly Wings": "instant",
    "Cozy Hoodie": "onchain",
    "New Years Tiara": "instant",
    "Northern Lights Background": "onchain",
    "Short Shorts": "onchain",
    "Winter Jacket": "onchain",
    "Beehive Staff": "instant",
    "Bee Smoker": "instant",
    "Bee Suit": "instant",
    "Bee Wings": "instant",
    "Beekeeper Hat": "instant",
    "Beekeeper Suit": "instant",
    "Crimstone Boots": "instant",
    "Crimstone Pants": "instant",
    "Crimstone Armor": "instant",
    "Gardening Overalls": "instant",
    "Crimstone Hammer": "onchain",
    "Crimstone Amulet": "onchain",
    "Full Bloom Shirt": "instant",
    "Blue Blossom Shirt": "instant",
    "Fairy Sandals": "instant",
    "Daisy Tee": "instant",
    "Propeller Hat": "instant",
    "Honeycomb Shield": "onchain",
    "Hornet Mask": "onchain",
    "Flower Crown": "onchain",
    "Blue Monarch Dress": "instant",
    "Green Monarch Dress": "instant",
    "Orange Monarch Dress": "instant",
    "Blue Monarch Shirt": "instant",
    "Green Monarch Shirt": "instant",
    "Orange Monarch Shirt": "instant",
    "Queen Bee Crown": "instant",
    "Rose Dress": "instant",
    "Blue Rose Dress": "instant",
    "Chicken Hat": "instant",
    "Lucky Red Hat": "instant",
    "Lucky Red Suit": "instant",
    "Valentine's Field Background": "instant",
    "Love's Topper": "instant",
    "Oil Can": "onchain",
    "Non La Hat": "onchain",
    "Olive Shield": "onchain",
    "Paw Shield": "onchain",
    "Royal Robe": "instant",
    Crown: "instant",
    Pan: "onchain",
    "Soybean Onesie": "instant",
    "Gift Giver": "instant",
    "Olive Royalty Shirt": "instant",
    "Royal Scepter": "onchain",
    "Tofu Mask": "instant",
    "Goblin Armor": "instant",
    "Goblin Helmet": "instant",
    "Goblin Pants": "instant",
    "Goblin Sabatons": "instant",
    "Goblin Axe": "instant",
    "Nightshade Armor": "instant",
    "Nightshade Helmet": "instant",
    "Nightshade Pants": "instant",
    "Nightshade Sabatons": "instant",
    "Nightshade Sword": "instant",
    "Bumpkin Armor": "instant",
    "Bumpkin Helmet": "instant",
    "Bumpkin Sword": "instant",
    "Bumpkin Pants": "instant",
    "Bumpkin Sabatons": "instant",
    "Sunflorian Armor": "instant",
    "Sunflorian Sword": "instant",
    "Sunflorian Helmet": "instant",
    "Sunflorian Pants": "instant",
    "Sunflorian Sabatons": "instant",
    "Cap n Bells": "instant",
    "Knight Gambit": "instant",
    "Pixel Perfect Hoodie": "instant",
    "Queen's Crown": "instant",
    "Royal Dress": "instant",
    Motley: "instant",
    "Royal Braids": "instant",
    "Painter's Cap": "instant",
    "Festival of Colors Background": "instant",
    "Pharaoh Headdress": "instant",
    "Camel Onesie": "instant",
    "Amber Amulet": "instant",
    "Desert Background": "onchain",
    "Explorer Shirt": "instant",
    "Dev Wrench": "onchain",
    "Rock Hammer": "instant",
    "Sun Scarab Amulet": "instant",
    "Explorer Hat": "instant",
    "Oil Protection Hat": "instant",
    "Explorer Shorts": "instant",
    "Oil Overalls": "onchain",
    "Desert Merchant Turban": "instant",
    "Desert Merchant Shoes": "instant",
    "Desert Merchant Suit": "instant",
    "Desert Camel Background": "instant",
    "Water Gourd": "instant",
    "Rocket Onesie": "onchain",
    "Coin Aura": "onchain",
    "Ankh Shirt": "instant",
    "Ancient Shovel": "onchain",
    "Infernal Drill": "onchain",
    "Lemon Shield": "onchain",
    "Scarab Wings": "instant",
    "Grape Pants": "instant",
    "Bionic Drill": "instant",
    "Fossil Head": "onchain",
    "Bumpkin Crown": "instant",
    "Goblin Crown": "instant",
    "Nightshade Crown": "instant",
    "Sunflorian Crown": "instant",
    "Bumpkin Shield": "instant",
    "Goblin Shield": "instant",
    "Nightshade Shield": "instant",
    "Sunflorian Shield": "instant",
    "Bumpkin Quiver": "instant",
    "Goblin Quiver": "instant",
    "Nightshade Quiver": "instant",
    "Sunflorian Quiver": "instant",
    "Bumpkin Medallion": "instant",
    "Goblin Medallion": "instant",
    "Nightshade Medallion": "instant",
    "Sunflorian Medallion": "instant",
    "Pumpkin Plaza Background": "instant",
    "Goblin Retreat Background": "instant",
    "Kingdom Background": "instant",
    "Gam3s Cap": "instant",
    "Cowboy Hat": "instant",
    "Cowboy Shirt": "instant",
    "Cowboy Trouser": "instant",
    "Cowboy Boots": "onchain",
    "Infernal Bullwhip": "onchain",
    "White Sheep Onesie": "instant",
    "Black Sheep Onesie": "onchain",
    "Chicken Suit": "onchain",
    "Cowgirl Skirt": "instant",
    "Merino Jumper": "onchain",
    "Dream Scarf": "instant",
    "Cowbell Necklace": "onchain",
    "Milk Apron": "instant",
    "Shepherd Staff": "onchain",
    "Sol & Luna": "onchain",
    "Fossil Armor": "onchain",
    "Fossil Pants": "onchain",
    "Rice Shirt": "onchain",
    Sickle: "onchain",
    "Speed Boots": "onchain",
    "Tomato Apron": "onchain",
    "Adventurer's Suit": "instant",
    "Adventurer's Torch": "instant",
    "Pumpkin Head": "instant",
    "Gingerbread Onesie": "instant",
  },
};

export const MAX_INSTANT_SFL_TRADE = 250;

export const getTradeType = ({
  collection,
  id,
  trade,
}: {
  collection: CollectionName;
  id: number;
  trade: {
    sfl: number;
  };
}) => {
  if (collection === "buds") return "onchain";
  if (collection === "wearables") {
    const item = ITEM_NAMES[id];

    if (trade.sfl > MAX_INSTANT_SFL_TRADE) {
      return "onchain";
    }

    return ITEM_TRADE_TYPES.wearables[item];
  }

  if (trade.sfl > MAX_INSTANT_SFL_TRADE) {
    return "onchain";
  }

  return ITEM_TRADE_TYPES.collectibles[KNOWN_ITEMS[id]];
};
