/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type BlockBucksBought = ContractEventLog<{
  farmId: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface BuyBlockBucks extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): BuyBlockBucks;
  clone(): BuyBlockBucks;
  methods: {
    addGameRole(_game: string): NonPayableTransactionObject<void>;

    buyBlockBucksMATIC(
      _signature: string | number[],
      _farmId: number | string | BN,
      _blockBuckAmount: number | string | BN,
      _fee: number | string | BN,
      _deadline: number | string | BN
    ): PayableTransactionObject<void>;

    buyBlockBucksUSDC(
      _signature: string | number[],
      _farmId: number | string | BN,
      _blockBuckAmount: number | string | BN,
      _fee: number | string | BN,
      _deadline: number | string | BN
    ): NonPayableTransactionObject<void>;

    feeWallet(): NonPayableTransactionObject<string>;

    gameAddGameRole(_game: string): NonPayableTransactionObject<void>;

    gameRemoveGameRole(_game: string): NonPayableTransactionObject<void>;

    gameRoles(arg0: string): NonPayableTransactionObject<boolean>;

    owner(): NonPayableTransactionObject<string>;

    removeGameRole(_game: string): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    signer(): NonPayableTransactionObject<string>;

    transferFeeWallet(_feeWallet: string): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    transferSigner(_signer: string): NonPayableTransactionObject<void>;
  };
  events: {
    BlockBucksBought(cb?: Callback<BlockBucksBought>): EventEmitter;
    BlockBucksBought(
      options?: EventOptions,
      cb?: Callback<BlockBucksBought>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "BlockBucksBought", cb: Callback<BlockBucksBought>): void;
  once(
    event: "BlockBucksBought",
    options: EventOptions,
    cb: Callback<BlockBucksBought>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
