/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface Withdrawals extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Withdrawals;
  clone(): Withdrawals;
  methods: {
    addGameRole(_game: string): NonPayableTransactionObject<void>;

    buds(): NonPayableTransactionObject<string>;

    bumpkin(): NonPayableTransactionObject<string>;

    bumpkinDetails(): NonPayableTransactionObject<string>;

    bumpkinWearables(): NonPayableTransactionObject<string>;

    communityTax(): NonPayableTransactionObject<string>;

    destroy(): NonPayableTransactionObject<void>;

    executed(arg0: string | number[]): NonPayableTransactionObject<boolean>;

    farm(): NonPayableTransactionObject<string>;

    gameAddGameRole(_game: string): NonPayableTransactionObject<void>;

    gameRemoveGameRole(_game: string): NonPayableTransactionObject<void>;

    gameRoles(arg0: string): NonPayableTransactionObject<boolean>;

    getResourceTaxes(
      _ids: (number | string | BN)[]
    ): NonPayableTransactionObject<string[]>;

    inventory(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    removeGameRole(_game: string): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    resourceTax(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    session(): NonPayableTransactionObject<string>;

    setCommunityTax(
      _tax: number | string | BN
    ): NonPayableTransactionObject<void>;

    setCommunityTreasuy(
      _communityTreasury: string
    ): NonPayableTransactionObject<void>;

    setLiquify(_liquify: boolean): NonPayableTransactionObject<void>;

    setResourceTaxes(
      _ids: (number | string | BN)[],
      _amounts: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    setSession(_session: string): NonPayableTransactionObject<void>;

    setTeamWithrawalMinimum(
      _minimum: number | string | BN
    ): NonPayableTransactionObject<void>;

    setWishingWell(_wishingWell: string): NonPayableTransactionObject<void>;

    setWishingWellTax(
      _tax: number | string | BN
    ): NonPayableTransactionObject<void>;

    token(): NonPayableTransactionObject<string>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    transferSigner(_signer: string): NonPayableTransactionObject<void>;

    transferWithdrawFeeWallet(_team: string): NonPayableTransactionObject<void>;

    wishingWellTax(): NonPayableTransactionObject<string>;

    withdrawBuds(
      signature: string | number[],
      sessionId: string | number[],
      nextSessionId: string | number[],
      deadline: number | string | BN,
      farmId: number | string | BN,
      budIds: (number | string | BN)[]
    ): NonPayableTransactionObject<boolean>;

    withdrawItems(
      signature: string | number[],
      sessionId: string | number[],
      nextSessionId: string | number[],
      deadline: number | string | BN,
      farmId: number | string | BN,
      ids: (number | string | BN)[],
      amounts: (number | string | BN)[]
    ): NonPayableTransactionObject<boolean>;

    withdrawSFL(
      signature: string | number[],
      sessionId: string | number[],
      nextSessionId: string | number[],
      deadline: number | string | BN,
      farmId: number | string | BN,
      sfl: number | string | BN,
      tax: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    withdrawWearables(
      signature: string | number[],
      sessionId: string | number[],
      nextSessionId: string | number[],
      deadline: number | string | BN,
      farmId: number | string | BN,
      ids: (number | string | BN)[],
      amounts: (number | string | BN)[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
