/**
 * GENERATED by docs/phaser-farm-migration/scripts/gif-to-spritesheet.js —
 * do not edit by hand; re-run the script to refresh.
 *
 * Maps every animated-GIF art URL the farm renders to its converted vertical
 * strip. The DOM shows these GIFs in <img> tags; Phaser plays the strip
 * instead, so the engine animates what the DOM animates.
 */
import { CONFIG } from "lib/config";
import sftsFountainGif from "assets/sfts/fountain.gif";
import sftsBeaverGif from "assets/sfts/beaver.gif";
import sftsApprenticeBeaverGif from "assets/sfts/apprentice_beaver.gif";
import sftsConstructionBeaverGif from "assets/sfts/construction_beaver.gif";
import sftsKuebikoGif from "assets/sfts/kuebiko.gif";
import sftsTunnelMoleGif from "assets/sfts/tunnel_mole.gif";
import sftsRockyMoleGif from "assets/sfts/rocky_mole.gif";
import sftsNuggetGif from "assets/sfts/nugget.gif";
import sftsWoodNymphWendyGif from "assets/sfts/wood_nymph_wendy.gif";
import sftsCabbageBoyGif from "assets/sfts/cabbage_boy.gif";
import sftsCabbageGirlGif from "assets/sfts/cabbage_girl.gif";
import sftsPeeledPotatoGif from "assets/sfts/peeled_potato.gif";
import sftsLadybugGif from "assets/sfts/ladybug.gif";
import sftsBlackBearGif from "assets/sfts/black_bear.gif";
import sftsObieGif from "assets/sfts/obie.gif";
import sftsMaximusGif from "assets/sfts/maximus.gif";
import sftsTomatoClownGif from "assets/sfts/tomato_clown.gif";
import sftsLabGrownCarrotGif from "assets/sfts/lab_grown_carrot.gif";
import sftsLabGrownPumpkinGif from "assets/sfts/lab_grown_pumpkin.gif";
import sftsLabGrownRadishGif from "assets/sfts/lab_grown_radish.gif";
import sftsVictoriaSistersGif from "assets/sfts/victoria_sisters.gif";
import sftsManekiNekoGif from "assets/sfts/maneki_neko.gif";
import sftsHeartOfDavyJonesGif from "assets/sfts/heart_of_davy_jones.gif";
import sftsPabloBunnyGif from "assets/sfts/pablo_bunny.gif";
import sftsSapoDocurasGif from "assets/sfts/sapo_docuras.gif";
import sftsSapoTravessuraGif from "assets/sfts/sapo_travessura.gif";
import sftsRevelingLemonGif from "assets/sfts/reveling_lemon.gif";
import sftsEasterEasterBunnyGif from "assets/sfts/easter/easter_bunny.gif";
import decorationsSnowglobeGif from "assets/decorations/snowglobe.gif";
import decorationsBannersSpringBannerGif from "assets/decorations/banners/spring_banner.gif";
import decorationsBannersWindsOfChangeBannerLoopGif from "assets/decorations/banners/winds-of-change_banner_loop.gif";
import decorationsIsleBoatGif from "assets/decorations/isle_boat.gif";
import eventsGoldenCropGoldenCropGif from "assets/events/golden_crop/golden_crop.gif";
import sftsFountain from "assets/animations/sfts_fountain.png";
import sftsBeaver from "assets/animations/sfts_beaver.png";
import sftsApprenticeBeaver from "assets/animations/sfts_apprentice_beaver.png";
import sftsConstructionBeaver from "assets/animations/sfts_construction_beaver.png";
import sftsKuebiko from "assets/animations/sfts_kuebiko.png";
import sftsTunnelMole from "assets/animations/sfts_tunnel_mole.png";
import sftsRockyMole from "assets/animations/sfts_rocky_mole.png";
import sftsNugget from "assets/animations/sfts_nugget.png";
import sftsWoodNymphWendy from "assets/animations/sfts_wood_nymph_wendy.png";
import sftsCabbageBoy from "assets/animations/sfts_cabbage_boy.png";
import sftsCabbageGirl from "assets/animations/sfts_cabbage_girl.png";
import sftsPeeledPotato from "assets/animations/sfts_peeled_potato.png";
import sftsLadybug from "assets/animations/sfts_ladybug.png";
import sftsBlackBear from "assets/animations/sfts_black_bear.png";
import sftsObie from "assets/animations/sfts_obie.png";
import sftsMaximus from "assets/animations/sfts_maximus.png";
import sftsTomatoClown from "assets/animations/sfts_tomato_clown.png";
import sftsLabGrownCarrot from "assets/animations/sfts_lab_grown_carrot.png";
import sftsLabGrownPumpkin from "assets/animations/sfts_lab_grown_pumpkin.png";
import sftsLabGrownRadish from "assets/animations/sfts_lab_grown_radish.png";
import sftsVictoriaSisters from "assets/animations/sfts_victoria_sisters.png";
import sftsManekiNeko from "assets/animations/sfts_maneki_neko.png";
import sftsHeartOfDavyJones from "assets/animations/sfts_heart_of_davy_jones.png";
import sftsPabloBunny from "assets/animations/sfts_pablo_bunny.png";
import sftsSapoDocuras from "assets/animations/sfts_sapo_docuras.png";
import sftsSapoTravessura from "assets/animations/sfts_sapo_travessura.png";
import sftsRevelingLemon from "assets/animations/sfts_reveling_lemon.png";
import sftsEasterEasterBunny from "assets/animations/sfts_easter_easter_bunny.png";
import decorationsSnowglobe from "assets/animations/decorations_snowglobe.png";
import decorationsBannersSpringBanner from "assets/animations/decorations_banners_spring_banner.png";
import decorationsBannersWindsOfChangeBannerLoop from "assets/animations/decorations_banners_winds-of-change_banner_loop.png";
import decorationsIsleBoat from "assets/animations/decorations_isle_boat.png";
import eventsGoldenCropGoldenCrop from "assets/animations/events_golden_crop_golden_crop.png";
import buildingsSmoke from "assets/animations/buildings_smoke.png";
import fxSparkle2 from "assets/animations/fx_sparkle2.png";
import landLevelsPontoon from "assets/animations/land_levels_pontoon.png";
import npcsArtisianDoing from "assets/animations/npcs_artisian_doing.png";
import npcsArtisian from "assets/animations/npcs_artisian.png";
import npcsChefDoing from "assets/animations/npcs_chef_doing.png";
import npcsChef from "assets/animations/npcs_chef.png";
import npcsCookDoing from "assets/animations/npcs_cook_doing.png";
import npcsCook from "assets/animations/npcs_cook.png";
import npcsGoblinChefDoing from "assets/animations/npcs_goblin_chef_doing.png";
import npcsGoblinChef from "assets/animations/npcs_goblin_chef.png";
import npcsGoblinSnorkling from "assets/animations/npcs_goblin_snorkling.png";
import npcsGoblinSwimming from "assets/animations/npcs_goblin_swimming.png";
import npcsNevilleDoing from "assets/animations/npcs_neville_doing.png";
import npcsSmoothieMaking from "assets/animations/npcs_smoothie_making.png";
import npcsSmoothie from "assets/animations/npcs_smoothie.png";
import npcsSwimmer from "assets/animations/npcs_swimmer.png";

export type AnimatedArt = {
  sheet: string;
  frameWidth: number;
  frameHeight: number;
  frames: number;
  fps: number;
};

/** Keyed by the ORIGINAL art URL, so lookups work wherever art is resolved. */
export const ANIMATED_ART: Record<string, AnimatedArt> = Object.fromEntries([
  [
    sftsFountainGif,
    { sheet: sftsFountain, frameWidth: 26, frameHeight: 29, frames: 6, fps: 3 },
  ],
  [
    sftsBeaverGif,
    { sheet: sftsBeaver, frameWidth: 15, frameHeight: 16, frames: 9, fps: 14 },
  ],
  [
    sftsApprenticeBeaverGif,
    {
      sheet: sftsApprenticeBeaver,
      frameWidth: 15,
      frameHeight: 16,
      frames: 9,
      fps: 14,
    },
  ],
  [
    sftsConstructionBeaverGif,
    {
      sheet: sftsConstructionBeaver,
      frameWidth: 15,
      frameHeight: 19,
      frames: 9,
      fps: 14,
    },
  ],
  [
    sftsKuebikoGif,
    { sheet: sftsKuebiko, frameWidth: 30, frameHeight: 30, frames: 17, fps: 3 },
  ],
  [
    sftsTunnelMoleGif,
    {
      sheet: sftsTunnelMole,
      frameWidth: 20,
      frameHeight: 16,
      frames: 27,
      fps: 10,
    },
  ],
  [
    sftsRockyMoleGif,
    {
      sheet: sftsRockyMole,
      frameWidth: 21,
      frameHeight: 20,
      frames: 27,
      fps: 10,
    },
  ],
  [
    sftsNuggetGif,
    { sheet: sftsNugget, frameWidth: 21, frameHeight: 22, frames: 27, fps: 10 },
  ],
  [
    sftsWoodNymphWendyGif,
    {
      sheet: sftsWoodNymphWendy,
      frameWidth: 15,
      frameHeight: 24,
      frames: 9,
      fps: 14,
    },
  ],
  [
    sftsCabbageBoyGif,
    {
      sheet: sftsCabbageBoy,
      frameWidth: 16,
      frameHeight: 16,
      frames: 9,
      fps: 14,
    },
  ],
  [
    sftsCabbageGirlGif,
    {
      sheet: sftsCabbageGirl,
      frameWidth: 16,
      frameHeight: 16,
      frames: 9,
      fps: 14,
    },
  ],
  [
    sftsPeeledPotatoGif,
    {
      sheet: sftsPeeledPotato,
      frameWidth: 15,
      frameHeight: 15,
      frames: 9,
      fps: 14,
    },
  ],
  [
    sftsLadybugGif,
    { sheet: sftsLadybug, frameWidth: 16, frameHeight: 15, frames: 9, fps: 14 },
  ],
  [
    sftsBlackBearGif,
    {
      sheet: sftsBlackBear,
      frameWidth: 16,
      frameHeight: 18,
      frames: 4,
      fps: 8,
    },
  ],
  [
    sftsObieGif,
    { sheet: sftsObie, frameWidth: 15, frameHeight: 19, frames: 9, fps: 14 },
  ],
  [
    sftsMaximusGif,
    { sheet: sftsMaximus, frameWidth: 23, frameHeight: 26, frames: 9, fps: 14 },
  ],
  [
    sftsTomatoClownGif,
    {
      sheet: sftsTomatoClown,
      frameWidth: 19,
      frameHeight: 30,
      frames: 4,
      fps: 10,
    },
  ],
  [
    sftsLabGrownCarrotGif,
    {
      sheet: sftsLabGrownCarrot,
      frameWidth: 12,
      frameHeight: 22,
      frames: 9,
      fps: 7,
    },
  ],
  [
    sftsLabGrownPumpkinGif,
    {
      sheet: sftsLabGrownPumpkin,
      frameWidth: 12,
      frameHeight: 20,
      frames: 9,
      fps: 7,
    },
  ],
  [
    sftsLabGrownRadishGif,
    {
      sheet: sftsLabGrownRadish,
      frameWidth: 14,
      frameHeight: 21,
      frames: 9,
      fps: 7,
    },
  ],
  [
    sftsVictoriaSistersGif,
    {
      sheet: sftsVictoriaSisters,
      frameWidth: 32,
      frameHeight: 32,
      frames: 60,
      fps: 2,
    },
  ],
  [
    sftsManekiNekoGif,
    {
      sheet: sftsManekiNeko,
      frameWidth: 16,
      frameHeight: 16,
      frames: 20,
      fps: 7,
    },
  ],
  [
    sftsHeartOfDavyJonesGif,
    {
      sheet: sftsHeartOfDavyJones,
      frameWidth: 23,
      frameHeight: 22,
      frames: 9,
      fps: 3,
    },
  ],
  [
    sftsPabloBunnyGif,
    {
      sheet: sftsPabloBunny,
      frameWidth: 14,
      frameHeight: 20,
      frames: 9,
      fps: 14,
    },
  ],
  [
    sftsSapoDocurasGif,
    {
      sheet: sftsSapoDocuras,
      frameWidth: 20,
      frameHeight: 24,
      frames: 41,
      fps: 13,
    },
  ],
  [
    sftsSapoTravessuraGif,
    {
      sheet: sftsSapoTravessura,
      frameWidth: 20,
      frameHeight: 24,
      frames: 41,
      fps: 13,
    },
  ],
  [
    sftsRevelingLemonGif,
    {
      sheet: sftsRevelingLemon,
      frameWidth: 23,
      frameHeight: 39,
      frames: 48,
      fps: 25,
    },
  ],
  [
    sftsEasterEasterBunnyGif,
    {
      sheet: sftsEasterEasterBunny,
      frameWidth: 14,
      frameHeight: 20,
      frames: 9,
      fps: 14,
    },
  ],
  [
    decorationsSnowglobeGif,
    {
      sheet: decorationsSnowglobe,
      frameWidth: 20,
      frameHeight: 24,
      frames: 6,
      fps: 7,
    },
  ],
  [
    decorationsBannersSpringBannerGif,
    {
      sheet: decorationsBannersSpringBanner,
      frameWidth: 22,
      frameHeight: 36,
      frames: 2,
      fps: 7,
    },
  ],
  [
    decorationsBannersWindsOfChangeBannerLoopGif,
    {
      sheet: decorationsBannersWindsOfChangeBannerLoop,
      frameWidth: 16,
      frameHeight: 30,
      frames: 4,
      fps: 1,
    },
  ],
  [
    decorationsIsleBoatGif,
    {
      sheet: decorationsIsleBoat,
      frameWidth: 104,
      frameHeight: 46,
      frames: 7,
      fps: 10,
    },
  ],
  [
    eventsGoldenCropGoldenCropGif,
    {
      sheet: eventsGoldenCropGoldenCrop,
      frameWidth: 10,
      frameHeight: 13,
      frames: 7,
      fps: 5,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/buildings/smoke.gif`,
    {
      sheet: buildingsSmoke,
      frameWidth: 20,
      frameHeight: 32,
      frames: 30,
      fps: 10,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/fx/sparkle2.gif`,
    { sheet: fxSparkle2, frameWidth: 7, frameHeight: 7, frames: 16, fps: 8 },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/pontoon.gif`,
    {
      sheet: landLevelsPontoon,
      frameWidth: 129,
      frameHeight: 57,
      frames: 23,
      fps: 14,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/artisian_doing.gif`,
    {
      sheet: npcsArtisianDoing,
      frameWidth: 17,
      frameHeight: 17,
      frames: 8,
      fps: 10,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/artisian.gif`,
    {
      sheet: npcsArtisian,
      frameWidth: 15,
      frameHeight: 17,
      frames: 9,
      fps: 11,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/chef_doing.gif`,
    {
      sheet: npcsChefDoing,
      frameWidth: 16,
      frameHeight: 19,
      frames: 8,
      fps: 10,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/chef.gif`,
    { sheet: npcsChef, frameWidth: 15, frameHeight: 18, frames: 9, fps: 14 },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/cook_doing.gif`,
    {
      sheet: npcsCookDoing,
      frameWidth: 16,
      frameHeight: 17,
      frames: 8,
      fps: 10,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/cook.gif`,
    { sheet: npcsCook, frameWidth: 14, frameHeight: 16, frames: 8, fps: 14 },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_chef_doing.gif`,
    {
      sheet: npcsGoblinChefDoing,
      frameWidth: 25,
      frameHeight: 27,
      frames: 8,
      fps: 10,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_chef.gif`,
    {
      sheet: npcsGoblinChef,
      frameWidth: 22,
      frameHeight: 25,
      frames: 9,
      fps: 14,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_snorkling.gif`,
    {
      sheet: npcsGoblinSnorkling,
      frameWidth: 24,
      frameHeight: 21,
      frames: 38,
      fps: 10,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_swimming.gif`,
    {
      sheet: npcsGoblinSwimming,
      frameWidth: 96,
      frameHeight: 64,
      frames: 63,
      fps: 13,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/neville_doing.gif`,
    {
      sheet: npcsNevilleDoing,
      frameWidth: 20,
      frameHeight: 19,
      frames: 8,
      fps: 14,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/smoothie_making.gif`,
    {
      sheet: npcsSmoothieMaking,
      frameWidth: 15,
      frameHeight: 18,
      frames: 9,
      fps: 11,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/smoothie.gif`,
    {
      sheet: npcsSmoothie,
      frameWidth: 14,
      frameHeight: 17,
      frames: 9,
      fps: 14,
    },
  ],
  [
    `${CONFIG.PROTECTED_IMAGE_URL}/npcs/swimmer.gif`,
    {
      sheet: npcsSwimmer,
      frameWidth: 16,
      frameHeight: 16,
      frames: 12,
      fps: 10,
    },
  ],
]);

/** The converted strip for an art URL, when one exists. */
export const animatedArtFor = (
  url: string | undefined,
): AnimatedArt | undefined => (url ? ANIMATED_ART[url] : undefined);
