/**
 * GENERATED by docs/phaser-farm-migration/scripts/gif-to-spritesheet.js —
 * do not edit by hand; re-run the script to refresh.
 *
 * Maps every animated-GIF art URL the farm renders to its converted vertical
 * strip. The DOM shows these GIFs in <img> tags; Phaser plays the strip
 * instead, so the engine animates what the DOM animates.
 */
import { CONFIG } from "lib/config";
import sftsFountainGif from "assets/sfts/fountain.gif";
import sftsBeaverGif from "assets/sfts/beaver.gif";
import sftsApprenticeBeaverGif from "assets/sfts/apprentice_beaver.gif";
import sftsConstructionBeaverGif from "assets/sfts/construction_beaver.gif";
import sftsKuebikoGif from "assets/sfts/kuebiko.gif";
import sftsTunnelMoleGif from "assets/sfts/tunnel_mole.gif";
import sftsRockyMoleGif from "assets/sfts/rocky_mole.gif";
import sftsNuggetGif from "assets/sfts/nugget.gif";
import sftsWoodNymphWendyGif from "assets/sfts/wood_nymph_wendy.gif";
import sftsCabbageBoyGif from "assets/sfts/cabbage_boy.gif";
import sftsCabbageGirlGif from "assets/sfts/cabbage_girl.gif";
import sftsPeeledPotatoGif from "assets/sfts/peeled_potato.gif";
import sftsLadybugGif from "assets/sfts/ladybug.gif";
import sftsBlackBearGif from "assets/sfts/black_bear.gif";
import sftsObieGif from "assets/sfts/obie.gif";
import sftsMaximusGif from "assets/sfts/maximus.gif";
import sftsTomatoClownGif from "assets/sfts/tomato_clown.gif";
import sftsLabGrownCarrotGif from "assets/sfts/lab_grown_carrot.gif";
import sftsLabGrownPumpkinGif from "assets/sfts/lab_grown_pumpkin.gif";
import sftsLabGrownRadishGif from "assets/sfts/lab_grown_radish.gif";
import sftsVictoriaSistersGif from "assets/sfts/victoria_sisters.gif";
import sftsManekiNekoGif from "assets/sfts/maneki_neko.gif";
import sftsHeartOfDavyJonesGif from "assets/sfts/heart_of_davy_jones.gif";
import sftsPabloBunnyGif from "assets/sfts/pablo_bunny.gif";
import sftsSapoDocurasGif from "assets/sfts/sapo_docuras.gif";
import sftsSapoTravessuraGif from "assets/sfts/sapo_travessura.gif";
import sftsRevelingLemonGif from "assets/sfts/reveling_lemon.gif";
import sftsEasterEasterBunnyGif from "assets/sfts/easter/easter_bunny.gif";
import decorationsSnowglobeGif from "assets/decorations/snowglobe.gif";
import decorationsBannersSpringBannerGif from "assets/decorations/banners/spring_banner.gif";
import decorationsBannersWindsOfChangeBannerLoopGif from "assets/decorations/banners/winds-of-change_banner_loop.gif";
import decorationsIsleBoatGif from "assets/decorations/isle_boat.gif";
import eventsGoldenCropGoldenCropGif from "assets/events/golden_crop/golden_crop.gif";
import animalsChickensAyamCemaniGif from "assets/animals/chickens/ayam_cemani.webp";
import animalsChickensBananaChickenGif from "assets/animals/chickens/banana_chicken.webp";
import animalsChickensElPolloVelozGif from "assets/animals/chickens/el_pollo_veloz.webp";
import animalsChickensFatChickenGif from "assets/animals/chickens/fat_chicken.webp";
import animalsChickensGoldenCockerelGif from "assets/animals/chickens/golden_cockerel.webp";
import animalsChickensKnightChickenGif from "assets/animals/chickens/knight_chicken.webp";
import animalsChickensRichChickenGif from "assets/animals/chickens/rich_chicken.webp";
import animalsChickensRoosterGif from "assets/animals/chickens/rooster.webp";
import animalsChickensSpeedChickenGif from "assets/animals/chickens/speed_chicken.webp";
import animalsChickensUndeadChickenGif from "assets/animals/chickens/undead_chicken.webp";
import buildingsCraftingBoxAnimationGif from "assets/buildings/crafting_box_animation.webp";
import buildingsLevelOne2Gif from "assets/buildings/level-one-2.webp";
import buildingsLevelOneStartGif from "assets/buildings/level-one-start.webp";
import buildingsTentGif from "assets/buildings/tent.webp";
import decorationsBannersBullRunBannerGif from "assets/decorations/banners/bull_run_banner.webp";
import decorationsCandlesOnGif from "assets/decorations/candles_on.webp";
import decorationsObserverGif from "assets/decorations/observer.webp";
import decorationsWhiteCrowGif from "assets/decorations/white_crow.webp";
import resourcesLavaLavaPitAnimationGif from "assets/resources/lava/lava_pit_animation.webp";
import resourcesOilSpurtingWellGif from "assets/resources/oil/spurting_well.webp";
import sftsAlbaGif from "assets/sfts/alba.webp";
import sftsAlienChickenGif from "assets/sfts/alien_chicken.webp";
import sftsBaoziGif from "assets/sfts/baozi.webp";
import sftsBluePaintBucketGif from "assets/sfts/blue_paint_bucket.webp";
import sftsBlueSlimeBalloonGif from "assets/sfts/blue_slime_balloon.webp";
import sftsCerberusGif from "assets/sfts/cerberus.webp";
import sftsCetusGif from "assets/sfts/cetus.webp";
import sftsCluckulatorGif from "assets/sfts/cluckulator.webp";
import sftsColorWheelGif from "assets/sfts/color_wheel.webp";
import sftsEasterEasterBunnyEggsGif from "assets/sfts/easter/easter_bunny_eggs.webp";
import sftsEasterDonationEggGif from "assets/sfts/easter_donation_egg.webp";
import sftsFarmCatGif from "assets/sfts/farm_cat.webp";
import sftsFarmDogGif from "assets/sfts/farm_dog.webp";
import sftsFishKiteGif from "assets/sfts/fish_kite.webp";
import sftsFlagsAlgerianFlagGif from "assets/sfts/flags/algerian_flag.webp";
import sftsFlagsArgentinianFlagGif from "assets/sfts/flags/argentinian_flag.webp";
import sftsFlagsAustraliaFlagGif from "assets/sfts/flags/australia_flag.webp";
import sftsFlagsBelgiumFlagGif from "assets/sfts/flags/belgium_flag.webp";
import sftsFlagsBrazilFlagGif from "assets/sfts/flags/brazil_flag.webp";
import sftsFlagsBritishFlagGif from "assets/sfts/flags/british_flag.webp";
import sftsFlagsCanadianFlagGif from "assets/sfts/flags/canadian_flag.webp";
import sftsFlagsChinaFlagGif from "assets/sfts/flags/china_flag.webp";
import sftsFlagsColombianFlagGif from "assets/sfts/flags/colombian_flag.webp";
import sftsFlagsDominicanRepublicFlagGif from "assets/sfts/flags/dominican_republic_flag.webp";
import sftsFlagsFinlandFlagGif from "assets/sfts/flags/finland_flag.webp";
import sftsFlagsFranceFlagGif from "assets/sfts/flags/france_flag.webp";
import sftsFlagsGermanyFlagGif from "assets/sfts/flags/germany_flag.webp";
import sftsFlagsGoblinFlagGif from "assets/sfts/flags/goblin_flag.webp";
import sftsFlagsIndiaFlagGif from "assets/sfts/flags/india_flag.webp";
import sftsFlagsIndonesiaFlagGif from "assets/sfts/flags/indonesia_flag.webp";
import sftsFlagsIranFlagGif from "assets/sfts/flags/iran_flag.webp";
import sftsFlagsItalyFlagGif from "assets/sfts/flags/italy_flag.webp";
import sftsFlagsJapanFlagGif from "assets/sfts/flags/japan_flag.webp";
import sftsFlagsLithuanianFlagGif from "assets/sfts/flags/lithuanian_flag.webp";
import sftsFlagsMalaysianFlagGif from "assets/sfts/flags/malaysian_flag.webp";
import sftsFlagsMexicanFlagGif from "assets/sfts/flags/mexican_flag.webp";
import sftsFlagsMoroccoFlagGif from "assets/sfts/flags/morocco_flag.webp";
import sftsFlagsNetherlandsFlagGif from "assets/sfts/flags/netherlands_flag.webp";
import sftsFlagsPhilippinesFlagGif from "assets/sfts/flags/philippines_flag.webp";
import sftsFlagsPirateFlagGif from "assets/sfts/flags/pirate_flag.webp";
import sftsFlagsPolandFlagGif from "assets/sfts/flags/poland_flag.webp";
import sftsFlagsPortugalFlagGif from "assets/sfts/flags/portugal_flag.webp";
import sftsFlagsRainbowFlagGif from "assets/sfts/flags/rainbow_flag.webp";
import sftsFlagsRomanianFlagGif from "assets/sfts/flags/romanian_flag.webp";
import sftsFlagsRussiaFlagGif from "assets/sfts/flags/russia_flag.webp";
import sftsFlagsSaudiArabiaFlagGif from "assets/sfts/flags/saudi_arabia_flag.webp";
import sftsFlagsSierraLeoneFlagGif from "assets/sfts/flags/sierra_leone_flag.webp";
import sftsFlagsSingaporeanFlagGif from "assets/sfts/flags/singaporean_flag.webp";
import sftsFlagsSouthKoreaFlagGif from "assets/sfts/flags/south_korea_flag.webp";
import sftsFlagsSpainFlagGif from "assets/sfts/flags/spain_flag.webp";
import sftsFlagsSunflowerFlagGif from "assets/sfts/flags/sunflower_flag.webp";
import sftsFlagsThailandFlagGif from "assets/sfts/flags/thailand_flag.webp";
import sftsFlagsTurkeyFlagGif from "assets/sfts/flags/turkey_flag.webp";
import sftsFlagsUkraineFlagGif from "assets/sfts/flags/ukraine_flag.webp";
import sftsFlagsUsaFlagGif from "assets/sfts/flags/usa_flag.webp";
import sftsFlagsVietnamFlagGif from "assets/sfts/flags/vietnam_flag.webp";
import sftsFloatingToyGif from "assets/sfts/floating_toy.webp";
import sftsFlowerCoinGif from "assets/sfts/flower_coin.webp";
import sftsFoolsGoldGif from "assets/sfts/fools_gold.webp";
import sftsFrozenMeatGif from "assets/sfts/frozen_meat.webp";
import sftsGiftTurtleGif from "assets/sfts/gift_turtle.webp";
import sftsGreenPaintBucketGif from "assets/sfts/green_paint_bucket.webp";
import sftsGuillotineGif from "assets/sfts/guillotine.webp";
import sftsHauntedHouseGif from "assets/sfts/haunted_house.webp";
import sftsHauntedTombGif from "assets/sfts/haunted_tomb.webp";
import sftsHummingbirdGif from "assets/sfts/hummingbird.webp";
import sftsJellyLampGif from "assets/sfts/jelly_lamp.webp";
import sftsKiteGif from "assets/sfts/kite.webp";
import sftsMechaBullGif from "assets/sfts/mecha_bull.webp";
import sftsMimicEggGif from "assets/sfts/mimic_egg.webp";
import sftsMimicSlimeBallGif from "assets/sfts/mimic_slime_ball.webp";
import sftsMimicWingedSlimeBallGif from "assets/sfts/mimic_winged_slime_ball.webp";
import sftsMomMomObservatoryAnimationGif from "assets/sfts/mom/mom_observatory_animation.webp";
import sftsMomObservatoryGif from "assets/sfts/mom/observatory.webp";
import sftsMooVerGif from "assets/sfts/moo_ver.webp";
import sftsOrangeTunnelBunnyGif from "assets/sfts/orange_tunnel_bunny.webp";
import sftsPenguinPoolGif from "assets/sfts/penguin_pool.webp";
import sftsPenguinSurpriseGif from "assets/sfts/penguin_surprise.webp";
import sftsPetsBullsBisonGif from "assets/sfts/pets/bulls/Bison.webp";
import sftsPetsBullsOxenGif from "assets/sfts/pets/bulls/Oxen.webp";
import sftsPetsBullsBisonAsleepGif from "assets/sfts/pets/bulls/bison_asleep.webp";
import sftsPetsBullsMudhornGif from "assets/sfts/pets/bulls/mudhorn.webp";
import sftsPetsBullsMudhornAsleepGif from "assets/sfts/pets/bulls/mudhorn_asleep.webp";
import sftsPetsBullsOxenAsleepGif from "assets/sfts/pets/bulls/oxen_asleep.webp";
import sftsPetsCatsButtersGif from "assets/sfts/pets/cats/butters.webp";
import sftsPetsCatsButtersAsleepGif from "assets/sfts/pets/cats/butters_asleep.webp";
import sftsPetsCatsMeowchiGif from "assets/sfts/pets/cats/meowchi.webp";
import sftsPetsCatsMeowchiAsleepGif from "assets/sfts/pets/cats/meowchi_asleep.webp";
import sftsPetsCatsSmokeyGif from "assets/sfts/pets/cats/smokey.webp";
import sftsPetsCatsSmokeyAsleepGif from "assets/sfts/pets/cats/smokey_asleep.webp";
import sftsPetsDogsBarkleyGif from "assets/sfts/pets/dogs/barkley.webp";
import sftsPetsDogsBarkleyAsleepGif from "assets/sfts/pets/dogs/barkley_asleep.webp";
import sftsPetsDogsBiscuitGif from "assets/sfts/pets/dogs/biscuit.webp";
import sftsPetsDogsBiscuitAsleepGif from "assets/sfts/pets/dogs/biscuit_asleep.webp";
import sftsPetsDogsCloudyGif from "assets/sfts/pets/dogs/cloudy.webp";
import sftsPetsDogsCloudyAsleepGif from "assets/sfts/pets/dogs/cloudy_asleep.webp";
import sftsPetsHamstersNibblesGif from "assets/sfts/pets/hamsters/nibbles.webp";
import sftsPetsHamstersNibblesAsleepGif from "assets/sfts/pets/hamsters/nibbles_asleep.webp";
import sftsPetsHamstersPeanutGif from "assets/sfts/pets/hamsters/peanut.webp";
import sftsPetsHamstersPeanutsAsleepGif from "assets/sfts/pets/hamsters/peanuts_asleep.webp";
import sftsPetsHorsesBurroGif from "assets/sfts/pets/horses/burro.webp";
import sftsPetsHorsesBurroAsleepGif from "assets/sfts/pets/horses/burro_asleep.webp";
import sftsPetsHorsesPintoGif from "assets/sfts/pets/horses/pinto.webp";
import sftsPetsHorsesPintoAsleepGif from "assets/sfts/pets/horses/pinto_asleep.webp";
import sftsPetsHorsesRoanGif from "assets/sfts/pets/horses/roan.webp";
import sftsPetsHorsesRoanAsleepGif from "assets/sfts/pets/horses/roan_asleep.webp";
import sftsPetsHorsesStallionGif from "assets/sfts/pets/horses/stallion.webp";
import sftsPetsHorsesStallionAsleepGif from "assets/sfts/pets/horses/stallion_asleep.webp";
import sftsPetsOwlsFlickerGif from "assets/sfts/pets/owls/flicker.webp";
import sftsPetsOwlsFlickerAsleepGif from "assets/sfts/pets/owls/flicker_asleep.webp";
import sftsPetsOwlsPippinGif from "assets/sfts/pets/owls/pippin.webp";
import sftsPetsOwlsPippinAsleepGif from "assets/sfts/pets/owls/pippin_asleep.webp";
import sftsPetsOwlsTwizzleGif from "assets/sfts/pets/owls/twizzle.webp";
import sftsPetsOwlsTwizzleAsleepGif from "assets/sfts/pets/owls/twizzle_asleep.webp";
import sftsPetsPenguinsPipGif from "assets/sfts/pets/penguins/pip.webp";
import sftsPetsPenguinsPipAsleepGif from "assets/sfts/pets/penguins/pip_asleep.webp";
import sftsPetsPenguinsSkipperGif from "assets/sfts/pets/penguins/skipper.webp";
import sftsPetsPenguinsSkipperAsleepGif from "assets/sfts/pets/penguins/skipper_asleep.webp";
import sftsPetsPenguinsWaddlesGif from "assets/sfts/pets/penguins/waddles.webp";
import sftsPetsPenguinsWaddlesAsleepGif from "assets/sfts/pets/penguins/waddles_asleep.webp";
import sftsPetsRamseyGif from "assets/sfts/pets/ramsey.webp";
import sftsPonyToyGif from "assets/sfts/pony_toy.webp";
import sftsPorkJellyGif from "assets/sfts/pork_jelly.webp";
import sftsPotatoMutantGif from "assets/sfts/potato_mutant.webp";
import sftsPurplePaintBucketGif from "assets/sfts/purple_paint_bucket.webp";
import sftsQueenBeeGif from "assets/sfts/queen_bee.webp";
import sftsRadishMutantGif from "assets/sfts/radish_mutant.webp";
import sftsRainbowFlowerGif from "assets/sfts/rainbow_flower.webp";
import sftsRainbowPorkJellyGif from "assets/sfts/rainbow_pork_jelly.webp";
import sftsRaveyardGif from "assets/sfts/raveyard.webp";
import sftsRedNoseReindeerGif from "assets/sfts/red_nose_reindeer.webp";
import sftsRedSlimeBalloonGif from "assets/sfts/red_slime_balloon.webp";
import sftsRockGolemGif from "assets/sfts/rock_golem.webp";
import sftsSantaPenguinGif from "assets/sfts/santa_penguin.webp";
import sftsSkillShrimpyGif from "assets/sfts/skill_shrimpy.webp";
import sftsSpinningWheelGif from "assets/sfts/spinning_wheel.webp";
import sftsSummerChickenGif from "assets/sfts/summer_chicken.webp";
import sftsSunflowerMutantGif from "assets/sfts/sunflower_mutant.webp";
import sftsThermalStoneGif from "assets/sfts/thermal_stone.webp";
import sftsTornadoPinwheelGif from "assets/sfts/tornado_pinwheel.webp";
import sftsTuxedoClausGif from "assets/sfts/tuxedo_claus.webp";
import sftsUfoGif from "assets/sfts/ufo.webp";
import sftsVampireCoffinGif from "assets/sfts/vampire_coffin.webp";
import sftsWalrusGif from "assets/sfts/walrus.webp";
import sftsWhiteTunnelBunnyGif from "assets/sfts/white_tunnel_bunny.webp";
import sftsWinterAlpacaGif from "assets/sfts/winter_alpaca.webp";
import sftsWitchsCauldronGif from "assets/sfts/witchs_cauldron.webp";
import sftsYellowPaintBucketGif from "assets/sfts/yellow_paint_bucket.webp";
import sftsFountain from "assets/animations/sfts_fountain.png";
import sftsBeaver from "assets/animations/sfts_beaver.png";
import sftsApprenticeBeaver from "assets/animations/sfts_apprentice_beaver.png";
import sftsConstructionBeaver from "assets/animations/sfts_construction_beaver.png";
import sftsKuebiko from "assets/animations/sfts_kuebiko.png";
import sftsTunnelMole from "assets/animations/sfts_tunnel_mole.png";
import sftsRockyMole from "assets/animations/sfts_rocky_mole.png";
import sftsNugget from "assets/animations/sfts_nugget.png";
import sftsWoodNymphWendy from "assets/animations/sfts_wood_nymph_wendy.png";
import sftsCabbageBoy from "assets/animations/sfts_cabbage_boy.png";
import sftsCabbageGirl from "assets/animations/sfts_cabbage_girl.png";
import sftsPeeledPotato from "assets/animations/sfts_peeled_potato.png";
import sftsLadybug from "assets/animations/sfts_ladybug.png";
import sftsBlackBear from "assets/animations/sfts_black_bear.png";
import sftsObie from "assets/animations/sfts_obie.png";
import sftsMaximus from "assets/animations/sfts_maximus.png";
import sftsTomatoClown from "assets/animations/sfts_tomato_clown.png";
import sftsLabGrownCarrot from "assets/animations/sfts_lab_grown_carrot.png";
import sftsLabGrownPumpkin from "assets/animations/sfts_lab_grown_pumpkin.png";
import sftsLabGrownRadish from "assets/animations/sfts_lab_grown_radish.png";
import sftsVictoriaSisters from "assets/animations/sfts_victoria_sisters.png";
import sftsManekiNeko from "assets/animations/sfts_maneki_neko.png";
import sftsHeartOfDavyJones from "assets/animations/sfts_heart_of_davy_jones.png";
import sftsPabloBunny from "assets/animations/sfts_pablo_bunny.png";
import sftsSapoDocuras from "assets/animations/sfts_sapo_docuras.png";
import sftsSapoTravessura from "assets/animations/sfts_sapo_travessura.png";
import sftsRevelingLemon from "assets/animations/sfts_reveling_lemon.png";
import sftsEasterEasterBunny from "assets/animations/sfts_easter_easter_bunny.png";
import decorationsSnowglobe from "assets/animations/decorations_snowglobe.png";
import decorationsBannersSpringBanner from "assets/animations/decorations_banners_spring_banner.png";
import decorationsBannersWindsOfChangeBannerLoop from "assets/animations/decorations_banners_winds-of-change_banner_loop.png";
import decorationsIsleBoat from "assets/animations/decorations_isle_boat.png";
import eventsGoldenCropGoldenCrop from "assets/animations/events_golden_crop_golden_crop.png";
import animalsChickensAyamCemani from "assets/animations/animals_chickens_ayam_cemani.png";
import animalsChickensBananaChicken from "assets/animations/animals_chickens_banana_chicken.png";
import animalsChickensElPolloVeloz from "assets/animations/animals_chickens_el_pollo_veloz.png";
import animalsChickensFatChicken from "assets/animations/animals_chickens_fat_chicken.png";
import animalsChickensGoldenCockerel from "assets/animations/animals_chickens_golden_cockerel.png";
import animalsChickensKnightChicken from "assets/animations/animals_chickens_knight_chicken.png";
import animalsChickensRichChicken from "assets/animations/animals_chickens_rich_chicken.png";
import animalsChickensRooster from "assets/animations/animals_chickens_rooster.png";
import animalsChickensSpeedChicken from "assets/animations/animals_chickens_speed_chicken.png";
import animalsChickensUndeadChicken from "assets/animations/animals_chickens_undead_chicken.png";
import buildingsCraftingBoxAnimation from "assets/animations/buildings_crafting_box_animation.png";
import buildingsLevelOne2 from "assets/animations/buildings_level-one-2.png";
import buildingsLevelOneStart from "assets/animations/buildings_level-one-start.png";
import buildingsTent from "assets/animations/buildings_tent.png";
import decorationsBannersBullRunBanner from "assets/animations/decorations_banners_bull_run_banner.png";
import decorationsCandlesOn from "assets/animations/decorations_candles_on.png";
import decorationsObserver from "assets/animations/decorations_observer.png";
import decorationsWhiteCrow from "assets/animations/decorations_white_crow.png";
import resourcesLavaLavaPitAnimation from "assets/animations/resources_lava_lava_pit_animation.png";
import resourcesOilSpurtingWell from "assets/animations/resources_oil_spurting_well.png";
import sftsAlba from "assets/animations/sfts_alba.png";
import sftsAlienChicken from "assets/animations/sfts_alien_chicken.png";
import sftsBaozi from "assets/animations/sfts_baozi.png";
import sftsBluePaintBucket from "assets/animations/sfts_blue_paint_bucket.png";
import sftsBlueSlimeBalloon from "assets/animations/sfts_blue_slime_balloon.png";
import sftsCerberus from "assets/animations/sfts_cerberus.png";
import sftsCetus from "assets/animations/sfts_cetus.png";
import sftsCluckulator from "assets/animations/sfts_cluckulator.png";
import sftsColorWheel from "assets/animations/sfts_color_wheel.png";
import sftsEasterEasterBunnyEggs from "assets/animations/sfts_easter_easter_bunny_eggs.png";
import sftsEasterDonationEgg from "assets/animations/sfts_easter_donation_egg.png";
import sftsFarmCat from "assets/animations/sfts_farm_cat.png";
import sftsFarmDog from "assets/animations/sfts_farm_dog.png";
import sftsFishKite from "assets/animations/sfts_fish_kite.png";
import sftsFlagsAlgerianFlag from "assets/animations/sfts_flags_algerian_flag.png";
import sftsFlagsArgentinianFlag from "assets/animations/sfts_flags_argentinian_flag.png";
import sftsFlagsAustraliaFlag from "assets/animations/sfts_flags_australia_flag.png";
import sftsFlagsBelgiumFlag from "assets/animations/sfts_flags_belgium_flag.png";
import sftsFlagsBrazilFlag from "assets/animations/sfts_flags_brazil_flag.png";
import sftsFlagsBritishFlag from "assets/animations/sfts_flags_british_flag.png";
import sftsFlagsCanadianFlag from "assets/animations/sfts_flags_canadian_flag.png";
import sftsFlagsChinaFlag from "assets/animations/sfts_flags_china_flag.png";
import sftsFlagsColombianFlag from "assets/animations/sfts_flags_colombian_flag.png";
import sftsFlagsDominicanRepublicFlag from "assets/animations/sfts_flags_dominican_republic_flag.png";
import sftsFlagsFinlandFlag from "assets/animations/sfts_flags_finland_flag.png";
import sftsFlagsFranceFlag from "assets/animations/sfts_flags_france_flag.png";
import sftsFlagsGermanyFlag from "assets/animations/sfts_flags_germany_flag.png";
import sftsFlagsGoblinFlag from "assets/animations/sfts_flags_goblin_flag.png";
import sftsFlagsIndiaFlag from "assets/animations/sfts_flags_india_flag.png";
import sftsFlagsIndonesiaFlag from "assets/animations/sfts_flags_indonesia_flag.png";
import sftsFlagsIranFlag from "assets/animations/sfts_flags_iran_flag.png";
import sftsFlagsItalyFlag from "assets/animations/sfts_flags_italy_flag.png";
import sftsFlagsJapanFlag from "assets/animations/sfts_flags_japan_flag.png";
import sftsFlagsLithuanianFlag from "assets/animations/sfts_flags_lithuanian_flag.png";
import sftsFlagsMalaysianFlag from "assets/animations/sfts_flags_malaysian_flag.png";
import sftsFlagsMexicanFlag from "assets/animations/sfts_flags_mexican_flag.png";
import sftsFlagsMoroccoFlag from "assets/animations/sfts_flags_morocco_flag.png";
import sftsFlagsNetherlandsFlag from "assets/animations/sfts_flags_netherlands_flag.png";
import sftsFlagsPhilippinesFlag from "assets/animations/sfts_flags_philippines_flag.png";
import sftsFlagsPirateFlag from "assets/animations/sfts_flags_pirate_flag.png";
import sftsFlagsPolandFlag from "assets/animations/sfts_flags_poland_flag.png";
import sftsFlagsPortugalFlag from "assets/animations/sfts_flags_portugal_flag.png";
import sftsFlagsRainbowFlag from "assets/animations/sfts_flags_rainbow_flag.png";
import sftsFlagsRomanianFlag from "assets/animations/sfts_flags_romanian_flag.png";
import sftsFlagsRussiaFlag from "assets/animations/sfts_flags_russia_flag.png";
import sftsFlagsSaudiArabiaFlag from "assets/animations/sfts_flags_saudi_arabia_flag.png";
import sftsFlagsSierraLeoneFlag from "assets/animations/sfts_flags_sierra_leone_flag.png";
import sftsFlagsSingaporeanFlag from "assets/animations/sfts_flags_singaporean_flag.png";
import sftsFlagsSouthKoreaFlag from "assets/animations/sfts_flags_south_korea_flag.png";
import sftsFlagsSpainFlag from "assets/animations/sfts_flags_spain_flag.png";
import sftsFlagsSunflowerFlag from "assets/animations/sfts_flags_sunflower_flag.png";
import sftsFlagsThailandFlag from "assets/animations/sfts_flags_thailand_flag.png";
import sftsFlagsTurkeyFlag from "assets/animations/sfts_flags_turkey_flag.png";
import sftsFlagsUkraineFlag from "assets/animations/sfts_flags_ukraine_flag.png";
import sftsFlagsUsaFlag from "assets/animations/sfts_flags_usa_flag.png";
import sftsFlagsVietnamFlag from "assets/animations/sfts_flags_vietnam_flag.png";
import sftsFloatingToy from "assets/animations/sfts_floating_toy.png";
import sftsFlowerCoin from "assets/animations/sfts_flower_coin.png";
import sftsFoolsGold from "assets/animations/sfts_fools_gold.png";
import sftsFrozenMeat from "assets/animations/sfts_frozen_meat.png";
import sftsGiftTurtle from "assets/animations/sfts_gift_turtle.png";
import sftsGreenPaintBucket from "assets/animations/sfts_green_paint_bucket.png";
import sftsGuillotine from "assets/animations/sfts_guillotine.png";
import sftsHauntedHouse from "assets/animations/sfts_haunted_house.png";
import sftsHauntedTomb from "assets/animations/sfts_haunted_tomb.png";
import sftsHummingbird from "assets/animations/sfts_hummingbird.png";
import sftsJellyLamp from "assets/animations/sfts_jelly_lamp.png";
import sftsKite from "assets/animations/sfts_kite.png";
import sftsMechaBull from "assets/animations/sfts_mecha_bull.png";
import sftsMimicEgg from "assets/animations/sfts_mimic_egg.png";
import sftsMimicSlimeBall from "assets/animations/sfts_mimic_slime_ball.png";
import sftsMimicWingedSlimeBall from "assets/animations/sfts_mimic_winged_slime_ball.png";
import sftsMomMomObservatoryAnimation from "assets/animations/sfts_mom_mom_observatory_animation.png";
import sftsMomObservatory from "assets/animations/sfts_mom_observatory.png";
import sftsMooVer from "assets/animations/sfts_moo_ver.png";
import sftsOrangeTunnelBunny from "assets/animations/sfts_orange_tunnel_bunny.png";
import sftsPenguinPool from "assets/animations/sfts_penguin_pool.png";
import sftsPenguinSurprise from "assets/animations/sfts_penguin_surprise.png";
import sftsPetsBullsBison from "assets/animations/sfts_pets_bulls_Bison.png";
import sftsPetsBullsOxen from "assets/animations/sfts_pets_bulls_Oxen.png";
import sftsPetsBullsBisonAsleep from "assets/animations/sfts_pets_bulls_bison_asleep.png";
import sftsPetsBullsMudhorn from "assets/animations/sfts_pets_bulls_mudhorn.png";
import sftsPetsBullsMudhornAsleep from "assets/animations/sfts_pets_bulls_mudhorn_asleep.png";
import sftsPetsBullsOxenAsleep from "assets/animations/sfts_pets_bulls_oxen_asleep.png";
import sftsPetsCatsButters from "assets/animations/sfts_pets_cats_butters.png";
import sftsPetsCatsButtersAsleep from "assets/animations/sfts_pets_cats_butters_asleep.png";
import sftsPetsCatsMeowchi from "assets/animations/sfts_pets_cats_meowchi.png";
import sftsPetsCatsMeowchiAsleep from "assets/animations/sfts_pets_cats_meowchi_asleep.png";
import sftsPetsCatsSmokey from "assets/animations/sfts_pets_cats_smokey.png";
import sftsPetsCatsSmokeyAsleep from "assets/animations/sfts_pets_cats_smokey_asleep.png";
import sftsPetsDogsBarkley from "assets/animations/sfts_pets_dogs_barkley.png";
import sftsPetsDogsBarkleyAsleep from "assets/animations/sfts_pets_dogs_barkley_asleep.png";
import sftsPetsDogsBiscuit from "assets/animations/sfts_pets_dogs_biscuit.png";
import sftsPetsDogsBiscuitAsleep from "assets/animations/sfts_pets_dogs_biscuit_asleep.png";
import sftsPetsDogsCloudy from "assets/animations/sfts_pets_dogs_cloudy.png";
import sftsPetsDogsCloudyAsleep from "assets/animations/sfts_pets_dogs_cloudy_asleep.png";
import sftsPetsHamstersNibbles from "assets/animations/sfts_pets_hamsters_nibbles.png";
import sftsPetsHamstersNibblesAsleep from "assets/animations/sfts_pets_hamsters_nibbles_asleep.png";
import sftsPetsHamstersPeanut from "assets/animations/sfts_pets_hamsters_peanut.png";
import sftsPetsHamstersPeanutsAsleep from "assets/animations/sfts_pets_hamsters_peanuts_asleep.png";
import sftsPetsHorsesBurro from "assets/animations/sfts_pets_horses_burro.png";
import sftsPetsHorsesBurroAsleep from "assets/animations/sfts_pets_horses_burro_asleep.png";
import sftsPetsHorsesPinto from "assets/animations/sfts_pets_horses_pinto.png";
import sftsPetsHorsesPintoAsleep from "assets/animations/sfts_pets_horses_pinto_asleep.png";
import sftsPetsHorsesRoan from "assets/animations/sfts_pets_horses_roan.png";
import sftsPetsHorsesRoanAsleep from "assets/animations/sfts_pets_horses_roan_asleep.png";
import sftsPetsHorsesStallion from "assets/animations/sfts_pets_horses_stallion.png";
import sftsPetsHorsesStallionAsleep from "assets/animations/sfts_pets_horses_stallion_asleep.png";
import sftsPetsOwlsFlicker from "assets/animations/sfts_pets_owls_flicker.png";
import sftsPetsOwlsFlickerAsleep from "assets/animations/sfts_pets_owls_flicker_asleep.png";
import sftsPetsOwlsPippin from "assets/animations/sfts_pets_owls_pippin.png";
import sftsPetsOwlsPippinAsleep from "assets/animations/sfts_pets_owls_pippin_asleep.png";
import sftsPetsOwlsTwizzle from "assets/animations/sfts_pets_owls_twizzle.png";
import sftsPetsOwlsTwizzleAsleep from "assets/animations/sfts_pets_owls_twizzle_asleep.png";
import sftsPetsPenguinsPip from "assets/animations/sfts_pets_penguins_pip.png";
import sftsPetsPenguinsPipAsleep from "assets/animations/sfts_pets_penguins_pip_asleep.png";
import sftsPetsPenguinsSkipper from "assets/animations/sfts_pets_penguins_skipper.png";
import sftsPetsPenguinsSkipperAsleep from "assets/animations/sfts_pets_penguins_skipper_asleep.png";
import sftsPetsPenguinsWaddles from "assets/animations/sfts_pets_penguins_waddles.png";
import sftsPetsPenguinsWaddlesAsleep from "assets/animations/sfts_pets_penguins_waddles_asleep.png";
import sftsPetsRamsey from "assets/animations/sfts_pets_ramsey.png";
import sftsPonyToy from "assets/animations/sfts_pony_toy.png";
import sftsPorkJelly from "assets/animations/sfts_pork_jelly.png";
import sftsPotatoMutant from "assets/animations/sfts_potato_mutant.png";
import sftsPurplePaintBucket from "assets/animations/sfts_purple_paint_bucket.png";
import sftsQueenBee from "assets/animations/sfts_queen_bee.png";
import sftsRadishMutant from "assets/animations/sfts_radish_mutant.png";
import sftsRainbowFlower from "assets/animations/sfts_rainbow_flower.png";
import sftsRainbowPorkJelly from "assets/animations/sfts_rainbow_pork_jelly.png";
import sftsRaveyard from "assets/animations/sfts_raveyard.png";
import sftsRedNoseReindeer from "assets/animations/sfts_red_nose_reindeer.png";
import sftsRedSlimeBalloon from "assets/animations/sfts_red_slime_balloon.png";
import sftsRockGolem from "assets/animations/sfts_rock_golem.png";
import sftsSantaPenguin from "assets/animations/sfts_santa_penguin.png";
import sftsSkillShrimpy from "assets/animations/sfts_skill_shrimpy.png";
import sftsSpinningWheel from "assets/animations/sfts_spinning_wheel.png";
import sftsSummerChicken from "assets/animations/sfts_summer_chicken.png";
import sftsSunflowerMutant from "assets/animations/sfts_sunflower_mutant.png";
import sftsThermalStone from "assets/animations/sfts_thermal_stone.png";
import sftsTornadoPinwheel from "assets/animations/sfts_tornado_pinwheel.png";
import sftsTuxedoClaus from "assets/animations/sfts_tuxedo_claus.png";
import sftsUfo from "assets/animations/sfts_ufo.png";
import sftsVampireCoffin from "assets/animations/sfts_vampire_coffin.png";
import sftsWalrus from "assets/animations/sfts_walrus.png";
import sftsWhiteTunnelBunny from "assets/animations/sfts_white_tunnel_bunny.png";
import sftsWinterAlpaca from "assets/animations/sfts_winter_alpaca.png";
import sftsWitchsCauldron from "assets/animations/sfts_witchs_cauldron.png";
import sftsYellowPaintBucket from "assets/animations/sfts_yellow_paint_bucket.png";
import buildingsSmoke from "assets/animations/buildings_smoke.png";
import fxSparkle2 from "assets/animations/fx_sparkle2.png";
import landLevelsPontoon from "assets/animations/land_levels_pontoon.png";
import npcsArtisianDoing from "assets/animations/npcs_artisian_doing.png";
import npcsArtisian from "assets/animations/npcs_artisian.png";
import npcsChefDoing from "assets/animations/npcs_chef_doing.png";
import npcsChef from "assets/animations/npcs_chef.png";
import npcsCookDoing from "assets/animations/npcs_cook_doing.png";
import npcsCook from "assets/animations/npcs_cook.png";
import npcsGoblinChefDoing from "assets/animations/npcs_goblin_chef_doing.png";
import npcsGoblinChef from "assets/animations/npcs_goblin_chef.png";
import npcsGoblinSnorkling from "assets/animations/npcs_goblin_snorkling.png";
import npcsGoblinSwimming from "assets/animations/npcs_goblin_swimming.png";
import npcsNevilleDoing from "assets/animations/npcs_neville_doing.png";
import npcsSmoothieMaking from "assets/animations/npcs_smoothie_making.png";
import npcsSmoothie from "assets/animations/npcs_smoothie.png";
import npcsSwimmer from "assets/animations/npcs_swimmer.png";
import animalsChickensIdleChicken from "assets/animations/animals_chickens_idle_chicken.png";
import animalsChickensSleepingChicken from "assets/animations/animals_chickens_sleeping_chicken.png";
import animalsChickensReady from "assets/animations/animals_chickens_ready.png";
import buds933 from "assets/animations/buds_933.png";
import petsSleepings20 from "assets/animations/pets_sleepings_20.png";
import petsSleepings2921 from "assets/animations/pets_sleepings_2921.png";
import petsSleepings3000 from "assets/animations/pets_sleepings_3000.png";

export type AnimatedArt = {
  sheet: string;
  frameWidth: number;
  frameHeight: number;
  frames: number;
  fps: number;
};

/** Keyed by the ORIGINAL art URL, so lookups work wherever art is resolved. */
export const ANIMATED_ART: Record<string, AnimatedArt> = Object.fromEntries([
  [sftsFountainGif, { sheet: sftsFountain, frameWidth: 26, frameHeight: 29, frames: 6, fps: 3 }],
  [sftsBeaverGif, { sheet: sftsBeaver, frameWidth: 15, frameHeight: 16, frames: 9, fps: 14 }],
  [sftsApprenticeBeaverGif, { sheet: sftsApprenticeBeaver, frameWidth: 15, frameHeight: 16, frames: 9, fps: 14 }],
  [sftsConstructionBeaverGif, { sheet: sftsConstructionBeaver, frameWidth: 15, frameHeight: 19, frames: 9, fps: 14 }],
  [sftsKuebikoGif, { sheet: sftsKuebiko, frameWidth: 30, frameHeight: 30, frames: 17, fps: 3 }],
  [sftsTunnelMoleGif, { sheet: sftsTunnelMole, frameWidth: 20, frameHeight: 16, frames: 27, fps: 10 }],
  [sftsRockyMoleGif, { sheet: sftsRockyMole, frameWidth: 21, frameHeight: 20, frames: 27, fps: 10 }],
  [sftsNuggetGif, { sheet: sftsNugget, frameWidth: 21, frameHeight: 22, frames: 27, fps: 10 }],
  [sftsWoodNymphWendyGif, { sheet: sftsWoodNymphWendy, frameWidth: 15, frameHeight: 24, frames: 9, fps: 14 }],
  [sftsCabbageBoyGif, { sheet: sftsCabbageBoy, frameWidth: 16, frameHeight: 16, frames: 9, fps: 14 }],
  [sftsCabbageGirlGif, { sheet: sftsCabbageGirl, frameWidth: 16, frameHeight: 16, frames: 9, fps: 14 }],
  [sftsPeeledPotatoGif, { sheet: sftsPeeledPotato, frameWidth: 15, frameHeight: 15, frames: 9, fps: 14 }],
  [sftsLadybugGif, { sheet: sftsLadybug, frameWidth: 16, frameHeight: 15, frames: 9, fps: 14 }],
  [sftsBlackBearGif, { sheet: sftsBlackBear, frameWidth: 16, frameHeight: 18, frames: 4, fps: 8 }],
  [sftsObieGif, { sheet: sftsObie, frameWidth: 15, frameHeight: 19, frames: 9, fps: 14 }],
  [sftsMaximusGif, { sheet: sftsMaximus, frameWidth: 23, frameHeight: 26, frames: 9, fps: 14 }],
  [sftsTomatoClownGif, { sheet: sftsTomatoClown, frameWidth: 19, frameHeight: 30, frames: 4, fps: 10 }],
  [sftsLabGrownCarrotGif, { sheet: sftsLabGrownCarrot, frameWidth: 12, frameHeight: 22, frames: 9, fps: 7 }],
  [sftsLabGrownPumpkinGif, { sheet: sftsLabGrownPumpkin, frameWidth: 12, frameHeight: 20, frames: 9, fps: 7 }],
  [sftsLabGrownRadishGif, { sheet: sftsLabGrownRadish, frameWidth: 14, frameHeight: 21, frames: 9, fps: 7 }],
  [sftsVictoriaSistersGif, { sheet: sftsVictoriaSisters, frameWidth: 32, frameHeight: 32, frames: 60, fps: 2 }],
  [sftsManekiNekoGif, { sheet: sftsManekiNeko, frameWidth: 16, frameHeight: 16, frames: 20, fps: 7 }],
  [sftsHeartOfDavyJonesGif, { sheet: sftsHeartOfDavyJones, frameWidth: 23, frameHeight: 22, frames: 9, fps: 3 }],
  [sftsPabloBunnyGif, { sheet: sftsPabloBunny, frameWidth: 14, frameHeight: 20, frames: 9, fps: 14 }],
  [sftsSapoDocurasGif, { sheet: sftsSapoDocuras, frameWidth: 20, frameHeight: 24, frames: 41, fps: 13 }],
  [sftsSapoTravessuraGif, { sheet: sftsSapoTravessura, frameWidth: 20, frameHeight: 24, frames: 41, fps: 13 }],
  [sftsRevelingLemonGif, { sheet: sftsRevelingLemon, frameWidth: 23, frameHeight: 39, frames: 48, fps: 25 }],
  [sftsEasterEasterBunnyGif, { sheet: sftsEasterEasterBunny, frameWidth: 14, frameHeight: 20, frames: 9, fps: 14 }],
  [decorationsSnowglobeGif, { sheet: decorationsSnowglobe, frameWidth: 20, frameHeight: 24, frames: 6, fps: 7 }],
  [decorationsBannersSpringBannerGif, { sheet: decorationsBannersSpringBanner, frameWidth: 22, frameHeight: 36, frames: 2, fps: 7 }],
  [decorationsBannersWindsOfChangeBannerLoopGif, { sheet: decorationsBannersWindsOfChangeBannerLoop, frameWidth: 16, frameHeight: 30, frames: 4, fps: 1 }],
  [decorationsIsleBoatGif, { sheet: decorationsIsleBoat, frameWidth: 104, frameHeight: 46, frames: 7, fps: 10 }],
  [eventsGoldenCropGoldenCropGif, { sheet: eventsGoldenCropGoldenCrop, frameWidth: 10, frameHeight: 13, frames: 7, fps: 5 }],
  [animalsChickensAyamCemaniGif, { sheet: animalsChickensAyamCemani, frameWidth: 15, frameHeight: 20, frames: 8, fps: 14 }],
  [animalsChickensBananaChickenGif, { sheet: animalsChickensBananaChicken, frameWidth: 15, frameHeight: 26, frames: 7, fps: 14 }],
  [animalsChickensElPolloVelozGif, { sheet: animalsChickensElPolloVeloz, frameWidth: 16, frameHeight: 19, frames: 6, fps: 7 }],
  [animalsChickensFatChickenGif, { sheet: animalsChickensFatChicken, frameWidth: 17, frameHeight: 21, frames: 5, fps: 14 }],
  [animalsChickensGoldenCockerelGif, { sheet: animalsChickensGoldenCockerel, frameWidth: 24, frameHeight: 24, frames: 16, fps: 14 }],
  [animalsChickensKnightChickenGif, { sheet: animalsChickensKnightChicken, frameWidth: 26, frameHeight: 26, frames: 7, fps: 10 }],
  [animalsChickensRichChickenGif, { sheet: animalsChickensRichChicken, frameWidth: 21, frameHeight: 23, frames: 8, fps: 14 }],
  [animalsChickensRoosterGif, { sheet: animalsChickensRooster, frameWidth: 15, frameHeight: 20, frames: 9, fps: 11 }],
  [animalsChickensSpeedChickenGif, { sheet: animalsChickensSpeedChicken, frameWidth: 15, frameHeight: 20, frames: 8, fps: 14 }],
  [animalsChickensUndeadChickenGif, { sheet: animalsChickensUndeadChicken, frameWidth: 15, frameHeight: 20, frames: 8, fps: 11 }],
  [buildingsCraftingBoxAnimationGif, { sheet: buildingsCraftingBoxAnimation, frameWidth: 46, frameHeight: 38, frames: 12, fps: 10 }],
  [buildingsLevelOne2Gif, { sheet: buildingsLevelOne2, frameWidth: 384, frameHeight: 320, frames: 1, fps: 10 }],
  [buildingsLevelOneStartGif, { sheet: buildingsLevelOneStart, frameWidth: 384, frameHeight: 320, frames: 1, fps: 10 }],
  [buildingsTentGif, { sheet: buildingsTent, frameWidth: 380, frameHeight: 320, frames: 1, fps: 1000 }],
  [decorationsBannersBullRunBannerGif, { sheet: decorationsBannersBullRunBanner, frameWidth: 20, frameHeight: 35, frames: 6, fps: 7 }],
  [decorationsCandlesOnGif, { sheet: decorationsCandlesOn, frameWidth: 11, frameHeight: 15, frames: 3, fps: 10 }],
  [decorationsObserverGif, { sheet: decorationsObserver, frameWidth: 17, frameHeight: 27, frames: 28, fps: 5 }],
  [decorationsWhiteCrowGif, { sheet: decorationsWhiteCrow, frameWidth: 20, frameHeight: 27, frames: 6, fps: 10 }],
  [resourcesLavaLavaPitAnimationGif, { sheet: resourcesLavaLavaPitAnimation, frameWidth: 36, frameHeight: 35, frames: 20, fps: 7 }],
  [resourcesOilSpurtingWellGif, { sheet: resourcesOilSpurtingWell, frameWidth: 29, frameHeight: 38, frames: 9, fps: 14 }],
  [sftsAlbaGif, { sheet: sftsAlba, frameWidth: 13, frameHeight: 18, frames: 7, fps: 10 }],
  [sftsAlienChickenGif, { sheet: sftsAlienChicken, frameWidth: 16, frameHeight: 30, frames: 7, fps: 10 }],
  [sftsBaoziGif, { sheet: sftsBaozi, frameWidth: 17, frameHeight: 24, frames: 11, fps: 10 }],
  [sftsBluePaintBucketGif, { sheet: sftsBluePaintBucket, frameWidth: 16, frameHeight: 32, frames: 8, fps: 10 }],
  [sftsBlueSlimeBalloonGif, { sheet: sftsBlueSlimeBalloon, frameWidth: 19, frameHeight: 36, frames: 8, fps: 10 }],
  [sftsCerberusGif, { sheet: sftsCerberus, frameWidth: 28, frameHeight: 31, frames: 8, fps: 10 }],
  [sftsCetusGif, { sheet: sftsCetus, frameWidth: 50, frameHeight: 45, frames: 12, fps: 7 }],
  [sftsCluckulatorGif, { sheet: sftsCluckulator, frameWidth: 21, frameHeight: 32, frames: 7, fps: 10 }],
  [sftsColorWheelGif, { sheet: sftsColorWheel, frameWidth: 32, frameHeight: 32, frames: 15, fps: 10 }],
  [sftsEasterEasterBunnyEggsGif, { sheet: sftsEasterEasterBunnyEggs, frameWidth: 32, frameHeight: 21, frames: 6, fps: 7 }],
  [sftsEasterDonationEggGif, { sheet: sftsEasterDonationEgg, frameWidth: 16, frameHeight: 19, frames: 6, fps: 8 }],
  [sftsFarmCatGif, { sheet: sftsFarmCat, frameWidth: 20, frameHeight: 20, frames: 26, fps: 6 }],
  [sftsFarmDogGif, { sheet: sftsFarmDog, frameWidth: 17, frameHeight: 24, frames: 11, fps: 7 }],
  [sftsFishKiteGif, { sheet: sftsFishKite, frameWidth: 24, frameHeight: 40, frames: 6, fps: 10 }],
  [sftsFlagsAlgerianFlagGif, { sheet: sftsFlagsAlgerianFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsArgentinianFlagGif, { sheet: sftsFlagsArgentinianFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsAustraliaFlagGif, { sheet: sftsFlagsAustraliaFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsBelgiumFlagGif, { sheet: sftsFlagsBelgiumFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsBrazilFlagGif, { sheet: sftsFlagsBrazilFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsBritishFlagGif, { sheet: sftsFlagsBritishFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsCanadianFlagGif, { sheet: sftsFlagsCanadianFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsChinaFlagGif, { sheet: sftsFlagsChinaFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsColombianFlagGif, { sheet: sftsFlagsColombianFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsDominicanRepublicFlagGif, { sheet: sftsFlagsDominicanRepublicFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsFinlandFlagGif, { sheet: sftsFlagsFinlandFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsFranceFlagGif, { sheet: sftsFlagsFranceFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsGermanyFlagGif, { sheet: sftsFlagsGermanyFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsGoblinFlagGif, { sheet: sftsFlagsGoblinFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsIndiaFlagGif, { sheet: sftsFlagsIndiaFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsIndonesiaFlagGif, { sheet: sftsFlagsIndonesiaFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsIranFlagGif, { sheet: sftsFlagsIranFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsItalyFlagGif, { sheet: sftsFlagsItalyFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsJapanFlagGif, { sheet: sftsFlagsJapanFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsLithuanianFlagGif, { sheet: sftsFlagsLithuanianFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsMalaysianFlagGif, { sheet: sftsFlagsMalaysianFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsMexicanFlagGif, { sheet: sftsFlagsMexicanFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsMoroccoFlagGif, { sheet: sftsFlagsMoroccoFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsNetherlandsFlagGif, { sheet: sftsFlagsNetherlandsFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsPhilippinesFlagGif, { sheet: sftsFlagsPhilippinesFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsPirateFlagGif, { sheet: sftsFlagsPirateFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsPolandFlagGif, { sheet: sftsFlagsPolandFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsPortugalFlagGif, { sheet: sftsFlagsPortugalFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsRainbowFlagGif, { sheet: sftsFlagsRainbowFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsRomanianFlagGif, { sheet: sftsFlagsRomanianFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsRussiaFlagGif, { sheet: sftsFlagsRussiaFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsSaudiArabiaFlagGif, { sheet: sftsFlagsSaudiArabiaFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsSierraLeoneFlagGif, { sheet: sftsFlagsSierraLeoneFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsSingaporeanFlagGif, { sheet: sftsFlagsSingaporeanFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsSouthKoreaFlagGif, { sheet: sftsFlagsSouthKoreaFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsSpainFlagGif, { sheet: sftsFlagsSpainFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsSunflowerFlagGif, { sheet: sftsFlagsSunflowerFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsThailandFlagGif, { sheet: sftsFlagsThailandFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsTurkeyFlagGif, { sheet: sftsFlagsTurkeyFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsUkraineFlagGif, { sheet: sftsFlagsUkraineFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsUsaFlagGif, { sheet: sftsFlagsUsaFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFlagsVietnamFlagGif, { sheet: sftsFlagsVietnamFlag, frameWidth: 11, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsFloatingToyGif, { sheet: sftsFloatingToy, frameWidth: 16, frameHeight: 24, frames: 8, fps: 14 }],
  [sftsFlowerCoinGif, { sheet: sftsFlowerCoin, frameWidth: 34, frameHeight: 31, frames: 8, fps: 8 }],
  [sftsFoolsGoldGif, { sheet: sftsFoolsGold, frameWidth: 32, frameHeight: 32, frames: 5, fps: 5 }],
  [sftsFrozenMeatGif, { sheet: sftsFrozenMeat, frameWidth: 16, frameHeight: 16, frames: 9, fps: 10 }],
  [sftsGiftTurtleGif, { sheet: sftsGiftTurtle, frameWidth: 22, frameHeight: 28, frames: 5, fps: 1000 }],
  [sftsGreenPaintBucketGif, { sheet: sftsGreenPaintBucket, frameWidth: 16, frameHeight: 32, frames: 8, fps: 10 }],
  [sftsGuillotineGif, { sheet: sftsGuillotine, frameWidth: 24, frameHeight: 40, frames: 6, fps: 10 }],
  [sftsHauntedHouseGif, { sheet: sftsHauntedHouse, frameWidth: 88, frameHeight: 93, frames: 8, fps: 10 }],
  [sftsHauntedTombGif, { sheet: sftsHauntedTomb, frameWidth: 14, frameHeight: 30, frames: 8, fps: 10 }],
  [sftsHummingbirdGif, { sheet: sftsHummingbird, frameWidth: 18, frameHeight: 20, frames: 2, fps: 10 }],
  [sftsJellyLampGif, { sheet: sftsJellyLamp, frameWidth: 32, frameHeight: 32, frames: 9, fps: 10 }],
  [sftsKiteGif, { sheet: sftsKite, frameWidth: 24, frameHeight: 40, frames: 6, fps: 10 }],
  [sftsMechaBullGif, { sheet: sftsMechaBull, frameWidth: 35, frameHeight: 31, frames: 8, fps: 10 }],
  [sftsMimicEggGif, { sheet: sftsMimicEgg, frameWidth: 19, frameHeight: 30, frames: 8, fps: 10 }],
  [sftsMimicSlimeBallGif, { sheet: sftsMimicSlimeBall, frameWidth: 16, frameHeight: 16, frames: 7, fps: 10 }],
  [sftsMimicWingedSlimeBallGif, { sheet: sftsMimicWingedSlimeBall, frameWidth: 20, frameHeight: 16, frames: 7, fps: 14 }],
  [sftsMomMomObservatoryAnimationGif, { sheet: sftsMomMomObservatoryAnimation, frameWidth: 400, frameHeight: 225, frames: 515, fps: 20 }],
  [sftsMomObservatoryGif, { sheet: sftsMomObservatory, frameWidth: 29, frameHeight: 36, frames: 16, fps: 5 }],
  [sftsMooVerGif, { sheet: sftsMooVer, frameWidth: 36, frameHeight: 36, frames: 7, fps: 10 }],
  [sftsOrangeTunnelBunnyGif, { sheet: sftsOrangeTunnelBunny, frameWidth: 15, frameHeight: 16, frames: 25, fps: 2 }],
  [sftsPenguinPoolGif, { sheet: sftsPenguinPool, frameWidth: 32, frameHeight: 38, frames: 9, fps: 11 }],
  [sftsPenguinSurpriseGif, { sheet: sftsPenguinSurprise, frameWidth: 51, frameHeight: 32, frames: 13, fps: 7 }],
  [sftsPetsBullsBisonGif, { sheet: sftsPetsBullsBison, frameWidth: 22, frameHeight: 26, frames: 8, fps: 10 }],
  [sftsPetsBullsOxenGif, { sheet: sftsPetsBullsOxen, frameWidth: 23, frameHeight: 26, frames: 8, fps: 10 }],
  [sftsPetsBullsBisonAsleepGif, { sheet: sftsPetsBullsBisonAsleep, frameWidth: 22, frameHeight: 22, frames: 2, fps: 2 }],
  [sftsPetsBullsMudhornGif, { sheet: sftsPetsBullsMudhorn, frameWidth: 23, frameHeight: 26, frames: 8, fps: 10 }],
  [sftsPetsBullsMudhornAsleepGif, { sheet: sftsPetsBullsMudhornAsleep, frameWidth: 23, frameHeight: 22, frames: 2, fps: 2 }],
  [sftsPetsBullsOxenAsleepGif, { sheet: sftsPetsBullsOxenAsleep, frameWidth: 23, frameHeight: 21, frames: 2, fps: 2 }],
  [sftsPetsCatsButtersGif, { sheet: sftsPetsCatsButters, frameWidth: 20, frameHeight: 23, frames: 8, fps: 10 }],
  [sftsPetsCatsButtersAsleepGif, { sheet: sftsPetsCatsButtersAsleep, frameWidth: 19, frameHeight: 22, frames: 2, fps: 2 }],
  [sftsPetsCatsMeowchiGif, { sheet: sftsPetsCatsMeowchi, frameWidth: 20, frameHeight: 23, frames: 8, fps: 10 }],
  [sftsPetsCatsMeowchiAsleepGif, { sheet: sftsPetsCatsMeowchiAsleep, frameWidth: 19, frameHeight: 22, frames: 2, fps: 2 }],
  [sftsPetsCatsSmokeyGif, { sheet: sftsPetsCatsSmokey, frameWidth: 20, frameHeight: 23, frames: 8, fps: 10 }],
  [sftsPetsCatsSmokeyAsleepGif, { sheet: sftsPetsCatsSmokeyAsleep, frameWidth: 19, frameHeight: 22, frames: 2, fps: 2 }],
  [sftsPetsDogsBarkleyGif, { sheet: sftsPetsDogsBarkley, frameWidth: 20, frameHeight: 22, frames: 8, fps: 10 }],
  [sftsPetsDogsBarkleyAsleepGif, { sheet: sftsPetsDogsBarkleyAsleep, frameWidth: 21, frameHeight: 20, frames: 2, fps: 2 }],
  [sftsPetsDogsBiscuitGif, { sheet: sftsPetsDogsBiscuit, frameWidth: 20, frameHeight: 22, frames: 8, fps: 10 }],
  [sftsPetsDogsBiscuitAsleepGif, { sheet: sftsPetsDogsBiscuitAsleep, frameWidth: 20, frameHeight: 20, frames: 2, fps: 2 }],
  [sftsPetsDogsCloudyGif, { sheet: sftsPetsDogsCloudy, frameWidth: 20, frameHeight: 25, frames: 8, fps: 10 }],
  [sftsPetsDogsCloudyAsleepGif, { sheet: sftsPetsDogsCloudyAsleep, frameWidth: 19, frameHeight: 20, frames: 2, fps: 2 }],
  [sftsPetsHamstersNibblesGif, { sheet: sftsPetsHamstersNibbles, frameWidth: 16, frameHeight: 20, frames: 8, fps: 10 }],
  [sftsPetsHamstersNibblesAsleepGif, { sheet: sftsPetsHamstersNibblesAsleep, frameWidth: 16, frameHeight: 17, frames: 2, fps: 2 }],
  [sftsPetsHamstersPeanutGif, { sheet: sftsPetsHamstersPeanut, frameWidth: 16, frameHeight: 20, frames: 7, fps: 10 }],
  [sftsPetsHamstersPeanutsAsleepGif, { sheet: sftsPetsHamstersPeanutsAsleep, frameWidth: 16, frameHeight: 17, frames: 2, fps: 2 }],
  [sftsPetsHorsesBurroGif, { sheet: sftsPetsHorsesBurro, frameWidth: 20, frameHeight: 24, frames: 8, fps: 10 }],
  [sftsPetsHorsesBurroAsleepGif, { sheet: sftsPetsHorsesBurroAsleep, frameWidth: 20, frameHeight: 22, frames: 2, fps: 2 }],
  [sftsPetsHorsesPintoGif, { sheet: sftsPetsHorsesPinto, frameWidth: 22, frameHeight: 24, frames: 8, fps: 10 }],
  [sftsPetsHorsesPintoAsleepGif, { sheet: sftsPetsHorsesPintoAsleep, frameWidth: 22, frameHeight: 20, frames: 2, fps: 2 }],
  [sftsPetsHorsesRoanGif, { sheet: sftsPetsHorsesRoan, frameWidth: 19, frameHeight: 25, frames: 8, fps: 10 }],
  [sftsPetsHorsesRoanAsleepGif, { sheet: sftsPetsHorsesRoanAsleep, frameWidth: 19, frameHeight: 22, frames: 2, fps: 2 }],
  [sftsPetsHorsesStallionGif, { sheet: sftsPetsHorsesStallion, frameWidth: 21, frameHeight: 24, frames: 8, fps: 10 }],
  [sftsPetsHorsesStallionAsleepGif, { sheet: sftsPetsHorsesStallionAsleep, frameWidth: 21, frameHeight: 21, frames: 2, fps: 2 }],
  [sftsPetsOwlsFlickerGif, { sheet: sftsPetsOwlsFlicker, frameWidth: 17, frameHeight: 22, frames: 8, fps: 10 }],
  [sftsPetsOwlsFlickerAsleepGif, { sheet: sftsPetsOwlsFlickerAsleep, frameWidth: 17, frameHeight: 20, frames: 2, fps: 2 }],
  [sftsPetsOwlsPippinGif, { sheet: sftsPetsOwlsPippin, frameWidth: 17, frameHeight: 22, frames: 7, fps: 10 }],
  [sftsPetsOwlsPippinAsleepGif, { sheet: sftsPetsOwlsPippinAsleep, frameWidth: 17, frameHeight: 20, frames: 2, fps: 2 }],
  [sftsPetsOwlsTwizzleGif, { sheet: sftsPetsOwlsTwizzle, frameWidth: 17, frameHeight: 19, frames: 6, fps: 10 }],
  [sftsPetsOwlsTwizzleAsleepGif, { sheet: sftsPetsOwlsTwizzleAsleep, frameWidth: 17, frameHeight: 17, frames: 2, fps: 2 }],
  [sftsPetsPenguinsPipGif, { sheet: sftsPetsPenguinsPip, frameWidth: 17, frameHeight: 20, frames: 8, fps: 10 }],
  [sftsPetsPenguinsPipAsleepGif, { sheet: sftsPetsPenguinsPipAsleep, frameWidth: 17, frameHeight: 18, frames: 2, fps: 2 }],
  [sftsPetsPenguinsSkipperGif, { sheet: sftsPetsPenguinsSkipper, frameWidth: 21, frameHeight: 20, frames: 7, fps: 10 }],
  [sftsPetsPenguinsSkipperAsleepGif, { sheet: sftsPetsPenguinsSkipperAsleep, frameWidth: 21, frameHeight: 18, frames: 2, fps: 2 }],
  [sftsPetsPenguinsWaddlesGif, { sheet: sftsPetsPenguinsWaddles, frameWidth: 17, frameHeight: 20, frames: 8, fps: 10 }],
  [sftsPetsPenguinsWaddlesAsleepGif, { sheet: sftsPetsPenguinsWaddlesAsleep, frameWidth: 17, frameHeight: 18, frames: 2, fps: 2 }],
  [sftsPetsRamseyGif, { sheet: sftsPetsRamsey, frameWidth: 32, frameHeight: 36, frames: 17, fps: 14 }],
  [sftsPonyToyGif, { sheet: sftsPonyToy, frameWidth: 20, frameHeight: 20, frames: 6, fps: 6 }],
  [sftsPorkJellyGif, { sheet: sftsPorkJelly, frameWidth: 16, frameHeight: 16, frames: 8, fps: 14 }],
  [sftsPotatoMutantGif, { sheet: sftsPotatoMutant, frameWidth: 22, frameHeight: 22, frames: 2, fps: 3 }],
  [sftsPurplePaintBucketGif, { sheet: sftsPurplePaintBucket, frameWidth: 16, frameHeight: 32, frames: 8, fps: 10 }],
  [sftsQueenBeeGif, { sheet: sftsQueenBee, frameWidth: 15, frameHeight: 19, frames: 8, fps: 13 }],
  [sftsRadishMutantGif, { sheet: sftsRadishMutant, frameWidth: 22, frameHeight: 22, frames: 2, fps: 3 }],
  [sftsRainbowFlowerGif, { sheet: sftsRainbowFlower, frameWidth: 30, frameHeight: 34, frames: 27, fps: 5 }],
  [sftsRainbowPorkJellyGif, { sheet: sftsRainbowPorkJelly, frameWidth: 16, frameHeight: 16, frames: 9, fps: 14 }],
  [sftsRaveyardGif, { sheet: sftsRaveyard, frameWidth: 21, frameHeight: 26, frames: 8, fps: 10 }],
  [sftsRedNoseReindeerGif, { sheet: sftsRedNoseReindeer, frameWidth: 22, frameHeight: 29, frames: 9, fps: 7 }],
  [sftsRedSlimeBalloonGif, { sheet: sftsRedSlimeBalloon, frameWidth: 19, frameHeight: 36, frames: 8, fps: 10 }],
  [sftsRockGolemGif, { sheet: sftsRockGolem, frameWidth: 34, frameHeight: 42, frames: 40, fps: 10 }],
  [sftsSantaPenguinGif, { sheet: sftsSantaPenguin, frameWidth: 18, frameHeight: 16, frames: 6, fps: 6 }],
  [sftsSkillShrimpyGif, { sheet: sftsSkillShrimpy, frameWidth: 14, frameHeight: 16, frames: 4, fps: 5 }],
  [sftsSpinningWheelGif, { sheet: sftsSpinningWheel, frameWidth: 30, frameHeight: 27, frames: 7, fps: 10 }],
  [sftsSummerChickenGif, { sheet: sftsSummerChicken, frameWidth: 21, frameHeight: 25, frames: 8, fps: 14 }],
  [sftsSunflowerMutantGif, { sheet: sftsSunflowerMutant, frameWidth: 22, frameHeight: 22, frames: 2, fps: 3 }],
  [sftsThermalStoneGif, { sheet: sftsThermalStone, frameWidth: 18, frameHeight: 22, frames: 5, fps: 11 }],
  [sftsTornadoPinwheelGif, { sheet: sftsTornadoPinwheel, frameWidth: 17, frameHeight: 33, frames: 16, fps: 13 }],
  [sftsTuxedoClausGif, { sheet: sftsTuxedoClaus, frameWidth: 35, frameHeight: 46, frames: 8, fps: 7 }],
  [sftsUfoGif, { sheet: sftsUfo, frameWidth: 36, frameHeight: 35, frames: 12, fps: 10 }],
  [sftsVampireCoffinGif, { sheet: sftsVampireCoffin, frameWidth: 24, frameHeight: 34, frames: 8, fps: 10 }],
  [sftsWalrusGif, { sheet: sftsWalrus, frameWidth: 25, frameHeight: 26, frames: 5, fps: 14 }],
  [sftsWhiteTunnelBunnyGif, { sheet: sftsWhiteTunnelBunny, frameWidth: 15, frameHeight: 16, frames: 25, fps: 2 }],
  [sftsWinterAlpacaGif, { sheet: sftsWinterAlpaca, frameWidth: 32, frameHeight: 39, frames: 9, fps: 7 }],
  [sftsWitchsCauldronGif, { sheet: sftsWitchsCauldron, frameWidth: 32, frameHeight: 38, frames: 7, fps: 10 }],
  [sftsYellowPaintBucketGif, { sheet: sftsYellowPaintBucket, frameWidth: 16, frameHeight: 32, frames: 8, fps: 10 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/buildings/smoke.gif`, { sheet: buildingsSmoke, frameWidth: 20, frameHeight: 32, frames: 30, fps: 10 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/fx/sparkle2.gif`, { sheet: fxSparkle2, frameWidth: 7, frameHeight: 7, frames: 16, fps: 8 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/land/levels/pontoon.gif`, { sheet: landLevelsPontoon, frameWidth: 129, frameHeight: 57, frames: 23, fps: 14 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/artisian_doing.gif`, { sheet: npcsArtisianDoing, frameWidth: 17, frameHeight: 17, frames: 8, fps: 10 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/artisian.gif`, { sheet: npcsArtisian, frameWidth: 15, frameHeight: 17, frames: 9, fps: 11 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/chef_doing.gif`, { sheet: npcsChefDoing, frameWidth: 16, frameHeight: 19, frames: 8, fps: 10 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/chef.gif`, { sheet: npcsChef, frameWidth: 15, frameHeight: 18, frames: 9, fps: 14 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/cook_doing.gif`, { sheet: npcsCookDoing, frameWidth: 16, frameHeight: 17, frames: 8, fps: 10 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/cook.gif`, { sheet: npcsCook, frameWidth: 14, frameHeight: 16, frames: 8, fps: 14 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_chef_doing.gif`, { sheet: npcsGoblinChefDoing, frameWidth: 25, frameHeight: 27, frames: 8, fps: 10 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_chef.gif`, { sheet: npcsGoblinChef, frameWidth: 22, frameHeight: 25, frames: 9, fps: 14 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_snorkling.gif`, { sheet: npcsGoblinSnorkling, frameWidth: 24, frameHeight: 21, frames: 38, fps: 10 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_swimming.gif`, { sheet: npcsGoblinSwimming, frameWidth: 96, frameHeight: 64, frames: 63, fps: 13 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/neville_doing.gif`, { sheet: npcsNevilleDoing, frameWidth: 20, frameHeight: 19, frames: 8, fps: 14 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/smoothie_making.gif`, { sheet: npcsSmoothieMaking, frameWidth: 15, frameHeight: 18, frames: 9, fps: 11 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/smoothie.gif`, { sheet: npcsSmoothie, frameWidth: 14, frameHeight: 17, frames: 9, fps: 14 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/npcs/swimmer.gif`, { sheet: npcsSwimmer, frameWidth: 16, frameHeight: 16, frames: 12, fps: 10 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/idle_chicken.gif`, { sheet: animalsChickensIdleChicken, frameWidth: 11, frameHeight: 11, frames: 5, fps: 5 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/sleeping_chicken.gif`, { sheet: animalsChickensSleepingChicken, frameWidth: 13, frameHeight: 11, frames: 2, fps: 1 }],
  [`${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/ready.webp`, { sheet: animalsChickensReady, frameWidth: 26, frameHeight: 22, frames: 6, fps: 4 }],
  ["https://buds.sunflower-land.com/images/933.webp", { sheet: buds933, frameWidth: 32, frameHeight: 32, frames: 9, fps: 14 }],
  ["https://testnet-buds.sunflower-land.com/images/933.webp", { sheet: buds933, frameWidth: 32, frameHeight: 32, frames: 9, fps: 14 }],
  ["https://pets.sunflower-land.com/sleepings/20_animated.webp", { sheet: petsSleepings20, frameWidth: 44, frameHeight: 44, frames: 2, fps: 1 }],
  ["https://testnet-pets.sunflower-land.com/sleepings/20_animated.webp", { sheet: petsSleepings20, frameWidth: 44, frameHeight: 44, frames: 2, fps: 1 }],
  ["https://pets.sunflower-land.com/sleepings/2921_animated.webp", { sheet: petsSleepings2921, frameWidth: 44, frameHeight: 44, frames: 2, fps: 1 }],
  ["https://testnet-pets.sunflower-land.com/sleepings/2921_animated.webp", { sheet: petsSleepings2921, frameWidth: 44, frameHeight: 44, frames: 2, fps: 1 }],
  ["https://pets.sunflower-land.com/sleepings/3000_animated.webp", { sheet: petsSleepings3000, frameWidth: 44, frameHeight: 44, frames: 9, fps: 7 }],
  ["https://testnet-pets.sunflower-land.com/sleepings/3000_animated.webp", { sheet: petsSleepings3000, frameWidth: 44, frameHeight: 44, frames: 9, fps: 7 }],
]);

/** The converted strip for an art URL, when one exists. */
export const animatedArtFor = (url: string | undefined): AnimatedArt | undefined =>
  url ? ANIMATED_ART[url] : undefined;
