name: Bug report
description: Report a bug found in game.
title: "[BUG] "
labels: ["🐞 bug"]
assignees: []
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Search existing issues
      description: Please search to see if an issue already exists for this bug.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary of Bug
      description: Provide a brief summary of the bug you found.
      placeholder: A concise description of the bug...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed step-by-step instructions for how this bug can be reproduced.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Provide a description of what you expected to happen.
      placeholder: What should have happened...
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide a description of what actually happened.
      placeholder: What actually happened...
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can drag and drop images here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Device Information"
  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: false
  - type: textarea
    id: device-info
    attributes:
      label: Device Details
      description: Please complete the following information.
      placeholder: |
        - Device: [e.g. iPhone6, Pixel 6a]
        - OS: [e.g. iOS, Linux, Windows, Android]
        - Browser/App: [e.g. firefox, safari, chrome, metamask mobile]
        - Version: [e.g. 22]
    validations:
      required: false
