import { Scene } from "../Scene";

interface Props {
  x: number;
  y: number;
  scene: Scene;
}

/**
 * Puddle — A puddle generated by the DripWalker while walking.
 * It remains static on the map, beneath NPCs and the player.
 */
export class Puddle extends Phaser.GameObjects.Container {
  constructor({ x, y, scene }: Props) {
    super(scene, x, y);

    const sprite = scene.add.sprite(0, 0, "puddle")
      .setScale(0.9);
    this.add(sprite);
    this.setDepth(1);

    scene.add.existing(this);
    scene.physics.add.existing(this);

    const body = this.body as Phaser.Physics.Arcade.Body;
    body.setSize(sprite.width, sprite.height);
    body.setOffset(-sprite.width / 2, -sprite.height / 2);

    if (scene.currentPlayer) {
      scene.physics.add.overlap(scene.currentPlayer, this, () => {
        if (!scene.isSliding && scene.movementAngle !== undefined) {
          scene.isSliding = true;
          scene.slideAngle = scene.movementAngle;
        }
      });
    }
  }
}
