/**
 * Generates `src/features/world/lib/loveIslandTiles.ts`: which tiles of Love
 * Island a Lover's Push boulder can roll over, packed one bit per tile.
 *
 *   npx tsx _scripts/loveIslandTiles.ts
 *
 * A tile is walkable when a ground or path layer has a tile there (so it's
 * island, not the sky or water around it) and neither a `Collision`
 * rectangle nor one of the scene's own fixtures (`loveIslandFixtures.ts` -
 * the Love Boulder) touches it. Re-run whenever `love_island_map.json` or
 * the fixtures change, and copy the output to the API's
 * `src/colyseus/src/lib/loveIslandTiles.ts` - the room validates pushes and
 * rolls layouts against the same bits.
 */
import fs from "fs";
import path from "path";
import { LOVE_ISLAND_FIXTURES } from "../src/features/world/lib/loveIslandFixtures";

type TileLayer = { type: string; name: string; data?: number[] };
type ObjectLayer = {
  type: string;
  name: string;
  objects?: { x: number; y: number; width: number; height: number }[];
};

const mapPath = path.join(__dirname, "../src/assets/map/love_island_map.json");
const outPath = path.join(
  __dirname,
  "../src/features/world/lib/loveIslandTiles.ts",
);

const map = JSON.parse(fs.readFileSync(mapPath, "utf-8")) as {
  width: number;
  height: number;
  tilewidth: number;
  layers: (TileLayer | ObjectLayer)[];
};

const { width, height, tilewidth } = map;

const land = new Uint8Array(width * height);
map.layers
  .filter(
    (layer): layer is TileLayer =>
      layer.type === "tilelayer" &&
      (layer.name.startsWith("Ground") || layer.name.startsWith("Paths")),
  )
  .forEach((layer) => {
    layer.data?.forEach((gid, index) => {
      if (gid) land[index] = 1;
    });
  });

const collision = map.layers.find(
  (layer): layer is ObjectLayer =>
    layer.type === "objectgroup" && layer.name === "Collision",
);

const blocked = new Uint8Array(width * height);
[...(collision?.objects ?? []), ...LOVE_ISLAND_FIXTURES].forEach(
  ({ x, y, width: w, height: h }) => {
    const x0 = Math.floor(x / tilewidth);
    const y0 = Math.floor(y / tilewidth);
    const x1 = Math.ceil((x + w) / tilewidth);
    const y1 = Math.ceil((y + h) / tilewidth);
    for (let ty = Math.max(0, y0); ty < Math.min(height, y1); ty++) {
      for (let tx = Math.max(0, x0); tx < Math.min(width, x1); tx++) {
        blocked[ty * width + tx] = 1;
      }
    }
  },
);

const bytes = new Uint8Array(Math.ceil((width * height) / 8));
let walkable = 0;
for (let index = 0; index < width * height; index++) {
  if (land[index] && !blocked[index]) {
    bytes[index >> 3] |= 1 << (index & 7);
    walkable += 1;
  }
}

const packed = Buffer.from(bytes).toString("base64");

const lines = [
  "/**",
  " * GENERATED by `npx tsx _scripts/loveIslandTiles.ts` from",
  " * `src/assets/map/love_island_map.json` - do not edit by hand.",
  " *",
  " * Which tiles of Love Island a Lover's Push boulder can roll over: one bit",
  " * per 16px tile, row-major, least significant bit first within each byte,",
  " * base64. A tile is walkable when a ground or path layer covers it and",
  " * neither a `Collision` rectangle nor a scene fixture (`loveIslandFixtures.ts`)",
  " * touches it. The API carries a verbatim copy; the room and every client",
  " * must agree on these bits.",
  " */",
  "",
  `export const LOVE_ISLAND_MAP_WIDTH = ${width};`,
  `export const LOVE_ISLAND_MAP_HEIGHT = ${height};`,
  `export const LOVE_ISLAND_TILE_PX = ${tilewidth};`,
  `/** ${walkable} walkable tiles. */`,
  "export const LOVE_ISLAND_WALKABLE =",
  ...packed
    .match(/.{1,74}/g)!
    .map((chunk, i, all) => `  "${chunk}"${i === all.length - 1 ? ";" : " +"}`),
  "",
];

fs.writeFileSync(outPath, lines.join("\n"));
// eslint-disable-next-line no-console
console.log(`${outPath}: ${walkable} walkable tiles`);
