import React from "react";

import { SUNNYSIDE } from "assets/sunnyside";

import { NaturalImage } from "components/ui/NaturalImage";
import { Section } from "lib/utils/hooks/useScrollIntoView";
import type { GameState, TemperateSeasonName } from "features/game/types/game";
import { getCurrentBiome } from "features/island/biomes/biomes";
import type { LandBiomeName } from "features/island/biomes/biomes";

const SPRING_BASIC_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.basicLevel1,
  2: SUNNYSIDE.seasons.spring.basicLevel2,
  3: SUNNYSIDE.seasons.spring.basicLevel3,
  4: SUNNYSIDE.seasons.spring.basicLevel4,
  5: SUNNYSIDE.seasons.spring.basicLevel5,
  6: SUNNYSIDE.seasons.spring.basicLevel6,
  7: SUNNYSIDE.seasons.spring.basicLevel7,
  8: SUNNYSIDE.seasons.spring.basicLevel8,
  9: SUNNYSIDE.seasons.spring.basicLevel9,
  10: SUNNYSIDE.seasons.spring.basicLevel10,
  11: SUNNYSIDE.seasons.spring.basicLevel11,
  12: SUNNYSIDE.seasons.spring.basicLevel12,
  13: SUNNYSIDE.seasons.spring.basicLevel13,
  14: SUNNYSIDE.seasons.spring.basicLevel14,
  15: SUNNYSIDE.seasons.spring.basicLevel15,
  16: SUNNYSIDE.seasons.spring.basicLevel16,
  17: SUNNYSIDE.seasons.spring.basicLevel17,
  18: SUNNYSIDE.seasons.spring.basicLevel18,
  19: SUNNYSIDE.seasons.spring.basicLevel19,
  20: SUNNYSIDE.seasons.spring.basicLevel20,
  21: SUNNYSIDE.seasons.spring.basicLevel21,
  22: SUNNYSIDE.seasons.spring.basicLevel22,
  23: SUNNYSIDE.seasons.spring.basicLevel23,
  24: SUNNYSIDE.seasons.spring.basicLevel24,
  25: SUNNYSIDE.seasons.spring.basicLevel25,
  26: SUNNYSIDE.seasons.spring.basicLevel26,
  27: SUNNYSIDE.seasons.spring.basicLevel27,
  28: SUNNYSIDE.seasons.spring.basicLevel28,
  29: SUNNYSIDE.seasons.spring.basicLevel29,
  30: SUNNYSIDE.seasons.spring.basicLevel30,
  31: SUNNYSIDE.seasons.spring.basicLevel31,
  32: SUNNYSIDE.seasons.spring.basicLevel32,
  33: SUNNYSIDE.seasons.spring.basicLevel33,
  34: SUNNYSIDE.seasons.spring.basicLevel34,
  35: SUNNYSIDE.seasons.spring.basicLevel35,
  36: SUNNYSIDE.seasons.spring.basicLevel36,
  37: SUNNYSIDE.seasons.spring.basicLevel37,
  38: SUNNYSIDE.seasons.spring.basicLevel38,
  39: SUNNYSIDE.seasons.spring.basicLevel39,
  40: SUNNYSIDE.seasons.spring.basicLevel40,
  41: SUNNYSIDE.seasons.spring.basicLevel41,
  42: SUNNYSIDE.seasons.spring.basicLevel42,
};

const SUMMER_BASIC_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.basicLevel1,
  2: SUNNYSIDE.land.basicLevel2,
  3: SUNNYSIDE.land.basicLevel3,
  4: SUNNYSIDE.land.basicLevel4,
  5: SUNNYSIDE.land.basicLevel5,
  6: SUNNYSIDE.land.basicLevel6,
  7: SUNNYSIDE.land.basicLevel7,
  8: SUNNYSIDE.land.basicLevel8,
  9: SUNNYSIDE.land.basicLevel9,
  10: SUNNYSIDE.land.basicLevel10,
  11: SUNNYSIDE.land.basicLevel11,
  12: SUNNYSIDE.land.basicLevel12,
  13: SUNNYSIDE.land.basicLevel13,
  14: SUNNYSIDE.land.basicLevel14,
  15: SUNNYSIDE.land.basicLevel15,
  16: SUNNYSIDE.land.basicLevel16,
  17: SUNNYSIDE.land.basicLevel17,
  18: SUNNYSIDE.land.basicLevel18,
  19: SUNNYSIDE.land.basicLevel19,
  20: SUNNYSIDE.land.basicLevel20,
  21: SUNNYSIDE.land.basicLevel21,
  22: SUNNYSIDE.land.basicLevel22,
  23: SUNNYSIDE.land.basicLevel23,
  24: SUNNYSIDE.land.basicLevel24,
  25: SUNNYSIDE.land.basicLevel25,
  26: SUNNYSIDE.land.basicLevel26,
  27: SUNNYSIDE.land.basicLevel27,
  28: SUNNYSIDE.land.basicLevel28,
  29: SUNNYSIDE.land.basicLevel29,
  30: SUNNYSIDE.land.basicLevel30,
  31: SUNNYSIDE.land.basicLevel31,
  32: SUNNYSIDE.land.basicLevel32,
  33: SUNNYSIDE.land.basicLevel33,
  34: SUNNYSIDE.land.basicLevel34,
  35: SUNNYSIDE.land.basicLevel35,
  36: SUNNYSIDE.land.basicLevel36,
  37: SUNNYSIDE.land.basicLevel37,
  38: SUNNYSIDE.land.basicLevel38,
  39: SUNNYSIDE.land.basicLevel39,
  40: SUNNYSIDE.land.basicLevel40,
  41: SUNNYSIDE.land.basicLevel41,
  42: SUNNYSIDE.land.basicLevel42,
};
const AUTUMN_BASIC_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.basicLevel1,
  2: SUNNYSIDE.seasons.autumn.basicLevel2,
  3: SUNNYSIDE.seasons.autumn.basicLevel3,
  4: SUNNYSIDE.seasons.autumn.basicLevel4,
  5: SUNNYSIDE.seasons.autumn.basicLevel5,
  6: SUNNYSIDE.seasons.autumn.basicLevel6,
  7: SUNNYSIDE.seasons.autumn.basicLevel7,
  8: SUNNYSIDE.seasons.autumn.basicLevel8,
  9: SUNNYSIDE.seasons.autumn.basicLevel9,
  10: SUNNYSIDE.seasons.autumn.basicLevel10,
  11: SUNNYSIDE.seasons.autumn.basicLevel11,
  12: SUNNYSIDE.seasons.autumn.basicLevel12,
  13: SUNNYSIDE.seasons.autumn.basicLevel13,
  14: SUNNYSIDE.seasons.autumn.basicLevel14,
  15: SUNNYSIDE.seasons.autumn.basicLevel15,
  16: SUNNYSIDE.seasons.autumn.basicLevel16,
  17: SUNNYSIDE.seasons.autumn.basicLevel17,
  18: SUNNYSIDE.seasons.autumn.basicLevel18,
  19: SUNNYSIDE.seasons.autumn.basicLevel19,
  20: SUNNYSIDE.seasons.autumn.basicLevel20,
  21: SUNNYSIDE.seasons.autumn.basicLevel21,
  22: SUNNYSIDE.seasons.autumn.basicLevel22,
  23: SUNNYSIDE.seasons.autumn.basicLevel23,
  24: SUNNYSIDE.seasons.autumn.basicLevel24,
  25: SUNNYSIDE.seasons.autumn.basicLevel25,
  26: SUNNYSIDE.seasons.autumn.basicLevel26,
  27: SUNNYSIDE.seasons.autumn.basicLevel27,
  28: SUNNYSIDE.seasons.autumn.basicLevel28,
  29: SUNNYSIDE.seasons.autumn.basicLevel29,
  30: SUNNYSIDE.seasons.autumn.basicLevel30,
  31: SUNNYSIDE.seasons.autumn.basicLevel31,
  32: SUNNYSIDE.seasons.autumn.basicLevel32,
  33: SUNNYSIDE.seasons.autumn.basicLevel33,
  34: SUNNYSIDE.seasons.autumn.basicLevel34,
  35: SUNNYSIDE.seasons.autumn.basicLevel35,
  36: SUNNYSIDE.seasons.autumn.basicLevel36,
  37: SUNNYSIDE.seasons.autumn.basicLevel37,
  38: SUNNYSIDE.seasons.autumn.basicLevel38,
  39: SUNNYSIDE.seasons.autumn.basicLevel39,
  40: SUNNYSIDE.seasons.autumn.basicLevel40,
  41: SUNNYSIDE.seasons.autumn.basicLevel41,
  42: SUNNYSIDE.seasons.autumn.basicLevel42,
};
const WINTER_BASIC_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.basicLevel1,
  2: SUNNYSIDE.seasons.winter.basicLevel2,
  3: SUNNYSIDE.seasons.winter.basicLevel3,
  4: SUNNYSIDE.seasons.winter.basicLevel4,
  5: SUNNYSIDE.seasons.winter.basicLevel5,
  6: SUNNYSIDE.seasons.winter.basicLevel6,
  7: SUNNYSIDE.seasons.winter.basicLevel7,
  8: SUNNYSIDE.seasons.winter.basicLevel8,
  9: SUNNYSIDE.seasons.winter.basicLevel9,
  10: SUNNYSIDE.seasons.winter.basicLevel10,
  11: SUNNYSIDE.seasons.winter.basicLevel11,
  12: SUNNYSIDE.seasons.winter.basicLevel12,
  13: SUNNYSIDE.seasons.winter.basicLevel13,
  14: SUNNYSIDE.seasons.winter.basicLevel14,
  15: SUNNYSIDE.seasons.winter.basicLevel15,
  16: SUNNYSIDE.seasons.winter.basicLevel16,
  17: SUNNYSIDE.seasons.winter.basicLevel17,
  18: SUNNYSIDE.seasons.winter.basicLevel18,
  19: SUNNYSIDE.seasons.winter.basicLevel19,
  20: SUNNYSIDE.seasons.winter.basicLevel20,
  21: SUNNYSIDE.seasons.winter.basicLevel21,
  22: SUNNYSIDE.seasons.winter.basicLevel22,
  23: SUNNYSIDE.seasons.winter.basicLevel23,
  24: SUNNYSIDE.seasons.winter.basicLevel24,
  25: SUNNYSIDE.seasons.winter.basicLevel25,
  26: SUNNYSIDE.seasons.winter.basicLevel26,
  27: SUNNYSIDE.seasons.winter.basicLevel27,
  28: SUNNYSIDE.seasons.winter.basicLevel28,
  29: SUNNYSIDE.seasons.winter.basicLevel29,
  30: SUNNYSIDE.seasons.winter.basicLevel30,
  31: SUNNYSIDE.seasons.winter.basicLevel31,
  32: SUNNYSIDE.seasons.winter.basicLevel32,
  33: SUNNYSIDE.seasons.winter.basicLevel33,
  34: SUNNYSIDE.seasons.winter.basicLevel34,
  35: SUNNYSIDE.seasons.winter.basicLevel35,
  36: SUNNYSIDE.seasons.winter.basicLevel36,
  37: SUNNYSIDE.seasons.winter.basicLevel37,
  38: SUNNYSIDE.seasons.winter.basicLevel38,
  39: SUNNYSIDE.seasons.winter.basicLevel39,
  40: SUNNYSIDE.seasons.winter.basicLevel40,
  41: SUNNYSIDE.seasons.winter.basicLevel41,
  42: SUNNYSIDE.seasons.winter.basicLevel42,
};

const SPRING_DESERT_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.desertLevel1,
  2: SUNNYSIDE.seasons.spring.desertLevel2,
  3: SUNNYSIDE.seasons.spring.desertLevel3,
  4: SUNNYSIDE.seasons.spring.desertLevel4,
  5: SUNNYSIDE.seasons.spring.desertLevel5,
  6: SUNNYSIDE.seasons.spring.desertLevel6,
  7: SUNNYSIDE.seasons.spring.desertLevel7,
  8: SUNNYSIDE.seasons.spring.desertLevel8,
  9: SUNNYSIDE.seasons.spring.desertLevel9,
  10: SUNNYSIDE.seasons.spring.desertLevel10,
  11: SUNNYSIDE.seasons.spring.desertLevel11,
  12: SUNNYSIDE.seasons.spring.desertLevel12,
  13: SUNNYSIDE.seasons.spring.desertLevel13,
  14: SUNNYSIDE.seasons.spring.desertLevel14,
  15: SUNNYSIDE.seasons.spring.desertLevel15,
  16: SUNNYSIDE.seasons.spring.desertLevel16,
  17: SUNNYSIDE.seasons.spring.desertLevel17,
  18: SUNNYSIDE.seasons.spring.desertLevel18,
  19: SUNNYSIDE.seasons.spring.desertLevel19,
  20: SUNNYSIDE.seasons.spring.desertLevel20,
  21: SUNNYSIDE.seasons.spring.desertLevel21,
  22: SUNNYSIDE.seasons.spring.desertLevel22,
  23: SUNNYSIDE.seasons.spring.desertLevel23,
  24: SUNNYSIDE.seasons.spring.desertLevel24,
  25: SUNNYSIDE.seasons.spring.desertLevel25,
  26: SUNNYSIDE.seasons.spring.desertLevel26,
  27: SUNNYSIDE.seasons.spring.desertLevel27,
  28: SUNNYSIDE.seasons.spring.desertLevel28,
  29: SUNNYSIDE.seasons.spring.desertLevel29,
  30: SUNNYSIDE.seasons.spring.desertLevel30,
  31: SUNNYSIDE.seasons.spring.desertLevel31,
  32: SUNNYSIDE.seasons.spring.desertLevel32,
  33: SUNNYSIDE.seasons.spring.desertLevel33,
  34: SUNNYSIDE.seasons.spring.desertLevel34,
  35: SUNNYSIDE.seasons.spring.desertLevel35,
  36: SUNNYSIDE.seasons.spring.desertLevel36,
  37: SUNNYSIDE.seasons.spring.desertLevel37,
  38: SUNNYSIDE.seasons.spring.desertLevel38,
  39: SUNNYSIDE.seasons.spring.desertLevel39,
  40: SUNNYSIDE.seasons.spring.desertLevel40,
  41: SUNNYSIDE.seasons.spring.desertLevel41,
  42: SUNNYSIDE.seasons.spring.desertLevel42,
};

const SUMMER_DESERT_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.desertLevel1,
  2: SUNNYSIDE.land.desertLevel2,
  3: SUNNYSIDE.land.desertLevel3,
  4: SUNNYSIDE.land.desertLevel4,
  5: SUNNYSIDE.land.desertLevel5,
  6: SUNNYSIDE.land.desertLevel6,
  7: SUNNYSIDE.land.desertLevel7,
  8: SUNNYSIDE.land.desertLevel8,
  9: SUNNYSIDE.land.desertLevel9,
  10: SUNNYSIDE.land.desertLevel10,
  11: SUNNYSIDE.land.desertLevel11,
  12: SUNNYSIDE.land.desertLevel12,
  13: SUNNYSIDE.land.desertLevel13,
  14: SUNNYSIDE.land.desertLevel14,
  15: SUNNYSIDE.land.desertLevel15,
  16: SUNNYSIDE.land.desertLevel16,
  17: SUNNYSIDE.land.desertLevel17,
  18: SUNNYSIDE.land.desertLevel18,
  19: SUNNYSIDE.land.desertLevel19,
  20: SUNNYSIDE.land.desertLevel20,
  21: SUNNYSIDE.land.desertLevel21,
  22: SUNNYSIDE.land.desertLevel22,
  23: SUNNYSIDE.land.desertLevel23,
  24: SUNNYSIDE.land.desertLevel24,
  25: SUNNYSIDE.land.desertLevel25,
  26: SUNNYSIDE.land.desertLevel26,
  27: SUNNYSIDE.land.desertLevel27,
  28: SUNNYSIDE.land.desertLevel28,
  29: SUNNYSIDE.land.desertLevel29,
  30: SUNNYSIDE.land.desertLevel30,
  31: SUNNYSIDE.land.desertLevel31,
  32: SUNNYSIDE.land.desertLevel32,
  33: SUNNYSIDE.land.desertLevel33,
  34: SUNNYSIDE.land.desertLevel34,
  35: SUNNYSIDE.land.desertLevel35,
  36: SUNNYSIDE.land.desertLevel36,
  37: SUNNYSIDE.land.desertLevel37,
  38: SUNNYSIDE.land.desertLevel38,
  39: SUNNYSIDE.land.desertLevel39,
  40: SUNNYSIDE.land.desertLevel40,
  41: SUNNYSIDE.land.desertLevel41,
  42: SUNNYSIDE.land.desertLevel42,
};

const AUTUMN_DESERT_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.desertLevel1,
  2: SUNNYSIDE.seasons.autumn.desertLevel2,
  3: SUNNYSIDE.seasons.autumn.desertLevel3,
  4: SUNNYSIDE.seasons.autumn.desertLevel4,
  5: SUNNYSIDE.seasons.autumn.desertLevel5,
  6: SUNNYSIDE.seasons.autumn.desertLevel6,
  7: SUNNYSIDE.seasons.autumn.desertLevel7,
  8: SUNNYSIDE.seasons.autumn.desertLevel8,
  9: SUNNYSIDE.seasons.autumn.desertLevel9,
  10: SUNNYSIDE.seasons.autumn.desertLevel10,
  11: SUNNYSIDE.seasons.autumn.desertLevel11,
  12: SUNNYSIDE.seasons.autumn.desertLevel12,
  13: SUNNYSIDE.seasons.autumn.desertLevel13,
  14: SUNNYSIDE.seasons.autumn.desertLevel14,
  15: SUNNYSIDE.seasons.autumn.desertLevel15,
  16: SUNNYSIDE.seasons.autumn.desertLevel16,
  17: SUNNYSIDE.seasons.autumn.desertLevel17,
  18: SUNNYSIDE.seasons.autumn.desertLevel18,
  19: SUNNYSIDE.seasons.autumn.desertLevel19,
  20: SUNNYSIDE.seasons.autumn.desertLevel20,
  21: SUNNYSIDE.seasons.autumn.desertLevel21,
  22: SUNNYSIDE.seasons.autumn.desertLevel22,
  23: SUNNYSIDE.seasons.autumn.desertLevel23,
  24: SUNNYSIDE.seasons.autumn.desertLevel24,
  25: SUNNYSIDE.seasons.autumn.desertLevel25,
  26: SUNNYSIDE.seasons.autumn.desertLevel26,
  27: SUNNYSIDE.seasons.autumn.desertLevel27,
  28: SUNNYSIDE.seasons.autumn.desertLevel28,
  29: SUNNYSIDE.seasons.autumn.desertLevel29,
  30: SUNNYSIDE.seasons.autumn.desertLevel30,
  31: SUNNYSIDE.seasons.autumn.desertLevel31,
  32: SUNNYSIDE.seasons.autumn.desertLevel32,
  33: SUNNYSIDE.seasons.autumn.desertLevel33,
  34: SUNNYSIDE.seasons.autumn.desertLevel34,
  35: SUNNYSIDE.seasons.autumn.desertLevel35,
  36: SUNNYSIDE.seasons.autumn.desertLevel36,
  37: SUNNYSIDE.seasons.autumn.desertLevel37,
  38: SUNNYSIDE.seasons.autumn.desertLevel38,
  39: SUNNYSIDE.seasons.autumn.desertLevel39,
  40: SUNNYSIDE.seasons.autumn.desertLevel40,
  41: SUNNYSIDE.seasons.autumn.desertLevel41,
  42: SUNNYSIDE.seasons.autumn.desertLevel42,
};

const WINTER_DESERT_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.desertLevel1,
  2: SUNNYSIDE.seasons.winter.desertLevel2,
  3: SUNNYSIDE.seasons.winter.desertLevel3,
  4: SUNNYSIDE.seasons.winter.desertLevel4,
  5: SUNNYSIDE.seasons.winter.desertLevel5,
  6: SUNNYSIDE.seasons.winter.desertLevel6,
  7: SUNNYSIDE.seasons.winter.desertLevel7,
  8: SUNNYSIDE.seasons.winter.desertLevel8,
  9: SUNNYSIDE.seasons.winter.desertLevel9,
  10: SUNNYSIDE.seasons.winter.desertLevel10,
  11: SUNNYSIDE.seasons.winter.desertLevel11,
  12: SUNNYSIDE.seasons.winter.desertLevel12,
  13: SUNNYSIDE.seasons.winter.desertLevel13,
  14: SUNNYSIDE.seasons.winter.desertLevel14,
  15: SUNNYSIDE.seasons.winter.desertLevel15,
  16: SUNNYSIDE.seasons.winter.desertLevel16,
  17: SUNNYSIDE.seasons.winter.desertLevel17,
  18: SUNNYSIDE.seasons.winter.desertLevel18,
  19: SUNNYSIDE.seasons.winter.desertLevel19,
  20: SUNNYSIDE.seasons.winter.desertLevel20,
  21: SUNNYSIDE.seasons.winter.desertLevel21,
  22: SUNNYSIDE.seasons.winter.desertLevel22,
  23: SUNNYSIDE.seasons.winter.desertLevel23,
  24: SUNNYSIDE.seasons.winter.desertLevel24,
  25: SUNNYSIDE.seasons.winter.desertLevel25,
  26: SUNNYSIDE.seasons.winter.desertLevel26,
  27: SUNNYSIDE.seasons.winter.desertLevel27,
  28: SUNNYSIDE.seasons.winter.desertLevel28,
  29: SUNNYSIDE.seasons.winter.desertLevel29,
  30: SUNNYSIDE.seasons.winter.desertLevel30,
  31: SUNNYSIDE.seasons.winter.desertLevel31,
  32: SUNNYSIDE.seasons.winter.desertLevel32,
  33: SUNNYSIDE.seasons.winter.desertLevel33,
  34: SUNNYSIDE.seasons.winter.desertLevel34,
  35: SUNNYSIDE.seasons.winter.desertLevel35,
  36: SUNNYSIDE.seasons.winter.desertLevel36,
  37: SUNNYSIDE.seasons.winter.desertLevel37,
  38: SUNNYSIDE.seasons.winter.desertLevel38,
  39: SUNNYSIDE.seasons.winter.desertLevel39,
  40: SUNNYSIDE.seasons.winter.desertLevel40,
  41: SUNNYSIDE.seasons.winter.desertLevel41,
  42: SUNNYSIDE.seasons.winter.desertLevel42,
};

const SPRING_VOLCANO_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.volcanoLevel1,
  2: SUNNYSIDE.seasons.spring.volcanoLevel2,
  3: SUNNYSIDE.seasons.spring.volcanoLevel3,
  4: SUNNYSIDE.seasons.spring.volcanoLevel4,
  5: SUNNYSIDE.seasons.spring.volcanoLevel5,
  6: SUNNYSIDE.seasons.spring.volcanoLevel6,
  7: SUNNYSIDE.seasons.spring.volcanoLevel7,
  8: SUNNYSIDE.seasons.spring.volcanoLevel8,
  9: SUNNYSIDE.seasons.spring.volcanoLevel9,
  10: SUNNYSIDE.seasons.spring.volcanoLevel10,
  11: SUNNYSIDE.seasons.spring.volcanoLevel11,
  12: SUNNYSIDE.seasons.spring.volcanoLevel12,
  13: SUNNYSIDE.seasons.spring.volcanoLevel13,
  14: SUNNYSIDE.seasons.spring.volcanoLevel14,
  15: SUNNYSIDE.seasons.spring.volcanoLevel15,
  16: SUNNYSIDE.seasons.spring.volcanoLevel16,
  17: SUNNYSIDE.seasons.spring.volcanoLevel17,
  18: SUNNYSIDE.seasons.spring.volcanoLevel18,
  19: SUNNYSIDE.seasons.spring.volcanoLevel19,
  20: SUNNYSIDE.seasons.spring.volcanoLevel20,
  21: SUNNYSIDE.seasons.spring.volcanoLevel21,
  22: SUNNYSIDE.seasons.spring.volcanoLevel22,
  23: SUNNYSIDE.seasons.spring.volcanoLevel23,
  24: SUNNYSIDE.seasons.spring.volcanoLevel24,
  25: SUNNYSIDE.seasons.spring.volcanoLevel25,
  26: SUNNYSIDE.seasons.spring.volcanoLevel26,
  27: SUNNYSIDE.seasons.spring.volcanoLevel27,
  28: SUNNYSIDE.seasons.spring.volcanoLevel28,
  29: SUNNYSIDE.seasons.spring.volcanoLevel29,
  30: SUNNYSIDE.seasons.spring.volcanoLevel30,
  31: SUNNYSIDE.seasons.spring.volcanoLevel31,
  32: SUNNYSIDE.seasons.spring.volcanoLevel32,
  33: SUNNYSIDE.seasons.spring.volcanoLevel33,
  34: SUNNYSIDE.seasons.spring.volcanoLevel34,
  35: SUNNYSIDE.seasons.spring.volcanoLevel35,
  36: SUNNYSIDE.seasons.spring.volcanoLevel36,
  37: SUNNYSIDE.seasons.spring.volcanoLevel37,
  38: SUNNYSIDE.seasons.spring.volcanoLevel38,
  39: SUNNYSIDE.seasons.spring.volcanoLevel39,
  40: SUNNYSIDE.seasons.spring.volcanoLevel40,
  41: SUNNYSIDE.seasons.spring.volcanoLevel41,
  42: SUNNYSIDE.seasons.spring.volcanoLevel42,
};

const SUMMER_VOLCANO_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.volcanoLevel1,
  2: SUNNYSIDE.land.volcanoLevel2,
  3: SUNNYSIDE.land.volcanoLevel3,
  4: SUNNYSIDE.land.volcanoLevel4,
  5: SUNNYSIDE.land.volcanoLevel5,
  6: SUNNYSIDE.land.volcanoLevel6,
  7: SUNNYSIDE.land.volcanoLevel7,
  8: SUNNYSIDE.land.volcanoLevel8,
  9: SUNNYSIDE.land.volcanoLevel9,
  10: SUNNYSIDE.land.volcanoLevel10,
  11: SUNNYSIDE.land.volcanoLevel11,
  12: SUNNYSIDE.land.volcanoLevel12,
  13: SUNNYSIDE.land.volcanoLevel13,
  14: SUNNYSIDE.land.volcanoLevel14,
  15: SUNNYSIDE.land.volcanoLevel15,
  16: SUNNYSIDE.land.volcanoLevel16,
  17: SUNNYSIDE.land.volcanoLevel17,
  18: SUNNYSIDE.land.volcanoLevel18,
  19: SUNNYSIDE.land.volcanoLevel19,
  20: SUNNYSIDE.land.volcanoLevel20,
  21: SUNNYSIDE.land.volcanoLevel21,
  22: SUNNYSIDE.land.volcanoLevel22,
  23: SUNNYSIDE.land.volcanoLevel23,
  24: SUNNYSIDE.land.volcanoLevel24,
  25: SUNNYSIDE.land.volcanoLevel25,
  26: SUNNYSIDE.land.volcanoLevel26,
  27: SUNNYSIDE.land.volcanoLevel27,
  28: SUNNYSIDE.land.volcanoLevel28,
  29: SUNNYSIDE.land.volcanoLevel29,
  30: SUNNYSIDE.land.volcanoLevel30,
  31: SUNNYSIDE.land.volcanoLevel31,
  32: SUNNYSIDE.land.volcanoLevel32,
  33: SUNNYSIDE.land.volcanoLevel33,
  34: SUNNYSIDE.land.volcanoLevel34,
  35: SUNNYSIDE.land.volcanoLevel35,
  36: SUNNYSIDE.land.volcanoLevel36,
  37: SUNNYSIDE.land.volcanoLevel37,
  38: SUNNYSIDE.land.volcanoLevel38,
  39: SUNNYSIDE.land.volcanoLevel39,
  40: SUNNYSIDE.land.volcanoLevel40,
  41: SUNNYSIDE.land.volcanoLevel41,
  42: SUNNYSIDE.land.volcanoLevel42,
};

const AUTUMN_VOLCANO_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.volcanoLevel1,
  2: SUNNYSIDE.seasons.autumn.volcanoLevel2,
  3: SUNNYSIDE.seasons.autumn.volcanoLevel3,
  4: SUNNYSIDE.seasons.autumn.volcanoLevel4,
  5: SUNNYSIDE.seasons.autumn.volcanoLevel5,
  6: SUNNYSIDE.seasons.autumn.volcanoLevel6,
  7: SUNNYSIDE.seasons.autumn.volcanoLevel7,
  8: SUNNYSIDE.seasons.autumn.volcanoLevel8,
  9: SUNNYSIDE.seasons.autumn.volcanoLevel9,
  10: SUNNYSIDE.seasons.autumn.volcanoLevel10,
  11: SUNNYSIDE.seasons.autumn.volcanoLevel11,
  12: SUNNYSIDE.seasons.autumn.volcanoLevel12,
  13: SUNNYSIDE.seasons.autumn.volcanoLevel13,
  14: SUNNYSIDE.seasons.autumn.volcanoLevel14,
  15: SUNNYSIDE.seasons.autumn.volcanoLevel15,
  16: SUNNYSIDE.seasons.autumn.volcanoLevel16,
  17: SUNNYSIDE.seasons.autumn.volcanoLevel17,
  18: SUNNYSIDE.seasons.autumn.volcanoLevel18,
  19: SUNNYSIDE.seasons.autumn.volcanoLevel19,
  20: SUNNYSIDE.seasons.autumn.volcanoLevel20,
  21: SUNNYSIDE.seasons.autumn.volcanoLevel21,
  22: SUNNYSIDE.seasons.autumn.volcanoLevel22,
  23: SUNNYSIDE.seasons.autumn.volcanoLevel23,
  24: SUNNYSIDE.seasons.autumn.volcanoLevel24,
  25: SUNNYSIDE.seasons.autumn.volcanoLevel25,
  26: SUNNYSIDE.seasons.autumn.volcanoLevel26,
  27: SUNNYSIDE.seasons.autumn.volcanoLevel27,
  28: SUNNYSIDE.seasons.autumn.volcanoLevel28,
  29: SUNNYSIDE.seasons.autumn.volcanoLevel29,
  30: SUNNYSIDE.seasons.autumn.volcanoLevel30,
  31: SUNNYSIDE.seasons.autumn.volcanoLevel31,
  32: SUNNYSIDE.seasons.autumn.volcanoLevel32,
  33: SUNNYSIDE.seasons.autumn.volcanoLevel33,
  34: SUNNYSIDE.seasons.autumn.volcanoLevel34,
  35: SUNNYSIDE.seasons.autumn.volcanoLevel35,
  36: SUNNYSIDE.seasons.autumn.volcanoLevel36,
  37: SUNNYSIDE.seasons.autumn.volcanoLevel37,
  38: SUNNYSIDE.seasons.autumn.volcanoLevel38,
  39: SUNNYSIDE.seasons.autumn.volcanoLevel39,
  40: SUNNYSIDE.seasons.autumn.volcanoLevel40,
  41: SUNNYSIDE.seasons.autumn.volcanoLevel41,
  42: SUNNYSIDE.seasons.autumn.volcanoLevel42,
};

const WINTER_VOLCANO_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.volcanoLevel1,
  2: SUNNYSIDE.seasons.winter.volcanoLevel2,
  3: SUNNYSIDE.seasons.winter.volcanoLevel3,
  4: SUNNYSIDE.seasons.winter.volcanoLevel4,
  5: SUNNYSIDE.seasons.winter.volcanoLevel5,
  6: SUNNYSIDE.seasons.winter.volcanoLevel6,
  7: SUNNYSIDE.seasons.winter.volcanoLevel7,
  8: SUNNYSIDE.seasons.winter.volcanoLevel8,
  9: SUNNYSIDE.seasons.winter.volcanoLevel9,
  10: SUNNYSIDE.seasons.winter.volcanoLevel10,
  11: SUNNYSIDE.seasons.winter.volcanoLevel11,
  12: SUNNYSIDE.seasons.winter.volcanoLevel12,
  13: SUNNYSIDE.seasons.winter.volcanoLevel13,
  14: SUNNYSIDE.seasons.winter.volcanoLevel14,
  15: SUNNYSIDE.seasons.winter.volcanoLevel15,
  16: SUNNYSIDE.seasons.winter.volcanoLevel16,
  17: SUNNYSIDE.seasons.winter.volcanoLevel17,
  18: SUNNYSIDE.seasons.winter.volcanoLevel18,
  19: SUNNYSIDE.seasons.winter.volcanoLevel19,
  20: SUNNYSIDE.seasons.winter.volcanoLevel20,
  21: SUNNYSIDE.seasons.winter.volcanoLevel21,
  22: SUNNYSIDE.seasons.winter.volcanoLevel22,
  23: SUNNYSIDE.seasons.winter.volcanoLevel23,
  24: SUNNYSIDE.seasons.winter.volcanoLevel24,
  25: SUNNYSIDE.seasons.winter.volcanoLevel25,
  26: SUNNYSIDE.seasons.winter.volcanoLevel26,
  27: SUNNYSIDE.seasons.winter.volcanoLevel27,
  28: SUNNYSIDE.seasons.winter.volcanoLevel28,
  29: SUNNYSIDE.seasons.winter.volcanoLevel29,
  30: SUNNYSIDE.seasons.winter.volcanoLevel30,
  31: SUNNYSIDE.seasons.winter.volcanoLevel31,
  32: SUNNYSIDE.seasons.winter.volcanoLevel32,
  33: SUNNYSIDE.seasons.winter.volcanoLevel33,
  34: SUNNYSIDE.seasons.winter.volcanoLevel34,
  35: SUNNYSIDE.seasons.winter.volcanoLevel35,
  36: SUNNYSIDE.seasons.winter.volcanoLevel36,
  37: SUNNYSIDE.seasons.winter.volcanoLevel37,
  38: SUNNYSIDE.seasons.winter.volcanoLevel38,
  39: SUNNYSIDE.seasons.winter.volcanoLevel39,
  40: SUNNYSIDE.seasons.winter.volcanoLevel40,
  41: SUNNYSIDE.seasons.winter.volcanoLevel41,
  42: SUNNYSIDE.seasons.winter.volcanoLevel42,
};

const LEVEL_IMAGES: Record<
  LandBiomeName,
  Record<TemperateSeasonName, Record<number, string>>
> = {
  "Basic Biome": {
    spring: SPRING_BASIC_LEVEL_IMAGES,
    summer: SUMMER_BASIC_LEVEL_IMAGES,
    autumn: AUTUMN_BASIC_LEVEL_IMAGES,
    winter: WINTER_BASIC_LEVEL_IMAGES,
  },
  "Spring Biome": {
    spring: SPRING_BASIC_LEVEL_IMAGES,
    summer: SUMMER_BASIC_LEVEL_IMAGES,
    autumn: AUTUMN_BASIC_LEVEL_IMAGES,
    winter: WINTER_BASIC_LEVEL_IMAGES,
  },
  "Desert Biome": {
    spring: SPRING_DESERT_LEVEL_IMAGES,
    summer: SUMMER_DESERT_LEVEL_IMAGES,
    autumn: AUTUMN_DESERT_LEVEL_IMAGES,
    winter: WINTER_DESERT_LEVEL_IMAGES,
  },
  "Volcano Biome": {
    spring: SPRING_VOLCANO_LEVEL_IMAGES,
    summer: SUMMER_VOLCANO_LEVEL_IMAGES,
    autumn: AUTUMN_VOLCANO_LEVEL_IMAGES,
    winter: WINTER_VOLCANO_LEVEL_IMAGES,
  },
  "Swamp Biome": {
    spring: SPRING_VOLCANO_LEVEL_IMAGES,
    summer: SUMMER_VOLCANO_LEVEL_IMAGES,
    autumn: AUTUMN_VOLCANO_LEVEL_IMAGES,
    winter: WINTER_VOLCANO_LEVEL_IMAGES,
  },
  // Ascension biomes (spooky onward) reuse the swamp art for now.
  "Spooky Biome": {
    spring: SPRING_VOLCANO_LEVEL_IMAGES,
    summer: SUMMER_VOLCANO_LEVEL_IMAGES,
    autumn: AUTUMN_VOLCANO_LEVEL_IMAGES,
    winter: WINTER_VOLCANO_LEVEL_IMAGES,
  },
  "Crystal Biome": {
    spring: SPRING_VOLCANO_LEVEL_IMAGES,
    summer: SUMMER_VOLCANO_LEVEL_IMAGES,
    autumn: AUTUMN_VOLCANO_LEVEL_IMAGES,
    winter: WINTER_VOLCANO_LEVEL_IMAGES,
  },
  "Moon Biome": {
    spring: SPRING_VOLCANO_LEVEL_IMAGES,
    summer: SUMMER_VOLCANO_LEVEL_IMAGES,
    autumn: AUTUMN_VOLCANO_LEVEL_IMAGES,
    winter: WINTER_VOLCANO_LEVEL_IMAGES,
  },
  "Marble Age Biome": {
    spring: SPRING_VOLCANO_LEVEL_IMAGES,
    summer: SUMMER_VOLCANO_LEVEL_IMAGES,
    autumn: AUTUMN_VOLCANO_LEVEL_IMAGES,
    winter: WINTER_VOLCANO_LEVEL_IMAGES,
  },
};

interface Props {
  island: GameState["island"];
  expandedCount: number;
  season: TemperateSeasonName;
}

export const LandBase: React.FC<Props> = ({
  island,
  expandedCount,
  season,
}) => {
  const biome = getCurrentBiome(island);
  // Each land image is generated at 16px/tile with the world origin (coordinate 0,0) at its exact
  // centre, so it just needs to render at the game's natural scale (PIXEL_SCALE, via NaturalImage)
  // and be centred by the wrapper in Land.tsx — no per-biome width, "extended" or translateX.

  const MAX_LAND_IMAGE_LEVEL = 42;

  const imageLevel = Math.min(expandedCount, MAX_LAND_IMAGE_LEVEL);
  const src = LEVEL_IMAGES[biome][season][imageLevel];

  return (
    <NaturalImage
      id={Section.GenesisBlock}
      src={src}
      alt="land"
      className="-z-10"
    />
  );
};
