import React from "react";

import { SUNNYSIDE } from "assets/sunnyside";

import { NaturalImage } from "components/ui/NaturalImage";
import { Section } from "lib/utils/hooks/useScrollIntoView";
import type { GameState, TemperateSeasonName } from "features/game/types/game";
import { getCurrentBiome } from "features/island/biomes/biomes";
import type { LandBiomeName } from "features/island/biomes/biomes";

const SPRING_BASIC_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.basicLevel1,
  2: SUNNYSIDE.seasons.spring.basicLevel2,
  3: SUNNYSIDE.seasons.spring.basicLevel3,
  4: SUNNYSIDE.seasons.spring.basicLevel4,
  5: SUNNYSIDE.seasons.spring.basicLevel5,
  6: SUNNYSIDE.seasons.spring.basicLevel6,
  7: SUNNYSIDE.seasons.spring.basicLevel7,
  8: SUNNYSIDE.seasons.spring.basicLevel8,
  9: SUNNYSIDE.seasons.spring.basicLevel9,
  10: SUNNYSIDE.seasons.spring.basicLevel10,
  11: SUNNYSIDE.seasons.spring.basicLevel11,
  12: SUNNYSIDE.seasons.spring.basicLevel12,
  13: SUNNYSIDE.seasons.spring.basicLevel13,
  14: SUNNYSIDE.seasons.spring.basicLevel14,
  15: SUNNYSIDE.seasons.spring.basicLevel15,
  16: SUNNYSIDE.seasons.spring.basicLevel16,
  17: SUNNYSIDE.seasons.spring.basicLevel17,
  18: SUNNYSIDE.seasons.spring.basicLevel18,
  19: SUNNYSIDE.seasons.spring.basicLevel19,
  20: SUNNYSIDE.seasons.spring.basicLevel20,
  21: SUNNYSIDE.seasons.spring.basicLevel21,
  22: SUNNYSIDE.seasons.spring.basicLevel22,
  23: SUNNYSIDE.seasons.spring.basicLevel23,
  24: SUNNYSIDE.seasons.spring.basicLevel24,
  25: SUNNYSIDE.seasons.spring.basicLevel25,
  26: SUNNYSIDE.seasons.spring.basicLevel26,
  27: SUNNYSIDE.seasons.spring.basicLevel27,
  28: SUNNYSIDE.seasons.spring.basicLevel28,
  29: SUNNYSIDE.seasons.spring.basicLevel29,
  30: SUNNYSIDE.seasons.spring.basicLevel30,
  31: SUNNYSIDE.seasons.spring.basicLevel31,
  32: SUNNYSIDE.seasons.spring.basicLevel32,
  33: SUNNYSIDE.seasons.spring.basicLevel33,
  34: SUNNYSIDE.seasons.spring.basicLevel34,
  35: SUNNYSIDE.seasons.spring.basicLevel35,
  36: SUNNYSIDE.seasons.spring.basicLevel36,
  37: SUNNYSIDE.seasons.spring.basicLevel37,
  38: SUNNYSIDE.seasons.spring.basicLevel38,
  39: SUNNYSIDE.seasons.spring.basicLevel39,
  40: SUNNYSIDE.seasons.spring.basicLevel40,
  41: SUNNYSIDE.seasons.spring.basicLevel41,
  42: SUNNYSIDE.seasons.spring.basicLevel42,
};

const SUMMER_BASIC_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.basicLevel1,
  2: SUNNYSIDE.land.basicLevel2,
  3: SUNNYSIDE.land.basicLevel3,
  4: SUNNYSIDE.land.basicLevel4,
  5: SUNNYSIDE.land.basicLevel5,
  6: SUNNYSIDE.land.basicLevel6,
  7: SUNNYSIDE.land.basicLevel7,
  8: SUNNYSIDE.land.basicLevel8,
  9: SUNNYSIDE.land.basicLevel9,
  10: SUNNYSIDE.land.basicLevel10,
  11: SUNNYSIDE.land.basicLevel11,
  12: SUNNYSIDE.land.basicLevel12,
  13: SUNNYSIDE.land.basicLevel13,
  14: SUNNYSIDE.land.basicLevel14,
  15: SUNNYSIDE.land.basicLevel15,
  16: SUNNYSIDE.land.basicLevel16,
  17: SUNNYSIDE.land.basicLevel17,
  18: SUNNYSIDE.land.basicLevel18,
  19: SUNNYSIDE.land.basicLevel19,
  20: SUNNYSIDE.land.basicLevel20,
  21: SUNNYSIDE.land.basicLevel21,
  22: SUNNYSIDE.land.basicLevel22,
  23: SUNNYSIDE.land.basicLevel23,
  24: SUNNYSIDE.land.basicLevel24,
  25: SUNNYSIDE.land.basicLevel25,
  26: SUNNYSIDE.land.basicLevel26,
  27: SUNNYSIDE.land.basicLevel27,
  28: SUNNYSIDE.land.basicLevel28,
  29: SUNNYSIDE.land.basicLevel29,
  30: SUNNYSIDE.land.basicLevel30,
  31: SUNNYSIDE.land.basicLevel31,
  32: SUNNYSIDE.land.basicLevel32,
  33: SUNNYSIDE.land.basicLevel33,
  34: SUNNYSIDE.land.basicLevel34,
  35: SUNNYSIDE.land.basicLevel35,
  36: SUNNYSIDE.land.basicLevel36,
  37: SUNNYSIDE.land.basicLevel37,
  38: SUNNYSIDE.land.basicLevel38,
  39: SUNNYSIDE.land.basicLevel39,
  40: SUNNYSIDE.land.basicLevel40,
  41: SUNNYSIDE.land.basicLevel41,
  42: SUNNYSIDE.land.basicLevel42,
};
const AUTUMN_BASIC_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.basicLevel1,
  2: SUNNYSIDE.seasons.autumn.basicLevel2,
  3: SUNNYSIDE.seasons.autumn.basicLevel3,
  4: SUNNYSIDE.seasons.autumn.basicLevel4,
  5: SUNNYSIDE.seasons.autumn.basicLevel5,
  6: SUNNYSIDE.seasons.autumn.basicLevel6,
  7: SUNNYSIDE.seasons.autumn.basicLevel7,
  8: SUNNYSIDE.seasons.autumn.basicLevel8,
  9: SUNNYSIDE.seasons.autumn.basicLevel9,
  10: SUNNYSIDE.seasons.autumn.basicLevel10,
  11: SUNNYSIDE.seasons.autumn.basicLevel11,
  12: SUNNYSIDE.seasons.autumn.basicLevel12,
  13: SUNNYSIDE.seasons.autumn.basicLevel13,
  14: SUNNYSIDE.seasons.autumn.basicLevel14,
  15: SUNNYSIDE.seasons.autumn.basicLevel15,
  16: SUNNYSIDE.seasons.autumn.basicLevel16,
  17: SUNNYSIDE.seasons.autumn.basicLevel17,
  18: SUNNYSIDE.seasons.autumn.basicLevel18,
  19: SUNNYSIDE.seasons.autumn.basicLevel19,
  20: SUNNYSIDE.seasons.autumn.basicLevel20,
  21: SUNNYSIDE.seasons.autumn.basicLevel21,
  22: SUNNYSIDE.seasons.autumn.basicLevel22,
  23: SUNNYSIDE.seasons.autumn.basicLevel23,
  24: SUNNYSIDE.seasons.autumn.basicLevel24,
  25: SUNNYSIDE.seasons.autumn.basicLevel25,
  26: SUNNYSIDE.seasons.autumn.basicLevel26,
  27: SUNNYSIDE.seasons.autumn.basicLevel27,
  28: SUNNYSIDE.seasons.autumn.basicLevel28,
  29: SUNNYSIDE.seasons.autumn.basicLevel29,
  30: SUNNYSIDE.seasons.autumn.basicLevel30,
  31: SUNNYSIDE.seasons.autumn.basicLevel31,
  32: SUNNYSIDE.seasons.autumn.basicLevel32,
  33: SUNNYSIDE.seasons.autumn.basicLevel33,
  34: SUNNYSIDE.seasons.autumn.basicLevel34,
  35: SUNNYSIDE.seasons.autumn.basicLevel35,
  36: SUNNYSIDE.seasons.autumn.basicLevel36,
  37: SUNNYSIDE.seasons.autumn.basicLevel37,
  38: SUNNYSIDE.seasons.autumn.basicLevel38,
  39: SUNNYSIDE.seasons.autumn.basicLevel39,
  40: SUNNYSIDE.seasons.autumn.basicLevel40,
  41: SUNNYSIDE.seasons.autumn.basicLevel41,
  42: SUNNYSIDE.seasons.autumn.basicLevel42,
};
const WINTER_BASIC_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.basicLevel1,
  2: SUNNYSIDE.seasons.winter.basicLevel2,
  3: SUNNYSIDE.seasons.winter.basicLevel3,
  4: SUNNYSIDE.seasons.winter.basicLevel4,
  5: SUNNYSIDE.seasons.winter.basicLevel5,
  6: SUNNYSIDE.seasons.winter.basicLevel6,
  7: SUNNYSIDE.seasons.winter.basicLevel7,
  8: SUNNYSIDE.seasons.winter.basicLevel8,
  9: SUNNYSIDE.seasons.winter.basicLevel9,
  10: SUNNYSIDE.seasons.winter.basicLevel10,
  11: SUNNYSIDE.seasons.winter.basicLevel11,
  12: SUNNYSIDE.seasons.winter.basicLevel12,
  13: SUNNYSIDE.seasons.winter.basicLevel13,
  14: SUNNYSIDE.seasons.winter.basicLevel14,
  15: SUNNYSIDE.seasons.winter.basicLevel15,
  16: SUNNYSIDE.seasons.winter.basicLevel16,
  17: SUNNYSIDE.seasons.winter.basicLevel17,
  18: SUNNYSIDE.seasons.winter.basicLevel18,
  19: SUNNYSIDE.seasons.winter.basicLevel19,
  20: SUNNYSIDE.seasons.winter.basicLevel20,
  21: SUNNYSIDE.seasons.winter.basicLevel21,
  22: SUNNYSIDE.seasons.winter.basicLevel22,
  23: SUNNYSIDE.seasons.winter.basicLevel23,
  24: SUNNYSIDE.seasons.winter.basicLevel24,
  25: SUNNYSIDE.seasons.winter.basicLevel25,
  26: SUNNYSIDE.seasons.winter.basicLevel26,
  27: SUNNYSIDE.seasons.winter.basicLevel27,
  28: SUNNYSIDE.seasons.winter.basicLevel28,
  29: SUNNYSIDE.seasons.winter.basicLevel29,
  30: SUNNYSIDE.seasons.winter.basicLevel30,
  31: SUNNYSIDE.seasons.winter.basicLevel31,
  32: SUNNYSIDE.seasons.winter.basicLevel32,
  33: SUNNYSIDE.seasons.winter.basicLevel33,
  34: SUNNYSIDE.seasons.winter.basicLevel34,
  35: SUNNYSIDE.seasons.winter.basicLevel35,
  36: SUNNYSIDE.seasons.winter.basicLevel36,
  37: SUNNYSIDE.seasons.winter.basicLevel37,
  38: SUNNYSIDE.seasons.winter.basicLevel38,
  39: SUNNYSIDE.seasons.winter.basicLevel39,
  40: SUNNYSIDE.seasons.winter.basicLevel40,
  41: SUNNYSIDE.seasons.winter.basicLevel41,
  42: SUNNYSIDE.seasons.winter.basicLevel42,
};

const SPRING_DESERT_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.desertLevel1,
  2: SUNNYSIDE.seasons.spring.desertLevel2,
  3: SUNNYSIDE.seasons.spring.desertLevel3,
  4: SUNNYSIDE.seasons.spring.desertLevel4,
  5: SUNNYSIDE.seasons.spring.desertLevel5,
  6: SUNNYSIDE.seasons.spring.desertLevel6,
  7: SUNNYSIDE.seasons.spring.desertLevel7,
  8: SUNNYSIDE.seasons.spring.desertLevel8,
  9: SUNNYSIDE.seasons.spring.desertLevel9,
  10: SUNNYSIDE.seasons.spring.desertLevel10,
  11: SUNNYSIDE.seasons.spring.desertLevel11,
  12: SUNNYSIDE.seasons.spring.desertLevel12,
  13: SUNNYSIDE.seasons.spring.desertLevel13,
  14: SUNNYSIDE.seasons.spring.desertLevel14,
  15: SUNNYSIDE.seasons.spring.desertLevel15,
  16: SUNNYSIDE.seasons.spring.desertLevel16,
  17: SUNNYSIDE.seasons.spring.desertLevel17,
  18: SUNNYSIDE.seasons.spring.desertLevel18,
  19: SUNNYSIDE.seasons.spring.desertLevel19,
  20: SUNNYSIDE.seasons.spring.desertLevel20,
  21: SUNNYSIDE.seasons.spring.desertLevel21,
  22: SUNNYSIDE.seasons.spring.desertLevel22,
  23: SUNNYSIDE.seasons.spring.desertLevel23,
  24: SUNNYSIDE.seasons.spring.desertLevel24,
  25: SUNNYSIDE.seasons.spring.desertLevel25,
  26: SUNNYSIDE.seasons.spring.desertLevel26,
  27: SUNNYSIDE.seasons.spring.desertLevel27,
  28: SUNNYSIDE.seasons.spring.desertLevel28,
  29: SUNNYSIDE.seasons.spring.desertLevel29,
  30: SUNNYSIDE.seasons.spring.desertLevel30,
  31: SUNNYSIDE.seasons.spring.desertLevel31,
  32: SUNNYSIDE.seasons.spring.desertLevel32,
  33: SUNNYSIDE.seasons.spring.desertLevel33,
  34: SUNNYSIDE.seasons.spring.desertLevel34,
  35: SUNNYSIDE.seasons.spring.desertLevel35,
  36: SUNNYSIDE.seasons.spring.desertLevel36,
  37: SUNNYSIDE.seasons.spring.desertLevel37,
  38: SUNNYSIDE.seasons.spring.desertLevel38,
  39: SUNNYSIDE.seasons.spring.desertLevel39,
  40: SUNNYSIDE.seasons.spring.desertLevel40,
  41: SUNNYSIDE.seasons.spring.desertLevel41,
  42: SUNNYSIDE.seasons.spring.desertLevel42,
};

const SUMMER_DESERT_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.desertLevel1,
  2: SUNNYSIDE.land.desertLevel2,
  3: SUNNYSIDE.land.desertLevel3,
  4: SUNNYSIDE.land.desertLevel4,
  5: SUNNYSIDE.land.desertLevel5,
  6: SUNNYSIDE.land.desertLevel6,
  7: SUNNYSIDE.land.desertLevel7,
  8: SUNNYSIDE.land.desertLevel8,
  9: SUNNYSIDE.land.desertLevel9,
  10: SUNNYSIDE.land.desertLevel10,
  11: SUNNYSIDE.land.desertLevel11,
  12: SUNNYSIDE.land.desertLevel12,
  13: SUNNYSIDE.land.desertLevel13,
  14: SUNNYSIDE.land.desertLevel14,
  15: SUNNYSIDE.land.desertLevel15,
  16: SUNNYSIDE.land.desertLevel16,
  17: SUNNYSIDE.land.desertLevel17,
  18: SUNNYSIDE.land.desertLevel18,
  19: SUNNYSIDE.land.desertLevel19,
  20: SUNNYSIDE.land.desertLevel20,
  21: SUNNYSIDE.land.desertLevel21,
  22: SUNNYSIDE.land.desertLevel22,
  23: SUNNYSIDE.land.desertLevel23,
  24: SUNNYSIDE.land.desertLevel24,
  25: SUNNYSIDE.land.desertLevel25,
  26: SUNNYSIDE.land.desertLevel26,
  27: SUNNYSIDE.land.desertLevel27,
  28: SUNNYSIDE.land.desertLevel28,
  29: SUNNYSIDE.land.desertLevel29,
  30: SUNNYSIDE.land.desertLevel30,
  31: SUNNYSIDE.land.desertLevel31,
  32: SUNNYSIDE.land.desertLevel32,
  33: SUNNYSIDE.land.desertLevel33,
  34: SUNNYSIDE.land.desertLevel34,
  35: SUNNYSIDE.land.desertLevel35,
  36: SUNNYSIDE.land.desertLevel36,
  37: SUNNYSIDE.land.desertLevel37,
  38: SUNNYSIDE.land.desertLevel38,
  39: SUNNYSIDE.land.desertLevel39,
  40: SUNNYSIDE.land.desertLevel40,
  41: SUNNYSIDE.land.desertLevel41,
  42: SUNNYSIDE.land.desertLevel42,
};

const AUTUMN_DESERT_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.desertLevel1,
  2: SUNNYSIDE.seasons.autumn.desertLevel2,
  3: SUNNYSIDE.seasons.autumn.desertLevel3,
  4: SUNNYSIDE.seasons.autumn.desertLevel4,
  5: SUNNYSIDE.seasons.autumn.desertLevel5,
  6: SUNNYSIDE.seasons.autumn.desertLevel6,
  7: SUNNYSIDE.seasons.autumn.desertLevel7,
  8: SUNNYSIDE.seasons.autumn.desertLevel8,
  9: SUNNYSIDE.seasons.autumn.desertLevel9,
  10: SUNNYSIDE.seasons.autumn.desertLevel10,
  11: SUNNYSIDE.seasons.autumn.desertLevel11,
  12: SUNNYSIDE.seasons.autumn.desertLevel12,
  13: SUNNYSIDE.seasons.autumn.desertLevel13,
  14: SUNNYSIDE.seasons.autumn.desertLevel14,
  15: SUNNYSIDE.seasons.autumn.desertLevel15,
  16: SUNNYSIDE.seasons.autumn.desertLevel16,
  17: SUNNYSIDE.seasons.autumn.desertLevel17,
  18: SUNNYSIDE.seasons.autumn.desertLevel18,
  19: SUNNYSIDE.seasons.autumn.desertLevel19,
  20: SUNNYSIDE.seasons.autumn.desertLevel20,
  21: SUNNYSIDE.seasons.autumn.desertLevel21,
  22: SUNNYSIDE.seasons.autumn.desertLevel22,
  23: SUNNYSIDE.seasons.autumn.desertLevel23,
  24: SUNNYSIDE.seasons.autumn.desertLevel24,
  25: SUNNYSIDE.seasons.autumn.desertLevel25,
  26: SUNNYSIDE.seasons.autumn.desertLevel26,
  27: SUNNYSIDE.seasons.autumn.desertLevel27,
  28: SUNNYSIDE.seasons.autumn.desertLevel28,
  29: SUNNYSIDE.seasons.autumn.desertLevel29,
  30: SUNNYSIDE.seasons.autumn.desertLevel30,
  31: SUNNYSIDE.seasons.autumn.desertLevel31,
  32: SUNNYSIDE.seasons.autumn.desertLevel32,
  33: SUNNYSIDE.seasons.autumn.desertLevel33,
  34: SUNNYSIDE.seasons.autumn.desertLevel34,
  35: SUNNYSIDE.seasons.autumn.desertLevel35,
  36: SUNNYSIDE.seasons.autumn.desertLevel36,
  37: SUNNYSIDE.seasons.autumn.desertLevel37,
  38: SUNNYSIDE.seasons.autumn.desertLevel38,
  39: SUNNYSIDE.seasons.autumn.desertLevel39,
  40: SUNNYSIDE.seasons.autumn.desertLevel40,
  41: SUNNYSIDE.seasons.autumn.desertLevel41,
  42: SUNNYSIDE.seasons.autumn.desertLevel42,
};

const WINTER_DESERT_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.desertLevel1,
  2: SUNNYSIDE.seasons.winter.desertLevel2,
  3: SUNNYSIDE.seasons.winter.desertLevel3,
  4: SUNNYSIDE.seasons.winter.desertLevel4,
  5: SUNNYSIDE.seasons.winter.desertLevel5,
  6: SUNNYSIDE.seasons.winter.desertLevel6,
  7: SUNNYSIDE.seasons.winter.desertLevel7,
  8: SUNNYSIDE.seasons.winter.desertLevel8,
  9: SUNNYSIDE.seasons.winter.desertLevel9,
  10: SUNNYSIDE.seasons.winter.desertLevel10,
  11: SUNNYSIDE.seasons.winter.desertLevel11,
  12: SUNNYSIDE.seasons.winter.desertLevel12,
  13: SUNNYSIDE.seasons.winter.desertLevel13,
  14: SUNNYSIDE.seasons.winter.desertLevel14,
  15: SUNNYSIDE.seasons.winter.desertLevel15,
  16: SUNNYSIDE.seasons.winter.desertLevel16,
  17: SUNNYSIDE.seasons.winter.desertLevel17,
  18: SUNNYSIDE.seasons.winter.desertLevel18,
  19: SUNNYSIDE.seasons.winter.desertLevel19,
  20: SUNNYSIDE.seasons.winter.desertLevel20,
  21: SUNNYSIDE.seasons.winter.desertLevel21,
  22: SUNNYSIDE.seasons.winter.desertLevel22,
  23: SUNNYSIDE.seasons.winter.desertLevel23,
  24: SUNNYSIDE.seasons.winter.desertLevel24,
  25: SUNNYSIDE.seasons.winter.desertLevel25,
  26: SUNNYSIDE.seasons.winter.desertLevel26,
  27: SUNNYSIDE.seasons.winter.desertLevel27,
  28: SUNNYSIDE.seasons.winter.desertLevel28,
  29: SUNNYSIDE.seasons.winter.desertLevel29,
  30: SUNNYSIDE.seasons.winter.desertLevel30,
  31: SUNNYSIDE.seasons.winter.desertLevel31,
  32: SUNNYSIDE.seasons.winter.desertLevel32,
  33: SUNNYSIDE.seasons.winter.desertLevel33,
  34: SUNNYSIDE.seasons.winter.desertLevel34,
  35: SUNNYSIDE.seasons.winter.desertLevel35,
  36: SUNNYSIDE.seasons.winter.desertLevel36,
  37: SUNNYSIDE.seasons.winter.desertLevel37,
  38: SUNNYSIDE.seasons.winter.desertLevel38,
  39: SUNNYSIDE.seasons.winter.desertLevel39,
  40: SUNNYSIDE.seasons.winter.desertLevel40,
  41: SUNNYSIDE.seasons.winter.desertLevel41,
  42: SUNNYSIDE.seasons.winter.desertLevel42,
};

const SPRING_VOLCANO_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.volcanoLevel1,
  2: SUNNYSIDE.seasons.spring.volcanoLevel2,
  3: SUNNYSIDE.seasons.spring.volcanoLevel3,
  4: SUNNYSIDE.seasons.spring.volcanoLevel4,
  5: SUNNYSIDE.seasons.spring.volcanoLevel5,
  6: SUNNYSIDE.seasons.spring.volcanoLevel6,
  7: SUNNYSIDE.seasons.spring.volcanoLevel7,
  8: SUNNYSIDE.seasons.spring.volcanoLevel8,
  9: SUNNYSIDE.seasons.spring.volcanoLevel9,
  10: SUNNYSIDE.seasons.spring.volcanoLevel10,
  11: SUNNYSIDE.seasons.spring.volcanoLevel11,
  12: SUNNYSIDE.seasons.spring.volcanoLevel12,
  13: SUNNYSIDE.seasons.spring.volcanoLevel13,
  14: SUNNYSIDE.seasons.spring.volcanoLevel14,
  15: SUNNYSIDE.seasons.spring.volcanoLevel15,
  16: SUNNYSIDE.seasons.spring.volcanoLevel16,
  17: SUNNYSIDE.seasons.spring.volcanoLevel17,
  18: SUNNYSIDE.seasons.spring.volcanoLevel18,
  19: SUNNYSIDE.seasons.spring.volcanoLevel19,
  20: SUNNYSIDE.seasons.spring.volcanoLevel20,
  21: SUNNYSIDE.seasons.spring.volcanoLevel21,
  22: SUNNYSIDE.seasons.spring.volcanoLevel22,
  23: SUNNYSIDE.seasons.spring.volcanoLevel23,
  24: SUNNYSIDE.seasons.spring.volcanoLevel24,
  25: SUNNYSIDE.seasons.spring.volcanoLevel25,
  26: SUNNYSIDE.seasons.spring.volcanoLevel26,
  27: SUNNYSIDE.seasons.spring.volcanoLevel27,
  28: SUNNYSIDE.seasons.spring.volcanoLevel28,
  29: SUNNYSIDE.seasons.spring.volcanoLevel29,
  30: SUNNYSIDE.seasons.spring.volcanoLevel30,
  31: SUNNYSIDE.seasons.spring.volcanoLevel31,
  32: SUNNYSIDE.seasons.spring.volcanoLevel32,
  33: SUNNYSIDE.seasons.spring.volcanoLevel33,
  34: SUNNYSIDE.seasons.spring.volcanoLevel34,
  35: SUNNYSIDE.seasons.spring.volcanoLevel35,
  36: SUNNYSIDE.seasons.spring.volcanoLevel36,
  37: SUNNYSIDE.seasons.spring.volcanoLevel37,
  38: SUNNYSIDE.seasons.spring.volcanoLevel38,
  39: SUNNYSIDE.seasons.spring.volcanoLevel39,
  40: SUNNYSIDE.seasons.spring.volcanoLevel40,
  41: SUNNYSIDE.seasons.spring.volcanoLevel41,
  42: SUNNYSIDE.seasons.spring.volcanoLevel42,
};

const SUMMER_VOLCANO_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.volcanoLevel1,
  2: SUNNYSIDE.land.volcanoLevel2,
  3: SUNNYSIDE.land.volcanoLevel3,
  4: SUNNYSIDE.land.volcanoLevel4,
  5: SUNNYSIDE.land.volcanoLevel5,
  6: SUNNYSIDE.land.volcanoLevel6,
  7: SUNNYSIDE.land.volcanoLevel7,
  8: SUNNYSIDE.land.volcanoLevel8,
  9: SUNNYSIDE.land.volcanoLevel9,
  10: SUNNYSIDE.land.volcanoLevel10,
  11: SUNNYSIDE.land.volcanoLevel11,
  12: SUNNYSIDE.land.volcanoLevel12,
  13: SUNNYSIDE.land.volcanoLevel13,
  14: SUNNYSIDE.land.volcanoLevel14,
  15: SUNNYSIDE.land.volcanoLevel15,
  16: SUNNYSIDE.land.volcanoLevel16,
  17: SUNNYSIDE.land.volcanoLevel17,
  18: SUNNYSIDE.land.volcanoLevel18,
  19: SUNNYSIDE.land.volcanoLevel19,
  20: SUNNYSIDE.land.volcanoLevel20,
  21: SUNNYSIDE.land.volcanoLevel21,
  22: SUNNYSIDE.land.volcanoLevel22,
  23: SUNNYSIDE.land.volcanoLevel23,
  24: SUNNYSIDE.land.volcanoLevel24,
  25: SUNNYSIDE.land.volcanoLevel25,
  26: SUNNYSIDE.land.volcanoLevel26,
  27: SUNNYSIDE.land.volcanoLevel27,
  28: SUNNYSIDE.land.volcanoLevel28,
  29: SUNNYSIDE.land.volcanoLevel29,
  30: SUNNYSIDE.land.volcanoLevel30,
  31: SUNNYSIDE.land.volcanoLevel31,
  32: SUNNYSIDE.land.volcanoLevel32,
  33: SUNNYSIDE.land.volcanoLevel33,
  34: SUNNYSIDE.land.volcanoLevel34,
  35: SUNNYSIDE.land.volcanoLevel35,
  36: SUNNYSIDE.land.volcanoLevel36,
  37: SUNNYSIDE.land.volcanoLevel37,
  38: SUNNYSIDE.land.volcanoLevel38,
  39: SUNNYSIDE.land.volcanoLevel39,
  40: SUNNYSIDE.land.volcanoLevel40,
  41: SUNNYSIDE.land.volcanoLevel41,
  42: SUNNYSIDE.land.volcanoLevel42,
};

const AUTUMN_VOLCANO_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.volcanoLevel1,
  2: SUNNYSIDE.seasons.autumn.volcanoLevel2,
  3: SUNNYSIDE.seasons.autumn.volcanoLevel3,
  4: SUNNYSIDE.seasons.autumn.volcanoLevel4,
  5: SUNNYSIDE.seasons.autumn.volcanoLevel5,
  6: SUNNYSIDE.seasons.autumn.volcanoLevel6,
  7: SUNNYSIDE.seasons.autumn.volcanoLevel7,
  8: SUNNYSIDE.seasons.autumn.volcanoLevel8,
  9: SUNNYSIDE.seasons.autumn.volcanoLevel9,
  10: SUNNYSIDE.seasons.autumn.volcanoLevel10,
  11: SUNNYSIDE.seasons.autumn.volcanoLevel11,
  12: SUNNYSIDE.seasons.autumn.volcanoLevel12,
  13: SUNNYSIDE.seasons.autumn.volcanoLevel13,
  14: SUNNYSIDE.seasons.autumn.volcanoLevel14,
  15: SUNNYSIDE.seasons.autumn.volcanoLevel15,
  16: SUNNYSIDE.seasons.autumn.volcanoLevel16,
  17: SUNNYSIDE.seasons.autumn.volcanoLevel17,
  18: SUNNYSIDE.seasons.autumn.volcanoLevel18,
  19: SUNNYSIDE.seasons.autumn.volcanoLevel19,
  20: SUNNYSIDE.seasons.autumn.volcanoLevel20,
  21: SUNNYSIDE.seasons.autumn.volcanoLevel21,
  22: SUNNYSIDE.seasons.autumn.volcanoLevel22,
  23: SUNNYSIDE.seasons.autumn.volcanoLevel23,
  24: SUNNYSIDE.seasons.autumn.volcanoLevel24,
  25: SUNNYSIDE.seasons.autumn.volcanoLevel25,
  26: SUNNYSIDE.seasons.autumn.volcanoLevel26,
  27: SUNNYSIDE.seasons.autumn.volcanoLevel27,
  28: SUNNYSIDE.seasons.autumn.volcanoLevel28,
  29: SUNNYSIDE.seasons.autumn.volcanoLevel29,
  30: SUNNYSIDE.seasons.autumn.volcanoLevel30,
  31: SUNNYSIDE.seasons.autumn.volcanoLevel31,
  32: SUNNYSIDE.seasons.autumn.volcanoLevel32,
  33: SUNNYSIDE.seasons.autumn.volcanoLevel33,
  34: SUNNYSIDE.seasons.autumn.volcanoLevel34,
  35: SUNNYSIDE.seasons.autumn.volcanoLevel35,
  36: SUNNYSIDE.seasons.autumn.volcanoLevel36,
  37: SUNNYSIDE.seasons.autumn.volcanoLevel37,
  38: SUNNYSIDE.seasons.autumn.volcanoLevel38,
  39: SUNNYSIDE.seasons.autumn.volcanoLevel39,
  40: SUNNYSIDE.seasons.autumn.volcanoLevel40,
  41: SUNNYSIDE.seasons.autumn.volcanoLevel41,
  42: SUNNYSIDE.seasons.autumn.volcanoLevel42,
};

const WINTER_VOLCANO_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.volcanoLevel1,
  2: SUNNYSIDE.seasons.winter.volcanoLevel2,
  3: SUNNYSIDE.seasons.winter.volcanoLevel3,
  4: SUNNYSIDE.seasons.winter.volcanoLevel4,
  5: SUNNYSIDE.seasons.winter.volcanoLevel5,
  6: SUNNYSIDE.seasons.winter.volcanoLevel6,
  7: SUNNYSIDE.seasons.winter.volcanoLevel7,
  8: SUNNYSIDE.seasons.winter.volcanoLevel8,
  9: SUNNYSIDE.seasons.winter.volcanoLevel9,
  10: SUNNYSIDE.seasons.winter.volcanoLevel10,
  11: SUNNYSIDE.seasons.winter.volcanoLevel11,
  12: SUNNYSIDE.seasons.winter.volcanoLevel12,
  13: SUNNYSIDE.seasons.winter.volcanoLevel13,
  14: SUNNYSIDE.seasons.winter.volcanoLevel14,
  15: SUNNYSIDE.seasons.winter.volcanoLevel15,
  16: SUNNYSIDE.seasons.winter.volcanoLevel16,
  17: SUNNYSIDE.seasons.winter.volcanoLevel17,
  18: SUNNYSIDE.seasons.winter.volcanoLevel18,
  19: SUNNYSIDE.seasons.winter.volcanoLevel19,
  20: SUNNYSIDE.seasons.winter.volcanoLevel20,
  21: SUNNYSIDE.seasons.winter.volcanoLevel21,
  22: SUNNYSIDE.seasons.winter.volcanoLevel22,
  23: SUNNYSIDE.seasons.winter.volcanoLevel23,
  24: SUNNYSIDE.seasons.winter.volcanoLevel24,
  25: SUNNYSIDE.seasons.winter.volcanoLevel25,
  26: SUNNYSIDE.seasons.winter.volcanoLevel26,
  27: SUNNYSIDE.seasons.winter.volcanoLevel27,
  28: SUNNYSIDE.seasons.winter.volcanoLevel28,
  29: SUNNYSIDE.seasons.winter.volcanoLevel29,
  30: SUNNYSIDE.seasons.winter.volcanoLevel30,
  31: SUNNYSIDE.seasons.winter.volcanoLevel31,
  32: SUNNYSIDE.seasons.winter.volcanoLevel32,
  33: SUNNYSIDE.seasons.winter.volcanoLevel33,
  34: SUNNYSIDE.seasons.winter.volcanoLevel34,
  35: SUNNYSIDE.seasons.winter.volcanoLevel35,
  36: SUNNYSIDE.seasons.winter.volcanoLevel36,
  37: SUNNYSIDE.seasons.winter.volcanoLevel37,
  38: SUNNYSIDE.seasons.winter.volcanoLevel38,
  39: SUNNYSIDE.seasons.winter.volcanoLevel39,
  40: SUNNYSIDE.seasons.winter.volcanoLevel40,
  41: SUNNYSIDE.seasons.winter.volcanoLevel41,
  42: SUNNYSIDE.seasons.winter.volcanoLevel42,
};

const SPRING_SWAMP_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.swampLevel1,
  2: SUNNYSIDE.seasons.spring.swampLevel2,
  3: SUNNYSIDE.seasons.spring.swampLevel3,
  4: SUNNYSIDE.seasons.spring.swampLevel4,
  5: SUNNYSIDE.seasons.spring.swampLevel5,
  6: SUNNYSIDE.seasons.spring.swampLevel6,
  7: SUNNYSIDE.seasons.spring.swampLevel7,
  8: SUNNYSIDE.seasons.spring.swampLevel8,
  9: SUNNYSIDE.seasons.spring.swampLevel9,
  10: SUNNYSIDE.seasons.spring.swampLevel10,
  11: SUNNYSIDE.seasons.spring.swampLevel11,
  12: SUNNYSIDE.seasons.spring.swampLevel12,
  13: SUNNYSIDE.seasons.spring.swampLevel13,
  14: SUNNYSIDE.seasons.spring.swampLevel14,
  15: SUNNYSIDE.seasons.spring.swampLevel15,
  16: SUNNYSIDE.seasons.spring.swampLevel16,
  17: SUNNYSIDE.seasons.spring.swampLevel17,
  18: SUNNYSIDE.seasons.spring.swampLevel18,
  19: SUNNYSIDE.seasons.spring.swampLevel19,
  20: SUNNYSIDE.seasons.spring.swampLevel20,
  21: SUNNYSIDE.seasons.spring.swampLevel21,
  22: SUNNYSIDE.seasons.spring.swampLevel22,
  23: SUNNYSIDE.seasons.spring.swampLevel23,
  24: SUNNYSIDE.seasons.spring.swampLevel24,
  25: SUNNYSIDE.seasons.spring.swampLevel25,
  26: SUNNYSIDE.seasons.spring.swampLevel26,
  27: SUNNYSIDE.seasons.spring.swampLevel27,
  28: SUNNYSIDE.seasons.spring.swampLevel28,
  29: SUNNYSIDE.seasons.spring.swampLevel29,
  30: SUNNYSIDE.seasons.spring.swampLevel30,
  31: SUNNYSIDE.seasons.spring.swampLevel31,
  32: SUNNYSIDE.seasons.spring.swampLevel32,
  33: SUNNYSIDE.seasons.spring.swampLevel33,
  34: SUNNYSIDE.seasons.spring.swampLevel34,
  35: SUNNYSIDE.seasons.spring.swampLevel35,
  36: SUNNYSIDE.seasons.spring.swampLevel36,
  37: SUNNYSIDE.seasons.spring.swampLevel37,
  38: SUNNYSIDE.seasons.spring.swampLevel38,
  39: SUNNYSIDE.seasons.spring.swampLevel39,
  40: SUNNYSIDE.seasons.spring.swampLevel40,
  41: SUNNYSIDE.seasons.spring.swampLevel41,
  42: SUNNYSIDE.seasons.spring.swampLevel42,
};

const SUMMER_SWAMP_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.swampLevel1,
  2: SUNNYSIDE.land.swampLevel2,
  3: SUNNYSIDE.land.swampLevel3,
  4: SUNNYSIDE.land.swampLevel4,
  5: SUNNYSIDE.land.swampLevel5,
  6: SUNNYSIDE.land.swampLevel6,
  7: SUNNYSIDE.land.swampLevel7,
  8: SUNNYSIDE.land.swampLevel8,
  9: SUNNYSIDE.land.swampLevel9,
  10: SUNNYSIDE.land.swampLevel10,
  11: SUNNYSIDE.land.swampLevel11,
  12: SUNNYSIDE.land.swampLevel12,
  13: SUNNYSIDE.land.swampLevel13,
  14: SUNNYSIDE.land.swampLevel14,
  15: SUNNYSIDE.land.swampLevel15,
  16: SUNNYSIDE.land.swampLevel16,
  17: SUNNYSIDE.land.swampLevel17,
  18: SUNNYSIDE.land.swampLevel18,
  19: SUNNYSIDE.land.swampLevel19,
  20: SUNNYSIDE.land.swampLevel20,
  21: SUNNYSIDE.land.swampLevel21,
  22: SUNNYSIDE.land.swampLevel22,
  23: SUNNYSIDE.land.swampLevel23,
  24: SUNNYSIDE.land.swampLevel24,
  25: SUNNYSIDE.land.swampLevel25,
  26: SUNNYSIDE.land.swampLevel26,
  27: SUNNYSIDE.land.swampLevel27,
  28: SUNNYSIDE.land.swampLevel28,
  29: SUNNYSIDE.land.swampLevel29,
  30: SUNNYSIDE.land.swampLevel30,
  31: SUNNYSIDE.land.swampLevel31,
  32: SUNNYSIDE.land.swampLevel32,
  33: SUNNYSIDE.land.swampLevel33,
  34: SUNNYSIDE.land.swampLevel34,
  35: SUNNYSIDE.land.swampLevel35,
  36: SUNNYSIDE.land.swampLevel36,
  37: SUNNYSIDE.land.swampLevel37,
  38: SUNNYSIDE.land.swampLevel38,
  39: SUNNYSIDE.land.swampLevel39,
  40: SUNNYSIDE.land.swampLevel40,
  41: SUNNYSIDE.land.swampLevel41,
  42: SUNNYSIDE.land.swampLevel42,
};

const AUTUMN_SWAMP_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.swampLevel1,
  2: SUNNYSIDE.seasons.autumn.swampLevel2,
  3: SUNNYSIDE.seasons.autumn.swampLevel3,
  4: SUNNYSIDE.seasons.autumn.swampLevel4,
  5: SUNNYSIDE.seasons.autumn.swampLevel5,
  6: SUNNYSIDE.seasons.autumn.swampLevel6,
  7: SUNNYSIDE.seasons.autumn.swampLevel7,
  8: SUNNYSIDE.seasons.autumn.swampLevel8,
  9: SUNNYSIDE.seasons.autumn.swampLevel9,
  10: SUNNYSIDE.seasons.autumn.swampLevel10,
  11: SUNNYSIDE.seasons.autumn.swampLevel11,
  12: SUNNYSIDE.seasons.autumn.swampLevel12,
  13: SUNNYSIDE.seasons.autumn.swampLevel13,
  14: SUNNYSIDE.seasons.autumn.swampLevel14,
  15: SUNNYSIDE.seasons.autumn.swampLevel15,
  16: SUNNYSIDE.seasons.autumn.swampLevel16,
  17: SUNNYSIDE.seasons.autumn.swampLevel17,
  18: SUNNYSIDE.seasons.autumn.swampLevel18,
  19: SUNNYSIDE.seasons.autumn.swampLevel19,
  20: SUNNYSIDE.seasons.autumn.swampLevel20,
  21: SUNNYSIDE.seasons.autumn.swampLevel21,
  22: SUNNYSIDE.seasons.autumn.swampLevel22,
  23: SUNNYSIDE.seasons.autumn.swampLevel23,
  24: SUNNYSIDE.seasons.autumn.swampLevel24,
  25: SUNNYSIDE.seasons.autumn.swampLevel25,
  26: SUNNYSIDE.seasons.autumn.swampLevel26,
  27: SUNNYSIDE.seasons.autumn.swampLevel27,
  28: SUNNYSIDE.seasons.autumn.swampLevel28,
  29: SUNNYSIDE.seasons.autumn.swampLevel29,
  30: SUNNYSIDE.seasons.autumn.swampLevel30,
  31: SUNNYSIDE.seasons.autumn.swampLevel31,
  32: SUNNYSIDE.seasons.autumn.swampLevel32,
  33: SUNNYSIDE.seasons.autumn.swampLevel33,
  34: SUNNYSIDE.seasons.autumn.swampLevel34,
  35: SUNNYSIDE.seasons.autumn.swampLevel35,
  36: SUNNYSIDE.seasons.autumn.swampLevel36,
  37: SUNNYSIDE.seasons.autumn.swampLevel37,
  38: SUNNYSIDE.seasons.autumn.swampLevel38,
  39: SUNNYSIDE.seasons.autumn.swampLevel39,
  40: SUNNYSIDE.seasons.autumn.swampLevel40,
  41: SUNNYSIDE.seasons.autumn.swampLevel41,
  42: SUNNYSIDE.seasons.autumn.swampLevel42,
};

const WINTER_SWAMP_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.swampLevel1,
  2: SUNNYSIDE.seasons.winter.swampLevel2,
  3: SUNNYSIDE.seasons.winter.swampLevel3,
  4: SUNNYSIDE.seasons.winter.swampLevel4,
  5: SUNNYSIDE.seasons.winter.swampLevel5,
  6: SUNNYSIDE.seasons.winter.swampLevel6,
  7: SUNNYSIDE.seasons.winter.swampLevel7,
  8: SUNNYSIDE.seasons.winter.swampLevel8,
  9: SUNNYSIDE.seasons.winter.swampLevel9,
  10: SUNNYSIDE.seasons.winter.swampLevel10,
  11: SUNNYSIDE.seasons.winter.swampLevel11,
  12: SUNNYSIDE.seasons.winter.swampLevel12,
  13: SUNNYSIDE.seasons.winter.swampLevel13,
  14: SUNNYSIDE.seasons.winter.swampLevel14,
  15: SUNNYSIDE.seasons.winter.swampLevel15,
  16: SUNNYSIDE.seasons.winter.swampLevel16,
  17: SUNNYSIDE.seasons.winter.swampLevel17,
  18: SUNNYSIDE.seasons.winter.swampLevel18,
  19: SUNNYSIDE.seasons.winter.swampLevel19,
  20: SUNNYSIDE.seasons.winter.swampLevel20,
  21: SUNNYSIDE.seasons.winter.swampLevel21,
  22: SUNNYSIDE.seasons.winter.swampLevel22,
  23: SUNNYSIDE.seasons.winter.swampLevel23,
  24: SUNNYSIDE.seasons.winter.swampLevel24,
  25: SUNNYSIDE.seasons.winter.swampLevel25,
  26: SUNNYSIDE.seasons.winter.swampLevel26,
  27: SUNNYSIDE.seasons.winter.swampLevel27,
  28: SUNNYSIDE.seasons.winter.swampLevel28,
  29: SUNNYSIDE.seasons.winter.swampLevel29,
  30: SUNNYSIDE.seasons.winter.swampLevel30,
  31: SUNNYSIDE.seasons.winter.swampLevel31,
  32: SUNNYSIDE.seasons.winter.swampLevel32,
  33: SUNNYSIDE.seasons.winter.swampLevel33,
  34: SUNNYSIDE.seasons.winter.swampLevel34,
  35: SUNNYSIDE.seasons.winter.swampLevel35,
  36: SUNNYSIDE.seasons.winter.swampLevel36,
  37: SUNNYSIDE.seasons.winter.swampLevel37,
  38: SUNNYSIDE.seasons.winter.swampLevel38,
  39: SUNNYSIDE.seasons.winter.swampLevel39,
  40: SUNNYSIDE.seasons.winter.swampLevel40,
  41: SUNNYSIDE.seasons.winter.swampLevel41,
  42: SUNNYSIDE.seasons.winter.swampLevel42,
};

const SPRING_SPOOKY_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.spookyLevel1,
  2: SUNNYSIDE.seasons.spring.spookyLevel2,
  3: SUNNYSIDE.seasons.spring.spookyLevel3,
  4: SUNNYSIDE.seasons.spring.spookyLevel4,
  5: SUNNYSIDE.seasons.spring.spookyLevel5,
  6: SUNNYSIDE.seasons.spring.spookyLevel6,
  7: SUNNYSIDE.seasons.spring.spookyLevel7,
  8: SUNNYSIDE.seasons.spring.spookyLevel8,
  9: SUNNYSIDE.seasons.spring.spookyLevel9,
  10: SUNNYSIDE.seasons.spring.spookyLevel10,
  11: SUNNYSIDE.seasons.spring.spookyLevel11,
  12: SUNNYSIDE.seasons.spring.spookyLevel12,
  13: SUNNYSIDE.seasons.spring.spookyLevel13,
  14: SUNNYSIDE.seasons.spring.spookyLevel14,
  15: SUNNYSIDE.seasons.spring.spookyLevel15,
  16: SUNNYSIDE.seasons.spring.spookyLevel16,
  17: SUNNYSIDE.seasons.spring.spookyLevel17,
  18: SUNNYSIDE.seasons.spring.spookyLevel18,
  19: SUNNYSIDE.seasons.spring.spookyLevel19,
  20: SUNNYSIDE.seasons.spring.spookyLevel20,
  21: SUNNYSIDE.seasons.spring.spookyLevel21,
  22: SUNNYSIDE.seasons.spring.spookyLevel22,
  23: SUNNYSIDE.seasons.spring.spookyLevel23,
  24: SUNNYSIDE.seasons.spring.spookyLevel24,
  25: SUNNYSIDE.seasons.spring.spookyLevel25,
  26: SUNNYSIDE.seasons.spring.spookyLevel26,
  27: SUNNYSIDE.seasons.spring.spookyLevel27,
  28: SUNNYSIDE.seasons.spring.spookyLevel28,
  29: SUNNYSIDE.seasons.spring.spookyLevel29,
  30: SUNNYSIDE.seasons.spring.spookyLevel30,
  31: SUNNYSIDE.seasons.spring.spookyLevel31,
  32: SUNNYSIDE.seasons.spring.spookyLevel32,
  33: SUNNYSIDE.seasons.spring.spookyLevel33,
  34: SUNNYSIDE.seasons.spring.spookyLevel34,
  35: SUNNYSIDE.seasons.spring.spookyLevel35,
  36: SUNNYSIDE.seasons.spring.spookyLevel36,
  37: SUNNYSIDE.seasons.spring.spookyLevel37,
  38: SUNNYSIDE.seasons.spring.spookyLevel38,
  39: SUNNYSIDE.seasons.spring.spookyLevel39,
  40: SUNNYSIDE.seasons.spring.spookyLevel40,
  41: SUNNYSIDE.seasons.spring.spookyLevel41,
  42: SUNNYSIDE.seasons.spring.spookyLevel42,
};

const SUMMER_SPOOKY_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.spookyLevel1,
  2: SUNNYSIDE.land.spookyLevel2,
  3: SUNNYSIDE.land.spookyLevel3,
  4: SUNNYSIDE.land.spookyLevel4,
  5: SUNNYSIDE.land.spookyLevel5,
  6: SUNNYSIDE.land.spookyLevel6,
  7: SUNNYSIDE.land.spookyLevel7,
  8: SUNNYSIDE.land.spookyLevel8,
  9: SUNNYSIDE.land.spookyLevel9,
  10: SUNNYSIDE.land.spookyLevel10,
  11: SUNNYSIDE.land.spookyLevel11,
  12: SUNNYSIDE.land.spookyLevel12,
  13: SUNNYSIDE.land.spookyLevel13,
  14: SUNNYSIDE.land.spookyLevel14,
  15: SUNNYSIDE.land.spookyLevel15,
  16: SUNNYSIDE.land.spookyLevel16,
  17: SUNNYSIDE.land.spookyLevel17,
  18: SUNNYSIDE.land.spookyLevel18,
  19: SUNNYSIDE.land.spookyLevel19,
  20: SUNNYSIDE.land.spookyLevel20,
  21: SUNNYSIDE.land.spookyLevel21,
  22: SUNNYSIDE.land.spookyLevel22,
  23: SUNNYSIDE.land.spookyLevel23,
  24: SUNNYSIDE.land.spookyLevel24,
  25: SUNNYSIDE.land.spookyLevel25,
  26: SUNNYSIDE.land.spookyLevel26,
  27: SUNNYSIDE.land.spookyLevel27,
  28: SUNNYSIDE.land.spookyLevel28,
  29: SUNNYSIDE.land.spookyLevel29,
  30: SUNNYSIDE.land.spookyLevel30,
  31: SUNNYSIDE.land.spookyLevel31,
  32: SUNNYSIDE.land.spookyLevel32,
  33: SUNNYSIDE.land.spookyLevel33,
  34: SUNNYSIDE.land.spookyLevel34,
  35: SUNNYSIDE.land.spookyLevel35,
  36: SUNNYSIDE.land.spookyLevel36,
  37: SUNNYSIDE.land.spookyLevel37,
  38: SUNNYSIDE.land.spookyLevel38,
  39: SUNNYSIDE.land.spookyLevel39,
  40: SUNNYSIDE.land.spookyLevel40,
  41: SUNNYSIDE.land.spookyLevel41,
  42: SUNNYSIDE.land.spookyLevel42,
};

const AUTUMN_SPOOKY_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.spookyLevel1,
  2: SUNNYSIDE.seasons.autumn.spookyLevel2,
  3: SUNNYSIDE.seasons.autumn.spookyLevel3,
  4: SUNNYSIDE.seasons.autumn.spookyLevel4,
  5: SUNNYSIDE.seasons.autumn.spookyLevel5,
  6: SUNNYSIDE.seasons.autumn.spookyLevel6,
  7: SUNNYSIDE.seasons.autumn.spookyLevel7,
  8: SUNNYSIDE.seasons.autumn.spookyLevel8,
  9: SUNNYSIDE.seasons.autumn.spookyLevel9,
  10: SUNNYSIDE.seasons.autumn.spookyLevel10,
  11: SUNNYSIDE.seasons.autumn.spookyLevel11,
  12: SUNNYSIDE.seasons.autumn.spookyLevel12,
  13: SUNNYSIDE.seasons.autumn.spookyLevel13,
  14: SUNNYSIDE.seasons.autumn.spookyLevel14,
  15: SUNNYSIDE.seasons.autumn.spookyLevel15,
  16: SUNNYSIDE.seasons.autumn.spookyLevel16,
  17: SUNNYSIDE.seasons.autumn.spookyLevel17,
  18: SUNNYSIDE.seasons.autumn.spookyLevel18,
  19: SUNNYSIDE.seasons.autumn.spookyLevel19,
  20: SUNNYSIDE.seasons.autumn.spookyLevel20,
  21: SUNNYSIDE.seasons.autumn.spookyLevel21,
  22: SUNNYSIDE.seasons.autumn.spookyLevel22,
  23: SUNNYSIDE.seasons.autumn.spookyLevel23,
  24: SUNNYSIDE.seasons.autumn.spookyLevel24,
  25: SUNNYSIDE.seasons.autumn.spookyLevel25,
  26: SUNNYSIDE.seasons.autumn.spookyLevel26,
  27: SUNNYSIDE.seasons.autumn.spookyLevel27,
  28: SUNNYSIDE.seasons.autumn.spookyLevel28,
  29: SUNNYSIDE.seasons.autumn.spookyLevel29,
  30: SUNNYSIDE.seasons.autumn.spookyLevel30,
  31: SUNNYSIDE.seasons.autumn.spookyLevel31,
  32: SUNNYSIDE.seasons.autumn.spookyLevel32,
  33: SUNNYSIDE.seasons.autumn.spookyLevel33,
  34: SUNNYSIDE.seasons.autumn.spookyLevel34,
  35: SUNNYSIDE.seasons.autumn.spookyLevel35,
  36: SUNNYSIDE.seasons.autumn.spookyLevel36,
  37: SUNNYSIDE.seasons.autumn.spookyLevel37,
  38: SUNNYSIDE.seasons.autumn.spookyLevel38,
  39: SUNNYSIDE.seasons.autumn.spookyLevel39,
  40: SUNNYSIDE.seasons.autumn.spookyLevel40,
  41: SUNNYSIDE.seasons.autumn.spookyLevel41,
  42: SUNNYSIDE.seasons.autumn.spookyLevel42,
};

const WINTER_SPOOKY_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.spookyLevel1,
  2: SUNNYSIDE.seasons.winter.spookyLevel2,
  3: SUNNYSIDE.seasons.winter.spookyLevel3,
  4: SUNNYSIDE.seasons.winter.spookyLevel4,
  5: SUNNYSIDE.seasons.winter.spookyLevel5,
  6: SUNNYSIDE.seasons.winter.spookyLevel6,
  7: SUNNYSIDE.seasons.winter.spookyLevel7,
  8: SUNNYSIDE.seasons.winter.spookyLevel8,
  9: SUNNYSIDE.seasons.winter.spookyLevel9,
  10: SUNNYSIDE.seasons.winter.spookyLevel10,
  11: SUNNYSIDE.seasons.winter.spookyLevel11,
  12: SUNNYSIDE.seasons.winter.spookyLevel12,
  13: SUNNYSIDE.seasons.winter.spookyLevel13,
  14: SUNNYSIDE.seasons.winter.spookyLevel14,
  15: SUNNYSIDE.seasons.winter.spookyLevel15,
  16: SUNNYSIDE.seasons.winter.spookyLevel16,
  17: SUNNYSIDE.seasons.winter.spookyLevel17,
  18: SUNNYSIDE.seasons.winter.spookyLevel18,
  19: SUNNYSIDE.seasons.winter.spookyLevel19,
  20: SUNNYSIDE.seasons.winter.spookyLevel20,
  21: SUNNYSIDE.seasons.winter.spookyLevel21,
  22: SUNNYSIDE.seasons.winter.spookyLevel22,
  23: SUNNYSIDE.seasons.winter.spookyLevel23,
  24: SUNNYSIDE.seasons.winter.spookyLevel24,
  25: SUNNYSIDE.seasons.winter.spookyLevel25,
  26: SUNNYSIDE.seasons.winter.spookyLevel26,
  27: SUNNYSIDE.seasons.winter.spookyLevel27,
  28: SUNNYSIDE.seasons.winter.spookyLevel28,
  29: SUNNYSIDE.seasons.winter.spookyLevel29,
  30: SUNNYSIDE.seasons.winter.spookyLevel30,
  31: SUNNYSIDE.seasons.winter.spookyLevel31,
  32: SUNNYSIDE.seasons.winter.spookyLevel32,
  33: SUNNYSIDE.seasons.winter.spookyLevel33,
  34: SUNNYSIDE.seasons.winter.spookyLevel34,
  35: SUNNYSIDE.seasons.winter.spookyLevel35,
  36: SUNNYSIDE.seasons.winter.spookyLevel36,
  37: SUNNYSIDE.seasons.winter.spookyLevel37,
  38: SUNNYSIDE.seasons.winter.spookyLevel38,
  39: SUNNYSIDE.seasons.winter.spookyLevel39,
  40: SUNNYSIDE.seasons.winter.spookyLevel40,
  41: SUNNYSIDE.seasons.winter.spookyLevel41,
  42: SUNNYSIDE.seasons.winter.spookyLevel42,
};

const SPRING_CRYSTAL_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.crystalLevel1,
  2: SUNNYSIDE.seasons.spring.crystalLevel2,
  3: SUNNYSIDE.seasons.spring.crystalLevel3,
  4: SUNNYSIDE.seasons.spring.crystalLevel4,
  5: SUNNYSIDE.seasons.spring.crystalLevel5,
  6: SUNNYSIDE.seasons.spring.crystalLevel6,
  7: SUNNYSIDE.seasons.spring.crystalLevel7,
  8: SUNNYSIDE.seasons.spring.crystalLevel8,
  9: SUNNYSIDE.seasons.spring.crystalLevel9,
  10: SUNNYSIDE.seasons.spring.crystalLevel10,
  11: SUNNYSIDE.seasons.spring.crystalLevel11,
  12: SUNNYSIDE.seasons.spring.crystalLevel12,
  13: SUNNYSIDE.seasons.spring.crystalLevel13,
  14: SUNNYSIDE.seasons.spring.crystalLevel14,
  15: SUNNYSIDE.seasons.spring.crystalLevel15,
  16: SUNNYSIDE.seasons.spring.crystalLevel16,
  17: SUNNYSIDE.seasons.spring.crystalLevel17,
  18: SUNNYSIDE.seasons.spring.crystalLevel18,
  19: SUNNYSIDE.seasons.spring.crystalLevel19,
  20: SUNNYSIDE.seasons.spring.crystalLevel20,
  21: SUNNYSIDE.seasons.spring.crystalLevel21,
  22: SUNNYSIDE.seasons.spring.crystalLevel22,
  23: SUNNYSIDE.seasons.spring.crystalLevel23,
  24: SUNNYSIDE.seasons.spring.crystalLevel24,
  25: SUNNYSIDE.seasons.spring.crystalLevel25,
  26: SUNNYSIDE.seasons.spring.crystalLevel26,
  27: SUNNYSIDE.seasons.spring.crystalLevel27,
  28: SUNNYSIDE.seasons.spring.crystalLevel28,
  29: SUNNYSIDE.seasons.spring.crystalLevel29,
  30: SUNNYSIDE.seasons.spring.crystalLevel30,
  31: SUNNYSIDE.seasons.spring.crystalLevel31,
  32: SUNNYSIDE.seasons.spring.crystalLevel32,
  33: SUNNYSIDE.seasons.spring.crystalLevel33,
  34: SUNNYSIDE.seasons.spring.crystalLevel34,
  35: SUNNYSIDE.seasons.spring.crystalLevel35,
  36: SUNNYSIDE.seasons.spring.crystalLevel36,
  37: SUNNYSIDE.seasons.spring.crystalLevel37,
  38: SUNNYSIDE.seasons.spring.crystalLevel38,
  39: SUNNYSIDE.seasons.spring.crystalLevel39,
  40: SUNNYSIDE.seasons.spring.crystalLevel40,
  41: SUNNYSIDE.seasons.spring.crystalLevel41,
  42: SUNNYSIDE.seasons.spring.crystalLevel42,
};

const SUMMER_CRYSTAL_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.crystalLevel1,
  2: SUNNYSIDE.land.crystalLevel2,
  3: SUNNYSIDE.land.crystalLevel3,
  4: SUNNYSIDE.land.crystalLevel4,
  5: SUNNYSIDE.land.crystalLevel5,
  6: SUNNYSIDE.land.crystalLevel6,
  7: SUNNYSIDE.land.crystalLevel7,
  8: SUNNYSIDE.land.crystalLevel8,
  9: SUNNYSIDE.land.crystalLevel9,
  10: SUNNYSIDE.land.crystalLevel10,
  11: SUNNYSIDE.land.crystalLevel11,
  12: SUNNYSIDE.land.crystalLevel12,
  13: SUNNYSIDE.land.crystalLevel13,
  14: SUNNYSIDE.land.crystalLevel14,
  15: SUNNYSIDE.land.crystalLevel15,
  16: SUNNYSIDE.land.crystalLevel16,
  17: SUNNYSIDE.land.crystalLevel17,
  18: SUNNYSIDE.land.crystalLevel18,
  19: SUNNYSIDE.land.crystalLevel19,
  20: SUNNYSIDE.land.crystalLevel20,
  21: SUNNYSIDE.land.crystalLevel21,
  22: SUNNYSIDE.land.crystalLevel22,
  23: SUNNYSIDE.land.crystalLevel23,
  24: SUNNYSIDE.land.crystalLevel24,
  25: SUNNYSIDE.land.crystalLevel25,
  26: SUNNYSIDE.land.crystalLevel26,
  27: SUNNYSIDE.land.crystalLevel27,
  28: SUNNYSIDE.land.crystalLevel28,
  29: SUNNYSIDE.land.crystalLevel29,
  30: SUNNYSIDE.land.crystalLevel30,
  31: SUNNYSIDE.land.crystalLevel31,
  32: SUNNYSIDE.land.crystalLevel32,
  33: SUNNYSIDE.land.crystalLevel33,
  34: SUNNYSIDE.land.crystalLevel34,
  35: SUNNYSIDE.land.crystalLevel35,
  36: SUNNYSIDE.land.crystalLevel36,
  37: SUNNYSIDE.land.crystalLevel37,
  38: SUNNYSIDE.land.crystalLevel38,
  39: SUNNYSIDE.land.crystalLevel39,
  40: SUNNYSIDE.land.crystalLevel40,
  41: SUNNYSIDE.land.crystalLevel41,
  42: SUNNYSIDE.land.crystalLevel42,
};

const AUTUMN_CRYSTAL_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.crystalLevel1,
  2: SUNNYSIDE.seasons.autumn.crystalLevel2,
  3: SUNNYSIDE.seasons.autumn.crystalLevel3,
  4: SUNNYSIDE.seasons.autumn.crystalLevel4,
  5: SUNNYSIDE.seasons.autumn.crystalLevel5,
  6: SUNNYSIDE.seasons.autumn.crystalLevel6,
  7: SUNNYSIDE.seasons.autumn.crystalLevel7,
  8: SUNNYSIDE.seasons.autumn.crystalLevel8,
  9: SUNNYSIDE.seasons.autumn.crystalLevel9,
  10: SUNNYSIDE.seasons.autumn.crystalLevel10,
  11: SUNNYSIDE.seasons.autumn.crystalLevel11,
  12: SUNNYSIDE.seasons.autumn.crystalLevel12,
  13: SUNNYSIDE.seasons.autumn.crystalLevel13,
  14: SUNNYSIDE.seasons.autumn.crystalLevel14,
  15: SUNNYSIDE.seasons.autumn.crystalLevel15,
  16: SUNNYSIDE.seasons.autumn.crystalLevel16,
  17: SUNNYSIDE.seasons.autumn.crystalLevel17,
  18: SUNNYSIDE.seasons.autumn.crystalLevel18,
  19: SUNNYSIDE.seasons.autumn.crystalLevel19,
  20: SUNNYSIDE.seasons.autumn.crystalLevel20,
  21: SUNNYSIDE.seasons.autumn.crystalLevel21,
  22: SUNNYSIDE.seasons.autumn.crystalLevel22,
  23: SUNNYSIDE.seasons.autumn.crystalLevel23,
  24: SUNNYSIDE.seasons.autumn.crystalLevel24,
  25: SUNNYSIDE.seasons.autumn.crystalLevel25,
  26: SUNNYSIDE.seasons.autumn.crystalLevel26,
  27: SUNNYSIDE.seasons.autumn.crystalLevel27,
  28: SUNNYSIDE.seasons.autumn.crystalLevel28,
  29: SUNNYSIDE.seasons.autumn.crystalLevel29,
  30: SUNNYSIDE.seasons.autumn.crystalLevel30,
  31: SUNNYSIDE.seasons.autumn.crystalLevel31,
  32: SUNNYSIDE.seasons.autumn.crystalLevel32,
  33: SUNNYSIDE.seasons.autumn.crystalLevel33,
  34: SUNNYSIDE.seasons.autumn.crystalLevel34,
  35: SUNNYSIDE.seasons.autumn.crystalLevel35,
  36: SUNNYSIDE.seasons.autumn.crystalLevel36,
  37: SUNNYSIDE.seasons.autumn.crystalLevel37,
  38: SUNNYSIDE.seasons.autumn.crystalLevel38,
  39: SUNNYSIDE.seasons.autumn.crystalLevel39,
  40: SUNNYSIDE.seasons.autumn.crystalLevel40,
  41: SUNNYSIDE.seasons.autumn.crystalLevel41,
  42: SUNNYSIDE.seasons.autumn.crystalLevel42,
};

const WINTER_CRYSTAL_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.crystalLevel1,
  2: SUNNYSIDE.seasons.winter.crystalLevel2,
  3: SUNNYSIDE.seasons.winter.crystalLevel3,
  4: SUNNYSIDE.seasons.winter.crystalLevel4,
  5: SUNNYSIDE.seasons.winter.crystalLevel5,
  6: SUNNYSIDE.seasons.winter.crystalLevel6,
  7: SUNNYSIDE.seasons.winter.crystalLevel7,
  8: SUNNYSIDE.seasons.winter.crystalLevel8,
  9: SUNNYSIDE.seasons.winter.crystalLevel9,
  10: SUNNYSIDE.seasons.winter.crystalLevel10,
  11: SUNNYSIDE.seasons.winter.crystalLevel11,
  12: SUNNYSIDE.seasons.winter.crystalLevel12,
  13: SUNNYSIDE.seasons.winter.crystalLevel13,
  14: SUNNYSIDE.seasons.winter.crystalLevel14,
  15: SUNNYSIDE.seasons.winter.crystalLevel15,
  16: SUNNYSIDE.seasons.winter.crystalLevel16,
  17: SUNNYSIDE.seasons.winter.crystalLevel17,
  18: SUNNYSIDE.seasons.winter.crystalLevel18,
  19: SUNNYSIDE.seasons.winter.crystalLevel19,
  20: SUNNYSIDE.seasons.winter.crystalLevel20,
  21: SUNNYSIDE.seasons.winter.crystalLevel21,
  22: SUNNYSIDE.seasons.winter.crystalLevel22,
  23: SUNNYSIDE.seasons.winter.crystalLevel23,
  24: SUNNYSIDE.seasons.winter.crystalLevel24,
  25: SUNNYSIDE.seasons.winter.crystalLevel25,
  26: SUNNYSIDE.seasons.winter.crystalLevel26,
  27: SUNNYSIDE.seasons.winter.crystalLevel27,
  28: SUNNYSIDE.seasons.winter.crystalLevel28,
  29: SUNNYSIDE.seasons.winter.crystalLevel29,
  30: SUNNYSIDE.seasons.winter.crystalLevel30,
  31: SUNNYSIDE.seasons.winter.crystalLevel31,
  32: SUNNYSIDE.seasons.winter.crystalLevel32,
  33: SUNNYSIDE.seasons.winter.crystalLevel33,
  34: SUNNYSIDE.seasons.winter.crystalLevel34,
  35: SUNNYSIDE.seasons.winter.crystalLevel35,
  36: SUNNYSIDE.seasons.winter.crystalLevel36,
  37: SUNNYSIDE.seasons.winter.crystalLevel37,
  38: SUNNYSIDE.seasons.winter.crystalLevel38,
  39: SUNNYSIDE.seasons.winter.crystalLevel39,
  40: SUNNYSIDE.seasons.winter.crystalLevel40,
  41: SUNNYSIDE.seasons.winter.crystalLevel41,
  42: SUNNYSIDE.seasons.winter.crystalLevel42,
};

const SPRING_GALAXY_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.galaxyLevel1,
  2: SUNNYSIDE.seasons.spring.galaxyLevel2,
  3: SUNNYSIDE.seasons.spring.galaxyLevel3,
  4: SUNNYSIDE.seasons.spring.galaxyLevel4,
  5: SUNNYSIDE.seasons.spring.galaxyLevel5,
  6: SUNNYSIDE.seasons.spring.galaxyLevel6,
  7: SUNNYSIDE.seasons.spring.galaxyLevel7,
  8: SUNNYSIDE.seasons.spring.galaxyLevel8,
  9: SUNNYSIDE.seasons.spring.galaxyLevel9,
  10: SUNNYSIDE.seasons.spring.galaxyLevel10,
  11: SUNNYSIDE.seasons.spring.galaxyLevel11,
  12: SUNNYSIDE.seasons.spring.galaxyLevel12,
  13: SUNNYSIDE.seasons.spring.galaxyLevel13,
  14: SUNNYSIDE.seasons.spring.galaxyLevel14,
  15: SUNNYSIDE.seasons.spring.galaxyLevel15,
  16: SUNNYSIDE.seasons.spring.galaxyLevel16,
  17: SUNNYSIDE.seasons.spring.galaxyLevel17,
  18: SUNNYSIDE.seasons.spring.galaxyLevel18,
  19: SUNNYSIDE.seasons.spring.galaxyLevel19,
  20: SUNNYSIDE.seasons.spring.galaxyLevel20,
  21: SUNNYSIDE.seasons.spring.galaxyLevel21,
  22: SUNNYSIDE.seasons.spring.galaxyLevel22,
  23: SUNNYSIDE.seasons.spring.galaxyLevel23,
  24: SUNNYSIDE.seasons.spring.galaxyLevel24,
  25: SUNNYSIDE.seasons.spring.galaxyLevel25,
  26: SUNNYSIDE.seasons.spring.galaxyLevel26,
  27: SUNNYSIDE.seasons.spring.galaxyLevel27,
  28: SUNNYSIDE.seasons.spring.galaxyLevel28,
  29: SUNNYSIDE.seasons.spring.galaxyLevel29,
  30: SUNNYSIDE.seasons.spring.galaxyLevel30,
  31: SUNNYSIDE.seasons.spring.galaxyLevel31,
  32: SUNNYSIDE.seasons.spring.galaxyLevel32,
  33: SUNNYSIDE.seasons.spring.galaxyLevel33,
  34: SUNNYSIDE.seasons.spring.galaxyLevel34,
  35: SUNNYSIDE.seasons.spring.galaxyLevel35,
  36: SUNNYSIDE.seasons.spring.galaxyLevel36,
  37: SUNNYSIDE.seasons.spring.galaxyLevel37,
  38: SUNNYSIDE.seasons.spring.galaxyLevel38,
  39: SUNNYSIDE.seasons.spring.galaxyLevel39,
  40: SUNNYSIDE.seasons.spring.galaxyLevel40,
  41: SUNNYSIDE.seasons.spring.galaxyLevel41,
  42: SUNNYSIDE.seasons.spring.galaxyLevel42,
};

const SUMMER_GALAXY_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.galaxyLevel1,
  2: SUNNYSIDE.land.galaxyLevel2,
  3: SUNNYSIDE.land.galaxyLevel3,
  4: SUNNYSIDE.land.galaxyLevel4,
  5: SUNNYSIDE.land.galaxyLevel5,
  6: SUNNYSIDE.land.galaxyLevel6,
  7: SUNNYSIDE.land.galaxyLevel7,
  8: SUNNYSIDE.land.galaxyLevel8,
  9: SUNNYSIDE.land.galaxyLevel9,
  10: SUNNYSIDE.land.galaxyLevel10,
  11: SUNNYSIDE.land.galaxyLevel11,
  12: SUNNYSIDE.land.galaxyLevel12,
  13: SUNNYSIDE.land.galaxyLevel13,
  14: SUNNYSIDE.land.galaxyLevel14,
  15: SUNNYSIDE.land.galaxyLevel15,
  16: SUNNYSIDE.land.galaxyLevel16,
  17: SUNNYSIDE.land.galaxyLevel17,
  18: SUNNYSIDE.land.galaxyLevel18,
  19: SUNNYSIDE.land.galaxyLevel19,
  20: SUNNYSIDE.land.galaxyLevel20,
  21: SUNNYSIDE.land.galaxyLevel21,
  22: SUNNYSIDE.land.galaxyLevel22,
  23: SUNNYSIDE.land.galaxyLevel23,
  24: SUNNYSIDE.land.galaxyLevel24,
  25: SUNNYSIDE.land.galaxyLevel25,
  26: SUNNYSIDE.land.galaxyLevel26,
  27: SUNNYSIDE.land.galaxyLevel27,
  28: SUNNYSIDE.land.galaxyLevel28,
  29: SUNNYSIDE.land.galaxyLevel29,
  30: SUNNYSIDE.land.galaxyLevel30,
  31: SUNNYSIDE.land.galaxyLevel31,
  32: SUNNYSIDE.land.galaxyLevel32,
  33: SUNNYSIDE.land.galaxyLevel33,
  34: SUNNYSIDE.land.galaxyLevel34,
  35: SUNNYSIDE.land.galaxyLevel35,
  36: SUNNYSIDE.land.galaxyLevel36,
  37: SUNNYSIDE.land.galaxyLevel37,
  38: SUNNYSIDE.land.galaxyLevel38,
  39: SUNNYSIDE.land.galaxyLevel39,
  40: SUNNYSIDE.land.galaxyLevel40,
  41: SUNNYSIDE.land.galaxyLevel41,
  42: SUNNYSIDE.land.galaxyLevel42,
};

const AUTUMN_GALAXY_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.galaxyLevel1,
  2: SUNNYSIDE.seasons.autumn.galaxyLevel2,
  3: SUNNYSIDE.seasons.autumn.galaxyLevel3,
  4: SUNNYSIDE.seasons.autumn.galaxyLevel4,
  5: SUNNYSIDE.seasons.autumn.galaxyLevel5,
  6: SUNNYSIDE.seasons.autumn.galaxyLevel6,
  7: SUNNYSIDE.seasons.autumn.galaxyLevel7,
  8: SUNNYSIDE.seasons.autumn.galaxyLevel8,
  9: SUNNYSIDE.seasons.autumn.galaxyLevel9,
  10: SUNNYSIDE.seasons.autumn.galaxyLevel10,
  11: SUNNYSIDE.seasons.autumn.galaxyLevel11,
  12: SUNNYSIDE.seasons.autumn.galaxyLevel12,
  13: SUNNYSIDE.seasons.autumn.galaxyLevel13,
  14: SUNNYSIDE.seasons.autumn.galaxyLevel14,
  15: SUNNYSIDE.seasons.autumn.galaxyLevel15,
  16: SUNNYSIDE.seasons.autumn.galaxyLevel16,
  17: SUNNYSIDE.seasons.autumn.galaxyLevel17,
  18: SUNNYSIDE.seasons.autumn.galaxyLevel18,
  19: SUNNYSIDE.seasons.autumn.galaxyLevel19,
  20: SUNNYSIDE.seasons.autumn.galaxyLevel20,
  21: SUNNYSIDE.seasons.autumn.galaxyLevel21,
  22: SUNNYSIDE.seasons.autumn.galaxyLevel22,
  23: SUNNYSIDE.seasons.autumn.galaxyLevel23,
  24: SUNNYSIDE.seasons.autumn.galaxyLevel24,
  25: SUNNYSIDE.seasons.autumn.galaxyLevel25,
  26: SUNNYSIDE.seasons.autumn.galaxyLevel26,
  27: SUNNYSIDE.seasons.autumn.galaxyLevel27,
  28: SUNNYSIDE.seasons.autumn.galaxyLevel28,
  29: SUNNYSIDE.seasons.autumn.galaxyLevel29,
  30: SUNNYSIDE.seasons.autumn.galaxyLevel30,
  31: SUNNYSIDE.seasons.autumn.galaxyLevel31,
  32: SUNNYSIDE.seasons.autumn.galaxyLevel32,
  33: SUNNYSIDE.seasons.autumn.galaxyLevel33,
  34: SUNNYSIDE.seasons.autumn.galaxyLevel34,
  35: SUNNYSIDE.seasons.autumn.galaxyLevel35,
  36: SUNNYSIDE.seasons.autumn.galaxyLevel36,
  37: SUNNYSIDE.seasons.autumn.galaxyLevel37,
  38: SUNNYSIDE.seasons.autumn.galaxyLevel38,
  39: SUNNYSIDE.seasons.autumn.galaxyLevel39,
  40: SUNNYSIDE.seasons.autumn.galaxyLevel40,
  41: SUNNYSIDE.seasons.autumn.galaxyLevel41,
  42: SUNNYSIDE.seasons.autumn.galaxyLevel42,
};

const WINTER_GALAXY_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.galaxyLevel1,
  2: SUNNYSIDE.seasons.winter.galaxyLevel2,
  3: SUNNYSIDE.seasons.winter.galaxyLevel3,
  4: SUNNYSIDE.seasons.winter.galaxyLevel4,
  5: SUNNYSIDE.seasons.winter.galaxyLevel5,
  6: SUNNYSIDE.seasons.winter.galaxyLevel6,
  7: SUNNYSIDE.seasons.winter.galaxyLevel7,
  8: SUNNYSIDE.seasons.winter.galaxyLevel8,
  9: SUNNYSIDE.seasons.winter.galaxyLevel9,
  10: SUNNYSIDE.seasons.winter.galaxyLevel10,
  11: SUNNYSIDE.seasons.winter.galaxyLevel11,
  12: SUNNYSIDE.seasons.winter.galaxyLevel12,
  13: SUNNYSIDE.seasons.winter.galaxyLevel13,
  14: SUNNYSIDE.seasons.winter.galaxyLevel14,
  15: SUNNYSIDE.seasons.winter.galaxyLevel15,
  16: SUNNYSIDE.seasons.winter.galaxyLevel16,
  17: SUNNYSIDE.seasons.winter.galaxyLevel17,
  18: SUNNYSIDE.seasons.winter.galaxyLevel18,
  19: SUNNYSIDE.seasons.winter.galaxyLevel19,
  20: SUNNYSIDE.seasons.winter.galaxyLevel20,
  21: SUNNYSIDE.seasons.winter.galaxyLevel21,
  22: SUNNYSIDE.seasons.winter.galaxyLevel22,
  23: SUNNYSIDE.seasons.winter.galaxyLevel23,
  24: SUNNYSIDE.seasons.winter.galaxyLevel24,
  25: SUNNYSIDE.seasons.winter.galaxyLevel25,
  26: SUNNYSIDE.seasons.winter.galaxyLevel26,
  27: SUNNYSIDE.seasons.winter.galaxyLevel27,
  28: SUNNYSIDE.seasons.winter.galaxyLevel28,
  29: SUNNYSIDE.seasons.winter.galaxyLevel29,
  30: SUNNYSIDE.seasons.winter.galaxyLevel30,
  31: SUNNYSIDE.seasons.winter.galaxyLevel31,
  32: SUNNYSIDE.seasons.winter.galaxyLevel32,
  33: SUNNYSIDE.seasons.winter.galaxyLevel33,
  34: SUNNYSIDE.seasons.winter.galaxyLevel34,
  35: SUNNYSIDE.seasons.winter.galaxyLevel35,
  36: SUNNYSIDE.seasons.winter.galaxyLevel36,
  37: SUNNYSIDE.seasons.winter.galaxyLevel37,
  38: SUNNYSIDE.seasons.winter.galaxyLevel38,
  39: SUNNYSIDE.seasons.winter.galaxyLevel39,
  40: SUNNYSIDE.seasons.winter.galaxyLevel40,
  41: SUNNYSIDE.seasons.winter.galaxyLevel41,
  42: SUNNYSIDE.seasons.winter.galaxyLevel42,
};

const SPRING_MARBLE_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.spring.marbleLevel1,
  2: SUNNYSIDE.seasons.spring.marbleLevel2,
  3: SUNNYSIDE.seasons.spring.marbleLevel3,
  4: SUNNYSIDE.seasons.spring.marbleLevel4,
  5: SUNNYSIDE.seasons.spring.marbleLevel5,
  6: SUNNYSIDE.seasons.spring.marbleLevel6,
  7: SUNNYSIDE.seasons.spring.marbleLevel7,
  8: SUNNYSIDE.seasons.spring.marbleLevel8,
  9: SUNNYSIDE.seasons.spring.marbleLevel9,
  10: SUNNYSIDE.seasons.spring.marbleLevel10,
  11: SUNNYSIDE.seasons.spring.marbleLevel11,
  12: SUNNYSIDE.seasons.spring.marbleLevel12,
  13: SUNNYSIDE.seasons.spring.marbleLevel13,
  14: SUNNYSIDE.seasons.spring.marbleLevel14,
  15: SUNNYSIDE.seasons.spring.marbleLevel15,
  16: SUNNYSIDE.seasons.spring.marbleLevel16,
  17: SUNNYSIDE.seasons.spring.marbleLevel17,
  18: SUNNYSIDE.seasons.spring.marbleLevel18,
  19: SUNNYSIDE.seasons.spring.marbleLevel19,
  20: SUNNYSIDE.seasons.spring.marbleLevel20,
  21: SUNNYSIDE.seasons.spring.marbleLevel21,
  22: SUNNYSIDE.seasons.spring.marbleLevel22,
  23: SUNNYSIDE.seasons.spring.marbleLevel23,
  24: SUNNYSIDE.seasons.spring.marbleLevel24,
  25: SUNNYSIDE.seasons.spring.marbleLevel25,
  26: SUNNYSIDE.seasons.spring.marbleLevel26,
  27: SUNNYSIDE.seasons.spring.marbleLevel27,
  28: SUNNYSIDE.seasons.spring.marbleLevel28,
  29: SUNNYSIDE.seasons.spring.marbleLevel29,
  30: SUNNYSIDE.seasons.spring.marbleLevel30,
  31: SUNNYSIDE.seasons.spring.marbleLevel31,
  32: SUNNYSIDE.seasons.spring.marbleLevel32,
  33: SUNNYSIDE.seasons.spring.marbleLevel33,
  34: SUNNYSIDE.seasons.spring.marbleLevel34,
  35: SUNNYSIDE.seasons.spring.marbleLevel35,
  36: SUNNYSIDE.seasons.spring.marbleLevel36,
  37: SUNNYSIDE.seasons.spring.marbleLevel37,
  38: SUNNYSIDE.seasons.spring.marbleLevel38,
  39: SUNNYSIDE.seasons.spring.marbleLevel39,
  40: SUNNYSIDE.seasons.spring.marbleLevel40,
  41: SUNNYSIDE.seasons.spring.marbleLevel41,
  42: SUNNYSIDE.seasons.spring.marbleLevel42,
};

const SUMMER_MARBLE_LEVEL_IMAGES = {
  1: SUNNYSIDE.land.marbleLevel1,
  2: SUNNYSIDE.land.marbleLevel2,
  3: SUNNYSIDE.land.marbleLevel3,
  4: SUNNYSIDE.land.marbleLevel4,
  5: SUNNYSIDE.land.marbleLevel5,
  6: SUNNYSIDE.land.marbleLevel6,
  7: SUNNYSIDE.land.marbleLevel7,
  8: SUNNYSIDE.land.marbleLevel8,
  9: SUNNYSIDE.land.marbleLevel9,
  10: SUNNYSIDE.land.marbleLevel10,
  11: SUNNYSIDE.land.marbleLevel11,
  12: SUNNYSIDE.land.marbleLevel12,
  13: SUNNYSIDE.land.marbleLevel13,
  14: SUNNYSIDE.land.marbleLevel14,
  15: SUNNYSIDE.land.marbleLevel15,
  16: SUNNYSIDE.land.marbleLevel16,
  17: SUNNYSIDE.land.marbleLevel17,
  18: SUNNYSIDE.land.marbleLevel18,
  19: SUNNYSIDE.land.marbleLevel19,
  20: SUNNYSIDE.land.marbleLevel20,
  21: SUNNYSIDE.land.marbleLevel21,
  22: SUNNYSIDE.land.marbleLevel22,
  23: SUNNYSIDE.land.marbleLevel23,
  24: SUNNYSIDE.land.marbleLevel24,
  25: SUNNYSIDE.land.marbleLevel25,
  26: SUNNYSIDE.land.marbleLevel26,
  27: SUNNYSIDE.land.marbleLevel27,
  28: SUNNYSIDE.land.marbleLevel28,
  29: SUNNYSIDE.land.marbleLevel29,
  30: SUNNYSIDE.land.marbleLevel30,
  31: SUNNYSIDE.land.marbleLevel31,
  32: SUNNYSIDE.land.marbleLevel32,
  33: SUNNYSIDE.land.marbleLevel33,
  34: SUNNYSIDE.land.marbleLevel34,
  35: SUNNYSIDE.land.marbleLevel35,
  36: SUNNYSIDE.land.marbleLevel36,
  37: SUNNYSIDE.land.marbleLevel37,
  38: SUNNYSIDE.land.marbleLevel38,
  39: SUNNYSIDE.land.marbleLevel39,
  40: SUNNYSIDE.land.marbleLevel40,
  41: SUNNYSIDE.land.marbleLevel41,
  42: SUNNYSIDE.land.marbleLevel42,
};

const AUTUMN_MARBLE_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.autumn.marbleLevel1,
  2: SUNNYSIDE.seasons.autumn.marbleLevel2,
  3: SUNNYSIDE.seasons.autumn.marbleLevel3,
  4: SUNNYSIDE.seasons.autumn.marbleLevel4,
  5: SUNNYSIDE.seasons.autumn.marbleLevel5,
  6: SUNNYSIDE.seasons.autumn.marbleLevel6,
  7: SUNNYSIDE.seasons.autumn.marbleLevel7,
  8: SUNNYSIDE.seasons.autumn.marbleLevel8,
  9: SUNNYSIDE.seasons.autumn.marbleLevel9,
  10: SUNNYSIDE.seasons.autumn.marbleLevel10,
  11: SUNNYSIDE.seasons.autumn.marbleLevel11,
  12: SUNNYSIDE.seasons.autumn.marbleLevel12,
  13: SUNNYSIDE.seasons.autumn.marbleLevel13,
  14: SUNNYSIDE.seasons.autumn.marbleLevel14,
  15: SUNNYSIDE.seasons.autumn.marbleLevel15,
  16: SUNNYSIDE.seasons.autumn.marbleLevel16,
  17: SUNNYSIDE.seasons.autumn.marbleLevel17,
  18: SUNNYSIDE.seasons.autumn.marbleLevel18,
  19: SUNNYSIDE.seasons.autumn.marbleLevel19,
  20: SUNNYSIDE.seasons.autumn.marbleLevel20,
  21: SUNNYSIDE.seasons.autumn.marbleLevel21,
  22: SUNNYSIDE.seasons.autumn.marbleLevel22,
  23: SUNNYSIDE.seasons.autumn.marbleLevel23,
  24: SUNNYSIDE.seasons.autumn.marbleLevel24,
  25: SUNNYSIDE.seasons.autumn.marbleLevel25,
  26: SUNNYSIDE.seasons.autumn.marbleLevel26,
  27: SUNNYSIDE.seasons.autumn.marbleLevel27,
  28: SUNNYSIDE.seasons.autumn.marbleLevel28,
  29: SUNNYSIDE.seasons.autumn.marbleLevel29,
  30: SUNNYSIDE.seasons.autumn.marbleLevel30,
  31: SUNNYSIDE.seasons.autumn.marbleLevel31,
  32: SUNNYSIDE.seasons.autumn.marbleLevel32,
  33: SUNNYSIDE.seasons.autumn.marbleLevel33,
  34: SUNNYSIDE.seasons.autumn.marbleLevel34,
  35: SUNNYSIDE.seasons.autumn.marbleLevel35,
  36: SUNNYSIDE.seasons.autumn.marbleLevel36,
  37: SUNNYSIDE.seasons.autumn.marbleLevel37,
  38: SUNNYSIDE.seasons.autumn.marbleLevel38,
  39: SUNNYSIDE.seasons.autumn.marbleLevel39,
  40: SUNNYSIDE.seasons.autumn.marbleLevel40,
  41: SUNNYSIDE.seasons.autumn.marbleLevel41,
  42: SUNNYSIDE.seasons.autumn.marbleLevel42,
};

const WINTER_MARBLE_LEVEL_IMAGES = {
  1: SUNNYSIDE.seasons.winter.marbleLevel1,
  2: SUNNYSIDE.seasons.winter.marbleLevel2,
  3: SUNNYSIDE.seasons.winter.marbleLevel3,
  4: SUNNYSIDE.seasons.winter.marbleLevel4,
  5: SUNNYSIDE.seasons.winter.marbleLevel5,
  6: SUNNYSIDE.seasons.winter.marbleLevel6,
  7: SUNNYSIDE.seasons.winter.marbleLevel7,
  8: SUNNYSIDE.seasons.winter.marbleLevel8,
  9: SUNNYSIDE.seasons.winter.marbleLevel9,
  10: SUNNYSIDE.seasons.winter.marbleLevel10,
  11: SUNNYSIDE.seasons.winter.marbleLevel11,
  12: SUNNYSIDE.seasons.winter.marbleLevel12,
  13: SUNNYSIDE.seasons.winter.marbleLevel13,
  14: SUNNYSIDE.seasons.winter.marbleLevel14,
  15: SUNNYSIDE.seasons.winter.marbleLevel15,
  16: SUNNYSIDE.seasons.winter.marbleLevel16,
  17: SUNNYSIDE.seasons.winter.marbleLevel17,
  18: SUNNYSIDE.seasons.winter.marbleLevel18,
  19: SUNNYSIDE.seasons.winter.marbleLevel19,
  20: SUNNYSIDE.seasons.winter.marbleLevel20,
  21: SUNNYSIDE.seasons.winter.marbleLevel21,
  22: SUNNYSIDE.seasons.winter.marbleLevel22,
  23: SUNNYSIDE.seasons.winter.marbleLevel23,
  24: SUNNYSIDE.seasons.winter.marbleLevel24,
  25: SUNNYSIDE.seasons.winter.marbleLevel25,
  26: SUNNYSIDE.seasons.winter.marbleLevel26,
  27: SUNNYSIDE.seasons.winter.marbleLevel27,
  28: SUNNYSIDE.seasons.winter.marbleLevel28,
  29: SUNNYSIDE.seasons.winter.marbleLevel29,
  30: SUNNYSIDE.seasons.winter.marbleLevel30,
  31: SUNNYSIDE.seasons.winter.marbleLevel31,
  32: SUNNYSIDE.seasons.winter.marbleLevel32,
  33: SUNNYSIDE.seasons.winter.marbleLevel33,
  34: SUNNYSIDE.seasons.winter.marbleLevel34,
  35: SUNNYSIDE.seasons.winter.marbleLevel35,
  36: SUNNYSIDE.seasons.winter.marbleLevel36,
  37: SUNNYSIDE.seasons.winter.marbleLevel37,
  38: SUNNYSIDE.seasons.winter.marbleLevel38,
  39: SUNNYSIDE.seasons.winter.marbleLevel39,
  40: SUNNYSIDE.seasons.winter.marbleLevel40,
  41: SUNNYSIDE.seasons.winter.marbleLevel41,
  42: SUNNYSIDE.seasons.winter.marbleLevel42,
};

const LEVEL_IMAGES: Record<
  LandBiomeName,
  Record<TemperateSeasonName, Record<number, string>>
> = {
  "Basic Biome": {
    spring: SPRING_BASIC_LEVEL_IMAGES,
    summer: SUMMER_BASIC_LEVEL_IMAGES,
    autumn: AUTUMN_BASIC_LEVEL_IMAGES,
    winter: WINTER_BASIC_LEVEL_IMAGES,
  },
  "Spring Biome": {
    spring: SPRING_BASIC_LEVEL_IMAGES,
    summer: SUMMER_BASIC_LEVEL_IMAGES,
    autumn: AUTUMN_BASIC_LEVEL_IMAGES,
    winter: WINTER_BASIC_LEVEL_IMAGES,
  },
  "Desert Biome": {
    spring: SPRING_DESERT_LEVEL_IMAGES,
    summer: SUMMER_DESERT_LEVEL_IMAGES,
    autumn: AUTUMN_DESERT_LEVEL_IMAGES,
    winter: WINTER_DESERT_LEVEL_IMAGES,
  },
  "Volcano Biome": {
    spring: SPRING_VOLCANO_LEVEL_IMAGES,
    summer: SUMMER_VOLCANO_LEVEL_IMAGES,
    autumn: AUTUMN_VOLCANO_LEVEL_IMAGES,
    winter: WINTER_VOLCANO_LEVEL_IMAGES,
  },
  "Swamp Biome": {
    spring: SPRING_SWAMP_LEVEL_IMAGES,
    summer: SUMMER_SWAMP_LEVEL_IMAGES,
    autumn: AUTUMN_SWAMP_LEVEL_IMAGES,
    winter: WINTER_SWAMP_LEVEL_IMAGES,
  },
  "Spooky Biome": {
    spring: SPRING_SPOOKY_LEVEL_IMAGES,
    summer: SUMMER_SPOOKY_LEVEL_IMAGES,
    autumn: AUTUMN_SPOOKY_LEVEL_IMAGES,
    winter: WINTER_SPOOKY_LEVEL_IMAGES,
  },
  "Crystal Biome": {
    spring: SPRING_CRYSTAL_LEVEL_IMAGES,
    summer: SUMMER_CRYSTAL_LEVEL_IMAGES,
    autumn: AUTUMN_CRYSTAL_LEVEL_IMAGES,
    winter: WINTER_CRYSTAL_LEVEL_IMAGES,
  },
  "Galaxy Biome": {
    spring: SPRING_GALAXY_LEVEL_IMAGES,
    summer: SUMMER_GALAXY_LEVEL_IMAGES,
    autumn: AUTUMN_GALAXY_LEVEL_IMAGES,
    winter: WINTER_GALAXY_LEVEL_IMAGES,
  },
  "Marble Age Biome": {
    spring: SPRING_MARBLE_LEVEL_IMAGES,
    summer: SUMMER_MARBLE_LEVEL_IMAGES,
    autumn: AUTUMN_MARBLE_LEVEL_IMAGES,
    winter: WINTER_MARBLE_LEVEL_IMAGES,
  },
};

/** Highest land-image level shipped — counts above this reuse the level-42 art. */
export const MAX_LAND_IMAGE_LEVEL = 42;

/**
 * The composite land sprite for an island at a given expansion count + season.
 * Each image is 16px/tile with the world origin (0,0) at its exact centre, so a
 * consumer can overlay world-coordinate items on it with an origin-centred map.
 */
export const getLandImage = (
  island: GameState["island"],
  expandedCount: number,
  season: TemperateSeasonName,
): string => {
  const biome = getCurrentBiome(island);
  const imageLevel = Math.min(expandedCount, MAX_LAND_IMAGE_LEVEL);
  return LEVEL_IMAGES[biome][season][imageLevel];
};

interface Props {
  island: GameState["island"];
  expandedCount: number;
  season: TemperateSeasonName;
}

export const LandBase: React.FC<Props> = ({
  island,
  expandedCount,
  season,
}) => {
  // Centred by the wrapper in Land.tsx and rendered at the game's natural scale
  // (PIXEL_SCALE, via NaturalImage) — see getLandImage for the 16px/tile origin.
  const src = getLandImage(island, expandedCount, season);

  return (
    <NaturalImage
      id={Section.GenesisBlock}
      src={src}
      alt="land"
      className="-z-10"
    />
  );
};
