import { makeGame } from "./transforms";

// export const OFFLINE_FARM = INITIAL_FARM;
export const OFFLINE_FARM = makeGame({
  coins: 14391.400000000001,
  balance: "128742.068375",
  previousBalance: "129316.068375",
  inventory: {
    "Sunflower Seed": "141",
    "Potato Seed": "204",
    "Pumpkin Seed": "160",
    "Carrot Seed": "100",
    "Cabbage Seed": "99",
    "Beetroot Seed": "80",
    "Cauliflower Seed": "81",
    "Parsnip Seed": "70",
    "Radish Seed": "44",
    "Wheat Seed": "46",
    "Kale Seed": "70",
    "Apple Seed": "20",
    "Blueberry Seed": "22",
    "Orange Seed": "20",
    "Magic Bean": "2",
    Sunflower: "10053.3335",
    Potato: "10860.88",
    Pumpkin: "11022",
    Carrot: "10643",
    Beetroot: "11012",
    Cauliflower: "10899",
    Parsnip: "11000",
    Radish: "10944",
    Wheat: "11911",
    Kale: "960",
    Apple: "18",
    Blueberry: "1.3",
    Axe: "231",
    Pickaxe: "61",
    "Stone Pickaxe": "2",
    "Iron Pickaxe": "6",
    "Rusty Shovel": "108",
    Shovel: "1",
    "Sand Shovel": "3",
    "Potato Statue": "1",
    "Farm Cat": "1",
    "Farm Dog": "1",
    Gnome: "1",
    "Chicken Coop": "1",
    "Sunflower Tombstone": "1",
    "Sunflower Rock": "1",
    "Goblin Crown": "1",
    Fountain: "1",
    "Woody the Beaver": "1",
    "Mysterious Parsnip": "1",
    "Carrot Sword": "1",
    Nancy: "1",
    "Nyon Statue": "1",
    "Farmer Bath": "1",
    "Homeless Tent": "1",
    "Mysterious Head": "1",
    "Golden Bonsai": "1",
    "Rock Golem": "1",
    "Tunnel Mole": "1",
    "Rocky the Mole": "1",
    Nugget: "1",
    "Wicker Man": "1",
    "Victoria Sisters": "1",
    "Peeled Potato": "2",
    "Cabbage Girl": "1",
    "Wood Nymph Wendy": "1",
    "Stellar Sunflower": "3",
    "Potent Potato": "4",
    "Radical Radish": "2",
    "Immortal Pear": "2",
    "Lady Bug": "2",
    "Squirrel Monkey": "1",
    "Black Bearry": "1",
    "Ayam Cemani": "1",
    "Tiki Totem": "1",
    "Lunar Calendar": "1",
    "Treasure Map": "1",
    "Heart of Davy Jones": "2",
    "Heart Balloons": "2",
    Flamingo: "2",
    "Blossom Tree": "1",
    "Iron Idol": "1",
    Karkinos: "1",
    "Mushroom House": "1",
    "Purple Trail": "1",
    Obie: "1",
    Maximus: "1",
    "Genie Lamp": "1",
    Hoot: "1",
    "Basic Scarecrow": "1",
    "Emerald Turtle": "1",
    "Sir Goldensnout": "1",
    "Pumpkin Soup": "541",
    "Roasted Cauliflower": "500",
    Sauerkraut: "500",
    "Radish Pie": "500",
    "Sunflower Cake": "595",
    "Potato Cake": "499",
    "Pumpkin Cake": "499",
    "Carrot Cake": "500",
    "Cabbage Cake": "497",
    "Beetroot Cake": "497",
    "Cauliflower Cake": "499",
    "Parsnip Cake": "599",
    "Radish Cake": "21115",
    "Wheat Cake": "500",
    "Boiled Eggs": "500",
    "Bumpkin Broth": "499",
    "Bumpkin Salad": "500",
    "Goblin's Treat": "499",
    "Mashed Potato": "487",
    "Cauliflower Burger": "499",
    "Club Sandwich": "502",
    "Roast Veggies": "598",
    Pancakes: "500",
    "Apple Pie": "500",
    "Blueberry Jam": "499",
    "Fermented Carrots": "500",
    "Honey Cake": "490",
    "Kale & Mushroom Pie": "500",
    "Kale Stew": "500",
    "Mushroom Jacket Potatoes": "500",
    "Mushroom Soup": "600",
    "Orange Cake": "500",
    "Sunflower Crunch": "500",
    "Reindeer Carrot": "5533",
    "Apple Juice": "499",
    "Orange Juice": "499",
    "Purple Smoothie": "498",
    "Power Smoothie": "500",
    "Bumpkin Detox": "499",
    "Pirate Cake": "500",
    "Bumpkin Roast": "489",
    "Goblin Brunch": "500",
    "Fruit Salad": "480",
    "Kale Omelette": "490",
    "Cabbers n Mash": "500",
    "Fancy Fries": "500",
    Wood: "17006.6",
    Stone: "21533",
    Iron: "22004",
    Gold: "20812.999999999999999",
    Egg: "722",
    Chicken: "10",
    "Wild Mushroom": "36",
    "Magic Mushroom": "20",
    Tree: "17",
    "Stone Rock": "15",
    "Iron Rock": "8",
    "Gold Rock": "5",
    "Crop Plot": "77",
    "Fruit Patch": "6",
    "Basic Land": "21",
    "Beta Pass": "1",
    "Solar Flare Ticket": "2332",
    "Sunflower Supporter": "2",
    "Witches' Eve Banner": "2",
    "Crow Feather": "64",
    "Gold Pass": "1",
    Mark: "943750",
    "Pharaoh's Treasure Banner": "1",
    "Amber Fossil": "1",
    Gem: "4970",
    "Human War Banner": "1",
    "Golden Crop": "1",
    "Wooden Compass": "3",
    "Prize Ticket": "4",
    "Goblin Faction Banner": "1",
    Market: "1",
    "Fire Pit": "3",
    Workbench: "1",
    "Water Well": "4",
    "Hen House": "2",
    Bakery: "1",
    Kitchen: "1",
    Deli: "1",
    "Smoothie Shack": "1",
    "White Tulips": "31",
    "Potted Sunflower": "9",
    Cactus: "4",
    "Basic Bear": "11",
    "Potted Potato": "10",
    "Potted Pumpkin": "12",
    "Christmas Bear": "1",
    "Christmas Snow Globe": "1",
    "Collectible Bear": "1",
    "Sunflower Coin": "1",
    "Skeleton King Staff": "1",
    "Lifeguard Bear": "4",
    "Golden Bear Head": "1",
    Galleon: "1",
    "Human Bear": "2",
    "Palm Tree": "1",
    "Beach Ball": "1",
    "Beta Bear": "1",
    "Betty Lantern": "1",
    "Bumpkin Lantern": "1",
    "Dawn Flower": "1",
    Starfish: "1",
    "Sea Cucumber": "3",
    Crab: "1",
    Rug: "1",
    Wardrobe: "1",
    "Laurie the Chuckle Crow": "1",
    "Compost Bin": "1",
    "Fishing Lure": "3",
    "Kernel Blend": "16",
    Barn: "1",
    Milk: "3",
    "Crafting Box": "1",
    "Chef Bear": "1",
    "Angel Bear": "1",
    "Devil Bear": "1",
    "Brilliant Bear": "1",
    "Badass Bear": "1",
    "Classy Bear": "1",
    "Rainbow Artist Bear": "1",
    "Easter Bear": "1",
    "King of Bears": "1",
    "Cow Skull": "45",
    "Cow Scratcher": "1",
    "Spinning Wheel": "1",
    "Treasure Key": "1",
    "Sleepy Rug": "1",
    Meteorite: "1",
    Horseshoe: "500",
    "Rare Key": "1",
    "Mechanical Bull": "1",
  },
  previousInventory: {
    "Sunflower Seed": "141",
    "Potato Seed": "204",
    "Pumpkin Seed": "160",
    "Carrot Seed": "100",
    "Cabbage Seed": "99",
    "Beetroot Seed": "80",
    "Cauliflower Seed": "81",
    "Parsnip Seed": "70",
    "Radish Seed": "44",
    "Wheat Seed": "46",
    "Kale Seed": "40",
    "Apple Seed": "20",
    "Blueberry Seed": "22",
    "Orange Seed": "20",
    "Magic Bean": "2",
    Sunflower: "10056.3335",
    Potato: "10859.88",
    Pumpkin: "11052",
    Carrot: "10645",
    Cabbage: "11009",
    Beetroot: "11012",
    Cauliflower: "10899",
    Parsnip: "11000",
    Radish: "11004",
    Wheat: "12000",
    Kale: "1000",
    Apple: "18",
    Blueberry: "1.3",
    Axe: "234",
    Pickaxe: "61",
    "Stone Pickaxe": "2",
    "Iron Pickaxe": "6",
    "Rusty Shovel": "108",
    Shovel: "1",
    "Sand Shovel": "3",
    "Potato Statue": "1",
    "Farm Cat": "1",
    "Farm Dog": "1",
    Gnome: "1",
    "Chicken Coop": "1",
    "Sunflower Tombstone": "1",
    "Sunflower Rock": "1",
    "Goblin Crown": "1",
    Fountain: "1",
    "Woody the Beaver": "1",
    "Mysterious Parsnip": "1",
    "Carrot Sword": "1",
    Nancy: "1",
    "Nyon Statue": "1",
    "Farmer Bath": "1",
    "Homeless Tent": "1",
    "Mysterious Head": "1",
    "Golden Bonsai": "1",
    "Rock Golem": "1",
    "Tunnel Mole": "1",
    "Rocky the Mole": "1",
    Nugget: "1",
    "Wicker Man": "1",
    "Victoria Sisters": "1",
    "Peeled Potato": "2",
    "Cabbage Girl": "1",
    "Wood Nymph Wendy": "1",
    "Stellar Sunflower": "3",
    "Potent Potato": "4",
    "Radical Radish": "2",
    "Immortal Pear": "2",
    "Lady Bug": "2",
    "Squirrel Monkey": "1",
    "Black Bearry": "1",
    "Ayam Cemani": "1",
    "Tiki Totem": "1",
    "Lunar Calendar": "1",
    "Treasure Map": "1",
    "Heart of Davy Jones": "2",
    "Heart Balloons": "2",
    Flamingo: "2",
    "Blossom Tree": "1",
    "Iron Idol": "1",
    Karkinos: "1",
    "Mushroom House": "1",
    "Purple Trail": "1",
    Obie: "1",
    Maximus: "1",
    "Genie Lamp": "1",
    Hoot: "1",
    "Basic Scarecrow": "1",
    "Emerald Turtle": "1",
    "Sir Goldensnout": "1",
    "Pumpkin Soup": "541",
    "Roasted Cauliflower": "500",
    Sauerkraut: "500",
    "Radish Pie": "500",
    "Sunflower Cake": "595",
    "Potato Cake": "499",
    "Pumpkin Cake": "499",
    "Carrot Cake": "500",
    "Cabbage Cake": "497",
    "Beetroot Cake": "497",
    "Cauliflower Cake": "499",
    "Parsnip Cake": "599",
    "Radish Cake": "21115",
    "Wheat Cake": "500",
    "Boiled Eggs": "500",
    "Bumpkin Broth": "499",
    "Bumpkin Salad": "500",
    "Goblin's Treat": "499",
    "Mashed Potato": "487",
    "Cauliflower Burger": "499",
    "Club Sandwich": "502",
    "Roast Veggies": "598",
    Pancakes: "500",
    "Apple Pie": "500",
    "Blueberry Jam": "499",
    "Fermented Carrots": "500",
    "Honey Cake": "490",
    "Kale & Mushroom Pie": "500",
    "Kale Stew": "500",
    "Mushroom Jacket Potatoes": "500",
    "Mushroom Soup": "600",
    "Orange Cake": "500",
    "Sunflower Crunch": "500",
    "Reindeer Carrot": "5533",
    "Apple Juice": "499",
    "Orange Juice": "499",
    "Purple Smoothie": "498",
    "Power Smoothie": "500",
    "Bumpkin Detox": "499",
    "Pirate Cake": "500",
    "Bumpkin Roast": "489",
    "Goblin Brunch": "500",
    "Fruit Salad": "480",
    "Kale Omelette": "490",
    "Cabbers n Mash": "500",
    "Fancy Fries": "500",
    Wood: "17356.6",
    Stone: "21543",
    Iron: "22014",
    Gold: "20822.999999999999999",
    Egg: "719",
    Chicken: "10",
    "Wild Mushroom": "31",
    "Magic Mushroom": "19",
    Tree: "17",
    "Stone Rock": "15",
    "Iron Rock": "8",
    "Gold Rock": "5",
    "Crop Plot": "77",
    "Fruit Patch": "6",
    "Basic Land": "21",
    "Beta Pass": "1",
    "Block Buck": "2",
    "Solar Flare Ticket": "2332",
    "Sunflower Supporter": "2",
    "Witches' Eve Banner": "2",
    "Crow Feather": "64",
    "Gold Pass": "1",
    Mark: "50",
    "Pharaoh's Treasure Banner": "1",
    "Amber Fossil": "1",
    Gem: "950",
    "Human War Banner": "1",
    "Golden Crop": "1",
    "Wooden Compass": "3",
    "Prize Ticket": "4",
    "Goblin Faction Banner": "1",
    Market: "1",
    "Fire Pit": "3",
    Workbench: "1",
    "Water Well": "4",
    "Hen House": "2",
    Bakery: "1",
    Kitchen: "1",
    Deli: "1",
    "Smoothie Shack": "1",
    "White Tulips": "31",
    "Potted Sunflower": "9",
    Cactus: "4",
    "Basic Bear": "11",
    "Potted Potato": "10",
    "Potted Pumpkin": "12",
    "Christmas Bear": "1",
    "Christmas Snow Globe": "1",
    "Collectible Bear": "1",
    "Sunflower Coin": "1",
    "Skeleton King Staff": "1",
    "Lifeguard Bear": "5",
    "Golden Bear Head": "1",
    "Goblin Bear": "1",
    Galleon: "1",
    "Human Bear": "2",
    "Palm Tree": "1",
    "Beach Ball": "1",
    "Beta Bear": "1",
    "Betty Lantern": "1",
    "Bumpkin Lantern": "1",
    "Dawn Flower": "1",
    Starfish: "1",
    "Sea Cucumber": "3",
    Crab: "1",
    Rug: "1",
    Wardrobe: "1",
  },
  shipments: {},
  choreBoard: {
    chores: {
      garth: {
        name: "Craft 3 Pickaxes",
        reward: {
          items: {},
          coins: 100,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      grimbly: {
        name: "Cook 3 Bumpkin ganoush",
        reward: {
          items: {},
          coins: 100,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      miranda: {
        name: "Grow 3 Red Pansy",
        reward: {
          items: {},
          coins: 100,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      corale: {
        name: "Eat 5 Anchovies",
        reward: {
          items: {},
          coins: 100,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      "pumpkin' pete": {
        name: "Eat 10 Pumpkin Soup",
        reward: {
          items: {},
          coins: 150,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      betty: {
        name: "Harvest 10 Cauliflowers",
        reward: {
          items: {},
          coins: 150,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      peggy: {
        name: "Harvest 75 Carrots",
        reward: {
          items: {},
          coins: 150,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      finn: {
        name: "Cook 5 Gumbo",
        reward: {
          items: {},
          coins: 150,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      timmy: {
        name: "Pick 30 Apples",
        reward: {
          items: {},
          coins: 200,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      raven: {
        name: "Harvest 120 Eggplant",
        reward: {
          items: {},
          coins: 200,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      bert: {
        name: "Chop 70 Trees",
        reward: {
          items: {},
          coins: 200,
        },
        initialProgress: 6,
        startedAt: 1730690671478,
      },
      victoria: {
        name: "Grow 5 Red Balloon Flower",
        reward: {
          items: {},
          coins: 200,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      birdie: {
        name: "Collect 10 Eggs",
        reward: {
          items: {},
          coins: 200,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      "old salty": {
        name: "Drink 20 Orange Juice",
        reward: {
          items: {},
          coins: 250,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      chase: {
        name: "Collect 60 Eggs",
        reward: {
          items: {},
          coins: 250,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      blacksmith: {
        name: "Mine 100 Iron",
        reward: {
          items: {},
          coins: 250,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      finley: {
        name: "Cook 12 Chowder",
        reward: {
          items: {
            Gem: 10,
          },
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      guria: {
        name: "Grow 6 Red Balloon Flower",
        reward: {
          items: {
            Gem: 10,
          },
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      petro: {
        name: "Harvest 10 Rice",
        reward: {
          items: {
            Gem: 5,
          },
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      tango: {
        name: "Cook 35 Fruit Salad",
        reward: {
          items: {
            "Treasure Key": 1,
          },
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
      cornwell: {
        name: "Harvest 300 Eggplants",
        reward: {
          items: {},
          coins: 400,
        },
        initialProgress: 0,
        startedAt: 1730690671478,
      },
    },
  },
  rewards: {
    challenges: {
      completed: 0,
      active: {
        index: 0,
        startCount: 0,
      },
    },
  },
  bumpkin: {
    id: 1,
    tokenUri: "1_v1_32_1_5_13_18_22_23",
    equipped: {
      background: "Farm Background",
      body: "Beige Farmer Potion",
      hair: "Basic Hair",
      shoes: "Black Farmer Boots",
      pants: "Farmer Overalls",
      tool: "Farmer Pitchfork",
      shirt: "Cowboy Shirt",
      hat: "Cowboy Hat",
    },
    experience: 26700,
    skills: {},
    achievements: {},
    activity: {
      "Club Sandwich Fed": 10,
      "Bumpkin Roast Fed": 10,
      "Goblin Helmet Bought": 1,
      "Tree Chopped": 6,
      "Potato Harvested": 3,
      "Coins Spent": 210.1,
      "Sunflower Seed Bought": 10,
      "Sunflower Planted": 3,
      "Sunflower Harvested": 2,
      "Coins Earned": 16664.5,
      "Block Buck Sold": 2,
      "Kale Seed Bought": 30,
      "Cabbage Sold": 11009,
      "Laurie the Chuckle Crow Crafted": 1,
      "Building Constructed": 3,
      "Kernel Blend Mixed": 69,
      "Cow Fed": 1,
      "Collectible Placed": 1,
    },
    updatedAt: 1722908207844,
  },
  experiments: [],
  wardrobe: {
    "Beige Farmer Potion": 2,
    "Dark Brown Farmer Potion": 2,
    "Light Brown Farmer Potion": 3,
    "Goblin Potion": 2,
    "Basic Hair": 3,
    "Rancher Hair": 1,
    "Explorer Hair": 1,
    "Red Farmer Shirt": 2,
    "Yellow Farmer Shirt": 1,
    "Blue Farmer Shirt": 3,
    "Chef Apron": 1,
    "Warrior Shirt": 1,
    "Farmer Overalls": 1,
    "Lumberjack Overalls": 1,
    "Farmer Pants": 1,
    "Warrior Pants": 1,
    "Black Farmer Boots": 3,
    "Farmer Pitchfork": 3,
    "Farmer Hat": 1,
    "Chef Hat": 1,
    "Warrior Helmet": 1,
    "Sunflower Amulet": 1,
    "Carrot Amulet": 1,
    "Beetroot Amulet": 1,
    "Green Amulet": 1,
    "Sunflower Shield": 1,
    "Farm Background": 3,
    "Fancy Top": 1,
    "Brown Boots": 2,
    "Brown Suspenders": 2,
    "Fancy Pants": 2,
    "Maiden Skirt": 2,
    "Maiden Top": 2,
    "Peasant Skirt": 1,
    "SFL T-Shirt": 1,
    "Yellow Boots": 2,
    "Buzz Cut": 1,
    "Parlour Hair": 1,
    Axe: 2,
    Sword: 2,
    "Blue Suspenders": 2,
    "Forest Background": 4,
    "Seashore Background": 1,
    Blondie: 1,
    "Brown Long Hair": 2,
    "Sun Spots": 2,
    "White Long Hair": 1,
    "Cemetery Background": 1,
    "Teal Mohawk": 1,
    "Space Background": 1,
    Parsnip: 1,
    "Jail Background": 1,
    "Artist Scarf": 1,
    "Project Dignity Hoodie": 1,
    "Developer Hoodie": 1,
    "Blacksmith Hair": 1,
    Hammer: 1,
    "Bumpkin Boots": 1,
    "Fire Shirt": 1,
    "Red Long Hair": 1,
    "Snowman Onesie": 1,
    "Reindeer Suit": 2,
    "Shark Onesie": 2,
    "Christmas Background": 1,
    "Devil Wings": 1,
    "Angel Wings": 1,
    "Fire Hair": 1,
    "Luscious Hair": 1,
    "Ancient War Hammer": 1,
    "Ancient Goblin Sword": 1,
    "Mountain View Background": 1,
    "Skull Hat": 1,
    "Reindeer Antlers": 1,
    "Santa Hat": 1,
    "Pineapple Shirt": 1,
    "China Town Background": 1,
    "Lion Dance Mask": 1,
    "Fruit Picker Shirt": 1,
    "Fruit Picker Apron": 1,
    "Fruit Bowl": 1,
    "Striped Blue Shirt": 1,
    "Peg Leg": 1,
    "Pirate Potion": 1,
    "Pirate Hat": 2,
    "Pirate General Coat": 1,
    "Pirate Pants": 1,
    "Pirate Leather Polo": 1,
    "Crab Claw": 1,
    "Pirate Scimitar": 1,
    "Cupid Hair": 1,
    "Cupid Dress": 1,
    "Cupid Sandals": 1,
    "Love Quiver": 1,
    "SFL Office Background": 1,
    "Bumpkin Puppet": 1,
    "Goblin Puppet": 1,
    "Hawaiian Shirt": 1,
    "Bear Onesie": 1,
    "Frog Onesie": 1,
    "Tiger Onesie": 1,
    "Beach Sarong": 1,
    "Lifeguard Hat": 1,
    "Lifeguard Pants": 1,
    "Lifeguard Shirt": 1,
    "Sleeping Otter": 1,
    "Tropical Sarong": 1,
    "Sequence Hat": 1,
    "Sequence Shirt": 1,
    "St Patricks Hat": 2,
    "Bunny Onesie": 1,
    "Light Brown Worried Farmer Potion": 1,
    "Polkastarter Shirt": 1,
    "Beach Trunks": 1,
    "Club Polo": 1,
    "Dawn Breaker Background": 1,
    "Dawn Lamp": 1,
    "Eggplant Onesie": 1,
    "Fox Hat": 2,
    "Grave Diggers Shovel": 1,
    "Infected Potion": 1,
    "Mushroom Hat": 2,
    "Mushroom Lamp": 1,
    "Mushroom Lights Background": 1,
    "Mushroom Pants": 1,
    "Mushroom Shield": 1,
    "Mushroom Shoes": 1,
    "Rash Vest": 1,
    "Squid Hat": 1,
    "Striped Red Shirt": 1,
    "Striped Yellow Shirt": 1,
    "Summer Top": 2,
    "Sunburst Potion": 1,
    "Water Gun": 1,
    "Wavy Pants": 1,
    "White Turtle Neck": 1,
    "Trial Tee": 1,
    "Auction Megaphone": 1,
    "Auctioneer Slacks": 1,
    "Bidder's Brocade": 1,
    "Harry's Hat": 2,
    "Leather Shoes": 1,
    "Tangerine Hair": 2,
    "Straw Hat": 2,
    "Traveller's Backpack": 1,
    "Traveller's Pants": 1,
    "Traveller's Shirt": 1,
    "Witching Wardrobe": 1,
    "Witch's Broom": 1,
    "Infernal Bumpkin Potion": 1,
    "Infernal Goblin Potion": 1,
    "Imp Costume": 1,
    "Ox Costume": 2,
    "Luna's Hat": 1,
    "Infernal Pitchfork": 1,
    "Infernal Horns": 1,
    Cattlegrim: 1,
    "Crumple Crown": 1,
    "Merch Bucket Hat": 2,
    "Merch Coffee Mug": 2,
    "Dawn Breaker Tee": 2,
    "Merch Tee": 2,
    "Merch Hoodie": 2,
    "Birthday Hat": 2,
    "Double Harvest Cap": 2,
    "Streamer Helmet": 2,
    "Corn Onesie": 2,
    "Crow Wings": 2,
    "Witches' Eve Tee": 2,
    "Wise Beard": 2,
    "Pumpkin Hat": 2,
    "Wise Book": 2,
    "Wise Hair": 2,
    "Wise Robes": 2,
    "Wise Slacks": 2,
    "Wise Staff": 2,
    "Greyed Glory": 2,
    "Tattered Jacket": 2,
    "Hoary Chin": 2,
    "Tattered Slacks": 2,
    "Old Shoes": 2,
    "Bat Wings": 2,
    "Gothic Twilight": 2,
    "Dark Enchantment Gown": 2,
    "Goth Hair": 2,
    "Pale Potion": 2,
    "Stretched Jeans": 2,
    "Skull Shirt": 2,
    "Victorian Hat": 2,
    "Boater Hat": 3,
    "Antique Dress": 2,
    "Crimson Skirt": 2,
    "Chic Gala Blouse": 2,
    "Ash Ponytail": 2,
    "Pink Ponytail": 2,
    "Silver Streaks": 2,
    "Brown Rancher Hair": 2,
    "Parsnip Horns": 2,
    "Potato Suit": 2,
    "Whale Hat": 2,
    "Pumpkin Shirt": 2,
    Halo: 2,
    Kama: 2,
    "Grey Merch Hoodie": 1,
    "Unicorn Horn": 1,
    "Desert Background": 1,
    "Cowgirl Skirt": 1,
    "Cowboy Hat": 1,
    "Cowboy Shirt": 1,
    "Dream Scarf": 1,
    "Cowboy Trouser": 1,
    "Milk Apron": 1,
  },
  previousWardrobe: {
    "Beige Farmer Potion": 2,
    "Dark Brown Farmer Potion": 2,
    "Light Brown Farmer Potion": 3,
    "Goblin Potion": 2,
    "Basic Hair": 3,
    "Rancher Hair": 1,
    "Explorer Hair": 1,
    "Red Farmer Shirt": 2,
    "Yellow Farmer Shirt": 1,
    "Blue Farmer Shirt": 3,
    "Chef Apron": 1,
    "Warrior Shirt": 1,
    "Farmer Overalls": 1,
    "Lumberjack Overalls": 1,
    "Farmer Pants": 1,
    "Warrior Pants": 1,
    "Black Farmer Boots": 3,
    "Farmer Pitchfork": 3,
    "Farmer Hat": 1,
    "Chef Hat": 1,
    "Warrior Helmet": 1,
    "Sunflower Amulet": 1,
    "Carrot Amulet": 1,
    "Beetroot Amulet": 1,
    "Green Amulet": 1,
    "Sunflower Shield": 1,
    "Farm Background": 3,
    "Fancy Top": 1,
    "Brown Boots": 2,
    "Brown Suspenders": 2,
    "Fancy Pants": 2,
    "Maiden Skirt": 2,
    "Maiden Top": 2,
    "Peasant Skirt": 1,
    "SFL T-Shirt": 1,
    "Yellow Boots": 2,
    "Buzz Cut": 1,
    "Parlour Hair": 1,
    Axe: 2,
    Sword: 2,
    "Blue Suspenders": 2,
    "Forest Background": 4,
    "Seashore Background": 1,
    Blondie: 1,
    "Brown Long Hair": 2,
    "Sun Spots": 2,
    "White Long Hair": 1,
    "Cemetery Background": 1,
    "Teal Mohawk": 1,
    "Space Background": 1,
    Parsnip: 1,
    "Jail Background": 1,
    "Artist Scarf": 1,
    "Project Dignity Hoodie": 1,
    "Developer Hoodie": 1,
    "Blacksmith Hair": 1,
    Hammer: 1,
    "Bumpkin Boots": 1,
    "Fire Shirt": 1,
    "Red Long Hair": 1,
    "Snowman Onesie": 1,
    "Reindeer Suit": 2,
    "Shark Onesie": 2,
    "Christmas Background": 1,
    "Devil Wings": 1,
    "Angel Wings": 1,
    "Fire Hair": 1,
    "Luscious Hair": 1,
    "Ancient War Hammer": 1,
    "Ancient Goblin Sword": 1,
    "Mountain View Background": 1,
    "Skull Hat": 1,
    "Reindeer Antlers": 1,
    "Santa Hat": 1,
    "Pineapple Shirt": 1,
    "China Town Background": 1,
    "Lion Dance Mask": 1,
    "Fruit Picker Shirt": 1,
    "Fruit Picker Apron": 1,
    "Fruit Bowl": 1,
    "Striped Blue Shirt": 1,
    "Peg Leg": 1,
    "Pirate Potion": 1,
    "Pirate Hat": 2,
    "Pirate General Coat": 1,
    "Pirate Pants": 1,
    "Pirate Leather Polo": 1,
    "Crab Claw": 1,
    "Pirate Scimitar": 1,
    "Cupid Hair": 1,
    "Cupid Dress": 1,
    "Cupid Sandals": 1,
    "Love Quiver": 1,
    "SFL Office Background": 1,
    "Bumpkin Puppet": 1,
    "Goblin Puppet": 1,
    "Hawaiian Shirt": 1,
    "Bear Onesie": 1,
    "Frog Onesie": 1,
    "Tiger Onesie": 1,
    "Beach Sarong": 1,
    "Lifeguard Hat": 1,
    "Lifeguard Pants": 1,
    "Lifeguard Shirt": 1,
    "Sleeping Otter": 1,
    "Tropical Sarong": 1,
    "Sequence Hat": 1,
    "Sequence Shirt": 1,
    "St Patricks Hat": 2,
    "Bunny Onesie": 1,
    "Light Brown Worried Farmer Potion": 1,
    "Polkastarter Shirt": 1,
    "Beach Trunks": 1,
    "Club Polo": 1,
    "Dawn Breaker Background": 1,
    "Dawn Lamp": 1,
    "Eggplant Onesie": 1,
    "Fox Hat": 2,
    "Grave Diggers Shovel": 1,
    "Infected Potion": 1,
    "Mushroom Hat": 2,
    "Mushroom Lamp": 1,
    "Mushroom Lights Background": 1,
    "Mushroom Pants": 1,
    "Mushroom Shield": 1,
    "Mushroom Shoes": 1,
    "Rash Vest": 1,
    "Squid Hat": 1,
    "Striped Red Shirt": 1,
    "Striped Yellow Shirt": 1,
    "Summer Top": 2,
    "Sunburst Potion": 1,
    "Water Gun": 1,
    "Wavy Pants": 1,
    "White Turtle Neck": 1,
    "Trial Tee": 1,
    "Auction Megaphone": 1,
    "Auctioneer Slacks": 1,
    "Bidder's Brocade": 1,
    "Harry's Hat": 2,
    "Leather Shoes": 1,
    "Tangerine Hair": 2,
    "Straw Hat": 2,
    "Traveller's Backpack": 1,
    "Traveller's Pants": 1,
    "Traveller's Shirt": 1,
    "Witching Wardrobe": 1,
    "Witch's Broom": 1,
    "Infernal Bumpkin Potion": 1,
    "Infernal Goblin Potion": 1,
    "Imp Costume": 1,
    "Ox Costume": 2,
    "Luna's Hat": 1,
    "Infernal Pitchfork": 1,
    "Infernal Horns": 1,
    Cattlegrim: 1,
    "Crumple Crown": 1,
    "Merch Bucket Hat": 2,
    "Merch Coffee Mug": 2,
    "Dawn Breaker Tee": 2,
    "Merch Tee": 2,
    "Merch Hoodie": 2,
    "Birthday Hat": 2,
    "Double Harvest Cap": 2,
    "Streamer Helmet": 2,
    "Corn Onesie": 2,
    "Crow Wings": 2,
    "Witches' Eve Tee": 2,
    "Wise Beard": 2,
    "Pumpkin Hat": 2,
    "Wise Book": 2,
    "Wise Hair": 2,
    "Wise Robes": 2,
    "Wise Slacks": 2,
    "Wise Staff": 2,
    "Greyed Glory": 2,
    "Tattered Jacket": 2,
    "Hoary Chin": 2,
    "Tattered Slacks": 2,
    "Old Shoes": 2,
    "Bat Wings": 2,
    "Gothic Twilight": 2,
    "Dark Enchantment Gown": 2,
    "Goth Hair": 2,
    "Pale Potion": 2,
    "Stretched Jeans": 2,
    "Skull Shirt": 2,
    "Victorian Hat": 2,
    "Boater Hat": 3,
    "Antique Dress": 2,
    "Crimson Skirt": 2,
    "Chic Gala Blouse": 2,
    "Ash Ponytail": 2,
    "Pink Ponytail": 2,
    "Silver Streaks": 2,
    "Brown Rancher Hair": 2,
    "Parsnip Horns": 2,
    "Potato Suit": 2,
    "Whale Hat": 2,
    "Pumpkin Shirt": 2,
    Halo: 2,
    Kama: 2,
    "Grey Merch Hoodie": 1,
    "Unicorn Horn": 1,
    "Desert Background": 1,
  },
  home: {
    collectibles: {
      Rug: [
        {
          coordinates: {
            x: 2,
            y: 6,
          },
          readyAt: 1705365486857,
          createdAt: 1705365486857,
          id: "2",
        },
      ],
      Wardrobe: [
        {
          coordinates: {
            x: 3,
            y: 6,
          },
          readyAt: 1705365486857,
          createdAt: 1705365486857,
          id: "1",
        },
      ],
    },
  },
  island: {
    type: "spring",
  },
  farmHands: {
    bumpkins: {
      "1": {
        equipped: {
          hair: "Basic Hair",
          shirt: "Yellow Farmer Shirt",
          pants: "Farmer Overalls",
          background: "Farm Background",
          hat: "Crumple Crown",
          body: "Beige Farmer Potion",
          shoes: "Black Farmer Boots",
          tool: "Ancient War Hammer",
        },
      },
    },
  },
  greenhouse: {
    oil: 100,
    pots: {},
  },
  competitions: {
    progress: {
      TESTING: {
        startedAt: 1727234388429,
        initialProgress: {
          "Complete chore": 0,
          "Complete delivery": 7,
          "Expand island": 23,
          "Level up": 12,
        },
        points: 4,
      },
      FSL: {
        startedAt: 1730156684048,
        initialProgress: {
          "Complete chore": 0,
          "Complete delivery": 9,
          "Level up": 14,
          "Expand island": 24,
        },
        points: 0,
      },
    },
  },
  createdAt: 1697493815740,
  stock: {
    Axe: "200",
    Pickaxe: "60",
    "Stone Pickaxe": "20",
    "Iron Pickaxe": "5",
    "Gold Pickaxe": "5",
    "Oil Drill": "5",
    Rod: "50",
    "Sunflower Seed": "400",
    "Potato Seed": "200",
    "Pumpkin Seed": "150",
    "Carrot Seed": "100",
    "Cabbage Seed": "90",
    "Soybean Seed": "90",
    "Beetroot Seed": "80",
    "Cauliflower Seed": "80",
    "Parsnip Seed": "60",
    "Eggplant Seed": "50",
    "Corn Seed": "50",
    "Radish Seed": "40",
    "Wheat Seed": "40",
    "Kale Seed": "30",
    "Barley Seed": "30",
    "Grape Seed": "10",
    "Olive Seed": "10",
    "Rice Seed": "10",
    "Tomato Seed": "10",
    "Lemon Seed": "10",
    "Blueberry Seed": "10",
    "Orange Seed": "10",
    "Apple Seed": "10",
    "Banana Plant": "10",
    "Sunpetal Seed": "16",
    "Bloom Seed": "8",
    "Lily Seed": "4",
    "Sand Shovel": "50",
    "Sand Drill": "10",
    Chicken: "5",
    "Immortal Pear": "1",
    "Treasure Map": "1",
    "Magic Bean": "5",
  },
  crops: {
    "1": {
      width: 1,
      x: -2,
      createdAt: 1697493815117,
      y: -1,
      crop: {
        name: "Potato",
        reward: {
          items: [
            {
              name: "Potato Seed",
              amount: 2,
            },
          ],
        },
        amount: 1,
        id: "04e8e1f5",
        plantedAt: 1717746162074,
      },
      height: 1,
    },
    "2": {
      width: 1,
      x: -1,
      createdAt: 1697493815117,
      y: -1,
      height: 1,
    },
    "3": {
      width: 1,
      x: 0,
      createdAt: 1697493815117,
      y: -1,
      height: 1,
    },
    "4": {
      width: 1,
      x: -2,
      createdAt: 1697493815117,
      y: 0,
      height: 1,
    },
    "5": {
      width: 1,
      x: -1,
      createdAt: 1697493815117,
      y: 0,
      height: 1,
    },
    "6": {
      width: 1,
      x: 0,
      createdAt: 1697493815117,
      y: 0,
      height: 1,
    },
    "7": {
      width: 1,
      x: -2,
      createdAt: 1697493815117,
      y: 1,
      height: 1,
    },
    "8": {
      width: 1,
      x: -1,
      createdAt: 1697493815117,
      y: 1,
      height: 1,
    },
    "9": {
      width: 1,
      x: 0,
      createdAt: 1697493815117,
      y: 1,
      height: 1,
    },
    "10": {
      width: 1,
      x: 6,
      createdAt: 1697493815117,
      y: -2,
      height: 1,
    },
    "11": {
      width: 1,
      x: 6,
      createdAt: 1697493815117,
      y: -1,
      height: 1,
    },
    "12": {
      width: 1,
      x: 7,
      createdAt: 1697493815117,
      y: -2,
      height: 1,
      crop: {
        id: "636ed3c5",
        plantedAt: 1725954754589,
        name: "Sunflower",
        amount: 1,
        reward: {
          items: [
            {
              amount: 2,
              name: "Sunflower Seed",
            },
          ],
        },
      },
    },
    "13": {
      width: 1,
      x: 7,
      createdAt: 1697493815117,
      y: -1,
      height: 1,
    },
  },
  trees: {
    "1": {
      width: 2,
      x: -3,
      createdAt: 1697493815117,
      y: 3,
      wood: {
        choppedAt: 1729570405193,
        amount: 1,
      },
      height: 2,
    },
    "2": {
      width: 2,
      x: 7,
      createdAt: 1697493815117,
      y: 3,
      wood: {
        choppedAt: 1729570392387,
        amount: 1,
      },
      height: 2,
    },
    "3": {
      width: 2,
      x: 7,
      createdAt: 1697493815117,
      y: 9,
      wood: {
        choppedAt: 1729570391340,
        amount: 1,
      },
      height: 2,
    },
  },
  stones: {
    "1": {
      width: 1,
      x: 0,
      createdAt: 1697493815117,
      y: 7,
      height: 1,
      stone: {
        minedAt: 0,
        amount: 1,
      },
    },
    "2": {
      width: 1,
      x: 4,
      createdAt: 1697493815117,
      y: 5,
      height: 1,
      stone: {
        minedAt: 0,
        amount: 1,
      },
    },
  },
  iron: {},
  gold: {},
  crimstones: {},
  oilReserves: {},
  sunstones: {},
  fruitPatches: {},
  flowers: {
    flowerBeds: {},
    discovered: {},
  },
  beehives: {},
  trades: {
    dailyListings: {
      count: 0,
      date: 159,
    },
    dailyPurchases: {
      count: 1,
      date: 158,
    },
    listings: {},
    offers: {
      "24d6fd": {
        createdAt: 1724893844981,
        items: {
          "Gold Egg": 1,
        },
        sfl: 10,
        collection: "collectibles",
      },
      de0ab7: {
        createdAt: 1726118624857,
        items: {
          "Skull Hat": 1,
        },
        sfl: 3,
        collection: "wearables",
        signature:
          "0xa328fd38fd5d0d5a2e3d664325e3f947c8dc109232a3620ebcae59e124c0713362793d08047993ad7e38432ab00f0832ebb076cd13c1087a2feb5ee5787ff3271c",
      },
      "51aa0c": {
        createdAt: 1727233148231,
        items: {
          "Fat Chicken": 1,
        },
        sfl: 5,
        collection: "collectibles",
      },
      aefe3b: {
        createdAt: 1727233193962,
        items: {
          "Christmas Tree": 1,
        },
        sfl: 5,
        collection: "collectibles",
        signature:
          "0xb3cc9b8770a8af853bf30aa1c848c55ef05141f8fbb51a44318596e8797999da404e636bc6b46ce0b2ef756e63cc21c2ab867453ea97ebe508ebaee9b66b686c1c",
      },
    },
  },
  chickens: {},
  stockExpiry: {
    "Sunflower Cake": "2023-06-19T00:00:00.000Z",
    "Potato Cake": "2023-07-24T00:00:00.000Z",
    "Pumpkin Cake": "2023-07-31T00:00:00.000Z",
    "Carrot Cake": "2023-08-21T00:00:00.000Z",
    "Cabbage Cake": "2023-06-26T00:00:00.000Z",
    "Beetroot Cake": "2023-07-10T00:00:00.000Z",
    "Cauliflower Cake": "2023-08-07T00:00:00.000Z",
    "Parsnip Cake": "2023-08-14T00:00:00.000Z",
    "Radish Cake": "2023-07-03T00:00:00.000Z",
    "Wheat Cake": "2023-07-17T00:00:00.000Z",
  },
  buildings: {
    "Fire Pit": [
      {
        coordinates: {
          x: 2,
          y: -1,
        },
        readyAt: 0,
        createdAt: 0,
        id: "123",
      },
    ],
    "Town Center": [
      {
        coordinates: {
          x: 2,
          y: 3,
        },
        readyAt: 0,
        createdAt: 0,
        id: "123",
      },
    ],
    Workbench: [
      {
        coordinates: {
          x: 4,
          y: 9,
        },
        readyAt: 0,
        createdAt: 0,
        id: "123",
      },
    ],
    "Compost Bin": [
      {
        coordinates: {
          x: -1,
          y: 5,
        },
        readyAt: 1698105124260,
        createdAt: 1698105124260,
        id: "3aa73602",
        requires: {
          Sunflower: 5,
          Carrot: 2,
          Pumpkin: 15,
        },
        producing: {
          items: {
            "Sprout Mix": 10,
            Earthworm: 3,
          },
          startedAt: 1729831022955,
          readyAt: 1729852622955,
        },
      },
      {
        id: "5eec242e",
        createdAt: 1727841454829,
        coordinates: {
          x: -7,
          y: 4,
        },
        readyAt: 1727845054829,
        requires: {
          Sunflower: 50,
          Beetroot: 2,
        },
      },
    ],
    Market: [
      {
        coordinates: {
          x: 6,
          y: 6,
        },
        readyAt: 0,
        createdAt: 0,
        id: "123",
      },
    ],
    Barn: [
      {
        id: "cca6fe99",
        createdAt: 1729552928574,
        coordinates: {
          x: -1,
          y: 14,
        },
        readyAt: 1729560128574,
      },
    ],
    "Crafting Box": [
      {
        id: "d6095b2f",
        createdAt: 1729571920578,
        coordinates: {
          x: -9,
          y: -1,
        },
        readyAt: 1729575520578,
      },
    ],
  },
  airdrops: [],
  collectibles: {
    "Laurie the Chuckle Crow": [
      {
        id: "d031153d",
        coordinates: {
          x: -8,
          y: 9,
        },
        readyAt: 1727841423884,
        createdAt: 1727841423884,
      },
    ],
    "King of Bears": [
      {
        id: "fb9773b8",
        createdAt: 1730330891944,
        coordinates: {
          x: -5,
          y: 0,
        },
        readyAt: 1730330891944,
      },
    ],
  },
  pumpkinPlaza: {
    raffle: {
      entries: {
        "2024-07": 6,
      },
    },
    giftGiver: {
      openedAt: 1729219750501,
    },
    keysBought: {
      treasureShop: {},
      megastore: {
        "Treasure Key": {
          boughtAt: 1730691145438,
        },
        "Rare Key": {
          boughtAt: 1730691340145,
        },
      },
      factionShop: {},
    },
  },
  treasureIsland: {
    holes: {},
  },
  dailyRewards: {
    streaks: 1,
    chest: {
      collectedAt: 1724891298122,
      code: 1,
    },
  },
  seed: "Lk/DsDMflNyDkvhYMTa1cNigrdHWid4JBW5vsqbUw3pm/REriPXAWc3S8mBDCcEKb/Ie/UXXIoOsWzSEvK/dzXeUJUb1fqNV95q/1qKNohioM3MBgR+nbVYOsUSJ98JgtbpReZS1pb2RwYwJ5rsUKgNHJ9RUhEhnEjv9dJ1XYBv9ykip+ivVzYMwE2mGy0PNXQ89fk5V8x8JsxgOZTlG0gEbEoOXRTBrufjGoNXrpCNh6+NlWY8hYtKdiYOIC8Uk+Hf2pxgqMe1g4hiRlVJnNVGYbk/23KGWFvwsJkOENqfSP0DluV/xfKd9DXB42s8oqqvwqm69Mz4K9osp5zxkj4tV7TCdIgLk4cNXUidi9nDRE5KkxUAbqBvswYXAwBvZKivukpCEo8Plrn+6spsNiFsa9xxyF26g/EH9jYiYH/aHuDNQh3MrilYQ740qt2+Vp0z0+gYM9VXTwcdi5Byje+pREam+XvGj0hsawnSp4fkUrWmzyGQCe0L2lnbLPW8PkHITBqPQKvfp1fVLOIjkKBi0BUEofiFFX/s5mh7SzL2bzZlt3BAZ7mgqNfDAbTzOvp3p+CKjpu3UO038BhlJNqAfnxJxx2LcRDHbWqqSJqpEtkAlgUtsORZTY15k0JlcmzIvtRsOgqozzNQK8GBVhp23p+3INE/5fsqeCNmRsitNnR85/vPwzzb2NFR6f0oAAO1voWTAhtAFKH+nKXSCI3n/++FfZ9LrZSIEcRJWvii4/0QNKe/EICrJHX1/9RxW0ZqlFKasV4ncpgNPaIvsFZVFVeSDH9zsF9zZtoYD7FGvXyyV9S1VdVV30Oj88OgTHFt8waV0xt2JzZC/MLahIMLhdewo+LyPKqGSJwNx9bPH648Q8LLFZDeb2KQq5hyVU8pEFi8Dn3HPCjA97bpAyHtXqTZl88bBlREgLfSUCrbKN3wJSUSrd2C0T0ZJRUV3ZI/QZUFvhKgcTqnwhGLVDmDRKqa9YHhH7y7FUJHQRqSuC4n17iJfkxG+ucGoUEprfKpg0qxglht8Tpof50fSNW22TKtpyDGQlt3kvVhn92TU1HnA+iSKXCKmYkqfsfk8C7S/IVaF1hHuLnSCQoW0mIczp2nLsO8mqeIu0zDZTzfHKjuD8JSNP/qzEVXAWO0LFwacFoWhAwxYSF87Lx4gsIkKWH8zGJLw8J/kVwL4lC+FdKuX59TkaNjIYAR7+9wIFwLDQabvENzB4P/D9Qk3oweuvDqK7rTDLRf/Ru0HkZFv478IQaa0/Liu6cACZjlfuB25zEBtZqJshz37qY0zTdmGwWyXxDrU0JXqAPSWzMH10WjTS/RHaPaiM2gbDprYTKafBql4di2yZrmF+4CBT0paZ/luBWObgjuNtggaHdufP1EO3KNlh5YvgloLF2Xj8pIdafq2R/fttXBd152JtycveKI=",
  auctioneer: {},
  farmActivity: {
    "Kraken Tentacle Caught": 1,
    "Seaweed Caught": 1,
    "Sea Cucumber Caught": 2,
    "Crab Caught": 1,
    "Olive Flounder Caught": 1,
    "Butterflyfish Caught": 1,
    "Anchovy Caught": 2,
  },
  milestones: {},
  fishing: {
    wharf: {
      bait: "Earthworm",
    },
    beach: {},
    dailyAttempts: {
      "2023-11-20": 2,
    },
  },
  chores: {
    choresCompleted: 0,
    choresSkipped: 0,
    chores: {
      "1": {
        activity: "Pumpkin Soup Cooked",
        requirement: 4,
        description: "Cook 4 Pumpkin Soup",
        createdAt: 1730428959587,
        bumpkinId: 1,
        startCount: 0,
      },
      "2": {
        activity: "Tree Chopped",
        requirement: 10,
        description: "Chop 10 Trees",
        createdAt: 1730428959587,
        bumpkinId: 1,
        startCount: 6,
      },
      "3": {
        activity: "Orange Cake Fed",
        requirement: 1,
        description: "Eat 1 Orange Cake",
        createdAt: 1730428959587,
        bumpkinId: 1,
        startCount: 0,
      },
      "4": {
        activity: "Iron Pickaxe Crafted",
        requirement: 2,
        description: "Craft 2 Iron Pickaxe",
        createdAt: 1730428959587,
        bumpkinId: 1,
        startCount: 0,
      },
      "5": {
        activity: "Corn Harvested",
        requirement: 80,
        description: "Harvest 80 Corn",
        createdAt: 1730428959587,
        bumpkinId: 1,
        startCount: 0,
      },
    },
  },
  kingdomChores: {
    chores: [
      {
        activity: "Axe Crafted",
        marks: 24,
        requirement: 3,
        image: "Axe",
        description: "Craft 3 Axes",
        startedAt: 1730690671812,
        startCount: 0,
      },
      {
        activity: "Tree Chopped",
        marks: 24,
        requirement: 3,
        image: "Wood",
        description: "Chop 3 Trees",
        startedAt: 1730690671812,
        startCount: 6,
      },
      {
        activity: "Stone Mined",
        marks: 22,
        requirement: 2,
        image: "Stone",
        description: "Mine 2 Stones",
        startedAt: 1730690671812,
        startCount: 0,
      },
      {
        activity: "Cabbage Harvested",
        marks: 24,
        requirement: 35,
        image: "Cabbage",
        description: "Harvest 35 Cabbage",
      },
      {
        activity: "Mashed Potato Cooked",
        marks: 22,
        requirement: 5,
        image: "Mashed Potato",
        description: "Cook 5 Mashed Potato",
      },
      {
        activity: "Reindeer Carrot Fed",
        marks: 21,
        requirement: 5,
        image: "Reindeer Carrot",
        description: "Eat 5 Reindeer Carrot",
      },
      {
        activity: "Axe Crafted",
        marks: 24,
        requirement: 3,
        image: "Axe",
        description: "Craft 3 Axes",
      },
      {
        activity: "Mushroom Soup Cooked",
        marks: 30,
        requirement: 1,
        image: "Mushroom Soup",
        description: "Cook 1 Mushroom Soup",
      },
      {
        activity: "Cauliflower Burger Fed",
        marks: 31,
        requirement: 3,
        image: "Cauliflower Burger",
        description: "Eat 3 Cauliflower Burger",
      },
    ],
    choresCompleted: 0,
    choresSkipped: 0,
    skipAvailableAt: 0,
    resetsAt: 1731283200000,
  },
  conversations: ["hank-intro"],
  mailbox: {
    read: [
      {
        readAt: 1698644118141,
        id: "catch-the-kraken",
      },
      {
        readAt: 1698644135678,
        id: "composting",
      },
      {
        readAt: 1698644141442,
        id: "travel-announcement",
      },
      {
        readAt: 1698644334735,
        id: "season-end",
      },
      {
        readAt: 1699242975539,
        id: "fishing-is-live",
      },
      {
        readAt: 1701987799048,
        id: "12-days-of-christmas",
      },
      {
        readAt: 1717746187652,
        id: "june-megastore",
      },
      {
        id: "sfl-drops",
        readAt: 1722573161094,
      },
      {
        id: "halloween",
        readAt: 1729570995264,
      },
    ],
  },
  mushrooms: {
    mushrooms: {
      b3e99835: {
        name: "Wild Mushroom",
        amount: 1,
        x: -4,
        y: 13,
      },
      ff65c844: {
        name: "Magic Mushroom",
        amount: 1,
        x: 7,
        y: 7,
      },
      "4bba7dc4": {
        name: "Wild Mushroom",
        amount: 1,
        x: -14,
        y: -12,
      },
      d9cb681a: {
        name: "Wild Mushroom",
        amount: 1,
        x: -7,
        y: 14,
      },
      "8f0a3fb9": {
        name: "Magic Mushroom",
        amount: 1,
        x: 0,
        y: 9,
      },
      e4e77160: {
        name: "Magic Mushroom",
        amount: 1,
        x: -13,
        y: 3,
      },
      bb3377cb: {
        name: "Wild Mushroom",
        amount: 1,
        x: -12,
        y: -11,
      },
      "52bc23c2": {
        name: "Wild Mushroom",
        amount: 1,
        x: -14,
        y: -2,
      },
    },
    magicSpawnedAt: 1730678400000,
    spawnedAt: 1730649600000,
  },
  delivery: {
    orders: [
      {
        readyAt: 1697493816898,
        reward: {
          sfl: 1.45,
          items: {},
        },
        createdAt: 1697493816898,
        from: "grimbly",
        id: "07bb0c",
        items: {
          "Cabbers n Mash": 1,
        },
      },
      {
        readyAt: 1697493816898,
        reward: {
          sfl: 1.4,
          items: {},
        },
        createdAt: 1697493816898,
        from: "grimtooth",
        id: "bd8dbb",
        items: {
          "Boiled Eggs": 1,
        },
      },
      {
        readyAt: 1697493816899,
        reward: {
          tickets: 6,
        },
        createdAt: 1697493816899,
        from: "cornwell",
        id: "780403",
        items: {
          Corn: 30,
        },
      },
      {
        readyAt: 1697493816899,
        reward: {
          tickets: 5,
        },
        createdAt: 1697493816899,
        from: "raven",
        id: "85d2bc",
        items: {
          Egg: 50,
          Radish: 60,
          Cabbage: 100,
        },
      },
      {
        readyAt: 1697493816900,
        reward: {
          tickets: 4,
        },
        createdAt: 1697493816900,
        from: "bert",
        id: "0bbb66",
        items: {
          Stone: 15,
          "Wild Mushroom": 1,
        },
      },
      {
        readyAt: 1697493816900,
        reward: {
          tickets: 6,
        },
        createdAt: 1697493816900,
        from: "timmy",
        id: "cfefcb",
        items: {
          Blueberry: 10,
        },
      },
      {
        readyAt: 1697493816900,
        reward: {
          tickets: 7,
        },
        createdAt: 1697493816900,
        from: "tywin",
        id: "069711",
        items: {
          sfl: 5,
          Gold: 5,
        },
      },
      {
        readyAt: 1698283111847,
        reward: {
          tickets: 4,
        },
        createdAt: 1698283111847,
        from: "miranda",
        id: "d8ead1",
        items: {
          Blueberry: 3,
        },
      },
      {
        readyAt: 1698283111847,
        reward: {
          tickets: 6,
        },
        createdAt: 1698283111847,
        from: "finn",
        id: "2a3ca1",
        items: {
          Anchovy: 1,
          Tuna: 1,
        },
      },
      {
        readyAt: 1698283111847,
        reward: {
          tickets: 5,
        },
        createdAt: 1698283111847,
        from: "finley",
        id: "c7d1ab",
        items: {
          Earthworm: 5,
        },
      },
      {
        readyAt: 1717657297928,
        reward: {
          sfl: 0.85,
        },
        createdAt: 1717657297928,
        from: "gordo",
        id: "e9fd3d",
        items: {
          "Bumpkin Salad": 3,
        },
      },
      {
        readyAt: 1717657297929,
        reward: {
          sfl: 1.05,
        },
        createdAt: 1717657297929,
        from: "guria",
        id: "7be273",
        items: {
          "Olive Flounder": 3,
        },
      },
      {
        readyAt: 1717657297929,
        reward: {
          sfl: 0.75,
        },
        createdAt: 1717657297929,
        from: "gambit",
        id: "ac8d01",
        items: {
          "Steamed Red Rice": 1,
        },
      },
      {
        readyAt: 1717657297929,
        reward: {},
        createdAt: 1717657297929,
        from: "jester",
        id: "7c82c3",
        items: {
          Olive: 1,
        },
      },
      {
        readyAt: 1717657457678,
        reward: {
          sfl: 0.5,
        },
        createdAt: 1717657457678,
        from: "grubnuk",
        id: "24bc97",
        items: {
          "Kale Stew": 4,
        },
      },
      {
        readyAt: 1717735696360,
        reward: {},
        createdAt: 1717735696360,
        from: "pumpkin' pete",
        id: "8c6f0c",
        items: {
          Sunflower: 15,
          Pumpkin: 15,
        },
      },
      {
        createdAt: 1720058505293,
        id: "b15891",
        from: "victoria",
        items: {
          Rice: 3,
          Anchovy: 3,
        },
        readyAt: 1720058505293,
        reward: {
          coins: 1695,
          items: {},
        },
      },
      {
        createdAt: 1721797402794,
        id: "328382",
        from: "corale",
        items: {
          Anchovy: 1,
        },
        readyAt: 1721797402794,
        reward: {
          coins: 184,
          items: {},
        },
      },
      {
        createdAt: 1721797409298,
        id: "c666a3",
        from: "tango",
        items: {
          Banana: 5,
        },
        readyAt: 1721797409298,
        reward: {
          coins: 189,
          items: {},
        },
      },
      {
        createdAt: 1721797476512,
        id: "ea554e",
        from: "peggy",
        items: {
          "Bumpkin Broth": 1,
        },
        readyAt: 1721797476512,
        reward: {
          coins: 80,
          items: {},
        },
      },
      {
        createdAt: 1722385080754,
        id: "e400ec",
        from: "old salty",
        items: {
          Sand: 12,
        },
        readyAt: 1722385080754,
        reward: {
          coins: 260,
          items: {},
        },
      },
      {
        createdAt: 1722573156100,
        readyAt: 1722573156100,
        from: "pharaoh",
        id: "7f6dbc",
        items: {
          "Camel Bone": 6,
        },
        reward: {},
      },
      {
        createdAt: 1727237758945,
        id: "0605a5",
        from: "betty",
        items: {
          Pumpkin: 5,
          Sunflower: 20,
          Potato: 10,
        },
        readyAt: 1727237758945,
        reward: {
          coins: 68,
          items: {},
        },
      },
      {
        createdAt: 1727237771825,
        id: "490c10",
        from: "blacksmith",
        items: {
          Wood: 20,
        },
        readyAt: 1727237771825,
        reward: {
          coins: 429,
          items: {},
        },
      },
    ],
    fulfilledCount: 9,
    milestone: {
      total: 10,
      goal: 10,
    },
    doubleDelivery: "2024-11-10",
    dailySFL: {
      day: 309,
      amount: 3.885418857894737,
    },
  },
  catchTheKraken: {
    weeklyCatches: {
      "3": 1,
    },
    hunger: "Potato",
  },
  npcs: {
    grubnuk: {
      deliveryCount: 0,
      skippedCount: 1,
    },
    "pumpkin' pete": {
      deliveryCount: 2,
      friendship: {
        giftClaimedAtPoints: 0,
        updatedAt: 1717709662230,
        points: 6,
      },
    },
    betty: {
      deliveryCount: 3,
      skippedCount: 1,
      friendship: {
        updatedAt: 1727237751849,
        points: 9,
        giftClaimedAtPoints: 0,
      },
    },
    corale: {
      deliveryCount: 0,
      skippedCount: 1,
    },
    blacksmith: {
      deliveryCount: 1,
      skippedCount: 1,
      friendship: {
        updatedAt: 1727237768897,
        points: 3,
        giftClaimedAtPoints: 0,
      },
    },
    tango: {
      deliveryCount: 0,
      skippedCount: 1,
    },
    peggy: {
      deliveryCount: 3,
    },
    miranda: {
      deliveryCount: 0,
      friendship: {
        points: 1,
        updatedAt: 1729570397988,
      },
      choreCount: 1,
    },
    garth: {
      deliveryCount: 0,
      friendship: {
        points: 1,
        updatedAt: 1729570408387,
      },
      choreCount: 1,
    },
  },
  islands: {},
  portals: {
    "crop-boom": {
      arcadeTokensMinted: 5,
      history: {
        "2023-12-07": {
          arcadeTokensMinted: 1,
        },
        "2023-12-04": {
          arcadeTokensMinted: 1,
        },
        "2023-12-19": {
          arcadeTokensMinted: 3,
        },
      },
    },
  },
  buds: {},
  minigames: {
    games: {
      "crops-and-chickens": {
        history: {
          "2024-08-14": {
            attempts: 1,
            highscore: 0,
          },
        },
        highscore: 0,
      },
    },
    prizes: {
      "chicken-rescue": {
        coins: 0,
        items: {
          Mark: 30,
        },
        wearables: {},
        score: 45,
        startAt: 1730678400000,
        endAt: 1730764800000,
      },
      "crops-and-chickens": {
        coins: 0,
        items: {
          Mark: 20,
        },
        wearables: {},
        score: 500,
        startAt: 1730678400000,
        endAt: 1730764800000,
      },
      "fruit-dash": {
        coins: 0,
        items: {
          Mark: 20,
        },
        wearables: {},
        score: 1000,
        startAt: 1730678400000,
        endAt: 1730764800000,
      },
    },
  },
  fulfilled: [],
  username: "adambum",
  christmas: {
    day: {
      "1": {
        candy: 10,
        collectedAt: 1701987908194,
      },
      "2": {
        candy: 2,
        collectedAt: 1703033806905,
      },
    },
  },
  megastore: {
    available: {
      from: 1730419200000,
      to: 1733011200000,
    },
    wearables: [],
    collectibles: [
      {
        name: "Treasure Key",
        shortDescription: "Use at the chest in the plaza to get your reward",
        currency: "Seasonal Ticket",
        price: "100",
        type: "keys",
        limit: null,
        availableAllSeason: true,
      },
      {
        name: "Rare Key",
        shortDescription: "Use at the chest in the beach to get your reward",
        currency: "Seasonal Ticket",
        price: "300",
        type: "keys",
        limit: null,
        availableAllSeason: true,
      },
      {
        name: "Luxury Key",
        shortDescription:
          "Use at the chest in the plaza near the woodlands to get your reward",
        currency: "Seasonal Ticket",
        price: "1000",
        type: "keys",
        limit: null,
        availableAllSeason: true,
      },
    ],
  },
  specialEvents: {
    current: {
      "La Tomatina": {
        text: "Double Tomato value at Betty's Market! Double fun with La Tomatina!",
        startAt: 1724716800000,
        endAt: 1725321600000,
        requiresWallet: false,
        tasks: [
          {
            requirements: {
              items: {
                Sunflower: 100,
              },
              sfl: 0,
            },
            reward: {
              items: {
                Tomato: 5,
              },
              sfl: 0,
              wearables: {},
            },
          },
          {
            requirements: {
              items: {
                Sunflower: 100,
              },
              sfl: 0,
            },
            reward: {
              items: {
                Tomato: 5,
              },
              sfl: 0,
              wearables: {},
            },
          },
          {
            requirements: {
              items: {
                Sunflower: 100,
              },
              sfl: 0,
            },
            reward: {
              items: {
                Tomato: 5,
              },
              sfl: 0,
              wearables: {},
            },
          },
          {
            requirements: {
              items: {
                Sunflower: 100,
              },
              sfl: 0,
            },
            reward: {
              items: {
                Tomato: 5,
                "Treasure Key": 1,
              },
              sfl: 0,
              wearables: {},
            },
          },
        ],
        bonus: {
          Tomato: {
            saleMultiplier: 2,
          },
        },
        isEligible: true,
      },
    },
    history: {},
  },
  goblinMarket: {
    resources: {},
  },
  faction: {
    history: {
      "2024-07-15": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 0,
          goalReached: true,
          streak: 1,
          sleeping: false,
        },
        results: {
          rank: 0,
        },
      },
      "2024-07-22": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 3500,
          goalReached: false,
          streak: 1,
          sleeping: false,
        },
        results: {
          rank: 0,
        },
      },
      "2024-07-29": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 3500,
          goalReached: false,
          streak: 1,
          sleeping: true,
        },
        results: {
          rank: 0,
        },
      },
      "2024-08-05": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 3500,
          goalReached: false,
          streak: 1,
          sleeping: false,
        },
        results: {
          rank: 0,
        },
      },
      "2024-08-12": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 3000,
          goalReached: false,
          streak: 0,
          sleeping: true,
        },
        results: {
          rank: 0,
        },
      },
      "2024-08-26": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 3000,
          goalReached: false,
          streak: 0,
          sleeping: true,
        },
        results: {
          rank: 0,
        },
      },
      "2024-09-02": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 3000,
          goalReached: false,
          streak: 0,
          sleeping: false,
        },
        results: {
          rank: 0,
        },
      },
      "2024-09-09": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 4000,
          goalReached: false,
          streak: 0,
          sleeping: true,
        },
        results: {
          rank: 0,
        },
      },
      "2024-09-23": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 5000,
          goalReached: false,
          streak: 0,
          sleeping: true,
        },
        results: {
          rank: 0,
        },
      },
      "2024-09-30": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 5000,
          goalReached: false,
          streak: 0,
          sleeping: false,
        },
        results: {
          rank: 0,
        },
      },
      "2024-10-14": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 4000,
          goalReached: false,
          streak: 0,
          sleeping: false,
        },
        results: {
          rank: 0,
        },
      },
      "2024-10-21": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 4000,
          goalReached: false,
          streak: 0,
          sleeping: true,
        },
        results: {
          rank: 0,
        },
      },
      "2024-10-28": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 4000,
          goalReached: false,
          streak: 0,
          sleeping: false,
        },
        results: {
          rank: 0,
        },
      },
      "2024-11-04": {
        petXP: 0,
        score: 0,
        collectivePet: {
          totalXP: 0,
          goalXP: 3000,
          goalReached: false,
          streak: 0,
          sleeping: true,
        },
      },
    },
    name: "goblins",
    pledgedAt: 1721015101725,
    points: 0,
    kitchen: {
      week: "2024-11-04",
      requests: [
        {
          item: "Soybean",
          amount: 60,
          dailyFulfilled: {},
        },
        {
          item: "Apple",
          amount: 11,
          dailyFulfilled: {},
        },
        {
          item: "Oil",
          amount: 2,
          dailyFulfilled: {},
        },
      ],
    },
    pet: {
      week: "2024-11-04",
      qualifiesForBoost: false,
      requests: [
        {
          food: "Fried Tofu",
          quantity: 1,
          dailyFulfilled: {},
        },
        {
          food: "Fruit Salad",
          quantity: 5,
          dailyFulfilled: {},
        },
        {
          food: "Cornbread",
          quantity: 1,
          dailyFulfilled: {},
        },
      ],
    },
  },
  desert: {
    digging: {
      grid: [],
      patterns: [
        "MONDAY_ARTEFACT_FORMATION",
        "MONDAY_ARTEFACT_FORMATION",
        "MONDAY_ARTEFACT_FORMATION",
        "HIEROGLYPH",
        "OLD_BOTTLE",
        "OLD_BOTTLE",
        "WOODEN_COMPASS",
        "PEARL",
      ],
    },
  },
  henHouse: {
    level: 1,
    animals: {
      "0": {
        id: "0",
        type: "Chicken",
        state: "sick",
        coordinates: {
          x: -4,
          y: 4,
        },
        asleepAt: 0,
        experience: 0,
        createdAt: 1729829653755,
        item: "Petting Hand",
        lovedAt: 0,
        healthCheckedAt: 1730589066559,
        awakeAt: 0,
      },
      "1": {
        id: "1",
        type: "Chicken",
        state: "sick",
        coordinates: {
          x: -2,
          y: 4,
        },
        asleepAt: 0,
        experience: 0,
        createdAt: 1729829653755,
        item: "Petting Hand",
        lovedAt: 0,
        healthCheckedAt: 1730690671812,
        awakeAt: 0,
      },
      "2": {
        id: "2",
        type: "Chicken",
        state: "idle",
        coordinates: {
          x: 0,
          y: 4,
        },
        asleepAt: 0,
        experience: 0,
        createdAt: 1729829653755,
        item: "Petting Hand",
        lovedAt: 0,
        healthCheckedAt: 1730690671812,
        awakeAt: 0,
      },
    },
  },
  barn: {
    level: 1,
    animals: {
      "0": {
        id: "0",
        type: "Cow",
        state: "idle",
        coordinates: {
          x: -4,
          y: 4,
        },
        asleepAt: 0,
        experience: 0,
        createdAt: 1729829653755,
        item: "Petting Hand",
        lovedAt: 0,
        healthCheckedAt: 1730690671812,
        awakeAt: 0,
      },
      "1": {
        id: "1",
        type: "Cow",
        state: "sick",
        coordinates: {
          x: -2,
          y: 4,
        },
        asleepAt: 0,
        experience: 0,
        createdAt: 1729829653755,
        item: "Petting Hand",
        lovedAt: 0,
        healthCheckedAt: 1730093413803,
      },
      "2": {
        id: "2",
        type: "Cow",
        state: "sick",
        coordinates: {
          x: 0,
          y: 4,
        },
        asleepAt: 0,
        experience: 60,
        createdAt: 1729829653755,
        item: "Petting Hand",
        lovedAt: 0,
        healthCheckedAt: 1730181585141,
      },
    },
  },
  bounties: {
    requests: [
      {
        level: 9,
        id: "80463e",
        name: "Chicken",
        coins: 260,
      },
      {
        level: 11,
        id: "c2ebcb",
        name: "Chicken",
        coins: 390,
      },
      {
        level: 15,
        id: "b54cb5",
        name: "Chicken",
        coins: 720,
      },
      {
        level: 10,
        id: "0f30b2",
        name: "Chicken",
        coins: 310,
      },
      {
        level: 7,
        id: "b6a497",
        name: "Chicken",
        coins: 180,
      },
      {
        level: 4,
        id: "916813",
        name: "Chicken",
        items: {},
        coins: 150,
      },
      {
        level: 5,
        id: "ec505f",
        name: "Chicken",
        items: {},
        coins: 160,
      },
      {
        level: 7,
        id: "b168cb",
        name: "Chicken",
        items: {
          Gem: 10,
        },
      },
      {
        level: 10,
        id: "8674af",
        name: "Cow",
        coins: 3760,
      },
      {
        level: 12,
        id: "db487d",
        name: "Sheep",
        coins: 2550,
      },
      {
        level: 4,
        id: "d58fc1",
        name: "Sheep",
        coins: 400,
      },
      {
        level: 11,
        id: "a0ada3",
        name: "Sheep",
        coins: 2080,
      },
      {
        level: 6,
        id: "aa62d3",
        name: "Sheep",
        items: {
          Gem: 5,
        },
      },
      {
        level: 6,
        id: "91f31a",
        name: "Cow",
        items: {},
        coins: 1220,
      },
      {
        level: 5,
        id: "37ea37",
        name: "Cow",
        items: {},
        coins: 930,
      },
      {
        level: 7,
        id: "02c53a",
        name: "Cow",
        items: {},
        coins: 1320,
      },
      {
        id: "9ffc4e",
        name: "Purple Pansy",
        items: {
          Gem: 5,
        },
      },
      {
        id: "f46921",
        name: "Purple Cosmos",
        items: {
          Gem: 10,
        },
      },
      {
        id: "f469a4",
        name: "Red Balloon Flower",
        items: {
          Gem: 15,
        },
      },
    ],
    completed: [],
  },
  craftingBox: {
    status: "idle",
    startedAt: 0,
    readyAt: 0,
    recipes: {
      "Dirt Path": {
        name: "Dirt Path",
        ingredients: [
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
        ],
        time: 0,
        type: "collectible",
      },
      Fence: {
        name: "Fence",
        ingredients: [
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
        ],
        time: 0,
        type: "collectible",
      },
      "Sturdy Bed": {
        name: "Sturdy Bed",
        ingredients: [
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
        ],
        time: 7200000,
        type: "collectible",
      },
      "Floral Bed": {
        name: "Floral Bed",
        ingredients: [
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
        ],
        time: 5400000,
        type: "collectible",
      },
      "Fisher Bed": {
        name: "Fisher Bed",
        ingredients: [
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
        ],
        time: 3600000,
        type: "collectible",
      },
      "Basic Bed": {
        name: "Basic Bed",
        ingredients: [
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
          {
            collectible: "Australian Flag",
          },
        ],
        time: 1800000,
        type: "collectible",
      },
    },
  },
});
