import Decimal from "decimal.js-light";

import { GameState, InventoryItemName } from "../types/game";

/**
 * Converts API response into a game state
 */
export function makeGame(farm: any): GameState {
  return {
    inventory: Object.keys(farm.inventory).reduce(
      (items, item) => ({
        ...items,
        [item]: new Decimal(farm.inventory[item]),
      }),
      {} as Record<InventoryItemName, Decimal>,
    ),
    previousInventory: Object.keys(farm.previousInventory).reduce(
      (items, item) => ({
        ...items,
        [item]: new Decimal(farm.previousInventory[item]),
      }),
      {} as Record<InventoryItemName, Decimal>,
    ),
    wardrobe: farm.wardrobe,
    calendar: farm.calendar,
    vip: farm.vip,
    previousWardrobe: farm.previousWardrobe,
    competitions: farm.competitions,
    verified: farm.verified,
    stock: Object.keys(farm.stock).reduce(
      (items, item) => ({
        ...items,
        [item]: new Decimal(farm.stock[item]),
      }),
      {} as Record<InventoryItemName, Decimal>,
    ),
    bounties: farm.bounties,
    island: farm.island,
    bank: farm.bank,
    home: farm.home,
    createdAt: farm.createdAt,
    stockExpiry: farm.stockExpiry || {},
    coins: farm.coins,
    balance: new Decimal(farm.balance),
    previousBalance: new Decimal(farm.previousBalance),
    username: farm.username,
    roninRewards: farm.roninRewards,
    settings: farm.settings,
    trades: farm.trades,
    farmHands: farm.farmHands,

    expansionConstruction: farm.expansionConstruction,
    expandedAt: farm.expandedAt,
    greenhouse: farm.greenhouse,
    choreBoard: farm.choreBoard,

    shipments: farm.shipments,
    gems: farm.gems,
    flower: farm.flower,
    bumpkin: farm.bumpkin,
    buildings: farm.buildings,
    fishing: farm.fishing ?? { wharf: {}, beach: {} },
    crabTraps: farm.crabTraps ?? { trapSpots: {} },
    farmActivity: farm.farmActivity ?? {},
    milestones: farm.milestones ?? {},
    airdrops: farm.airdrops,
    raffle: farm.raffle,
    collectibles: farm.collectibles,
    warCollectionOffer: farm.warCollectionOffer,
    mysteryPrizes: farm.mysteryPrizes,
    pumpkinPlaza: farm.pumpkinPlaza,
    dailyRewards: farm.dailyRewards,
    auctioneer: farm.auctioneer ?? {},
    minigames: farm.minigames,
    kingdomChores: farm.kingdomChores,
    buffs: farm.buffs,
    chores: farm.chores,
    tradedAt: farm.tradedAt,
    trees: farm.trees ?? {},
    stones: farm.stones ?? {},
    iron: farm.iron ?? {},
    gold: farm.gold ?? {},
    crimstones: farm.crimstones ?? {},
    oilReserves: farm.oilReserves ?? {},
    sunstones: farm.sunstones ?? {},
    crops: farm.crops ?? {},
    fruitPatches: farm.fruitPatches ?? {},
    flowers: farm.flowers ?? {},
    beehives: farm.beehives ?? {},
    conversations: farm.conversations ?? [],
    mailbox: farm.mailbox ?? {
      read: [],
      unread: [],
    },
    mushrooms: farm.mushrooms,
    delivery: farm.delivery,
    potionHouse: farm.potionHouse,
    npcs: farm.npcs,
    buds: farm.buds,
    flowerShop: farm.flowerShop,
    specialEvents: farm.specialEvents,
    floatingIsland: farm.floatingIsland,
    megastore: farm.megastore,
    goblinMarket: farm.goblinMarket,
    faction: farm.faction,
    previousFaction: farm.previousFaction,
    dailyFactionDonationRequest: farm.dailyFactionDonationRequest
      ? {
          resource: farm.dailyFactionDonationRequest.resource,
          amount: new Decimal(farm.dailyFactionDonationRequest.amount),
        }
      : undefined,
    desert: farm.desert,
    transaction: farm.transaction,
    henHouse: farm.henHouse,
    barn: farm.barn,
    waterWell: farm.waterWell,
    petHouse: farm.petHouse,
    craftingBox: farm.craftingBox,
    season: farm.season,
    lavaPits: farm.lavaPits,
    nfts: farm.nfts,
    faceRecognition: farm.faceRecognition,
    telegram: farm.telegram,
    discord: farm.discord,
    socialTasks: farm.socialTasks,
    referrals: farm.referrals,
    twitter: farm.twitter,
    ban: farm.ban,
    rewardBoxes: farm.rewardBoxes,
    withdrawals: farm.withdrawals,
    blessing: farm.blessing,
    aoe: farm.aoe,
    boostsUsedAt: farm.boostsUsedAt,
    socialFarming: farm.socialFarming,
    pets: farm.pets,
    prototypes: farm.prototypes,
  };
}
