export default [
  {
    inputs: [
      {
        internalType: "contract SunflowerLandSessionManager",
        name: "_session",
        type: "address",
      },
      {
        internalType: "contract SunflowerLand",
        name: "_farm",
        type: "address",
      },
      {
        internalType: "contract SunflowerLandInventory",
        name: "_inventory",
        type: "address",
      },
      {
        internalType: "contract BumpkinWearables",
        name: "_wearables",
        type: "address",
      },
      {
        internalType: "contract SunflowerLandToken",
        name: "_token",
        type: "address",
      },
      { internalType: "contract ERC721", name: "_buds", type: "address" },
      { internalType: "address", name: "_signer", type: "address" },
      {
        components: [
          { internalType: "address", name: "fee", type: "address" },
          { internalType: "address", name: "community", type: "address" },
        ],
        internalType: "struct SunflowerLandMarketplace.Wallets",
        name: "_wallets",
        type: "tuple",
      },
      {
        internalType: "contract SunflowerFees",
        name: "_fees",
        type: "address",
      },
      {
        internalType: "contract SunflowerLandMarketplaceVerifier",
        name: "_verifier",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes", name: "signature", type: "bytes" },
      { internalType: "bytes32", name: "sessionId", type: "bytes32" },
      { internalType: "bytes32", name: "nextSessionId", type: "bytes32" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint256", name: "farmId", type: "uint256" },
      { internalType: "uint256", name: "playerAmount", type: "uint256" },
      { internalType: "uint256", name: "teamAmount", type: "uint256" },
      { internalType: "uint256", name: "amountOutMinimum", type: "uint256" },
      {
        components: [
          { internalType: "uint256", name: "sfl", type: "uint256" },
          { internalType: "uint256", name: "items", type: "uint256" },
        ],
        internalType: "struct SunflowerLandMarketplace.MintAmounts",
        name: "mintAmounts",
        type: "tuple",
      },
      {
        components: [
          { internalType: "bytes", name: "signature", type: "bytes" },
          { internalType: "string", name: "tradeId", type: "string" },
          { internalType: "uint256", name: "farmId", type: "uint256" },
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "uint256", name: "sfl", type: "uint256" },
          { internalType: "string", name: "collection", type: "string" },
          { internalType: "string", name: "name", type: "string" },
        ],
        internalType: "struct SunflowerLandMarketplace.OfferData",
        name: "offer",
        type: "tuple",
      },
    ],
    name: "acceptOffer",
    outputs: [{ internalType: "bool", name: "success", type: "bool" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_game", type: "address" }],
    name: "addGameRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "buds",
    outputs: [{ internalType: "contract ERC721", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "destroy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "executedTxs",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "farm",
    outputs: [
      { internalType: "contract SunflowerLand", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fees",
    outputs: [
      { internalType: "contract SunflowerFees", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_game", type: "address" }],
    name: "gameAddGameRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_game", type: "address" }],
    name: "gameRemoveGameRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "gameRoles",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "inventory",
    outputs: [
      {
        internalType: "contract SunflowerLandInventory",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              { internalType: "bytes", name: "signature", type: "bytes" },
              { internalType: "string", name: "id", type: "string" },
              { internalType: "uint256", name: "farmId", type: "uint256" },
              { internalType: "uint256", name: "itemId", type: "uint256" },
              { internalType: "uint256", name: "sfl", type: "uint256" },
              { internalType: "uint256", name: "quantity", type: "uint256" },
              { internalType: "string", name: "collection", type: "string" },
              { internalType: "string", name: "itemName", type: "string" },
            ],
            internalType: "struct SunflowerLandMarketplace.Listing",
            name: "listing",
            type: "tuple",
          },
          { internalType: "uint256", name: "buyerFarmId", type: "uint256" },
          { internalType: "bytes32", name: "sessionId", type: "bytes32" },
          { internalType: "bytes32", name: "nextSessionId", type: "bytes32" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "uint256", name: "playerAmount", type: "uint256" },
          { internalType: "uint256", name: "teamAmount", type: "uint256" },
          {
            internalType: "uint256",
            name: "amountOutMinimum",
            type: "uint256",
          },
          {
            components: [
              { internalType: "uint256", name: "sfl", type: "uint256" },
              { internalType: "uint256", name: "items", type: "uint256" },
            ],
            internalType: "struct SunflowerLandMarketplace.MintAmounts",
            name: "mintAmounts",
            type: "tuple",
          },
          { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        internalType: "struct SunflowerLandMarketplace.PurchaseListingArgs",
        name: "args",
        type: "tuple",
      },
    ],
    name: "purchaseListing",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_game", type: "address" }],
    name: "removeGameRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "session",
    outputs: [
      {
        internalType: "contract SunflowerLandSessionManager",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_ids", type: "uint256[]" },
      { internalType: "uint256[]", name: "_amounts", type: "uint256[]" },
    ],
    name: "setMaxItemAmounts",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "setMaxSessionSFL",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_ids", type: "uint256[]" },
      { internalType: "uint256[]", name: "_amounts", type: "uint256[]" },
    ],
    name: "setMaxWearableAmounts",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "contract SunflowerLandToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_community", type: "address" }],
    name: "transferCommunityWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_team", type: "address" }],
    name: "transferFeeWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_signer", type: "address" }],
    name: "transferSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "verifier",
    outputs: [
      {
        internalType: "contract SunflowerLandMarketplaceVerifier",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "wearables",
    outputs: [
      { internalType: "contract BumpkinWearables", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
