/**
 * Sunnyside raw assets, crops and tiles are not stored in this repository
 * If you want access to these, you must download the asset pack from: https://danieldiggle.itch.io/sunnyside
 */

// import { progressBarBorderStyle } from "features/game/lib/style";
// import { SpookyTree } from "features/island/collectibles/components/SpookyTree";
// import { VIPGift } from "features/world/ui/VIPGift";
import { CONFIG } from "lib/config";

export const SUNNYSIDE = {
  //Achievements
  achievement: {
    bumpkinChainsawAmateur: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/bumpkin_chainsaw_amateur.png`,
    twentyTwentyVision: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/20-20-vision.png`,
    bakersDozen: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/bakers_dozen.png`,
    beetrootBeast: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/beetrootBeast.png`,
    bigSpender: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/big_spender.png`,
    brilliantBumpkin: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/brilliant_bumpkin.png`,
    bumpkinBillionaire: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/bumpkin_billionaire.png`,
    craftmanship: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/craftmanship.png`,
    busyBumpkin: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/busy_bumpkin.png`,
    cabbageKing: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/cabbage_king.png`,
    canary: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/canary.png`,
    chefDeCuisine: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/chef_de_cuisine.png`,
    contractor: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/contractor.png`,
    coolCauliflower: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/cool_cauliflower.png`,
    jackOLantern: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/jack_o_lantern.png`,
    cropChampion: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/crop_champion.png`,
    driller: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/driller.png`,
    elDorado: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/el-dorado.png`,
    goldFever: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/gold_fever.png`,
    ironEyes: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/iron_eyes.png`,
    stapleCrop: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/staple_crop.png`,
    kissTheCook: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/kiss_the_cook.png`,
    museum: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/museum.png`,
    myLifeIsPotato: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/my_life_is_potato.png`,
    patientParsnip: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/patient_parsnip.png`,
    rapidRadish: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/rapidRadish.png`,
    somethingShiny: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/something_shiny.png`,
    sunSeeker: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/sun_seeker.png`,
    sunflowerSuperstar: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/sunflower_superstar.png`,
    timberrr: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/timber.png`,
    timeToChop: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/time_to_chop.png`,
    breadWinner: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/bread_winner.png`,
    explorer: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/explorer.png`,
    farmHand: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/farm_hand.png`,
    highRoller: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/high_roller.png`,
    orangeSqueeze: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/orange_squeeze.png`,
    appleOfMyEye: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/apple_of_my_eye.png`,
    blueChip: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/blue_chip.png`,
    fruitPlatter: `${CONFIG.PROTECTED_IMAGE_URL}/achievements/fruit_platter.png`,
  },

  //Announcement
  announcement: {
    tornado: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/tornado.png`,
    springPrestige: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/spring_prestige.png`,
    desertPrestige: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/desert_prestige.png`,
    desert_digging: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/desert.webp`,
    factions: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/factions.png`,
    desertSeason: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/desert_season.png`,
    bullRunSeason: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/bull_run_season.png`,
    pharaohSeasonRares: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/pharaoh_seasonal_rares.png`,
    bullRunSeasonRares: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/bull_run_seasonal_rares.webp`,
    marketplace: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/marketplace_dark.png`,
    marketplaceLight: `${CONFIG.PROTECTED_IMAGE_URL}/announcements/marketplace.png`,
  },
  //Badges(Pre-LandExpansion Skills)
  badges: {
    greenThumb: `${CONFIG.PROTECTED_IMAGE_URL}/skills/green_thumb.png`,
    goldRush: `${CONFIG.PROTECTED_IMAGE_URL}/skills/gold_rush.png`,
    prospector: `${CONFIG.PROTECTED_IMAGE_URL}/skills/prospector.png`,
    wrangler: `${CONFIG.PROTECTED_IMAGE_URL}/skills/wrangler.png`,
    barnManager: `${CONFIG.PROTECTED_IMAGE_URL}/skills/barn_manager.png`,
    seedSpecialist: `${CONFIG.PROTECTED_IMAGE_URL}/skills/seed_specialist.png`,
    logger: `${CONFIG.PROTECTED_IMAGE_URL}/skills/logger.png`,
    lumberjack: `${CONFIG.PROTECTED_IMAGE_URL}/skills/lumberjack.png`,
    warrior: `${CONFIG.PROTECTED_IMAGE_URL}/skills/warrior.png`,
    artist: `${CONFIG.PROTECTED_IMAGE_URL}/skills/artist.png`,
    coder: `${CONFIG.PROTECTED_IMAGE_URL}/skills/coder.png`,
    discord: `${CONFIG.PROTECTED_IMAGE_URL}/skills/discord.png`,
    liquidityProvider: `${CONFIG.PROTECTED_IMAGE_URL}/skills/liquidity_provider.png`,
  },
  //Crops
  crops: {
    magicBean: `${CONFIG.PROTECTED_IMAGE_URL}/crops/magic_bean.png`,
    magicBeanplanted: `${CONFIG.PROTECTED_IMAGE_URL}/crops/bean_planted.png`,
    magicBeanready: `${CONFIG.PROTECTED_IMAGE_URL}/crops/bean_ready.png`,
    magicBeangrowing: `${CONFIG.PROTECTED_IMAGE_URL}/crops/bean_growing.png`,
  },
  //Captcha
  captcha: {
    background1: `${CONFIG.PROTECTED_IMAGE_URL}/captcha/chest_background_1.png`,
    background2: `${CONFIG.PROTECTED_IMAGE_URL}/captcha/chest_background_2.png`,
    background3: `${CONFIG.PROTECTED_IMAGE_URL}/captcha/chest_background_3.png`,
    background4: `${CONFIG.PROTECTED_IMAGE_URL}/captcha/chest_background_4.png`,
    background5: `${CONFIG.PROTECTED_IMAGE_URL}/captcha/chest_background_5.png`,
    background6: `${CONFIG.PROTECTED_IMAGE_URL}/captcha/chest_background_6.png`,
    background7: `${CONFIG.PROTECTED_IMAGE_URL}/captcha/chest_background_7.png`,
    background8: `${CONFIG.PROTECTED_IMAGE_URL}/captcha/chest_background_8.png`,
  },
  //Skills
  skills: {
    //skill-tree-icon
    animals: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/skill-tree-icon/animals.png`,
    cooking: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/skill-tree-icon/cooking.png`,
    crops: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/skill-tree-icon/crops.png`,
    rocks: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/skill-tree-icon/rocks.png`,
    trees: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/skill-tree-icon/trees.png`,
    green_thumb_LE: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/crops/green_thumb_LE.png`,
    cultivator: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/crops/cultivator.png`,
    master_farmer: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/crops/master_farmer.png`,
    golden_flowers: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/crops/golden_flowers.png`,
    happy_crop: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/crops/happy_crop.png`,
    buckaroo: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/animals/buckaroo.png`,
    coal_face: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/rocks/coal_face.png`,
    curer: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/cooking/curer.png`,
    digger: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/rocks/digger.png`,
    free_range: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/animals/free_range.png`,
    gold_rush_LE: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/rocks/gold_rush_LE.png`,
    horse_whisperer: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/animals/horse_whisperer.png`,
    kitchen_hand: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/cooking/kitchen_hand.png`,
    lumberjack_LE: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/trees/lumberjack_LE.png`,
    michelin_stars: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/cooking/michelin_stars.png`,
    money_tree: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/trees/money_tree.png`,
    rush_hour: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/cooking/rush_hour.png`,
    seeker: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/rocks/seeker.png`,
    stable_hand: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/animals/stable_hand.png`,
    tough_tree: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/trees/tough_tree.png`,
    tree_hugger: `${CONFIG.PROTECTED_IMAGE_URL}/skills/land/trees/tree_hugger.png`,
  },
  //Land
  land: {
    //Clouds
    mainCloudsTop: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/main_clouds_top.webp`,
    mainCloudsLeft: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/main_clouds_left.webp`,
    mainCloudsRight: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/main_clouds_right.webp`,
    mainCloudsBottom: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/main_clouds_bottom.webp`,

    //Dynamic Clouds
    cloud1: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/cloud_1.webp`,
    cloud2: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/cloud_2.webp`,
    cloud3: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/cloud_3.webp`,
    cloud4: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/cloud_4.webp`,
    cloud5: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/cloud_5.webp`,
    cloud6: `${CONFIG.PROTECTED_IMAGE_URL}/land/clouds/cloud_6.webp`,

    //Dirt Render
    fullEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/1_1_1_1.png`,
    noEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/0_0_0_0.png`,
    topAndBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/1_0_1_0.png`,
    topLeftAndBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/1_0_1_1.png`,
    topRightAndBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/1_1_1_0.png`,
    topRightAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/1_1_0_1.png`,
    rightBottomAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/0_1_1_1.png`,
    rightAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/0_1_0_1.png`,
    rightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/0_1_0_0.png`,
    bottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/0_0_1_0.png`,
    topEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/1_0_0_0.png`,
    leftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/0_0_0_1.png`,
    topAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/1_0_0_1.png`,
    bottomAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/0_0_1_1.png`,
    topAndRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/1_1_0_0.png`,
    bottomAndRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/land/dirt/0_1_1_0.png`,

    //Desert Dirt Render
    desertFullEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/1_1_1_1.png`,
    desertNoEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/0_0_0_0.png`,
    desertTopAndBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/1_0_1_0.png`,
    desertTopLeftAndBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/1_0_1_1.png`,
    desertTopRightAndBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/1_1_1_0.png`,
    desertTopRightAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/1_1_0_1.png`,
    desertRightBottomAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/0_1_1_1.png`,
    desertRightAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/0_1_0_1.png`,
    desertRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/0_1_0_0.png`,
    desertBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/0_0_1_0.png`,
    desertTopEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/1_0_0_0.png`,
    desertLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/0_0_0_1.png`,
    desertTopAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/1_0_0_1.png`,
    desertBottomAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/0_0_1_1.png`,
    desertTopAndRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/1_1_0_0.png`,
    desertBottomAndRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/desert/land/dirt/0_1_1_0.png`,

    //Prestige Island
    springRaft: `${CONFIG.PROTECTED_IMAGE_URL}/land/prestige_raft.png`,
    desertRaft: `${CONFIG.PROTECTED_IMAGE_URL}/land/desert_prestige_raft.png`,
    rewardsRaft: `${CONFIG.PROTECTED_IMAGE_URL}/land/rewards_raft.png`,

    island: `${CONFIG.PROTECTED_IMAGE_URL}/land/islands/island.webp`,
    mushroomIsland: `${CONFIG.PROTECTED_IMAGE_URL}/land/mushroom_island.png`,
    vip_island: `${CONFIG.PROTECTED_IMAGE_URL}/land/vip_island.png`,
    helios: `${CONFIG.PROTECTED_IMAGE_URL}/land/helios.webp`,
    lavaIsland: `${CONFIG.PROTECTED_IMAGE_URL}/land/islands/lava_island.webp`,
    greenIsland: `${CONFIG.PROTECTED_IMAGE_URL}/land/islands/green_island.webp`,
    cactusIsland: `${CONFIG.PROTECTED_IMAGE_URL}/land/islands/cactus_island.webp`,
    crabAtoll: `${CONFIG.PROTECTED_IMAGE_URL}/land/islands/crab_atoll.webp`,
    crossIsland: `${CONFIG.PROTECTED_IMAGE_URL}/land/islands/cross_island.webp`,
    potionIsland: `${CONFIG.PROTECTED_IMAGE_URL}/land/islands/potion_island.webp`,
    starfishAtoll: `${CONFIG.PROTECTED_IMAGE_URL}/land/islands/starfish_atoll.webp`,
    tombStoneIsland: `${CONFIG.PROTECTED_IMAGE_URL}/land/islands/tombstone_island.webp`,
    greenhouse_inside: `${CONFIG.PROTECTED_IMAGE_URL}/land/greenhouse_inside.png`,
    landComplete: `${CONFIG.PROTECTED_IMAGE_URL}/land/land_complete.png`,
    //Basic Land Expansion
    pontoon: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/pontoon.gif`,
    basicLevel1: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_1.webp`,
    basicLevel2: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_2.webp`,
    basicLevel3: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_3.webp`,
    basicLevel4: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_4.webp`,
    basicLevel5: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_5.webp`,
    basicLevel6: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_6.webp`,
    basicLevel7: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_7.webp`,
    basicLevel8: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_8.webp`,
    basicLevel9: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_9.webp`,
    basicLevel10: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_10.webp`,
    basicLevel11: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_11.webp`,
    basicLevel12: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_12.webp`,
    basicLevel13: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_13.webp`,
    basicLevel14: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_14.webp`,
    basicLevel15: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_15.webp`,
    basicLevel16: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_16.webp`,
    basicLevel17: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_17.webp`,
    basicLevel18: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_18.webp`,
    basicLevel19: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_19.webp`,
    basicLevel20: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_20.webp`,
    basicLevel21: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_21.webp`,
    basicLevel22: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_22.webp`,
    basicLevel23: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/basic/level_23.webp`,
    //Desert Land Expansion
    desertLevel1: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_1.webp`,
    desertLevel2: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_2.webp`,
    desertLevel3: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_3.webp`,
    desertLevel4: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_4.webp`,
    desertLevel5: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_5.webp`,
    desertLevel6: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_6.webp`,
    desertLevel7: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_7.webp`,
    desertLevel8: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_8.webp`,
    desertLevel9: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_9.webp`,
    desertLevel10: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_10.webp`,
    desertLevel11: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_11.webp`,
    desertLevel12: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_12.webp`,
    desertLevel13: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_13.webp`,
    desertLevel14: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_14.webp`,
    desertLevel15: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_15.webp`,
    desertLevel16: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_16.webp`,
    desertLevel17: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_17.webp`,
    desertLevel18: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_18.webp`,
    desertLevel19: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_19.webp`,
    desertLevel20: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_20.webp`,
    desertLevel21: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_21.webp`,
    desertLevel22: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_22.webp`,
    desertLevel23: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_23.webp`,
    desertLevel24: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_24.webp`,
    desertLevel25: `${CONFIG.PROTECTED_IMAGE_URL}/land/levels/desert/level_25.webp`,

    tent_inside: `${CONFIG.PROTECTED_IMAGE_URL}/land/tent_inside.png`,
    house_inside: `${CONFIG.PROTECTED_IMAGE_URL}/land/house_inside.png`,
    manor_inside: `${CONFIG.PROTECTED_IMAGE_URL}/land/manor_inside.png`,
    animal_house_inside_one: `${CONFIG.PROTECTED_IMAGE_URL}/land/animal_house_one.png`,
    animal_house_inside_two: `${CONFIG.PROTECTED_IMAGE_URL}/land/animal_house_two.png`,
    animal_house_inside_three: `${CONFIG.PROTECTED_IMAGE_URL}/land/animal_house_three.png`,

    basic_building_bg: `${CONFIG.PROTECTED_IMAGE_URL}/land/basic_building_bg.png`,
    spring_building_bg: `${CONFIG.PROTECTED_IMAGE_URL}/land/spring_building_bg.png`,
    desert_building_bg: `${CONFIG.PROTECTED_IMAGE_URL}/land/desert_building_bg.png`,
  },
  //Soil
  soil: {
    sand_dug: `${CONFIG.PROTECTED_IMAGE_URL}/crops/sand_dug.png`,
    sand_hill: `${CONFIG.PROTECTED_IMAGE_URL}/crops/sand_hill.png`,
    soil_dry: `${CONFIG.PROTECTED_IMAGE_URL}/crops/soil_dry.png`,
    soil_not_fertile: `${CONFIG.PROTECTED_IMAGE_URL}/crops/soil_not_fertile.png`,
    soil2: `${CONFIG.PROTECTED_IMAGE_URL}/crops/soil2.png`,
  },
  //Animals
  animals: {
    boxChicken: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/box_chicken.png`,
    hungryChicken: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/hungry_2.gif`,
    happyChicken: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/happy_2.gif`,
    sadChicken: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/sad_2.gif`,
    walkingChickenSheet: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/walking_sheet_2.png`,
    sleepingChicken: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/sleeping_2.gif`,
    chickenShadow: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/chicken_shadow.png`,
    layingEggSheet: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/laying-egg-sheet_2.png`,
    wheatOnGround: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/wheat_2.png`,

    // New Animals
    chickenIdle: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/idle_chicken.gif`,
    chickenAsleep: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/sleeping_chicken.gif`,
    chickenReady: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/ready.webp`,
    chickenSick: `${CONFIG.PROTECTED_IMAGE_URL}/animals/chickens/sick.webp`,
    cowIdle: `${CONFIG.PROTECTED_IMAGE_URL}/animals/cows/idle.webp`,
    cowReady: `${CONFIG.PROTECTED_IMAGE_URL}/animals/cows/ready.webp`,
    cowSleeping: `${CONFIG.PROTECTED_IMAGE_URL}/animals/cows/sleeping.webp`,
    cowFed: `${CONFIG.PROTECTED_IMAGE_URL}/animals/cows/fed.webp`,
    cowSick: `${CONFIG.PROTECTED_IMAGE_URL}/animals/cows/sick.webp`,
    sheepIdle: `${CONFIG.PROTECTED_IMAGE_URL}/animals/sheep/idle.webp`,
    sheepReady: `${CONFIG.PROTECTED_IMAGE_URL}/animals/sheep/ready.webp`,
    sheepSleeping: `${CONFIG.PROTECTED_IMAGE_URL}/animals/sheep/sleeping.webp`,
    sheepFed: `${CONFIG.PROTECTED_IMAGE_URL}/animals/sheep/fed.webp`,
    sheepSick: `${CONFIG.PROTECTED_IMAGE_URL}/animals/sheep/sick.webp`,

    bird: `${CONFIG.PROTECTED_IMAGE_URL}/animals/bird_sheet.png`,
  },
  animalFoods: {
    hay: `${CONFIG.PROTECTED_IMAGE_URL}/animals/foods/hay.webp`,
    kernel_blend: `${CONFIG.PROTECTED_IMAGE_URL}/animals/foods/kernel_blend_v2.webp`,
    nutribarley: `${CONFIG.PROTECTED_IMAGE_URL}/animals/foods/nutri_barley_v2.webp`,
    mixed_grain: `${CONFIG.PROTECTED_IMAGE_URL}/animals/foods/mixed_grain_v2.webp`,
    fish_oil: `${CONFIG.PROTECTED_IMAGE_URL}/animals/foods/fish_oil.webp`,
    barn_delight: `${CONFIG.PROTECTED_IMAGE_URL}/animals/foods/barn_delight.webp`,
    omnifeed: `${CONFIG.PROTECTED_IMAGE_URL}/animals/foods/omnifeed.webp`,
    grinder: `${CONFIG.PROTECTED_IMAGE_URL}/animals/foods/grinder_icon.webp`,
  },
  crafting: {
    cushion: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/cushion.webp`,
    timber: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/timber.webp`,
    beeBox: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/bee_box.webp`,
    crimsteel: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/crimsteel.webp`,
    merinoCushion: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/merino_cushion.webp`,
    kelpFibre: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/kelp_fibre.webp`,
    hardenedLeather: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/hardened_leather.webp`,
    syntheticFabric: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/synthetic_fabric.webp`,
    oceansTreasure: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/oceans_treasure_2.webp`,
    royalBedding: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/royal_bedding.webp`,
    royalOrnament: `${CONFIG.PROTECTED_IMAGE_URL}/crafting/royal_ornament.webp`,
  },
  //VFXs
  vfx: {
    blinking: `${CONFIG.PROTECTED_IMAGE_URL}/vfx/blinking.png`,
  },
  //FXs
  fx: {
    sparkle: `${CONFIG.PROTECTED_IMAGE_URL}/fx/sparkle2.gif`,
  },
  //Fruits
  fruit: {
    apple_seed: `${CONFIG.PROTECTED_IMAGE_URL}/fruit/apple/apple_seed.png`,
    apple_tree: `${CONFIG.PROTECTED_IMAGE_URL}/fruit/apple/apple_tree.png`,
    orangeTree: `${CONFIG.PROTECTED_IMAGE_URL}/fruit/orange/orange_tree.png`,
    blueberryBush: `${CONFIG.PROTECTED_IMAGE_URL}/fruit/blueberry/blueberry_bush.png`,
    harvestedTree: `${CONFIG.PROTECTED_IMAGE_URL}/fruit/harvested_tree.png`,
    harvestedBush: `${CONFIG.PROTECTED_IMAGE_URL}/fruit/harvested_bush.png`,
    deadTree: `${CONFIG.PROTECTED_IMAGE_URL}/fruit/dead_tree.webp`,
    bushShrub: `${CONFIG.PROTECTED_IMAGE_URL}/fruit/bush_shrub.png`,
  },
  //Brand
  brand: {
    landing: `${CONFIG.PROTECTED_IMAGE_URL}/brand/landing.webp`,
    greenBg: `${CONFIG.PROTECTED_IMAGE_URL}/brand/green_bg.png`,
    logo: `${CONFIG.PROTECTED_IMAGE_URL}/brand/logo_v2.png`,
    easterlogo: `${CONFIG.PROTECTED_IMAGE_URL}/brand/easterlogo.png`,
  },
  //Building
  building: {
    smoke: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/smoke.gif`,
    wishingwell: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/wishing_well.png`,
    bountyBoard: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/bounty_board.png`,
    //BASIC
    firePit: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/fire_pit.png`,
    kitchen: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/kitchen.png`,
    market: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/bettys_market.png`,
    townCenter: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/town_center.png`,
    workbench: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/workbench.png`,
    tent: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/tent.png`,
    well: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/well1.png`,
    chickenHouse: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/hen_house.png`,
    bakery: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/bakery.png`,
    deli: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/deli.png`,
    greenhouse: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/greenhouse.webp`,
    smoothieShack: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/smoothie_shack_background.webp`,
    smoothieShackDesk: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/smoothie_shack_desk.webp`,
    toolshed: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/toolshed.png`,
    warehouse: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/warehouse.png`,
    fruitPatchDirt: `${CONFIG.PROTECTED_IMAGE_URL}/fruit/fruit_patch.png`,
    barn: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/barn_sm.webp`,
    feederMachine: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/feeder_machine.webp`,

    //DESERT
    desertFirePit: `${CONFIG.PROTECTED_IMAGE_URL}/desert/buildings/fire_pit.webp`,
    desertBakery: `${CONFIG.PROTECTED_IMAGE_URL}/desert/buildings/bakery.webp`,
    desertDeli: `${CONFIG.PROTECTED_IMAGE_URL}/desert/buildings/deli.webp`,
    desertChickenHouse: `${CONFIG.PROTECTED_IMAGE_URL}/desert/buildings/hen_house.webp`,
    desertKitchen: `${CONFIG.PROTECTED_IMAGE_URL}/desert/buildings/kitchen.webp`,
    desertHouse: `${CONFIG.PROTECTED_IMAGE_URL}/desert/buildings/manor.webp`,
    desertMarket: `${CONFIG.PROTECTED_IMAGE_URL}/desert/buildings/bettys_market.webp`,
    desertSmoothieShack: `${CONFIG.PROTECTED_IMAGE_URL}/desert/buildings/smoothie_shack_background.webp`,
    desertWorkbench: `${CONFIG.PROTECTED_IMAGE_URL}/desert/buildings/workbench.webp`,
    desertFruitPatchDirt: `${CONFIG.PROTECTED_IMAGE_URL}/desert/fruit/fruit_patch.webp`,
    desertEmptyFlowerBed: `${CONFIG.PROTECTED_IMAGE_URL}/desert/flowers/empty.webp`,
    desertDirt: `${CONFIG.PROTECTED_IMAGE_URL}/desert/sfts/dirt_path.webp`,

    auction_floor: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/auction_floor.png`,
    blacksmith_building: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/blacksmith_building.gif`,
    farmersMarket: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/farmersMarket.png`,
    decorationsBuilding: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/decorations.png`,
    garbage: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/garbage.png`,
    garbage_stall: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/garbage_stall.png`,

    //Composter
    basicComposter: `${CONFIG.PROTECTED_IMAGE_URL}/composters/composter_basic.png`,
    basicComposting: `${CONFIG.PROTECTED_IMAGE_URL}/composters/composter_basic_closed.png`,
    basicReady: `${CONFIG.PROTECTED_IMAGE_URL}/composters/composter_basic_ready.png`,
    advancedComposter: `${CONFIG.PROTECTED_IMAGE_URL}/composters/composter_advanced.png`,
    advancedComposting: `${CONFIG.PROTECTED_IMAGE_URL}/composters/composter_advanced_closed.png`,
    advancedReady: `${CONFIG.PROTECTED_IMAGE_URL}/composters/composter_advanced_ready.png`,
    expertComposter: `${CONFIG.PROTECTED_IMAGE_URL}/composters/composter_expert.png`,
    expertComposting: `${CONFIG.PROTECTED_IMAGE_URL}/composters/composter_expert_closed.png`,
    expertReady: `${CONFIG.PROTECTED_IMAGE_URL}/composters/composter_expert_ready.png`,

    //Crop_Machine
    plantingCropMachine: `${CONFIG.PROTECTED_IMAGE_URL}/cropMachine/stage2_collector_seed_planting_sheet.webp`,
    sproutingCropMachine: `${CONFIG.PROTECTED_IMAGE_URL}/cropMachine/stage3_collector_sprout_sheet.webp`,
    maturingCropMachine: `${CONFIG.PROTECTED_IMAGE_URL}/cropMachine/stage4_collector_mature_plants_sheet.webp`,
    harvestingCropMachine: `${CONFIG.PROTECTED_IMAGE_URL}/cropMachine/stage5_collector_cut_plants_sheet.webp`,
    harvestedCropsImage: `${CONFIG.PROTECTED_IMAGE_URL}/cropMachine/readyCrops.webp`,
    idleMachine: `${CONFIG.PROTECTED_IMAGE_URL}/cropMachine/stage1_collector_empty.webp`,
    cropMachine: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/crop_machine.wep.webp`,
    shadowCropMachine: `${CONFIG.PROTECTED_IMAGE_URL}/cropMachine/shadow.webp`,

    // Animal Houses
    henHouseLevel1: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/hen_house_1.webp`,
    henHouseLevel2: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/hen_house_2.webp`,
    henHouseLevel3: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/hen_house_3.webp`,
    barnLevel1: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/barn_1.webp`,
    barnLevel2: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/barn_2.webp`,
    barnLevel3: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/barn_3.webp`,

    //Bumpkin Houses
    house: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/house.png`,
    manor: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/manor.png`,
  },
  //Icons
  icons: {
    upgrade_disc: `${CONFIG.PROTECTED_IMAGE_URL}/icons/upgrade_disc.webp`,
    angry: `${CONFIG.PROTECTED_IMAGE_URL}/icons/angry.png`,
    arrow_down: `${CONFIG.PROTECTED_IMAGE_URL}/icons/arrow_down.png`,
    arrow_left: `${CONFIG.PROTECTED_IMAGE_URL}/icons/arrow_left.png`,
    arrow_right: `${CONFIG.PROTECTED_IMAGE_URL}/icons/arrow_right.png`,
    arrow_up: `${CONFIG.PROTECTED_IMAGE_URL}/icons/arrow_up.png`,
    basket: `${CONFIG.PROTECTED_IMAGE_URL}/icons/basket.png`,
    cancel: `${CONFIG.PROTECTED_IMAGE_URL}/icons/cancel.png`,
    close: `${CONFIG.PROTECTED_IMAGE_URL}/icons/close.png`,
    confirm: `${CONFIG.PROTECTED_IMAGE_URL}/icons/confirm.png`,
    disc_large: `${CONFIG.PROTECTED_IMAGE_URL}/icons/disc_large.png`,
    disc: `${CONFIG.PROTECTED_IMAGE_URL}/icons/disc.png`,
    drag: `${CONFIG.PROTECTED_IMAGE_URL}/icons/drag.png`,
    dragging: `${CONFIG.PROTECTED_IMAGE_URL}/icons/dragging.png`,
    expand: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expand.png`,
    expression_stress: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_stress.png`,
    expression_alerted: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_alerted.png`,
    expression_chat: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_chat.png`,
    expression_confused: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_confused.png`,
    expression_ready: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_confused-1.png`,
    fish: `${CONFIG.PROTECTED_IMAGE_URL}/icons/fish.png`,
    hammer: `${CONFIG.PROTECTED_IMAGE_URL}/icons/hammer.png`,
    heart: `${CONFIG.PROTECTED_IMAGE_URL}/icons/heart.png`,
    helios: `${CONFIG.PROTECTED_IMAGE_URL}/icons/helios_icon.png`,
    indicator: `${CONFIG.PROTECTED_IMAGE_URL}/icons/indicator.png`,
    plant: `${CONFIG.PROTECTED_IMAGE_URL}/icons/plant.png`,
    player_small: `${CONFIG.PROTECTED_IMAGE_URL}/icons/player_small.png`,
    player: `${CONFIG.PROTECTED_IMAGE_URL}/icons/player.png`,
    sad: `${CONFIG.PROTECTED_IMAGE_URL}/icons/sad.png`,
    search: `${CONFIG.PROTECTED_IMAGE_URL}/icons/search.png`,
    seedling: `${CONFIG.PROTECTED_IMAGE_URL}/icons/seedling.png`,
    seeds: `${CONFIG.PROTECTED_IMAGE_URL}/icons/seeds.png`,
    shop: `${CONFIG.PROTECTED_IMAGE_URL}/icons/shop.png`,
    sleeping: `${CONFIG.PROTECTED_IMAGE_URL}/icons/sleeping.webp`,
    stopwatch: `${CONFIG.PROTECTED_IMAGE_URL}/icons/stopwatch.png`,
    sunflorea: `${CONFIG.PROTECTED_IMAGE_URL}/icons/sunflorea.png`,
    sword: `${CONFIG.PROTECTED_IMAGE_URL}/icons/sword.png`,
    timer: `${CONFIG.PROTECTED_IMAGE_URL}/icons/timer.png`,
    treasure: `${CONFIG.PROTECTED_IMAGE_URL}/icons/treasure_icon.png`,
    water: `${CONFIG.PROTECTED_IMAGE_URL}/icons/water.png`,
    happy: `${CONFIG.PROTECTED_IMAGE_URL}/icons/happy.png`,
    neutral: `${CONFIG.PROTECTED_IMAGE_URL}/icons/neutral.png`,
    stressed: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_stress.png`,
    death: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_attack.png`,
    plus: `${CONFIG.PROTECTED_IMAGE_URL}/icons/plus.png`,
    minus: `${CONFIG.PROTECTED_IMAGE_URL}/icons/minus.png`,
    wardrobe: `${CONFIG.PROTECTED_IMAGE_URL}/icons/wardrobe.png`,
    chevron_down: `${CONFIG.PROTECTED_IMAGE_URL}/icons/chevron_down.png`,
    chevron_right: `${CONFIG.PROTECTED_IMAGE_URL}/icons/chevron_right.png`,
    dig_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/dig_icon.png`,
    plant_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/plant_icon.png`,
    chop_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/chop_icon.png`,
    click_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/click_icon.png`,
    fish_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/fish_icon.png`,
    mine_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/mine_icon.png`,
    wood_mine_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/wood_mine_icon.png`,
    iron_mine_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/iron_mine_icon.png`,
    money_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/money_icon.png`,
    settings: `${CONFIG.PROTECTED_IMAGE_URL}/icons/settings.png`,
    sound_on: `${CONFIG.PROTECTED_IMAGE_URL}/icons/sound_on.png`,
    lock: `${CONFIG.PROTECTED_IMAGE_URL}/skills/lock.png`,
    powerup: `${CONFIG.PROTECTED_IMAGE_URL}/icons/level_up.png`,
    lightning: `${CONFIG.PROTECTED_IMAGE_URL}/icons/lightning.png`,
    xpIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/xp.png`,
    worldIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/world.png`,
    tradeIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/trade.png`,
    playIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/play.png`,
    decorationbush: `${CONFIG.PROTECTED_IMAGE_URL}/icons/decoration.png`,
    suspicious: `${CONFIG.PROTECTED_IMAGE_URL}/icons/decoration.png`,
    mouse: `${CONFIG.PROTECTED_IMAGE_URL}/icons/mouse.png`,
    hank: `${CONFIG.PROTECTED_IMAGE_URL}/icons/hank.png`,
    pete: `${CONFIG.PROTECTED_IMAGE_URL}/icons/pete.png`,
    //Social Icons
    polygonIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/polygon-token.png`,
    walletIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/wallet.png`,
    phantomIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/phantom.svg`,
    okxIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/okx.svg`,
    cryptoComIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/crypto-com-logo.svg`,
    bitgetIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/bitget_logo.svg`,
    googleIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/sign_in_with_google.svg`,
    wechatIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/wechat.png`,
    //Buildings Icon
    marketIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/market_icon.png`,
    firePitIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/fire_pit_icon.png`,
    workbenchIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/workbench_icon.png`,
    kitchenIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/kitchen_icon.png`,
    henHouseIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/hen_house_icon.png`,
    bakeryIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/bakery_icon.png`,
    deliIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/deli_icon.png`,
    smoothieIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/smoothie_shack_icon.png`,
    toolshedIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/toolshed_icon.png`,
    warehouseIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/warehouse_icon.png`,
    greenhouseIcon: `${CONFIG.PROTECTED_IMAGE_URL}/buildings/icons/greenhouse_icon.webp`,
    upgradeBuildingIcon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/upgrade_building.webp`,
  },
  //NPCs
  npcs: {
    hank_swimming: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/hank_swimming.webp`,
    betty: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/betty.gif`,
    bumpkin: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/idle.gif`,
    fisherman: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/fisherman.gif`,
    fishing_sheet: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/fishing_sheet.png`,
    female_fisher: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/female_fisher.png`,
    goblin_carry: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_carry.gif`,
    goblin_dig: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_dig.gif`,
    goblin_doing: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_doing.gif`,
    goblin_farting: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_farting.gif`,
    goblin_hammering: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_hammering.gif`,
    goblin_hammering_sheet: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_hammering_sheet.png`,
    goblinHead: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_head.png`,
    goblin_jumping: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_jumping.gif`,
    goblin_mining: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_mining.gif`,
    goblin_swimming: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_swimming.gif`,
    goblinSnorkling: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_snorkling.gif`,
    goblin_treasure: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_treasure.gif`,
    goblin_treasure_sheet: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_treasure_sheet.png`,
    goblin_watering: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_watering.gif`,
    goblin: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin.gif`,
    goblin_female: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_female.gif`,
    goblin_chef: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_chef.gif`,
    goblin_chef_doing: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_chef_doing.gif`,
    goblin_digger: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_digger.gif`,
    goblin_farmer: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_farmer.gif`,
    goblin_head: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_head.gif`,
    goblin_jump_rusty_shovel: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_jump_rusty_shovel.gif`,
    pirate_goblin: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/pirate_goblin.gif`,
    human_carry: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/human_carry.gif`,
    idle: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/idle.gif`,
    minting: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/minting.gif`,
    moonseeker_death: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton_death.gif`,
    moonseeker_walk: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton_walk.gif`,
    moonseeker2: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton2.png`,
    moonseeker3: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton3.png`,
    moonseeker4: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton4.png`,
    moonseeker5: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton5.png`,
    exotic_girl: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/exotic_girl.gif`,
    silhouette: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/silhouette.webp`,
    swimmer: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/swimmer.gif`,
    synced: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/synced.gif`,
    syncing: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/syncing.gif`,
    sunflorian: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/lost_sunflorian.gif`,
    artisian: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/artisian.gif`,
    artisianDoing: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/artisian_doing.gif`,
    smoothieChef: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/smoothie.gif`,
    smoothieChefMaking: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/smoothie_making.gif`,
    firePit_npc: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/cook.gif`,
    firePit_npcDoing: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/cook_doing.gif`,
    chef: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/chef.gif`,
    chef_doing: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/chef_doing.gif`,
    blacksmith_npc: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/blacksmith.gif`,
    trivia: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/trivia.gif`,
    humanDeath: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/human_death.gif`,
    suspiciousGoblin: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/suspicious_goblin.gif`,
    watering: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/watering.gif`,
    wheat_goblin: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/wheat_goblin.gif`,
  },
  //SFTS that uses SunnySide as base
  sfts: {
    easterBush: `${CONFIG.PROTECTED_IMAGE_URL}/sfts/easter_bush.gif`,
    easterBushShadow: `${CONFIG.PROTECTED_IMAGE_URL}/sfts/easter_bush_shadow.png`,
    dirt: `${CONFIG.PROTECTED_IMAGE_URL}/sfts/dirt_path.png`,
    //Potion House Exotic Crops
    adirondackPotato: `${CONFIG.PROTECTED_IMAGE_URL}/potion_house/adirondack_potato.png`,
    goldenHelios: `${CONFIG.PROTECTED_IMAGE_URL}/potion_house/golden_helios.png`,
    chiogga: `${CONFIG.PROTECTED_IMAGE_URL}/potion_house/chiogga.png`,
    blackMagic: `${CONFIG.PROTECTED_IMAGE_URL}/potion_house/black_magic.png`,
    purpleCauliflower: `${CONFIG.PROTECTED_IMAGE_URL}/potion_house/purple_cauliflower.png`,
    whiteCarrot: `${CONFIG.PROTECTED_IMAGE_URL}/potion_house/white_carrot.png`,
    wartyGoblinPumpkin: `${CONFIG.PROTECTED_IMAGE_URL}/potion_house/warty_goblin_pumpkin.png`,
  },
  //Resources
  resource: {
    // Animals
    chicken: `${CONFIG.PROTECTED_IMAGE_URL}/resources/animals/chicken.png`,
    egg: `${CONFIG.PROTECTED_IMAGE_URL}/resources/animals/egg.png`,
    feather: `${CONFIG.PROTECTED_IMAGE_URL}/resources/animals/feather.webp`,
    leather: `${CONFIG.PROTECTED_IMAGE_URL}/resources/animals/leather.webp`,
    merino_wool: `${CONFIG.PROTECTED_IMAGE_URL}/resources/animals/merino_wool.webp`,
    milk: `${CONFIG.PROTECTED_IMAGE_URL}/resources/animals/milk.webp`,
    wool: `${CONFIG.PROTECTED_IMAGE_URL}/resources/animals/wool.webp`,

    cow: `${CONFIG.PROTECTED_IMAGE_URL}/resources/cow.png`,
    //Treasures
    sand: `${CONFIG.PROTECTED_IMAGE_URL}/resources/treasures/sand.webp`,
    clam_shell: `${CONFIG.PROTECTED_IMAGE_URL}/resources/treasures/clam_shell.webp`,
    coral: `${CONFIG.PROTECTED_IMAGE_URL}/resources/treasures/coral.png`,
    crab: `${CONFIG.PROTECTED_IMAGE_URL}/resources/treasures/crab.png`,
    starfish: `${CONFIG.PROTECTED_IMAGE_URL}/resources/treasures/starfish.png`,
    pirate_bounty: `${CONFIG.PROTECTED_IMAGE_URL}/resources/treasures/pirate_bounty.webp`,
    sea_cucumber: `${CONFIG.PROTECTED_IMAGE_URL}/resources/treasures/sea_cucumber.png`,
    //Resources
    diamond: `${CONFIG.PROTECTED_IMAGE_URL}/resources/diamond.png`,
    magic_mushroom: `${CONFIG.PROTECTED_IMAGE_URL}/resources/magic_mushroom.png`,
    boulder: `${CONFIG.PROTECTED_IMAGE_URL}/resources/rare_mine.png`,
    small_stone: `${CONFIG.PROTECTED_IMAGE_URL}/resources/small_stone.png`,
    stone: `${CONFIG.PROTECTED_IMAGE_URL}/resources/stone.png`,
    stump: `${CONFIG.PROTECTED_IMAGE_URL}/resources/stump.png`,
    tree: `${CONFIG.PROTECTED_IMAGE_URL}/resources/tree.png`,
    shakeSheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/tree/shake_sheet.png`,
    springShakeSheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/tree/spring_shake_sheet.png`,
    spring_tree: `${CONFIG.PROTECTED_IMAGE_URL}/resources/flower_tree.png`,
    choppedSheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/tree/chopped_sheet.png`,
    tree_stump: `${CONFIG.PROTECTED_IMAGE_URL}/resources/tree/stump.png`,
    wild_mushroom: `${CONFIG.PROTECTED_IMAGE_URL}/resources/wild_mushroom.png`,
    wild_mushroom_sheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/wild_mushroom_sheet.png`,
    magic_mushroom_sheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/magic_mushroom_sheet.png`,
    wood: `${CONFIG.PROTECTED_IMAGE_URL}/resources/wood.png`,
    gold_rock: `${CONFIG.PROTECTED_IMAGE_URL}/resources/gold_rock.png`,
    goldStone: `${CONFIG.PROTECTED_IMAGE_URL}/resources/gold_small.png`,
    ironStone: `${CONFIG.PROTECTED_IMAGE_URL}/resources/iron_small.png`,
    stone_small: `${CONFIG.PROTECTED_IMAGE_URL}/resources/stone_small.png`,
    stone_rock: `${CONFIG.PROTECTED_IMAGE_URL}/resources/stone_rock.png`,
    iron_rock: `${CONFIG.PROTECTED_IMAGE_URL}/resources/iron_rock.png`,
    goldStrikeSheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/gold/gold_rock_spark.png`,
    ironStrikeSheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/iron/iron_rock_spark.png`,
    stoneStrikeSheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/stone/stone_rock_spark.png`,
    goldDropSheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/gold/gold_rock_drop.png`,
    ironDropSheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/iron/iron_rock_drop.png`,
    stoneDropSheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/stone/stone_rock_drop.png`,
    land: `${CONFIG.PROTECTED_IMAGE_URL}/resources/land.png`,
    plot: `${CONFIG.PROTECTED_IMAGE_URL}/resources/plot.png`,
    fruitPatch: `${CONFIG.PROTECTED_IMAGE_URL}/resources/fruit_patch.png`,
  },
  //Tools
  tools: {
    axe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/axe.png`,
    fishing_rod: `${CONFIG.PROTECTED_IMAGE_URL}/tools/fishing_rod.png`,
    hammer: `${CONFIG.PROTECTED_IMAGE_URL}/tools/hammer.png`,
    iron_pickaxe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/iron_pickaxe.png`,
    gold_pickaxe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/gold_pickaxe.png`,
    power_shovel: `${CONFIG.PROTECTED_IMAGE_URL}/tools/power_shovel.png`,
    rusty_shovel: `${CONFIG.PROTECTED_IMAGE_URL}/tools/rusty_shovel.png`,
    sand_shovel: `${CONFIG.PROTECTED_IMAGE_URL}/tools/sand_shovel.png`,
    shovel: `${CONFIG.PROTECTED_IMAGE_URL}/tools/shovel.png`,
    stone_pickaxe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/stone_pickaxe.png`,
    wood_pickaxe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/wood_pickaxe.png`,
  },
  //UIs
  ui: {
    add_button: `${CONFIG.PROTECTED_IMAGE_URL}/ui/add-button.png`,
    cursor: `${CONFIG.PROTECTED_IMAGE_URL}/ui/cursor.png`,
    round_button: `${CONFIG.PROTECTED_IMAGE_URL}/ui/round_button.png`,
    round_button_pressed: `${CONFIG.PROTECTED_IMAGE_URL}/ui/round_button_pressed.png`,
    select_box: `${CONFIG.PROTECTED_IMAGE_URL}/ui/select_box.png`,
    green_bar_0: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_00.png`,
    green_bar_1: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_01.png`,
    green_bar_2: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_02.png`,
    green_bar_3: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_03.png`,
    green_bar_4: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_04.png`,
    green_bar_5: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_05.png`,
    green_bar_6: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_06.png`,
    dot: `${CONFIG.PROTECTED_IMAGE_URL}/ui/select_dots.png`,
    primaryButton: `${CONFIG.PROTECTED_IMAGE_URL}/ui/light_button.png`,
    primaryButtonPressed: `${CONFIG.PROTECTED_IMAGE_URL}/ui/light_button_pressed.png`,
    greyButton: `${CONFIG.PROTECTED_IMAGE_URL}/ui/grey_button.png`,
    site_bg: `${CONFIG.PROTECTED_IMAGE_URL}/ui/site_bg.png`,
    more: `${CONFIG.PROTECTED_IMAGE_URL}/ui/more.png`,
    grey_background: `${CONFIG.PROTECTED_IMAGE_URL}/ui/grey_background.png`,
    coins: `${CONFIG.PROTECTED_IMAGE_URL}/ui/coins.png`,
    coinsImg: `${CONFIG.PROTECTED_IMAGE_URL}/ui/coins.png`,
    speechBubble: `${CONFIG.PROTECTED_IMAGE_URL}/ui/speech_border.png`,
    speechBubbleBottom: `${CONFIG.PROTECTED_IMAGE_URL}/ui/speech_bubble_bottom.webp`,
    reel: `${CONFIG.PROTECTED_IMAGE_URL}/ui/reel.png`,
    disc_cancel: `${CONFIG.PROTECTED_IMAGE_URL}/ui/disc_cancel.png`,

    //Panels
    grayBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/gray_border.png`,
    orangeBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/orange_border.png`,
    redBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/danger_border.png`,
    blueBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/blue_border.png`,
    formulaBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/formula_border.png`,
    calmBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/calm_border.png`,
    vibrantBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/vibrant_border.png`,
    lightBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/light_border.png`,
    darkBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/dark_border.png`,
    roomBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/room_border.webp`,
    tableBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/table_border2.webp`,
    greenBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/green_border.png`,
    tabBorderStart: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/tab_border_start.png`,
    tabBorderMiddle: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/tab_border_middle.png`,
    tabBorderVerticalStart: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/vertical_tab_border_start.png`,
    tabBorderVerticalMiddle: `${CONFIG.PROTECTED_IMAGE_URL}/ui/panel/vertical_tab_border_middle.png`,
    speechBubbleBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/speech_bubble.webp`,
    speechBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/speech_border.png`,
    tableTop: `${CONFIG.PROTECTED_IMAGE_URL}/ui/table_top.webp`,
    heartBg: `${CONFIG.PROTECTED_IMAGE_URL}/ui/heart_bg.png`,
    //Select
    selectBoxBL: `${CONFIG.PROTECTED_IMAGE_URL}/ui/select/selectbox_bl.png`,
    selectBoxBR: `${CONFIG.PROTECTED_IMAGE_URL}/ui/select/selectbox_br.png`,
    selectBoxTL: `${CONFIG.PROTECTED_IMAGE_URL}/ui/select/selectbox_tl.png`,
    selectBoxTR: `${CONFIG.PROTECTED_IMAGE_URL}/ui/select/selectbox_tr.png`,
    //Profile
    progressBarSprite: `${CONFIG.PROTECTED_IMAGE_URL}/ui/profile/progress_bar_sprite.png`,
    whiteBg: `${CONFIG.PROTECTED_IMAGE_URL}/ui/profile/bg.png`,
    //ProgressBar
    emptyBar: `${CONFIG.PROTECTED_IMAGE_URL}/ui/progress/empty_bar.png`,
    progressBarBorder: `${CONFIG.PROTECTED_IMAGE_URL}/ui/progress/progress_bar_border.png`,
    transparentBarEdge: `${CONFIG.PROTECTED_IMAGE_URL}/ui/progress/transparent_bar_edge.png`,
    transparentBarLong: `${CONFIG.PROTECTED_IMAGE_URL}/ui/progress/transparent_bar_long.png`,
    // Toggle
    turn_off: `${CONFIG.PROTECTED_IMAGE_URL}/ui/toggle/turn_off.png`,
    turn_on: `${CONFIG.PROTECTED_IMAGE_URL}/ui/toggle/turn_on.png`,
  },
  //Decorations
  decorations: {
    waterMovement: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/water_movement.png`,
    ocean: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/ocean.webp`,
    cossies: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/cossies.png`,
    bush: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/bush.png`,
    springBush: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/flower_bush.png`,
    treasure_chest: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/treasure_chest.png`,
    treasure_chest_opened: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/treasure_opened.png`,
    skull: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/skull.webp`,
    painting: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/painting.png`,
    rug: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/rug.png`,
    wardrobe: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/wardrobe.png`,
    bed: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/bed.png`,
    warSkull: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/war_skulls.png`,
    warTombstone: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/war_tombstone.png`,
    whiteTulips: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/white_tulips.png`,
    pottedSunflower: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/potted_sunflower.png`,
    pottedPumpkin: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/potted_pumpkin.webp`,
    pottedPotato: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/potted_potato.png`,
    fence: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence.png`,
    stoneFence: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stone_fence.png`,
    cactus: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/cactus.png`,
    pineTree: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/pine_tree.png`,
    crowRock: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/crow_rock.webp`,
    spookyTree: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/spooky_tree.png`,
    shroomGlow: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/shroom_glow.png`,
    bonniesTombstone: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/bonnies_tombstone.png`,
    grubnashTombstone: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/grubnash_tombstone.png`,
    planter_box: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/planter_box.webp`,
    raft: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/raft.png`,
    rewards_raft: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/rewards_raft.png`,
    //Potion House
    orangeBottle: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/orange_bottle.webp`,
    blueBottle: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/blue_bottle.webp`,
    pinkBottle: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/pink_bottle.webp`,
    blackBottle: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/black_bottle.webp`,
    greenBottle: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/green_bottle.webp`,
    mustardBottle: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/mustard_bottle.webp`,
    whiteBottle: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/white_bottle.webp`,
    //Fence
    /**
     * Naming is based on which sides have borders
     * Same as padding/margin order. Top, right, down, left
     * 0_1_1_0 = No top border, right border, bottom border and no bottom border
     */
    woodFenceFullEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/1_1_1_1.png`,
    woodFenceNoEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/0_0_0_0.png`,
    woodFenceTopAndBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/1_0_1_0.png`,
    woodFenceTopLeftAndBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/1_0_1_1.png`,
    woodFenceTopRightAndBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/1_1_1_0.png`,
    woodFenceTopRightAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/1_1_0_1.png`,
    woodFenceRightBottomAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/0_1_1_1.png`,
    woodFenceRightAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/0_1_0_1.png`,

    woodFenceRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/0_1_0_0.png`,
    woodFenceBottomEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/0_0_1_0.png`,
    woodFenceTopEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/1_0_0_0.png`,
    woodFenceLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/0_0_0_1.png`,

    woodFenceTopAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/1_0_0_1.png`,
    woodFenceBottomAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/0_0_1_1.png`,
    woodFenceTopAndRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/1_1_0_0.png`,
    woodFenceBottomAndRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/fence/0_1_1_0.png`,

    //Stone Fence
    stoneTopAndRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/top_right.png`,
    stoneTopAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/top_left.png`,
    stoneBottomAndLeftEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/bottom_left.png`,
    stoneBottomAndRightEdge: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/bottom_right.png`,
    stoneTopAndLeftAndRightAndBottom: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/top_left_right_bottom.png`,
    stoneTopAndLeftAndRight: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/top_left_right.png`,
    stoneBottomAndLeftAndRight: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/bottom_left_right.png`,
    stoneRightTopAndBottom: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/right_top_bottom.png`,
    stoneLeftTopAndBottom: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/left_top_bottom.png`,
    stoneBottom: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/bottom.png`,

    stoneHorizontalOne: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/x_1.png`,
    stoneHorizontalTwo: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/x_2.png`,
    stoneHorizontalThree: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/x_3.png`,
    stoneHorizontalFour: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/x_4.png`,

    stoneVerticalOne: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/y_1.png`,
    stoneVerticalTwo: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/y_2.png`,
    stoneVerticalThree: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/y_3.png`,
    stoneVerticalFour: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/stoneFence/y_2.png`,
  },
  //Splash
  splash: {
    donating: `${CONFIG.PROTECTED_IMAGE_URL}/splash/goblin_donation.gif`,
  },
  //Tutorials
  tutorial: {
    animals: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/new_animals.png`,
    workbench: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/workbench.png`,
    harvesting: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/harvesting.png`,
    cooking: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/fire_pit.png`,
    videoThumbnail: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/video_thumbnail.png`,
    plazaScreenshot: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/plaza_screenshot1.png`,
    composting: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/composting.png`,
    fishingTutorial: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/fishing.png`,
    fishingCodex: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/fishing_codex.png`,
    farmHandImage: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/farmHands.png`,
    flowersTutorial: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/flowers.webp`,
    beeTutorial: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/bees.webp`,
    craftingBox: `${CONFIG.PROTECTED_IMAGE_URL}/tutorials/crafting_box.webp`,
  },
};
