/**
 * Sunnyside raw assets, crops and tiles are not stored in this repository
 * If you want access to these, you must download the asset pack from: https://danieldiggle.itch.io/sunnyside
 */

import { CONFIG } from "lib/config";

export const SUNNYSIDE = {
  soil: {
    sand_dug: `${CONFIG.PROTECTED_IMAGE_URL}/crops/sand_dug.png`,
    sand_hill: `${CONFIG.PROTECTED_IMAGE_URL}/crops/sand_hill.png`,
    soil_dry: `${CONFIG.PROTECTED_IMAGE_URL}/crops/soil_dry.png`,
    soil_not_fertile: `${CONFIG.PROTECTED_IMAGE_URL}/crops/soil_not_fertile.png`,
    soil2: `${CONFIG.PROTECTED_IMAGE_URL}/crops/soil2.png`,
  },
  animals: {
    bird: `${CONFIG.PROTECTED_IMAGE_URL}/animals/bird_sheet.png`,
  },
  vfx: {
    blinking: `${CONFIG.PROTECTED_IMAGE_URL}/vfx/blinking.png`,
  },
  icons: {
    angry: `${CONFIG.PROTECTED_IMAGE_URL}/icons/angry.png`,
    arrow_down: `${CONFIG.PROTECTED_IMAGE_URL}/icons/arrow_down.png`,
    arrow_left: `${CONFIG.PROTECTED_IMAGE_URL}/icons/arrow_left.png`,
    arrow_right: `${CONFIG.PROTECTED_IMAGE_URL}/icons/arrow_right.png`,
    arrow_up: `${CONFIG.PROTECTED_IMAGE_URL}/icons/arrow_up.png`,
    basket: `${CONFIG.PROTECTED_IMAGE_URL}/icons/basket.png`,
    cancel: `${CONFIG.PROTECTED_IMAGE_URL}/icons/cancel.png`,
    close: `${CONFIG.PROTECTED_IMAGE_URL}/icons/close.png`,
    confirm: `${CONFIG.PROTECTED_IMAGE_URL}/icons/confirm.png`,
    disc_large: `${CONFIG.PROTECTED_IMAGE_URL}/icons/disc_large.png`,
    disc: `${CONFIG.PROTECTED_IMAGE_URL}/icons/disc.png`,
    drag: `${CONFIG.PROTECTED_IMAGE_URL}/icons/drag.png`,
    dragging: `${CONFIG.PROTECTED_IMAGE_URL}/icons/dragging.png`,
    expand: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expand.png`,
    expression_alerted: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_alerted.png`,
    expression_chat: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_chat.png`,
    expression_confused: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_confused.png`,
    fish: `${CONFIG.PROTECTED_IMAGE_URL}/icons/fish.png`,
    hammer: `${CONFIG.PROTECTED_IMAGE_URL}/icons/hammer.png`,
    heart: `${CONFIG.PROTECTED_IMAGE_URL}/icons/heart.png`,
    helios: `${CONFIG.PROTECTED_IMAGE_URL}/icons/helios_icon.png`,
    indicator: `${CONFIG.PROTECTED_IMAGE_URL}/icons/indicator.png`,
    plant: `${CONFIG.PROTECTED_IMAGE_URL}/icons/plant.png`,
    player_small: `${CONFIG.PROTECTED_IMAGE_URL}/icons/player_small.png`,
    player: `${CONFIG.PROTECTED_IMAGE_URL}/icons/player.png`,
    sad: `${CONFIG.PROTECTED_IMAGE_URL}/icons/sad.png`,
    search: `${CONFIG.PROTECTED_IMAGE_URL}/icons/search.png`,
    seedling: `${CONFIG.PROTECTED_IMAGE_URL}/icons/seedling.png`,
    seeds: `${CONFIG.PROTECTED_IMAGE_URL}/icons/seeds.png`,
    stopwatch: `${CONFIG.PROTECTED_IMAGE_URL}/icons/stopwatch.png`,
    sunflorea: `${CONFIG.PROTECTED_IMAGE_URL}/icons/sunflorea.png`,
    sword: `${CONFIG.PROTECTED_IMAGE_URL}/icons/sword.png`,
    timer: `${CONFIG.PROTECTED_IMAGE_URL}/icons/timer.png`,
    treasure: `${CONFIG.PROTECTED_IMAGE_URL}/icons/treasure_icon.png`,
    water: `${CONFIG.PROTECTED_IMAGE_URL}/icons/water.png`,
    happy: `${CONFIG.PROTECTED_IMAGE_URL}/icons/happy.png`,
    neutral: `${CONFIG.PROTECTED_IMAGE_URL}/icons/neutral.png`,
    stressed: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_stress.png`,
    death: `${CONFIG.PROTECTED_IMAGE_URL}/icons/expression_attack.png`,
    plus: `${CONFIG.PROTECTED_IMAGE_URL}/icons/plus.png`,
    minus: `${CONFIG.PROTECTED_IMAGE_URL}/icons/minus.png`,
    wardrobe: `${CONFIG.PROTECTED_IMAGE_URL}/icons/wardrobe.png`,
    chevron_right: `${CONFIG.PROTECTED_IMAGE_URL}/icons/chevron_right.png`,
    dig_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/dig_icon.png`,
    plant_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/plant_icon.png`,
    chop_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/chop_icon.png`,
    click_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/click_icon.png`,
    fish_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/fish_icon.png`,
    mine_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/mine_icon.png`,
    wood_mine_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/wood_mine_icon.png`,
    iron_mine_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/iron_mine_icon.png`,
    money_icon: `${CONFIG.PROTECTED_IMAGE_URL}/icons/money_icon.png`,
  },
  npcs: {
    betty: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/betty.gif`,
    bumpkin: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/idle.gif`,
    fisherman: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/fisherman.gif`,
    fishing_sheet: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/fishing_sheet.png`,
    female_fisher: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/female_fisher.png`,
    goblin_carry: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_carry.gif`,
    goblin_dig: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_dig.gif`,
    goblin_doing: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_doing.gif`,
    goblin_farting: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_farting.gif`,
    goblin_hammering: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_hammering.gif`,
    goblin_hammering_sheet: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_hammering_sheet.png`,
    goblin_jumping: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_jumping.gif`,
    goblin_mining: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_mining.gif`,
    goblin_swimming: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_swimming.gif`,
    goblin_treasure: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_treasure.gif`,
    goblin_treasure_sheet: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_treasure_sheet.png`,
    goblin_watering: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin_watering.gif`,
    goblin: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/goblin.gif`,
    human_carry: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/human_carry.gif`,
    idle: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/idle.gif`,
    moonseeker_death: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton_death.gif`,
    moonseeker_walk: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton_walk.gif`,
    moonseeker2: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton2.png`,
    moonseeker3: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton3.png`,
    moonseeker4: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton4.png`,
    moonseeker5: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/skeleton5.png`,
    swimmer: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/swimmer.gif`,
    watering: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/watering.gif`,
    wheat_goblin: `${CONFIG.PROTECTED_IMAGE_URL}/npcs/wheat_goblin.gif`,
  },
  resource: {
    chicken: `${CONFIG.PROTECTED_IMAGE_URL}/resources/chicken.png`,
    clam_shell: `${CONFIG.PROTECTED_IMAGE_URL}/resources/clam_shell.png`,
    coral: `${CONFIG.PROTECTED_IMAGE_URL}/resources/coral.png`,
    crab: `${CONFIG.PROTECTED_IMAGE_URL}/resources/crab.png`,
    diamond: `${CONFIG.PROTECTED_IMAGE_URL}/resources/diamond.png`,
    egg: `${CONFIG.PROTECTED_IMAGE_URL}/resources/egg.png`,
    magic_mushroom: `${CONFIG.PROTECTED_IMAGE_URL}/resources/magic_mushroom.png`,
    boulder: `${CONFIG.PROTECTED_IMAGE_URL}/resources/rare_mine.png`,
    pirate_bounty: `${CONFIG.PROTECTED_IMAGE_URL}/resources/pirate_bounty.webp`,
    sea_cucumber: `${CONFIG.PROTECTED_IMAGE_URL}/resources/sea_cucumber.png`,
    small_stone: `${CONFIG.PROTECTED_IMAGE_URL}/resources/small_stone.png`,
    starfish: `${CONFIG.PROTECTED_IMAGE_URL}/resources/starfish.png`,
    stone: `${CONFIG.PROTECTED_IMAGE_URL}/resources/stone.png`,
    stump: `${CONFIG.PROTECTED_IMAGE_URL}/resources/stump.png`,
    tree: `${CONFIG.PROTECTED_IMAGE_URL}/resources/tree.png`,
    spring_tree: `${CONFIG.PROTECTED_IMAGE_URL}/resources/flower_tree.png`,
    wild_mushroom: `${CONFIG.PROTECTED_IMAGE_URL}/resources/wild_mushroom.png`,
    wild_mushroom_sheet: `${CONFIG.PROTECTED_IMAGE_URL}/resources/wild_mushroom_sheet.png`,
    wood: `${CONFIG.PROTECTED_IMAGE_URL}/resources/wood.png`,
    gold_rock: `${CONFIG.PROTECTED_IMAGE_URL}/resources/gold_rock.png`,
    stone_rock: `${CONFIG.PROTECTED_IMAGE_URL}/resources/stone_rock.png`,
    iron_rock: `${CONFIG.PROTECTED_IMAGE_URL}/resources/iron_rock.png`,
    land: `${CONFIG.PROTECTED_IMAGE_URL}/resources/land.png`,
    plot: `${CONFIG.PROTECTED_IMAGE_URL}/resources/plot.png`,
    fruitPatch: `${CONFIG.PROTECTED_IMAGE_URL}/resources/fruit_patch.png`,
  },
  tools: {
    axe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/axe.png`,
    fishing_rod: `${CONFIG.PROTECTED_IMAGE_URL}/tools/fishing_rod.png`,
    hammer: `${CONFIG.PROTECTED_IMAGE_URL}/tools/hammer.png`,
    iron_pickaxe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/iron_pickaxe.png`,
    gold_pickaxe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/gold_pickaxe.png`,
    power_shovel: `${CONFIG.PROTECTED_IMAGE_URL}/tools/power_shovel.png`,
    rusty_shovel: `${CONFIG.PROTECTED_IMAGE_URL}/tools/rusty_shovel.png`,
    sand_shovel: `${CONFIG.PROTECTED_IMAGE_URL}/tools/sand_shovel.png`,
    shovel: `${CONFIG.PROTECTED_IMAGE_URL}/tools/shovel.png`,
    stone_pickaxe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/stone_pickaxe.png`,
    wood_pickaxe: `${CONFIG.PROTECTED_IMAGE_URL}/tools/wood_pickaxe.png`,
  },
  ui: {
    add_button: `${CONFIG.PROTECTED_IMAGE_URL}/ui/add-button.png`,
    cursor: `${CONFIG.PROTECTED_IMAGE_URL}/ui/cursor.png`,
    round_button: `${CONFIG.PROTECTED_IMAGE_URL}/ui/round_button.png`,
    select_box: `${CONFIG.PROTECTED_IMAGE_URL}/ui/select_box.png`,
    green_bar_0: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_00.png`,
    green_bar_1: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_01.png`,
    green_bar_2: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_02.png`,
    green_bar_3: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_03.png`,
    green_bar_4: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_04.png`,
    green_bar_5: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_05.png`,
    green_bar_6: `${CONFIG.PROTECTED_IMAGE_URL}/ui/greenbar_06.png`,
    dot: `${CONFIG.PROTECTED_IMAGE_URL}/ui/select_dots.png`,
  },
  decorations: {
    treasure_chest: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/treasure_chest.png`,
    treasure_chest_opened: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/treasure_opened.png`,
    blue_bottle: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/blue_bottle.webp`,
    orange_bottle: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/orange_bottle.webp`,
    skull: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/skull.webp`,
    painting: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/painting.png`,
    rug: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/rug.png`,
    wardrobe: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/wardrobe.png`,
    bed: `${CONFIG.PROTECTED_IMAGE_URL}/decorations/bed.png`,
  },
};
