import { SeasonWeek } from "features/game/types/game";
import { NPCBumpkin } from "features/world/scenes/BaseScene";

export type Enemy = NPCBumpkin & {
  target: {
    x: number;
    y: number;
    direction: "vertical" | "horizontal";
    duration: number;
    hold?: boolean;
    startFacingLeft?: boolean;
  };
};

export const ENEMIES: Record<SeasonWeek, Enemy[]> = {
  1: [
    {
      x: 104,
      y: 328,
      npc: "dreadhorn",
      target: {
        x: 104,
        y: 471,
        direction: "vertical",
        duration: 2000,
      },
    },
    {
      x: 57,
      y: 63,
      npc: "dreadhorn",
      target: {
        x: 294,
        y: 60,
        direction: "horizontal",
        duration: 3500,
      },
    },
    {
      x: 355,
      y: 458,
      npc: "dreadhorn",
      target: {
        x: 260,
        y: 458,
        direction: "horizontal",
        duration: 1800,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 585,
      y: 506,
      npc: "dreadhorn",
      target: {
        x: 585,
        y: 217,
        direction: "vertical",
        duration: 3500,
      },
    },
    {
      x: 89,
      y: 500,
      npc: "phantom face",
      target: {
        x: 46,
        y: 500,
        direction: "horizontal",
        duration: 1200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 518,
      y: 583,
      npc: "phantom face",
      target: {
        x: 483,
        y: 590,
        direction: "horizontal",
        duration: 900,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 130,
      y: 137,
      npc: "phantom face",
      target: {
        x: 185,
        y: 137,
        direction: "horizontal",
        duration: 1200,
        hold: true,
      },
    },
    {
      x: 342,
      y: 72,
      npc: "phantom face",
      target: {
        x: 440,
        y: 72,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
    {
      x: 412,
      y: 545,
      npc: "dreadhorn",
      target: {
        x: 435,
        y: 545,
        direction: "horizontal",
        duration: 800,
        hold: true,
      },
    },
  ],
  2: [
    {
      x: 89,
      y: 500,
      npc: "phantom face",
      target: {
        x: 46,
        y: 500,
        direction: "horizontal",
        duration: 1200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 56,
      y: 298,
      npc: "dreadhorn",
      target: {
        x: 56,
        y: 474,
        direction: "vertical",
        duration: 2400,
      },
    },
    {
      x: 139,
      y: 119,
      npc: "dreadhorn",
      target: {
        x: 296,
        y: 119,
        direction: "horizontal",
        duration: 2200,
      },
    },
    {
      x: 472,
      y: 56,
      npc: "phantom face",
      target: {
        x: 360,
        y: 81,
        direction: "horizontal",
        duration: 2000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 167,
      y: 567,
      npc: "phantom face",
      target: {
        x: 167,
        y: 600,
        direction: "vertical",
        duration: 1200,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 230,
      y: 566,
      npc: "dreadhorn",
      target: {
        x: 312,
        y: 566,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
    {
      x: 423,
      y: 328,
      npc: "dreadhorn",
      target: {
        x: 423,
        y: 517,
        direction: "vertical",
        duration: 2500,
        startFacingLeft: true,
      },
    },
    {
      x: 263,
      y: 183,
      npc: "phantom face",
      target: {
        x: 360,
        y: 183,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
  ],
  3: [
    {
      x: 279,
      y: 72,
      npc: "dreadhorn",
      target: {
        x: 279,
        y: 150,
        direction: "vertical",
        duration: 2500,
      },
    },
    {
      x: 470,
      y: 328,
      npc: "phantom face",
      target: {
        x: 375,
        y: 328,
        direction: "horizontal",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 535,
      y: 262,
      npc: "farmer flesh",
      target: {
        x: 535,
        y: 230,
        direction: "vertical",
        duration: 1500,
        hold: true,
      },
    },
    {
      x: 54,
      y: 201,
      npc: "phantom face",
      target: {
        x: 362,
        y: 201,
        direction: "horizontal",
        duration: 4500,
        hold: true,
      },
    },
    {
      x: 583,
      y: 70,
      npc: "boneyard betty",
      target: {
        x: 583,
        y: 233,
        direction: "vertical",
        duration: 3800,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 184,
      y: 519,
      npc: "dreadhorn",
      target: {
        x: 56,
        y: 535,
        direction: "horizontal",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 278,
      y: 469,
      npc: "farmer flesh",
      target: {
        x: 278,
        y: 518,
        direction: "horizontal",
        duration: 2000,
        startFacingLeft: true,
      },
    },
    {
      x: 479,
      y: 486,
      npc: "phantom face",
      target: {
        x: 520,
        y: 456,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 218,
      y: 599,
      npc: "boneyard betty",
      target: {
        x: 312,
        y: 599,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 487,
      y: 359,
      npc: "dreadhorn",
      target: {
        x: 487,
        y: 328,
        direction: "vertical",
        duration: 1500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 62,
      y: 426,
      npc: "farmer flesh",
      target: {
        x: 44,
        y: 426,
        direction: "horizontal",
        duration: 1000,
        hold: true,
        startFacingLeft: true,
      },
    },
  ],
  4: [
    {
      x: 376,
      y: 358,
      npc: "phantom face",
      target: {
        x: 522,
        y: 358,
        direction: "horizontal",
        duration: 3500,
        hold: true,
      },
    },
    {
      x: 584,
      y: 265,
      npc: "boneyard betty",
      target: {
        x: 584,
        y: 356,
        direction: "vertical",
        duration: 3000,
        startFacingLeft: true,
      },
    },
    {
      x: 520,
      y: 287,
      npc: "dreadhorn",
      target: {
        x: 520,
        y: 330,
        direction: "vertical",
        duration: 1500,
      },
    },
    {
      x: 267,
      y: 232,
      npc: "farmer flesh",
      target: {
        x: 343,
        y: 232,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
    {
      x: 154,
      y: 55,
      npc: "farmer flesh",
      target: {
        x: 258,
        y: 55,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 120,
      y: 248,
      npc: "dreadhorn",
      target: {
        x: 120,
        y: 356,
        direction: "vertical",
        duration: 3500,
      },
    },
    {
      x: 56,
      y: 344,
      npc: "boneyard betty",
      target: {
        x: 56,
        y: 422,
        direction: "vertical",
        duration: 3000,
        hold: true,
      },
    },
    {
      x: 272,
      y: 594,
      npc: "phantom face",
      target: {
        x: 291,
        y: 562,
        direction: "horizontal",
        duration: 2000,
      },
    },
    {
      x: 568,
      y: 599,
      npc: "farmer flesh",
      target: {
        x: 522,
        y: 599,
        direction: "horizontal",
        duration: 2500,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 471,
      y: 515,
      npc: "dreadhorn",
      target: {
        x: 586,
        y: 515,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 586,
      y: 535,
      npc: "farmer flesh",
      target: {
        x: 471,
        y: 535,
        direction: "horizontal",
        duration: 2500,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 106,
      y: 520,
      npc: "boneyard betty",
      target: {
        x: 129,
        y: 520,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
  ],
  5: [
    {
      x: 51,
      y: 564,
      npc: "phantom face",
      target: {
        x: 55,
        y: 599,
        direction: "vertical",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 138,
      y: 295,
      npc: "farmer flesh",
      target: {
        x: 50,
        y: 295,
        direction: "horizontal",
        duration: 2500,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 56,
      y: 339,
      npc: "boneyard betty",
      target: {
        x: 151,
        y: 339,
        direction: "horizontal",
        duration: 3000,
        hold: true,
      },
    },
    {
      x: 248,
      y: 103,
      npc: "dreadhorn",
      target: {
        x: 116,
        y: 103,
        direction: "horizontal",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 344,
      y: 248,
      npc: "phantom face",
      target: {
        x: 441,
        y: 248,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
    {
      x: 123,
      y: 232,
      npc: "phantom face",
      target: {
        x: 51,
        y: 232,
        direction: "horizontal",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 233,
      y: 87,
      npc: "boneyard betty",
      target: {
        x: 439,
        y: 87,
        direction: "horizontal",
        duration: 4700,
      },
    },
    {
      x: 567,
      y: 153,
      npc: "dreadhorn",
      target: {
        x: 502,
        y: 153,
        direction: "horizontal",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 570,
      y: 171,
      npc: "farmer flesh",
      target: {
        x: 570,
        y: 294,
        direction: "vertical",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 492,
      y: 214,
      npc: "phantom face",
      target: {
        x: 536,
        y: 241,
        direction: "vertical",
        duration: 2000,
        hold: true,
      },
    },
    {
      x: 400,
      y: 156,
      npc: "farmer flesh",
      target: {
        x: 400,
        y: 306,
        direction: "vertical",
        duration: 4700,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 344,
      y: 454,
      npc: "dreadhorn",
      target: {
        x: 273,
        y: 454,
        direction: "horizontal",
        duration: 2800,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 88,
      y: 596,
      npc: "boneyard betty",
      target: {
        x: 362,
        y: 596,
        direction: "horizontal",
        duration: 5500,
        hold: true,
      },
    },
  ],
  6: [
    {
      x: 119,
      y: 103,
      npc: "boneyard betty",
      target: {
        x: 50,
        y: 103,
        direction: "horizontal",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 184,
      y: 103,
      npc: "phantom face",
      target: {
        x: 234,
        y: 103,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 296,
      y: 180,
      npc: "dreadhorn",
      target: {
        x: 585,
        y: 180,
        direction: "horizontal",
        duration: 6500,
      },
    },
    {
      x: 496,
      y: 57,
      npc: "dreadhorn",
      target: {
        x: 496,
        y: 118,
        direction: "vertical",
        duration: 3500,
        startFacingLeft: true,
      },
    },
    {
      x: 420,
      y: 278,
      npc: "farmer flesh",
      target: {
        x: 554,
        y: 278,
        direction: "horizontal",
        duration: 4000,
      },
    },
    {
      x: 188,
      y: 279,
      npc: "farmer flesh",
      target: {
        x: 89,
        y: 279,
        direction: "horizontal",
        duration: 4000,
        startFacingLeft: true,
      },
    },
    {
      x: 171,
      y: 323,
      npc: "farmer flesh",
      target: {
        x: 171,
        y: 376,
        direction: "vertical",
        duration: 3500,
      },
    },
    {
      x: 272,
      y: 439,
      npc: "dreadhorn",
      target: {
        x: 174,
        y: 439,
        direction: "horizontal",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 217,
      y: 592,
      npc: "phantom face",
      target: {
        x: 328,
        y: 592,
        direction: "horizontal",
        duration: 3500,
        hold: true,
      },
    },
    {
      x: 558,
      y: 358,
      npc: "boneyard betty",
      target: {
        x: 425,
        y: 358,
        direction: "horizontal",
        duration: 3500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 492,
      y: 536,
      npc: "dreadhorn",
      target: {
        x: 529,
        y: 536,
        direction: "horizontal",
        duration: 1400,
        hold: true,
      },
    },
    {
      x: 96,
      y: 505,
      npc: "boneyard betty",
      target: {
        x: 96,
        y: 542,
        direction: "vertical",
        duration: 1500,
        hold: true,
      },
    },
    {
      x: 98,
      y: 406,
      npc: "phantom face",
      target: {
        x: 98,
        y: 455,
        direction: "vertical",
        duration: 1500,
        hold: true,
      },
    },
  ],
  7: [],
  8: [],
  9: [],
  10: [],
  11: [],
  12: [],
};
