import { SeasonWeek } from "features/game/types/game";
import { NPCBumpkin } from "features/world/scenes/BaseScene";

export type Enemy = NPCBumpkin & {
  target: {
    x: number;
    y: number;
    direction: "vertical" | "horizontal";
    duration: number;
    hold?: boolean;
    startFacingLeft?: boolean;
  };
};

export const ENEMIES: Record<SeasonWeek, Enemy[]> = {
  1: [
    {
      x: 104,
      y: 328,
      npc: "dreadhorn",
      target: {
        x: 104,
        y: 471,
        direction: "vertical",
        duration: 2000,
      },
    },
    {
      x: 57,
      y: 63,
      npc: "dreadhorn",
      target: {
        x: 294,
        y: 60,
        direction: "horizontal",
        duration: 3500,
      },
    },
    {
      x: 355,
      y: 458,
      npc: "dreadhorn",
      target: {
        x: 260,
        y: 458,
        direction: "horizontal",
        duration: 1800,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 585,
      y: 506,
      npc: "dreadhorn",
      target: {
        x: 585,
        y: 217,
        direction: "vertical",
        duration: 3500,
      },
    },
    {
      x: 89,
      y: 500,
      npc: "phantom face",
      target: {
        x: 46,
        y: 500,
        direction: "horizontal",
        duration: 1200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 518,
      y: 583,
      npc: "phantom face",
      target: {
        x: 483,
        y: 590,
        direction: "horizontal",
        duration: 900,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 130,
      y: 137,
      npc: "phantom face",
      target: {
        x: 185,
        y: 137,
        direction: "horizontal",
        duration: 1200,
        hold: true,
      },
    },
    {
      x: 342,
      y: 72,
      npc: "phantom face",
      target: {
        x: 440,
        y: 72,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
    {
      x: 412,
      y: 545,
      npc: "dreadhorn",
      target: {
        x: 435,
        y: 545,
        direction: "horizontal",
        duration: 800,
        hold: true,
      },
    },
  ],
  2: [
    {
      x: 89,
      y: 500,
      npc: "phantom face",
      target: {
        x: 46,
        y: 500,
        direction: "horizontal",
        duration: 1200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 56,
      y: 298,
      npc: "dreadhorn",
      target: {
        x: 56,
        y: 474,
        direction: "vertical",
        duration: 2400,
      },
    },
    {
      x: 139,
      y: 119,
      npc: "dreadhorn",
      target: {
        x: 296,
        y: 119,
        direction: "horizontal",
        duration: 2200,
      },
    },
    {
      x: 472,
      y: 56,
      npc: "phantom face",
      target: {
        x: 360,
        y: 81,
        direction: "horizontal",
        duration: 2000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 167,
      y: 567,
      npc: "phantom face",
      target: {
        x: 167,
        y: 600,
        direction: "vertical",
        duration: 1200,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 230,
      y: 566,
      npc: "dreadhorn",
      target: {
        x: 312,
        y: 566,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
    {
      x: 423,
      y: 328,
      npc: "dreadhorn",
      target: {
        x: 423,
        y: 517,
        direction: "vertical",
        duration: 2500,
        startFacingLeft: true,
      },
    },
    {
      x: 263,
      y: 183,
      npc: "phantom face",
      target: {
        x: 360,
        y: 183,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
  ],
  3: [
    {
      x: 279,
      y: 72,
      npc: "dreadhorn",
      target: {
        x: 279,
        y: 150,
        direction: "vertical",
        duration: 2500,
      },
    },
    {
      x: 470,
      y: 328,
      npc: "phantom face",
      target: {
        x: 375,
        y: 328,
        direction: "horizontal",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 535,
      y: 262,
      npc: "farmer flesh",
      target: {
        x: 535,
        y: 230,
        direction: "vertical",
        duration: 1500,
        hold: true,
      },
    },
    {
      x: 54,
      y: 201,
      npc: "phantom face",
      target: {
        x: 362,
        y: 201,
        direction: "horizontal",
        duration: 4500,
        hold: true,
      },
    },
    {
      x: 583,
      y: 70,
      npc: "boneyard betty",
      target: {
        x: 583,
        y: 233,
        direction: "vertical",
        duration: 3800,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 184,
      y: 519,
      npc: "dreadhorn",
      target: {
        x: 56,
        y: 535,
        direction: "horizontal",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 278,
      y: 469,
      npc: "farmer flesh",
      target: {
        x: 278,
        y: 518,
        direction: "horizontal",
        duration: 2000,
        startFacingLeft: true,
      },
    },
    {
      x: 479,
      y: 486,
      npc: "phantom face",
      target: {
        x: 520,
        y: 456,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 218,
      y: 599,
      npc: "boneyard betty",
      target: {
        x: 312,
        y: 599,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 487,
      y: 359,
      npc: "dreadhorn",
      target: {
        x: 487,
        y: 328,
        direction: "vertical",
        duration: 1500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 62,
      y: 426,
      npc: "farmer flesh",
      target: {
        x: 44,
        y: 426,
        direction: "horizontal",
        duration: 1000,
        hold: true,
        startFacingLeft: true,
      },
    },
  ],
  4: [
    {
      x: 376,
      y: 358,
      npc: "phantom face",
      target: {
        x: 522,
        y: 358,
        direction: "horizontal",
        duration: 3500,
        hold: true,
      },
    },
    {
      x: 584,
      y: 265,
      npc: "boneyard betty",
      target: {
        x: 584,
        y: 356,
        direction: "vertical",
        duration: 3000,
        startFacingLeft: true,
      },
    },
    {
      x: 520,
      y: 287,
      npc: "dreadhorn",
      target: {
        x: 520,
        y: 330,
        direction: "vertical",
        duration: 1500,
      },
    },
    {
      x: 267,
      y: 232,
      npc: "farmer flesh",
      target: {
        x: 343,
        y: 232,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
    {
      x: 154,
      y: 55,
      npc: "farmer flesh",
      target: {
        x: 258,
        y: 55,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 120,
      y: 248,
      npc: "dreadhorn",
      target: {
        x: 120,
        y: 356,
        direction: "vertical",
        duration: 3500,
      },
    },
    {
      x: 56,
      y: 344,
      npc: "boneyard betty",
      target: {
        x: 56,
        y: 422,
        direction: "vertical",
        duration: 3000,
        hold: true,
      },
    },
    {
      x: 272,
      y: 594,
      npc: "phantom face",
      target: {
        x: 291,
        y: 562,
        direction: "horizontal",
        duration: 2000,
      },
    },
    {
      x: 568,
      y: 599,
      npc: "farmer flesh",
      target: {
        x: 522,
        y: 599,
        direction: "horizontal",
        duration: 2500,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 471,
      y: 515,
      npc: "dreadhorn",
      target: {
        x: 586,
        y: 515,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 586,
      y: 535,
      npc: "farmer flesh",
      target: {
        x: 471,
        y: 535,
        direction: "horizontal",
        duration: 2500,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 106,
      y: 520,
      npc: "boneyard betty",
      target: {
        x: 129,
        y: 520,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
  ],
  5: [
    {
      x: 51,
      y: 564,
      npc: "phantom face",
      target: {
        x: 55,
        y: 599,
        direction: "vertical",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 138,
      y: 295,
      npc: "farmer flesh",
      target: {
        x: 50,
        y: 295,
        direction: "horizontal",
        duration: 2500,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 56,
      y: 339,
      npc: "boneyard betty",
      target: {
        x: 151,
        y: 339,
        direction: "horizontal",
        duration: 3000,
        hold: true,
      },
    },
    {
      x: 248,
      y: 103,
      npc: "dreadhorn",
      target: {
        x: 116,
        y: 103,
        direction: "horizontal",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 344,
      y: 248,
      npc: "phantom face",
      target: {
        x: 441,
        y: 248,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
    {
      x: 123,
      y: 232,
      npc: "phantom face",
      target: {
        x: 51,
        y: 232,
        direction: "horizontal",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 233,
      y: 87,
      npc: "boneyard betty",
      target: {
        x: 439,
        y: 87,
        direction: "horizontal",
        duration: 4700,
      },
    },
    {
      x: 567,
      y: 153,
      npc: "dreadhorn",
      target: {
        x: 502,
        y: 153,
        direction: "horizontal",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 570,
      y: 171,
      npc: "farmer flesh",
      target: {
        x: 570,
        y: 294,
        direction: "vertical",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 492,
      y: 214,
      npc: "phantom face",
      target: {
        x: 536,
        y: 214,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
    {
      x: 400,
      y: 156,
      npc: "farmer flesh",
      target: {
        x: 400,
        y: 306,
        direction: "vertical",
        duration: 4700,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 344,
      y: 454,
      npc: "dreadhorn",
      target: {
        x: 273,
        y: 454,
        direction: "horizontal",
        duration: 2800,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 88,
      y: 596,
      npc: "boneyard betty",
      target: {
        x: 362,
        y: 596,
        direction: "horizontal",
        duration: 5500,
        hold: true,
      },
    },
  ],
  6: [
    {
      x: 119,
      y: 103,
      npc: "boneyard betty",
      target: {
        x: 50,
        y: 103,
        direction: "horizontal",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 184,
      y: 103,
      npc: "phantom face",
      target: {
        x: 234,
        y: 103,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 296,
      y: 180,
      npc: "dreadhorn",
      target: {
        x: 585,
        y: 180,
        direction: "horizontal",
        duration: 6500,
      },
    },
    {
      x: 496,
      y: 57,
      npc: "dreadhorn",
      target: {
        x: 496,
        y: 118,
        direction: "vertical",
        duration: 3500,
        startFacingLeft: true,
      },
    },
    {
      x: 420,
      y: 278,
      npc: "farmer flesh",
      target: {
        x: 554,
        y: 278,
        direction: "horizontal",
        duration: 4000,
      },
    },
    {
      x: 188,
      y: 279,
      npc: "farmer flesh",
      target: {
        x: 89,
        y: 279,
        direction: "horizontal",
        duration: 4000,
        startFacingLeft: true,
      },
    },
    {
      x: 171,
      y: 323,
      npc: "farmer flesh",
      target: {
        x: 171,
        y: 376,
        direction: "vertical",
        duration: 3500,
      },
    },
    {
      x: 272,
      y: 439,
      npc: "dreadhorn",
      target: {
        x: 174,
        y: 439,
        direction: "horizontal",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 217,
      y: 592,
      npc: "phantom face",
      target: {
        x: 328,
        y: 592,
        direction: "horizontal",
        duration: 3500,
        hold: true,
      },
    },
    {
      x: 558,
      y: 358,
      npc: "boneyard betty",
      target: {
        x: 425,
        y: 358,
        direction: "horizontal",
        duration: 3500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 492,
      y: 536,
      npc: "dreadhorn",
      target: {
        x: 529,
        y: 536,
        direction: "horizontal",
        duration: 1400,
        hold: true,
      },
    },
    {
      x: 96,
      y: 505,
      npc: "boneyard betty",
      target: {
        x: 96,
        y: 542,
        direction: "vertical",
        duration: 1500,
        hold: true,
      },
    },
    {
      x: 98,
      y: 406,
      npc: "phantom face",
      target: {
        x: 98,
        y: 455,
        direction: "vertical",
        duration: 1500,
        hold: true,
      },
    },
  ],
  7: [
    {
      x: 47,
      y: 147,
      npc: "boneyard betty",
      target: {
        x: 98,
        y: 147,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 161,
      y: 63,
      npc: "dreadhorn",
      target: {
        x: 161,
        y: 147,
        direction: "vertical",
        duration: 3000,
      },
    },
    {
      x: 219,
      y: 67,
      npc: "phantom face",
      target: {
        x: 353,
        y: 67,
        direction: "horizontal",
        duration: 3700,
        hold: true,
      },
    },
    {
      x: 186,
      y: 311,
      npc: "farmer flesh",
      target: {
        x: 280,
        y: 311,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 50,
      y: 345,
      npc: "dreadhorn",
      target: {
        x: 50,
        y: 434,
        direction: "vertical",
        duration: 3000,
        hold: true,
      },
    },
    {
      x: 172,
      y: 328,
      npc: "dreadhorn",
      target: {
        x: 50,
        y: 328,
        direction: "horizontal",
        duration: 3200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 118,
      y: 597,
      npc: "phantom face",
      target: {
        x: 50,
        y: 597,
        direction: "horizontal",
        duration: 3200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 280,
      y: 536,
      npc: "farmer flesh",
      target: {
        x: 455,
        y: 536,
        direction: "horizontal",
        duration: 4000,
      },
    },
    {
      x: 584,
      y: 345,
      npc: "farmer flesh",
      target: {
        x: 584,
        y: 536,
        direction: "vertical",
        duration: 4000,
        startFacingLeft: true,
      },
    },
    {
      x: 476,
      y: 180,
      npc: "boneyard betty",
      target: {
        x: 476,
        y: 324,
        direction: "vertical",
        duration: 4200,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 471,
      y: 168,
      npc: "boneyard betty",
      target: {
        x: 584,
        y: 168,
        direction: "horizontal",
        duration: 3700,
        hold: true,
      },
    },
    {
      x: 334,
      y: 469,
      npc: "phantom face",
      target: {
        x: 399,
        y: 469,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
  ],
  8: [
    {
      x: 378,
      y: 299,
      npc: "dreadhorn",
      target: {
        x: 378,
        y: 360,
        direction: "vertical",
        duration: 2500,
        startFacingLeft: true,
      },
    },
    {
      x: 263,
      y: 299,
      npc: "dreadhorn",
      target: {
        x: 263,
        y: 360,
        direction: "vertical",
        duration: 2500,
      },
    },
    {
      x: 522,
      y: 327,
      npc: "phantom face",
      target: {
        x: 440,
        y: 327,
        direction: "horizontal",
        duration: 2500,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 185,
      y: 405,
      npc: "boneyard betty",
      target: {
        x: 328,
        y: 405,
        direction: "horizontal",
        duration: 4000,
        hold: true,
      },
    },
    {
      x: 584,
      y: 407,
      npc: "boneyard betty",
      target: {
        x: 393,
        y: 407,
        direction: "horizontal",
        duration: 4000,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 335,
      y: 555,
      npc: "boneyard betty",
      target: {
        x: 335,
        y: 593,
        direction: "vertical",
        duration: 2000,
        hold: true,
      },
    },
    {
      x: 186,
      y: 585,
      npc: "farmer flesh",
      target: {
        x: 223,
        y: 585,
        direction: "horizontal",
        duration: 2000,
      },
    },
    {
      x: 46,
      y: 377,
      npc: "farmer flesh",
      target: {
        x: 91,
        y: 377,
        direction: "horizontal",
        duration: 1800,
      },
    },
    {
      x: 91,
      y: 422,
      npc: "farmer flesh",
      target: {
        x: 46,
        y: 422,
        direction: "horizontal",
        duration: 1800,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 112,
      y: 88,
      npc: "dreadhorn",
      target: {
        x: 112,
        y: 190,
        direction: "vertical",
        duration: 2500,
      },
    },
    {
      x: 272,
      y: 178,
      npc: "phantom face",
      target: {
        x: 429,
        y: 178,
        direction: "horizontal",
        duration: 4000,
        hold: true,
      },
    },
    {
      x: 193,
      y: 97,
      npc: "phantom face",
      target: {
        x: 180,
        y: 97,
        direction: "horizontal",
        duration: 2000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 112,
      y: 487,
      npc: "dreadhorn",
      target: {
        x: 193,
        y: 487,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
    {
      x: 588,
      y: 149,
      npc: "farmer flesh",
      target: {
        x: 588,
        y: 69,
        direction: "vertical",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 356,
      y: 65,
      npc: "boneyard betty",
      target: {
        x: 480,
        y: 65,
        direction: "horizontal",
        duration: 3500,
        hold: true,
      },
    },
    {
      x: 328,
      y: 455,
      npc: "phantom face",
      target: {
        x: 240,
        y: 455,
        direction: "horizontal",
        duration: 3500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 46,
      y: 511,
      npc: "phantom face",
      target: {
        x: 63,
        y: 511,
        direction: "horizontal",
        duration: 1800,
      },
    },
    {
      x: 451,
      y: 471,
      npc: "phantom face",
      target: {
        x: 391,
        y: 471,
        direction: "horizontal",
        duration: 2500,
        startFacingLeft: true,
      },
    },
  ],
  9: [
    {
      x: 54,
      y: 68,
      npc: "phantom face",
      target: {
        x: 222,
        y: 68,
        direction: "horizontal",
        duration: 3500,
      },
    },
    {
      x: 50,
      y: 74,
      npc: "dreadhorn",
      target: {
        x: 50,
        y: 127,
        direction: "vertical",
        duration: 1500,
      },
    },
    {
      x: 114,
      y: 133,
      npc: "farmer flesh",
      target: {
        x: 265,
        y: 133,
        direction: "horizontal",
        duration: 2700,
        hold: true,
      },
    },
    {
      x: 175,
      y: 158,
      npc: "boneyard betty",
      target: {
        x: 175,
        y: 224,
        direction: "vertical",
        duration: 2000,
      },
    },
    {
      x: 258,
      y: 215,
      npc: "dreadhorn",
      target: {
        x: 320,
        y: 215,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
    {
      x: 299,
      y: 55,
      npc: "dreadhorn",
      target: {
        x: 299,
        y: 85,
        direction: "vertical",
        duration: 1500,
        hold: true,
      },
    },
    {
      x: 59,
      y: 183,
      npc: "dreadhorn",
      target: {
        x: 59,
        y: 248,
        direction: "vertical",
        duration: 1800,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 47,
      y: 568,
      npc: "phantom face",
      target: {
        x: 157,
        y: 568,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 168,
      y: 520,
      npc: "phantom face",
      target: {
        x: 315,
        y: 520,
        direction: "horizontal",
        duration: 3500,
        hold: true,
      },
    },
    {
      x: 150,
      y: 596,
      npc: "phantom face",
      target: {
        x: 47,
        y: 596,
        direction: "horizontal",
        duration: 2200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 296,
      y: 597,
      npc: "boneyard betty",
      target: {
        x: 518,
        y: 597,
        direction: "horizontal",
        duration: 4200,
        hold: true,
      },
    },
    {
      x: 432,
      y: 551,
      npc: "farmer flesh",
      target: {
        x: 481,
        y: 551,
        direction: "horizontal",
        duration: 2200,
      },
    },
    {
      x: 414,
      y: 410,
      npc: "farmer flesh",
      target: {
        x: 483,
        y: 410,
        direction: "horizontal",
        duration: 2800,
        hold: true,
      },
    },
    {
      x: 574,
      y: 265,
      npc: "dreadhorn",
      target: {
        x: 574,
        y: 357,
        direction: "vertical",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 303,
      y: 54,
      npc: "phantom face",
      target: {
        x: 533,
        y: 54,
        direction: "horizontal",
        duration: 3400,
        hold: true,
      },
    },
    {
      x: 416,
      y: 120,
      npc: "farmer flesh",
      target: {
        x: 416,
        y: 230,
        direction: "vertical",
        duration: 3200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 265,
      y: 279,
      npc: "farmer flesh",
      target: {
        x: 379,
        y: 279,
        direction: "horizontal",
        duration: 2800,
        hold: true,
      },
    },
    {
      x: 320,
      y: 422,
      npc: "farmer flesh",
      target: {
        x: 320,
        y: 488,
        direction: "vertical",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 49,
      y: 374,
      npc: "farmer flesh",
      target: {
        x: 112,
        y: 374,
        direction: "horizontal",
        duration: 2300,
        hold: true,
      },
    },
    {
      x: 589,
      y: 216,
      npc: "boneyard betty",
      target: {
        x: 589,
        y: 363,
        direction: "vertical",
        duration: 2500,
        hold: true,
        startFacingLeft: true,
      },
    },
  ],
  10: [
    {
      x: 104,
      y: 328,
      npc: "dreadhorn",
      target: {
        x: 104,
        y: 471,
        direction: "vertical",
        duration: 2000,
      },
    },
    {
      x: 57,
      y: 63,
      npc: "dreadhorn",
      target: {
        x: 294,
        y: 60,
        direction: "horizontal",
        duration: 3500,
      },
    },
    {
      x: 355,
      y: 458,
      npc: "dreadhorn",
      target: {
        x: 260,
        y: 458,
        direction: "horizontal",
        duration: 1800,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 585,
      y: 506,
      npc: "dreadhorn",
      target: {
        x: 585,
        y: 217,
        direction: "vertical",
        duration: 3500,
      },
    },
    {
      x: 89,
      y: 500,
      npc: "phantom face",
      target: {
        x: 46,
        y: 500,
        direction: "horizontal",
        duration: 1200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 518,
      y: 583,
      npc: "phantom face",
      target: {
        x: 483,
        y: 590,
        direction: "horizontal",
        duration: 900,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 130,
      y: 137,
      npc: "phantom face",
      target: {
        x: 185,
        y: 137,
        direction: "horizontal",
        duration: 1200,
        hold: true,
      },
    },
    {
      x: 342,
      y: 72,
      npc: "phantom face",
      target: {
        x: 440,
        y: 72,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
    {
      x: 412,
      y: 545,
      npc: "dreadhorn",
      target: {
        x: 435,
        y: 545,
        direction: "horizontal",
        duration: 800,
        hold: true,
      },
    },
  ],
  11: [
    {
      x: 89,
      y: 500,
      npc: "phantom face",
      target: {
        x: 46,
        y: 500,
        direction: "horizontal",
        duration: 1200,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 56,
      y: 298,
      npc: "dreadhorn",
      target: {
        x: 56,
        y: 474,
        direction: "vertical",
        duration: 2400,
      },
    },
    {
      x: 139,
      y: 119,
      npc: "dreadhorn",
      target: {
        x: 296,
        y: 119,
        direction: "horizontal",
        duration: 2200,
      },
    },
    {
      x: 472,
      y: 56,
      npc: "phantom face",
      target: {
        x: 360,
        y: 81,
        direction: "horizontal",
        duration: 2000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 167,
      y: 567,
      npc: "phantom face",
      target: {
        x: 167,
        y: 600,
        direction: "vertical",
        duration: 1200,
        startFacingLeft: true,
        hold: true,
      },
    },
    {
      x: 230,
      y: 566,
      npc: "dreadhorn",
      target: {
        x: 312,
        y: 566,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
    {
      x: 423,
      y: 328,
      npc: "dreadhorn",
      target: {
        x: 423,
        y: 517,
        direction: "vertical",
        duration: 2500,
        startFacingLeft: true,
      },
    },
    {
      x: 263,
      y: 183,
      npc: "phantom face",
      target: {
        x: 360,
        y: 183,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
  ],
  12: [
    {
      x: 279,
      y: 72,
      npc: "dreadhorn",
      target: {
        x: 279,
        y: 150,
        direction: "vertical",
        duration: 2500,
      },
    },
    {
      x: 470,
      y: 328,
      npc: "phantom face",
      target: {
        x: 375,
        y: 328,
        direction: "horizontal",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 535,
      y: 262,
      npc: "farmer flesh",
      target: {
        x: 535,
        y: 230,
        direction: "vertical",
        duration: 1500,
        hold: true,
      },
    },
    {
      x: 54,
      y: 201,
      npc: "phantom face",
      target: {
        x: 362,
        y: 201,
        direction: "horizontal",
        duration: 4500,
        hold: true,
      },
    },
    {
      x: 583,
      y: 70,
      npc: "boneyard betty",
      target: {
        x: 583,
        y: 233,
        direction: "vertical",
        duration: 3800,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 184,
      y: 519,
      npc: "dreadhorn",
      target: {
        x: 56,
        y: 535,
        direction: "horizontal",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 278,
      y: 469,
      npc: "farmer flesh",
      target: {
        x: 278,
        y: 518,
        direction: "horizontal",
        duration: 2000,
        startFacingLeft: true,
      },
    },
    {
      x: 479,
      y: 486,
      npc: "phantom face",
      target: {
        x: 520,
        y: 456,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 218,
      y: 599,
      npc: "boneyard betty",
      target: {
        x: 312,
        y: 599,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
    {
      x: 487,
      y: 359,
      npc: "dreadhorn",
      target: {
        x: 487,
        y: 328,
        direction: "vertical",
        duration: 1500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 62,
      y: 426,
      npc: "farmer flesh",
      target: {
        x: 44,
        y: 426,
        direction: "horizontal",
        duration: 1000,
        hold: true,
        startFacingLeft: true,
      },
    },
  ],
  13: [
    {
      x: 74,
      y: 263,
      npc: "boneyard betty",
      target: {
        x: 148,
        y: 263,
        direction: "horizontal",
        duration: 1800,
        hold: true,
      },
    },
    {
      x: 95,
      y: 426,
      npc: "farmer flesh",
      target: {
        x: 45,
        y: 426,
        direction: "horizontal",
        duration: 1500,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 472,
      y: 326,
      npc: "boneyard betty",
      target: {
        x: 585,
        y: 326,
        direction: "horizontal",
        duration: 2000,
        hold: true,
      },
    },
    {
      x: 260,
      y: 165,
      npc: "dreadhorn",
      target: {
        x: 392,
        y: 165,
        direction: "horizontal",
        duration: 4000,
        hold: true,
      },
    },
    {
      x: 590,
      y: 165,
      npc: "farmer flesh",
      target: {
        x: 493,
        y: 165,
        direction: "horizontal",
        duration: 3000,
        hold: true,
        startFacingLeft: true,
      },
    },
    {
      x: 159,
      y: 64,
      npc: "damien",
      target: {
        x: 159,
        y: 123,
        direction: "vertical",
        duration: 3000,
        hold: true,
      },
    },
    {
      x: 217,
      y: 487,
      npc: "damien",
      target: {
        x: 217,
        y: 585,
        direction: "vertical",
        duration: 3500,
        hold: true,
      },
    },
    {
      x: 515,
      y: 521,
      npc: "farmer flesh",
      target: {
        x: 590,
        y: 521,
        direction: "horizontal",
        duration: 2500,
        hold: true,
      },
    },
  ],
};
