name: Upload Website

on:
  push:
    branches:
      - feat/chicken-coop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CI: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://sunflower-farmers.com/bukbuk --delete

      - name: Invalidate Cloudfront Distribution
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: "/*"
          DISTRIBUTION: ELYUBARGP0CYQ
